image: archlinux
sources:
    - https://git.sr.ht/~ineptattech/aur-alire
packages:
    - gprbuild-bootstrap
    - xmlada
    - git
tasks:
- prepare: |
    git clone https://aur.archlinux.org/gprbuild.git
    cd gprbuild
    makepkg
    yay -R --noconfirm gprbuild-bootstrap
    makepkg -i --noconfirm
    cd ..
    yay -S --answerclean=All --noconfirm xmlada
    yay -S gnatcoll-core --noconfirm
- build: |
    cd aur-alire
    makepkg
