pre-commit:
  commands:
    update:
      run: |
        set -eu
        echo "Updating checksum"
        updpkgsums
        git add PKGBUILD

        echo "Updating .SRCINFO"
        makepkg --printsrcinfo > .SRCINFO
        git add .SRCINFO
