[vpn-unlimited-bin]
source = "cmd"
cmd = 'curl -ILs -w %{url_effective} https://www.vpnunlimited.com/api/keepsolid/vpn-download?platform=linux-new | tail -n1 | grep -oP "vpn-unlimited_\K[0-9]+\.[0-9]+\.[0-9]+"'
