version: 20
jobs:
- name: Build Package
  jobExecutor: Server
  steps:
  - !CommandStep
    name: Build
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - pwd
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Github
  jobExecutor: Server
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Push Tags
    runInContainer: false
    interpreter: !DefaultInterpreter
      commands:
      - git push https://polarian:@secret:ghpass@@@github.com/reposilite-playground/reposilite-aur
        HEAD:master
      - git push --tags https://polarian:@secret:ghpass@@@github.com/reposilite-playground/reposilite-aur
        HEAD:master
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger
    branches: master
    projects: polarrepo/reposilite
  - !TagCreateTrigger
    projects: polarrepo/reposilite
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
  postBuildActions:
  - !SendNotificationAction
    condition: always
    receivers: user(polariandev)
