repos:
- repo: local
  hooks:
    - id: updpkgsums
      name: updpkgsums
      entry: updpkgsums
      language: system
      files: PKGBUILD
    - id: makepkg
      name: makepkg
      entry: sh -c 'makepkg --printsrcinfo > .SRCINFO'
      language: system
      files: PKGBUILD
      pass_filenames: false

