pkgbase = leapp-bin
	pkgdesc = Leapp is a Desktop DevTool that handles the management and security of your cloud credentials for you, converted from .deb package
	pkgver = VERSION
	pkgrel = 1
	url = https://www.leapp.cloud/
	arch = x86_64
	license = custom
	depends = gtk3
	depends = libxss
	depends = libnotify
	depends = nss
	depends = libxss
	depends = libxtst
	depends = xdg-utils
	depends = util-linux-libs
	depends = libsecret
	depends = at-spi2-core
	depends = aws-session-manager-plugin
	provides = leapp
	source = Leapp_VERSION_amd64.deb::https://asset.noovolari.com/VERSION/Leapp_VERSION_amd64.deb
	sha512sums = SHA512SUMS

pkgname = leapp-bin
