#!/bin/sh

INTERFACE=$1
STATUS=$2

# $INIT should be either "init" (System V) or "systemd".
INIT=`cat /proc/1/comm`

no_valid_init() {
  echo 'No valid init system set. Please select either "init" or "systemd".'
  exit 1
}

pdnsd_is_running() {
  # Check whether pDNSd is running.
  case "$INIT" in
    'systemd')
      systemctl is-active pdnsd.service -q
      return [ ! $? = 0 ]
    ;;
    'init')
      return [ `rc.d list|grep pdnsd|cut -f1 -d']'|cut -d'[' -f2` == 'STARTED' ]
    ;;
    *)
      no_valid_init
    ;;
  esac
}

pdnsd_going_up() {
  if [ ! pdnsd_is_running ]; then
    # pDNSd isn't running. Start it.
    case "$INIT" in
      'systemd')
        systemctl start pdnsd.service
      ;;
      'init')
        rc.d start pdnsd
      ;;
    esac
  else
    # pDNSd is running. Restart it.
    case "$INIT" in
      'systemd')
        systemctl restart pdnsd.service
      ;;
      'init')
        rc.d restart pdnsd
      ;;
    esac

  fi
}

pdnsd_going_down() {
  # Check for active interface, take offline if none is active
  if [ ! `nm-tool|grep State|cut -f2 -d' '` = 'connected' ]; then
    case "$INIT" in
      'systemd')
        systemctl stop pdnsd.service
      ;;
      'init')
        rc.d stop pdnsd
      ;;
      *)
        no_valid_init
      ;;
    esac
  else
    # If another interface is active, restart so we're sure we're using
    # the active connection.
    case "$INIT" in
      'systemd')
        systemctl restart pdnsd.service
      ;;
      'init')
        rc.d restart pdnsd
      ;;
      *)
        no_valid_init
      ;;
    esac
  fi
}

case "$STATUS" in
  up)
    pdnsd_going_up
  ;;
  vpn-up)
    pdnsd_going_up
  ;;
  down)
    pdnsd_going_down
  ;;
  vpn-down)
    pdnsd_going_down
  ;;
esac
