# SPDX-FileCopyrightText: 2026 pacmanics
#
# SPDX-License-Identifier: 0BSD

# Generated by Django 4.2.16 on 2026-04-16 14:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0065_reportobservationlink_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='document',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/opt/pentest-ghostwriter/app/ghostwriter/media/templates'), upload_to=''),
        ),
    ]
