# --max-scale parameter for ChimeraOS Gamescope Session
MAX_SCALE=2

# Use NTsync with Proton-CachyOS. Not needed once 11.0 goes live
PROTON_USE_NTSYNC=1

# Use DXVK for D3D8 titles at all times.
PROTON_DXVK_D3D8=1
