#!/bin/sh

INTERFACE=$1
STATUS=$2

# Make sure we're always getting the standard response strings
LANG='C'

# Chrony set-up
CHRONY=/usr/bin/chronyc
STATECMD='nmcli -t --fields STATE g'

chrony_cmd() {
	echo Chrony going $1.
	exec $CHRONY -a $1
}

case "$STATUS" in
  up)
    chrony_cmd online
  ;;
  vpn-up)
    chrony_cmd online
  ;;
  down)
    # Check for active interface, take offline if none is active
    if [ ! `${STATECMD}` = 'connected' ]; then
      chrony_cmd offline
    fi
  ;;
  vpn-down)
    # Check for active interface, take offline if none is active
    if [ ! `${STATECMD}` = 'connected' ]; then
      chrony_cmd offline
    fi
  ;;
esac
