[Manager]
# Reduce timeout for starting and stopping services to 5s, see
# https://fedoraproject.org/wiki/Changes/Shorter_Shutdown_Timer
DefaultTimeoutStartSec=5
DefaultTimeoutStopSec=5
DefaultTimeoutAbortSec=5
