post_install() {
  echo ":: Downloading latest geo files..."

  update_geofiles() {
    case "${1}" in
      "main") dat_files=(geoip geosite); dat_source="Loyalsoldier/v2ray-rules-dat";;
        "IR") dat_files=(geoip_IR geosite_IR); dat_source="chocolate4u/Iran-v2ray-rules" ;;
        "RU") dat_files=(geoip_RU geosite_RU); dat_source="runetfreedom/russia-v2ray-rules-dat";;
    esac
    for dat in "${dat_files[@]}"; do
        # Remove suffix for remote filename (e.g., geoip_IR -> geoip)
        remote_file="${dat%%_*}"
        curl -sfLRo ${xui_folder}/bin/${dat}.dat -z ${xui_folder}/bin/${dat}.dat \
            https://github.com/${dat_source}/releases/latest/download/${remote_file}.dat
    done
  }
  
  update_geofiles "main"
  update_geofiles "IR"
  update_geofiles "RU"
}

post_upgrade() {
  post_install
}

pre_remove() {
  find /usr/lib/x-ui/bin -maxdepth 1 -type f -name 'geoip{,_IR,_RU}.dat'   -delete
  find /usr/lib/x-ui/bin -maxdepth 1 -type f -name 'geosite{,_IR,_RU}.dat' -delete
}
