# Copyright Sebastian Wiesner <sebastian@swsnr.de>
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted.
#
# THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
# OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

[wifi]
# Randomize MAC address on each connection attempt.
#
# The default is 'preserve' which retains the hardware address and offers no
# privacy at all.
#
# Alternatively, use 'stable'/'stable-ssid' to generate a per connection profile
# or per SSID MAC address, which still allows one AP to track you, but makes
# tracking across APs more difficult.
cloned-mac-address=random

[ipv6]
# Forcibly enable IPv6 RFC 4941 private addresses for auto-configuration.
# Typically, this would be enabled by setting net.ipv6.conf.all.use_tempaddr
# and net.ipv6.conf.default.use_tempaddr, but just in case let's set these
# explicitly for Network Manager connections.
ip6-privacy=2
