monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "alsa_output.pci-0000_c4_00.5-platform-amd_sdw.pro-output-2"
      }
    ]
    actions = {
      update-props = {
        audio.position = [ "FL", "FR" ]
      }
    }
  }
]
