monitor.bluez.properties = {
  bluez5.codecs = [ lhdc_v5 ldac aac sbc_xq sbc ]
  bluez5.enable-sbc-xq = true
  bluez5.default.rate = 48000
}

monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.a2dp.ldac.quality = "hq"
        bluez5.auto-connect = [ a2dp_sink ]
      }
    }
  }
]
