context.objects = [
    {
        factory = adapter
        args = {
            factory.name = api.alsa.pcm.source
            node.name = "roon-loopback-capture"
            node.description = "Roon Loopback Capture"
            media.class = "Audio/Source"
            api.alsa.path = "hw:Loopback,1"
            api.alsa.period-size = 2048
            api.alsa.headroom = 1024
            audio.format = "S32LE"
            audio.rate = 48000
            audio.channels = 2
            audio.position = "FL,FR"
            node.pause-on-idle = false
        }
        flags = [ nofail ]
    }
]
