context.modules = [
  {   name = libpipewire-module-echo-cancel
      args = {
          library.name  = aec/libspa-aec-webrtc
          aec.args = "noise_suppression=false high_pass_filter=true extended_filter=false delay_agnostic=true agc=false"
          monitor.mode = true
          source.props = {
            node.description = "Noise Suppressed Microphone"
          }
      }
  }
]
