post_install() {
    echo
    echo "Ensure to perform a full reboot after this installation"
    echo "Then enter the following command in the terminal to enable Acer's \"Battery Charge Limit\""
    echo "echo 1 | sudo tee /sys/bus/wmi/drivers/acer-wmi-battery/health_mode"
    echo "Now you should be good to go!"
    echo
    echo "In case something's wrong, please CHECK the following:"
    echo "- Ensure \"Battery Charge Limit\" is an option in \"Acer Care Center\" on Windows 10/11 (prior to switching to Linux)"
    echo "- Check & report the problem on https://github.com/frederik-h/acer-wmi-battery/issues"
    echo
}