post_install() {
    echo
    echo "Please restart your laptop to apply all changes to enable Battery Charge Limit."
    echo
    echo "In case something's wrong, please CHECK the following:"
    echo "- Ensure \"Battery Charge Limit\" is an option on your laptop in \"Acer Care Center\" on Windows 10/11"
    echo "- Check & report the problem on https://github.com/frederik-h/acer-wmi-battery/issues"
    echo
    echo "Loading. Please wait in 5 seconds..."
    sleep 5
}