post_install() {
    cat << \here
This software is heavily outdated and crashes reproducibly.
possible workarounds:
• use another pdf-reader whereever possible
• use acroread windows version in wine (HowTo: https://appdb.winehq.org/objectManager.php?sClass=version&iId=27093&iTestingId=92286)
• remove /opt/Adobe/Reader9/Reader/intellinux/plug_ins/EFS.api (this might have unknown consequences regarding your data and software functionality)
here
}

post_upgrade() {
    post_install
}
