## see: https://actualbudget.org/docs/config/

## Data Location Configuration
ACTUAL_DATA_DIR=/var/lib/actual
# ACTUAL_CONFIG_PATH=$ACTUAL_DATA_DIR/config.json
# ACTUAL_SERVER_FILES=$ACTUAL_DATA_DIR/server-files
# ACTUAL_USER_FILES=$ACTUAL_DATA_DIR/user-files
# ACTUAL_WEB_ROOT=

## HTTPS Configuration
# ACTUAL_HTTPS_KEY=
# ACTUAL_HTTPS_CERT=

## Network Configuration
# ACTUAL_PORT=5006
# ACTUAL_HOSTNAME=
# ACTUAL_TRUSTED_PROXIES='10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,fc00::/7,::1/128'

## Auth Configuration
# ACTUAL_LOGIN_METHOD=password
# ACTUAL_ALLOWED_LOGIN_METHODS='password,header,openid'
# ACTUAL_TRUSTED_AUTH_PROXIES=
# ACTUAL_TOKEN_EXPIRATION=never
# ACTUAL_USER_CREATION_MODE=manual

## Upload Configuration
# ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
# ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
# ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20

## OpenID Configuration
# ACTUAL_OPENID_DISCOVERY_URL=
# ACTUAL_OPENID_PROVIDER_NAME=
# ACTUAL_OPENID_AUTHORIZATION_ENDPOINT=
# ACTUAL_OPENID_TOKEN_ENDPOINT=
# ACTUAL_OPENID_USERINFO_ENDPOINT=
# ACTUAL_OPENID_CLIENT_ID=
# ACTUAL_OPENID_CLIENT_SECRET=
# ACTUAL_OPENID_SERVER_HOSTNAME=
# ACTUAL_OPENID_AUTH_METHOD=openid
# ACTUAL_OPENID_ENFORCE=false
