post_install()
{
  echo -e "\nThank you for choosing gittorrent"
  echo -e "For a better experience with this software, consider adding the line\n"
  echo -e "\t\033[1;33malias gt='gittorrent'\033[0m\n"
  echo -e "to the bottom of ~/.bashrc\n"
}

post_remove()
{
  echo -e "\nThank you for using gittorrent"
  echo -e "Don't forget to remove the line\n"
  echo -e "\t\033[1;33malias gt='gittorrent'\033[0m\n"
  echo -e "from ~/.bashrc\n"
}
