post_install() {
  post_upgrade
}

post_upgrade() {
  groupadd -r albion &> /dev/null

    cat << "EOM"
==> New group installed: albion
==> Your user must be in the albion group for the launcher to work properly, eg.
==> sudo usermod -a -G albion ${USER}
EOM
  chgrp -R albion "/opt/albion-online-launcher-bin/launcher"
  chgrp -R albion "/opt/albion-online-launcher-bin/game_x64"
  chgrp -R albion "/opt/albion-online-launcher-bin/staging_x64"
}
