export ALICEVISION_ROOT=/usr
export MESHROOM_NODES_PATH=$ALICEVISION_ROOT/share/meshroom:$MESHROOM_NODES_PATH
export MESHROOM_PIPELINE_TEMPLATES_PATH=$ALICEVISION_ROOT/share/meshroom:$MESHROOM_PIPELINE_TEMPLATES_PATH
export ALICEVISION_SENSOR_DB=/usr/share/aliceVision/cameraSensors.db 
