post_install(){

bash /opt/apps/amber-ce-bookworm/files/bin/ace-init

systemctl daemon-reload
systemctl enable --now ace-bookworm-auto-upgrade.service
systemctl reload apparmor

}

post_upgrade(){

if [ -d /opt/apps/cn.flamescion.bookworm-compatibility-mode/ ];then
echo "Migrating data..."
rsync -a /opt/apps/cn.flamescion.bookworm-compatibility-mode/ /opt/apps/amber-ce-bookworm/

rm -rf /opt/apps/cn.flamescion.bookworm-compatibility-mode

fi

bash /opt/apps/amber-ce-bookworm/files/bin/ace-init

systemctl daemon-reload
systemctl enable --now ace-bookworm-auto-upgrade.service
systemctl reload apparmor

}

post_remove(){

rm -rf /opt/apps/amber-ce-bookworm

}
