#!/bin/sh
home_dir_user=$USER
if [ ! -d "/opt/Audio Assault/AmpLockerData" ]; then
    sudo mkdir -p /opt/Audio\ Assault
    sudo ln -sf /home/$home_dir_user/.config/Amp\ Locker /opt/Audio\ Assault/AmpLockerData
fi
