#!/bin/sh
home_dir_user=$USER

if [ ! -d "/home/${home_dir_user}/Audio Assault/PluginData/Audio Assault/AmpLockerData" ]; then
    mkdir -p /home/${home_dir_user}/Audio\ Assault/PluginData/Audio\ Assault
    ln -sf /usr/lib/AmpLockerData /home/${home_dir_user}/Audio\ Assault/PluginData/Audio\ Assault/AmpLockerData
else
    rm -r /home/${home_dir_user}/Audio\ Assault/PluginData/Audio\ Assault/AmpLockerData
    ln -sf /usr/lib/AmpLockerData /home/${home_dir_user}/Audio\ Assault/PluginData/Audio\ Assault/AmpLockerData
fi
