post_install()
{
	systemctl --global enable anbox-launchers.service anbox-launchers.timer &> /dev/null
}
pre_remove()
{
	systemctl --global disable anbox-launchers.service anbox-launchers.timer &> /dev/null
}
post_upgrade()
{
	systemctl --global disable anbox-launchers.service anbox-launchers.timer &> /dev/null
	systemctl --global enable anbox-launchers.service anbox-launchers.timer &> /dev/null
}
