post_install() {
    /opt/android-ndk-ollvm/update_links.sh
}

post_upgrade() {
    /opt/android-ndk-ollvm/update_links.sh
}

pre_remove() {
    rm /opt/android-ndk-ollvm/build
    rm /opt/android-ndk-ollvm/source.properties
    rm /opt/android-ndk-ollvm/toolchains/llvm/prebuilt/linux-x86_64/sysroot
    
    rm `readlink /opt/android-ndk-ollvm/toolchains/llvm/prebuilt/linux-x86_64/ndk-libs`
    rm /opt/android-ndk-ollvm/toolchains/llvm/prebuilt/linux-x86_64/ndk-libs
}
