pre_install() {
	echo "This package is removed due to lack of maintenance and not adhering to AUR naming rules."
	echo "Please install anki-bin manually, or another Anki package of your choosing:"
	echo
	echo "- https://aur.archlinux.org/packages/anki-bin (prebuilt by upstream)"
	echo "- https://aur.archlinux.org/packages/anki (source build)"
	echo "- https://aur.archlinux.org/packages/anki-qt5 (source build)"
	echo "- https://aur.archlinux.org/packages/anki-git (source build, using main development branch)"
}

pre_upgrade() {
	pre_install
}
