post_install() {
  post_upgrade
}

post_upgrade() {
  useradd -r antimony
  useradd -r antimony-lockdown

  chown antimony:antimony -R /usr/share/antimony
  chown antimony:antimony /usr/bin/antimony

  mkdir /usr/share/antimony/lockdown
  chown antimony-lockdown:antimony-lockdown /usr/share/antimony/utilities/antimony-lockdown
  chown antimony-lockdown:antimony-lockdown /usr/share/antimony/lockdown

  chmod ug+s /usr/bin/antimony
  chmod ug+s /usr/share/antimony/utilities/antimony-lockdown

  setcap cap_sys_ptrace+ep /usr/share/antimony/utilities/antimony-dumper
  setcap cap_audit_read+ep /usr/share/antimony/utilities/antimony-monitor
}

post_remove() {
  userdel antimony
  userdel antimony-lockdown
}
