post_install() {
	if pacman -Q env-modules &> /dev/null; then
		echo "env-modules seems to be installed:"
		echo "If configured correctly, you can conveniently use"
		echo "  $ module load aocl-gcc"
		echo "to set up the environment for AMD Optimizing CPU Libraries."
	fi
	echo "You can enable AMD Optimizing CPU Libraries globally"
	echo 'by creating `/etc/ld.so.conf.d/aocl-gcc.conf` containing:'
	echo " 	/opt/aocl/gcc/lib/"
	echo 'then running `ldconfig`'
}

post_upgrade() {
	post_install
}
