post_install() {
	mkdir -p /var/{lib,log}/apache-spark /opt/apache-spark/work
	groupadd -r -f apache-spark
	useradd -r -g apache-spark -s /usr/bin/nologin -d /var/lib/apache-spark apache-spark || true
	chown -R apache-spark:apache-spark /var/{lib,log}/apache-spark /opt/apache-spark/work
}

pre_remove() {
	pkill -u apache-spark
	sleep 4
	rm -rf /var/log/apache-spark /opt/apache-spark/work
	userdel -r apache-spark
}
