.TH APW 1 "2016-06-09" apw(1.7.x) "User Manuals"
.SH NAME
apw \- A package wrapper
.SH SYNOPSIS
.B apw [option] [packages]
.SH DESCRIPTION
.B apw
is a *multi-distribution* wrapper to manage packages.

It is case insensitive and is able to recognize commands with and without dashes 
.SH OPTIONS
.IP -U
Update system. If errors, you can do -Uf to force it
.IP -I
Install packages (Updates system also for preventing problems)
.IP -Ir
Reinstall packages (Updates system also for preventing problems)
.IP -R
Remove a package
.IP -Rd
Remove a package along with dependences that are not more in use (Only for Arch)
.IP -C
Clean system from dependences that are not in use (ADVANCED, BE CAREFUL!)
.IP -S
Search in package database
.IP -F
Install file (distro family dependent, e.g. .deb, .pkg.tar.xz,...)

Append y to -U or -I (-Uy -Iy -Iry) for autoconfirm the operations
.SH EXAMPLES
 #apw -I pimagizer cryptojka

 #apw -R google-chrome

 #apw -S libgcrypt
.SH AUTHOR AND CREDITS
apw is write and maintain by JKA Network <contacto@jkanetwork.com>
