# Maintainer: Maurício de Lima <mauriciodelima.mol@gmail.com>

#pre_install() {
	# do something here
#}

post_install() {
	sed -i /GRUB_THEME=/s/.*/GRUB_THEME="\/usr\/share\/grub\/themes\/archiso\/theme.txt"/ /etc/default/grub
}

#pre_upgrade() {
	# do something here
#}

post_upgrade() {
	post_install
	grub-mkconfig -o /boot/grub/grub.cfg
}

#pre_remove() {
	# do something here
#}

#post_remove() {
	# do something here
#}
 
