#!/bin/sh
                                                                                     
#                                   88            ad88                             88         
#                                   88           d8"               ,d              88         
#                                   88           88                88              88         
#  ,adPPYYba, 8b,dPPYba,  ,adPPYba, 88,dPPYba, MM88MMM ,adPPYba, MM88MMM ,adPPYba, 88,dPPYba, 
#  ""     `Y8 88P'   "Y8 a8"     "" 88P'    "8a  88   a8P_____88   88   a8"     "" 88P'    "8a
#  ,adPPPPP88 88         8b         88       88  88   8PP"""""""   88   8b         88       88
#  88,    ,88 88         "8a,   ,aa 88       88  88   "8b,   ,aa   88,  "8a,   ,aa 88       88
#  `"8bbdP"Y8 88          `"Ybbd8"' 88       88  88    `"Ybbd8"'   "Y888 `"Ybbd8"' 88       88
#
#

## Basic Configuration

user="$(whoami || printf "%s" "${HOME/*\/}")"
hostname="$(hostname)"
os='Arch Linux'
kernel="$(uname -sr)"
gpu="$(lspci -mm | awk -F '\\"|\\" \\"|\\(' \ '/"Display|"3D|"VGA/ {a[$0] = $3 " " $4} END{for(i in a){if(!seen[a[i]]++) print a[i]}}' | cut -d "[" -f2 | cut -d "]" -f1)"
cpu="$(awk -F ':' '/model name/\
 {printf $2; exit}' "/proc/cpuinfo"
)"
uptime="$(uptime -p | sed 's/up //')"
packages="$(pacman -Q | wc -l)"
shell="$(basename ${SHELL})"

## Basic Colors

bc="$(tput bold)"       # bold
c0="$(tput setaf 0)"	# black
c1="$(tput setaf 1)"	# red
c2="$(tput setaf 2)"	# green
c3="$(tput setaf 3)"	# yellow
c4="$(tput setaf 4)"	# blue
c5="$(tput setaf 5)"	# magenta
c6="$(tput setaf 6)"	# cyan
c7="$(tput setaf 7)"	# white
rc="$(tput sgr0)"       # reset

## Color Configuration

lc="${rc}${bc}${c6}"	# Labels
nc="${rc}${bc}${c3}"	# User and hostname
ic="${rc}${bc}${c7}"	# Info
fc="${rc}${bc}${c6}"	# First color
sc="${rc}${c6}"	        # Second color

## Generate & Present the output

cat <<EOF
${pc}      ___${rc}     ${nc}${user}${ic}@${nc}${hostname}${rc}
${pc}     (${rc}${c7}.·${rc} ${pc}|${rc}    ${lc}OS:         ${ic}${os}${rc}
${pc}     (${rc}${c3}<>${rc} ${pc}|${rc}    ${lc}KERNEL:     ${ic}${kernel}${rc}
${pc}    /${rc} ${c7}__${rc}  ${pc}\\${rc}   ${lc}UPTIME:     ${ic}${uptime}${rc}
${pc}   (${rc} ${c7}/  \\${rc} ${pc}/|${rc}  ${lc}PACKAGES:   ${ic}${packages}${rc}
${c3}  _${pc}/\\${rc} ${c7}__)${rc}${pc}/${rc}${c3}_${rc}${pc})${rc}  ${lc}SHELL:      ${ic}${shell}${rc}
${c3}  \/${pc}-____${rc}${c3}\/${rc}   ${lc}CPU:       ${ic}${cpu}${rc}
${c3}              ${lc}GPU:        ${ic}${gpu}${rc}


EOF
