post_upgrade() {
	if [ $(vercmp $2 141.r46.g8433666dc-5) -lt 0 ]; then cat << EOF
********************************************************************************
* With v142 release, Ares has changed its build system from GNU Make to CMake  *
* making the build process more flexible.                                      *
* Furthermore, Retro shaders, which were recently included in Ares upstream,   *
* are bundled off to 'libretro-shaders' package, which is now a dependency.    *
* This allows 70%-75% reduction of Ares package's size compared to v141.       *
********************************************************************************
EOF
fi
}
