post_install() {
  echo -e "======================================================================="
  echo -e " Arm Compiler for Embedded has been installed"
  echo -e "  License terms: /usr/share/licenses/arm-compiler-for-embedded-bin/license_terms"
  echo -e "  Please review them carefully before use."
  echo -e ""
  echo -e " \e[1;33m==> IMPORTANT: License Activation\e[0m"
  echo -e "  A valid license is required to operate:"
  echo -e "  - Commercial use: Activate purchased code via 'armlm'."
  echo -e "  - Non-Commercial use: Free MDK Community License is available."
  echo -e "  To activate the free license, run the following (do not use sudo):"
  echo -e "\e[1;32m    armlm activate -product KEMDK-COM0 -server https://mdk-preview.keil.arm.com\e[0m"
  echo -e "======================================================================="
}

post_upgrade() {
  post_install
}
