post_install() {
  cat <<EOF
"asciiworld-waypoints", an optional tool not required by the core
"asciiworld" program, requires the python2 library "geographiclib". It
used to be available as an AUR package but has not been migrated to
AUR 4.

Either use the old PKGBUILD [1] or install the package using pip:

  # pip2 install geographiclib

[1]: http://pkgbuild.com/git/aur-mirror.git/tree/python2-geographiclib/PKGBUILD
EOF
}

post_upgrade() {
  post_install "$1"
}
