post_upgrade() {
  if [ $(systemctl is-active asusd.service) == "active" ]
    then
      printf ":: asusd is running, and requires a restart of the service…\n"
      systemctl restart asusd.service
  fi
    if [ $(systemctl is-active asusd-nohwdep.service) == "active" ]
    then
      printf ":: asusd is running, and requires a restart of the service…\n"
      systemctl restart asusd-nohwdep.service
  fi
}

