#!/usr/bin/env bash
# Original code (C) Felipe Facundes — GPL-3.0-only
# Modifications (C) Selene Bray-Hernandez — MIT
# SPDX-License-Identifier: GPL-3.0-only AND MIT

libtorch_cuda="/opt/libtorch-cuda"
libtorch_cpu="/opt/libtorch-cpu"

if [ -d "$libtorch_cuda" ]; then
	export LD_LIBRARY_PATH="/opt/libtorch-cuda/lib:/usr/lib"
elif [ -d "/opt/libtorch" ]; then
	export LD_LIBRARY_PATH="/opt/libtorch/lib:/usr/lib"
elif [ -d "$libtorch_cpu" ]; then
	export LD_LIBRARY_PATH="/opt/libtorch-cpu/lib:/usr/lib"
fi

audacity "$@"