[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/audiomuse-ai-web/supervisord.pid
childlogdir=/var/tmp/audiomuse-ai-web

[unix_http_server]
file=/run/audiomuse-ai-web/supervisor.sock
chmod=0600

[supervisorctl]
serverurl=unix:///run/audiomuse-ai-web/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:flask]
command=/usr/bin/gunicorn --bind 0.0.0.0:8000 --workers 1 --threads 4 --worker-class gthread --keep-alive 5 --timeout 300 --capture-output --error-logfile - --access-logfile - app:app
directory=/usr/lib/audiomuse-ai-web
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
priority=20
stdout_logfile=/var/tmp/audiomuse-ai-worker/%(program_name)s.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/tmp/audiomuse-ai-worker/%(program_name)s.stderr.log
stderr_logfile_maxbytes=0

[program:config-restart-listener]
command=/usr/bin/python -u -m taskqueue.control
directory=/usr/lib/audiomuse-ai-web
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
priority=10
stdout_logfile=/var/tmp/audiomuse-ai-worker/%(program_name)s.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/tmp/audiomuse-ai-worker/%(program_name)s.stderr.log
stderr_logfile_maxbytes=0