[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/run/audiomuse-ai-worker/supervisord.pid
childlogdir=/var/tmp/audiomuse-ai-worker

[unix_http_server]
file=/run/audiomuse-ai-worker/supervisor.sock
chmod=0600

[supervisorctl]
serverurl=unix:///run/audiomuse-ai-worker/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[program:config-restart-listener]
command=/usr/bin/python -u -m taskqueue.control
directory=/usr/lib/audiomuse-ai-worker
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
priority=10
stdout_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stderr.log
stderr_logfile_maxbytes=0

[program:queue-worker-high]
command=/usr/bin/python -u -m taskqueue.worker --queue high
directory=/usr/lib/audiomuse-ai-worker
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
priority=20
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stderr.log
stderr_logfile_maxbytes=0

[program:queue-worker-default]
command=/usr/bin/python -u -m taskqueue.worker --queue default
directory=/usr/lib/audiomuse-ai-worker
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
priority=20
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stderr.log
stderr_logfile_maxbytes=0

[program:queue-maintenance]
command=/usr/bin/python -u -m taskqueue.maintenance
directory=/usr/lib/audiomuse-ai-worker
autostart=true
autorestart=true
stopsignal=TERM
stopasgroup=true
killasgroup=true
stopwaitsecs=5
priority=30
environment=PYTHONUNBUFFERED="1"
stdout_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stdout.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/audiomuse-ai-worker/%(program_name)s.stderr.log
stderr_logfile_maxbytes=0
