#!/bin/sh

post_install() {
  SETTINGS_FILE="/etc/aur-check-rebuild"
  EXEC_FILE="/usr/share/libalpm/scripts/aur-check-rebuild/main.py"

  if [ ! -f "$SETTINGS_FILE" ]; then
    echo "Creating configuration file..."
    "$EXEC_FILE" --settings
  fi

  pip list | grep pyalspm > /dev/null 2>&1
  if [ $? -eq 1 ]; then
    echo "Installing pyalpm lib..."
    pip install --root-user-action ignore --break-system-packages pyalpm
  fi

  echo ""
  echo "This hook will look for AUR packages that requires rebuild to keep working due to ABI changes in shared libraries."
  echo ""
  echo "You can change the behaviour editing the following file"
  echo "    $SETTINGS_FILE"
  echo ""
  echo "Logs can be found here"
  echo "    $($EXEC_FILE --logpath)"
  echo ""
}
post_upgrade() {
  post_install
}