#!/usr/bin/env bash

set -euo pipefail

echo "Creating user"
useradd -m user
su user -c 'git clone https://aur.archlinux.org/slf4j.git /tmp/slf4j'
cd /tmp/slf4j
su user -c makepkg
userdel user
pacman -U --noconfirm ./slf4j-*-any.pkg.tar.zst
