post_install() {
  cat << EOF
==> Put the followings in your \$HOME/.emacs file to use auto-complete-nxml
;; auto-complete-nxml
(require 'auto-complete-nxml)

;; Keystroke for popup help about something at point.
(setq auto-complete-nxml-popup-help-key "C-:")

;; Keystroke for toggle on/off automatic completion.
(setq auto-complete-nxml-toggle-automatic-key "C-c C-t")

;; If you want to start completion manually from the beginning
(setq auto-complete-nxml-automatic-p nil)
EOF
}
