post_install() {
    echo -e "\n\033[1;32m========================================================================\033[0m"
    echo -e "\033[1;37m  AutoSync was successfully installed!\033[0m"
    echo -e "\033[1;32m========================================================================\033[0m"
    echo -e "  Before use, create your config file in:"
    echo -e "  ~/.config/autosync/config.toml\n"
    echo -e "  See https://gitlab.com/alukhia/autosync/ for the configuration guide."
    echo -e "  To enable automatic background synchronization, run:"
    echo -e "  \033[1;33msystemctl --user enable --now autosync.timer\033[0m"
    echo -e "\033[1;32m========================================================================\033[0m\n"
}

post_upgrade() {
    post_install
}
