#!/usr/bin/openrc-run
# Copyright 1999-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

extra_started_commands="reload"

depend() {
	need avahi-daemon
	use net
}

start() {
	ebegin "Starting avahi-dnsconfd"
	/usr/bin/avahi-dnsconfd -D
	eend $?
}

stop() {
	ebegin "Stopping avahi-dnsconfd"
	/usr/bin/avahi-dnsconfd -k
	eend $?
}

reload() {
	ebegin "Reloading avahi-dnsconfd"
	/usr/bin/avahi-dnsconfd -r
	eend $?
}
