compile_firmware() {
    echo '##### compiling firmware... #####'
    cd /opt/axoloti-runtime/platform_linux
    BUILDDIR=/opt/axoloti-runtime/firmware/build ./compile_firmware.sh
}

remove_firmware() {
    rm -rf /opt/axoloti-runtime/firmware
}

post_install() {
    compile_firmware
    echo 'Launch the GUI by running the script at /usr/bin/axoloti'
}

post_upgrade() {
    compile_firmware
}

pre_remove() {
    remove_firmware
}
