post_install()
{
    if which pycompile >/dev/null 2>&1; then
        pycompile -p ayatana-webmail
    fi

    glib-compile-schemas usr/share/glib-2.0/schemas
}

post_upgrade()
{
    post_install
}

pre_remove()
{
    if which pyclean >/dev/null 2>&1; then
        pyclean -p ayatana-webmail
    else
        pacman -Qql ayatana-webmail | grep '\.py$' | while read file
        do
            rm -f "${file}"[co] >/dev/null
        done
    fi
}

post_remove()
{
    glib-compile-schemas usr/share/glib-2.0/schemas
}



