# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
#pre_install() {
	# do something here
#}

## arg 1:  the new package version
post_install() {
	echo "Azahar 2021.1 has fixed a bug dealing with save states, resulting in any save state made before this version to be invalid. Use Vulkan renderer to create an in-game save"
}

## arg 1:  the new package version
## arg 2:  the old package version
#pre_upgrade() {
	# do something here
#}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
	# do something here
	echo "Azahar 2021.1 has fixed a bug dealing with save states, resulting in any save state made before this version to be invalid. Use Vulkan renderer to create an in-game save"
}

## arg 1:  the old package version
#pre_remove() {
	# do something here
#}

## arg 1:  the old package version
#post_remove() {
	# do something here
#}
