post_install() {
	_realmlist_ip=$(cat /tmp/azerothcore-wotlk-git-realmlist-ip)

	if command -v systemctl >/dev/null 2>&1; then
    	sudo systemctl daemon-reload >/dev/null 2>&1 || true
    fi

	if [[ ! -f /etc/azerothcore/authserver.conf ]]; then
		sudo cp /etc/azerothcore/authserver.conf.dist /etc/azerothcore/authserver.conf
	fi

	if [[ ! -f /etc/azerothcore/worldserver.conf ]]; then
		sudo cp /etc/azerothcore/worldserver.conf.dist /etc/azerothcore/worldserver.conf
	fi

	# I'm not distributing acore.sh for now
	#if [[ ! -f /usr/share/azerothcore/conf/config.conf ]]; then
	#	sudo cp /usr/share/azerothcore/conf/dist/config.conf /usr/share/azerothcore/conf/config.conf
	#fi

	# If source dir is empty, point it to our install location
	sudo sed -i 's#^SourceDirectory\s*=\s*""#SourceDirectory = "/usr/share/azerothcore"#' /etc/azerothcore/authserver.conf

	# Restart authserver
  	sudo systemctl restart acore-auth-server.service

	# Start worldserver
  	sudo systemctl start acore-world-server.service

	# Enable needed services
	sudo systemctl enable acore-auth-server.service
	sudo systemctl enable acore-world-server.service
	sudo systemctl enable mysqld.service

  	# Display some instructions
	echo ''
	echo ''
	echo '#####################  IMPORTANT  #####################'
	echo ''
	echo "The installation has finished. please, follow these steps to connect to the server:"

	echo ' TO BE FILLED IN'

	echo ''
	echo ''
	echo "#######################  NOTES  #######################"

	echo ''
	echo "the server is already running. If you reboot the computer, the server will also automatically run on boot (you can disable this by running 'sudo systemctl disable acore-{auth,world}-server.service')"

	echo ''
	echo ''
	echo "a list of GM commands is available on this link: https://www.azerothcore.org/wiki/gm-commands"

	echo ''
	echo ''
	echo 'the server may take some time to fully boot up, so if you can login, but is stuck at realm selection screen, maybe the server is still booting up, in this case just wait a few minutes and try again'
}

post_upgrade() {
    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload >/dev/null 2>&1 || true
    fi
}

pre_remove() {
	sudo systemctl stop acore-auth-server.service
	sudo systemctl stop acore-world-server.service

	sudo systemctl disable acore-auth-server.service
	sudo systemctl disable acore-world-server.service

	sudo rm -f /etc/systemd/system/acore-auth-server.service
	sudo rm -f /etc/systemd/system/acore-world-server.service
	sudo systemctl daemon-reload
}
