# 释放包中文件前运行的脚本。传递一个参数：新版本号。
#pre_install() {
	# do something here
#}

# 释放包中文件后运行的脚本。传递一个参数：新版本号。
post_install() {
  git clone https://github.com/LmeSzinc/AzurLaneAutoScript.git /opt/azurlaneautoscript/app
  python3.7 -m venv /opt/azurlaneautoscript/venv
  source /opt/azurlaneautoscript/venv/bin/activate
  pip install --no-cache-dir -r /opt/azurlaneautoscript/app/deploy/docker/requirements.txt
  pip install --no-cache-dir mxnet-alas
  cp /opt/azurlaneautoscript/app/config/deploy.template-linux.yaml /opt/azurlaneautoscript/app/config/deploy.yaml
}

# 释放包中文件前运行的脚本。两个参数按以下顺序传递：新版本号，旧版本号。
#pre_upgrade() {
	# do something here
#}

# 释放包中文件后运行的脚本。两个参数按以下顺序传递：新版本号，旧版本号。
#post_upgrade() {
	# do something here
#}

# 文件被删除前运行的脚本，传递一个参数：旧版本号。
#pre_remove() {
	# do something here
#}

# 文件被删除后运行的脚本，传递一个参数：旧版本号。
post_remove() {
  rm -rf /opt/azurlaneautoscript
}

