post_install() {
  echo "-- If you want to modify config.h (which has some GUI and WebKit parameters), you can do so by accessing the build directory (directory location varies depending on how you built it, e.g with makepkg or yay)."
  /bin/true
}

post_upgrade() {
  echo "-- Badwolf 1.0.0 changelog: the user interface is now customizable through interface.css (you'll have to modify it and then rebuild the package). A logo has been made. Downloads tab, back/forward, print buttons. You can toggle the automatic loading of images."
  /bin/true
}
