post_install() {
  echo "-- If you want to modify config.h (which has some GUI and WebKit parameters), you can do so by accessing the build directory (directory location varies depending on how you built it, e.g with makepkg or yay)."
  /bin/true
}

post_upgrade() {
  echo "-- Badwolf 1.0.2 changelog: Support for relative paths as command line arguments. Downloads tab no longer resizes the main window. Manpage's syntax doesn't break GNU groff anymore. When a new tab is opened by the user, switch to it."
  /bin/true
}
