post_install() {
  echo "-- If you want to modify config.h (which has some GUI and WebKit parameters), you can do so by accessing the build directory (directory location varies depending on how you built it, e.g with makepkg or yay)."
  /bin/true
}

post_upgrade() {
  echo "-- Badwolf 1.0.3 changelog: Added Turkish translation. Fixed a segfault found on some platforms when both removing a tab and destroying its child. Fixed a WebKitNetworkProcess leak. Changed Makefile and badwolf.c."
  /bin/true
}
