yellow='\e[0;33m'
coloroff='\e[0m'

post_install() {
   /usr/lib/bareos/scripts/bareos-config initialize_local_hostname
   /usr/lib/bareos/scripts/bareos-config initialize_passwords

   chown -R bareos:bareos /usr/share/bareos/config/bareos-dir.d
   chown bareos:bareos /usr/bin/bareos-dir

   /usr/lib/bareos/scripts/bareos-config initialize_database_driver
   /usr/lib/bareos/scripts/bareos-config apply_dbconfig_settings
}

post_upgrade() {
   post_install
   echo -e "${yellow}NOTE: Renamed bareos-dir.service to bareos-director.service${coloroff}"
}
