yellow='\e[0;33m'
coloroff='\e[0m'

# arg 0:  the new package version
post_install() {
   echo -e "${yellow}NOTE: Please see documentation to setup database${coloroff}"
}

# arg 0:  the new package version
# arg 2:  the old package version
post_upgrade() {
   echo -e "${yellow}NOTE: Please see documentation to setup database${coloroff}"
}

# arg 0:  the old package version
post_remove() {
   echo -e "${yellow}NOTE: To remove all traces of bareos please delete the bareos database.${coloroff}"
}
