## arg 1:  the new package version
post_install() {
	/usr/lib/bareos/scripts/bareos-config initialize_local_hostname
	/usr/lib/bareos/scripts/bareos-config initialize_passwords

	chown -R bareos:bareos /etc/bareos/tray-monitor.d/
	chmod -R 750 /etc/bareos/tray-monitor.d/

	chown -R root:bareos /etc/bareos/tray-monitor.d/
	chmod -R 755 /etc/bareos/tray-monitor.d
}

post_upgrade() {
	post_install
}
