# shellcheck shell=bash
_alert() {
cat << 'EOF'
Barnard UI server list format changed. If you used barnard-ui before this update, remove the old server list before starting barnard-ui again:
  rm -f ~/.config/barnard/servers.conf

For alerts and sound options, install the sox package and add the following line to your ~/.barnard.toml:
notifycommand = '/usr/share/barnard/barnard-sound.sh "%event" "%who" "%what"'
Make sure to edit the sound script to use your preferred settings.
EOF
}

post_install() {
    _alert
}

post_upgrade() {
    _alert
}
