
preexec_path="/usr/share/bash-preexec/bash-preexec.sh"  # bash-preexec dependancy
bash_timer_path="/usr/share/bash-timer/bash-timer.sh"
tag="## MANAGED BY AUR PACKAGE BASH-TIMER"

bash_timer_bashrc=$(cat <<EOF

$tag
if [[ -f "$preexec_path" ]]; then source "$preexec_path"; fi; $tag
if [[ -f "$bash_timer_path" ]]; then source "$bash_timer_path"; fi;       $tag
$tag

EOF
)

function remove_managed_blocks() {
    local file="$1"
    local tmpfile="${file}.$(date +'%Y%m%d.%H%M%S').tmp"
    cp "$file" "$tmpfile"
    cat "$tmpfile" \
      |grep -v "$tag" \
      >"$file"
}

function post_install() {

    bashrc_targets=(
        $(ls /home/*/.bashrc)
    )

    echo "Editing .bashrc for each user:"
    for bashrc in "${bashrc_targets[@]}"; do
        echo "  * ${bashrc}"
        remove_managed_blocks "$bashrc"
        echo "$bash_timer_bashrc" >> $bashrc
    done
}

function post_remove() {

    bashrc_targets=(
        $(ls /home/*/.bashrc)
    )

    echo "Editing .bashrc for each user:"
    for bashrc in "${bashrc_targets[@]}"; do
        echo "  * ${bashrc}"
        remove_managed_blocks "$bashrc"
    done
}