# This is a default template for a post-install scriptlet.  You can
# remove any functions you don't need (and this header).

# arg 1:  the new package version
post_install() {
  cat << EOF
Setting up battery-status
-------------------------

sudo systemctl enable battery-status-collect.timer
sudo systemctl start battery-status-collect.timer
sudo systemctl enable battery-status-collect-suspend.service
EOF
}

post_upgrade() {
  post_install $1
}

op=$1
shift
$op $*
