# Colored makepkg-like functions by Det
msg_blue() {
    printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note "It is necessary to enable 'File Manager Integration' under 'Tools' -> 'Options' from Beyond Compare interface."
}

post_upgrade() {
    post_install
}
