post_install() {
  dkms_install $1
}

pre_upgrade() {
  dkms_remove $2
}

post_upgrade() {
  dkms_install $1
}

pre_remove () {
  dkms_remove $1
}

dkms_remove() {
  local line=`dkms status -m bcwc-pcie`
  if echo "$line" | grep -E 'added|built|installed'; then
    dkms remove -m bcwc-pcie -v ${1%%-*} --all
  fi
}

dkms_install() {
  dkms install -m bcwc-pcie -v ${1%%-*}
  modprobe facetimehd

  /usr/bin/depmod -a
}
