#!/usr/bin/env sh
# -*- coding: UTF-8 -*- 
# Copyright (C) 2017 Armando Ibarra
# 
#----------------------------------------------------------------------
#
# Author: Ing. Armando Ibarra - armandoibarra1@gmail.com
# Email: armandoibarra1@gmail.com
# Date: 27/09/2017
# Purpose:
#  Open easy the Beaker Browser app
#
#----------------------------------------------------------------------
# NOTES:    
#----------------------------------------------------------------------

#    Test on Arch linux x64
#----------------------------------------------------------------------

###############################################################################

# Licensed under the GNU GPL v3 - http://www.gnu.org/licenses/gpl-3.0.txt
# - or any later version.

# A Desktop launcher for Beaker Browser

# @author: Ing. Armando Ibarra

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

###############################################################################

#variables

AUTHOR='Ing. Armando Ibarra <armandoibarra1@gmail.com>'
BEAKER_PATH_SOURCE="/opt/beakerbrowser"
BEAKER_BIN_PATH="/usr/bin/beakerbrowser"
BEAKER_ELECTRON_PATH="electron --app=/opt/beakerbrowser"

if [ ! -d "$BEAKER_PATH_SOURCE" ] ; then
  echo "/opt/beakerbrowser no exist" || exit 1
fi

#exec /usr/bin/beakerbrowser $@
cd $BEAKER_PATH_SOURCE; npm start;

exit 0