# systemd service options
LISTEN_HOST=0.0.0.0
LISTEN_PORT=8090

# for other options see https://beszel.dev/guide/environment-variables#hub
#BESZEL_HUB_APP_URL=https://example.com/path/
#BESZEL_HUB_CHECK_UPDATES=false
