all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
red="${bold}$(tput setaf 1)"

warn() {
  printf "${blue}==>${red} WARN:${bold} $1${all_off}\n"
}

post_install() {
  warn "If you want to use the upgraded version immediately, please stop your beyond-identity services by:"
  warn "killall --verbose --quiet byndid"
  warn "Running 'beyond-identity --help' will restore them."
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
