all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
red="${bold}$(tput setaf 1)"

warn() {
  printf "${blue}==>${red} WARN:${bold} $1${all_off}\n"
}

post_install() {
  if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q
  else
    warn "Could not rebuild MIME database, update-desktop-database is not found or not executable"
  fi
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
