#!/usr/bin/sh


cookies_db="$1"

tmpdir=$(mktemp -d)
cp "$1" $tmpdir

sqlite3 -newline '; ' -separator = "$tmpdir/cookies.sqlite" "select name, value  from moz_cookies where host = '.bilibili.com' and ( name = 'bili_jct' or name = 'SESSDATA' or name = 'DedeUserID')"

rm $tmpdir/cookies.sqlite
rmdir $tmpdir
