function func_write_log()
{
    var_str=$1
    var_color=$2
    if [ "x${var_str}" == "x" ];then
        var_str=""
    else
        var_str="${var_str}"
    fi
    if [ "${var_color}" == "g" ];then #green
        var_str="\n\033[32m${var_str}\033[0m"
    elif [ "${var_color}" == "y" ];then #yellow
        var_str="\033[33m${var_str}\033[0m"
    elif [ "${var_color}" == "r" ];then #red
        var_str="\033[1;41;33m${var_str}\033[0m"
    else
        var_str="\033[37m${var_str}\033[0m"
    fi
    echo -e "${var_str}"
}

## arg 1:  the new package version
post_install() {
	func_write_log "弹幕输出位于 ~/Downloads/BiLiBiLi_DanMu_Crawling/output/ 下" "g"
	func_write_log "若需要修改，请自行更改 /usr/share/applications/BiLiBiLi_DanMu_Crawling.desktop" "y"
}
