post_install() {
  # Setup install location in config file.
  sed -i 's/INSTALLDIR/\/opt\/zynamics\/BinDiff\//' /etc/opt/zynamics/BinDiff/bindiff.xml

  # Add application launcher to desktop DB
  update-desktop-database -q

  # Notify the user about the IDA plugins
  echo "You will need to fetch the IDA plugins:"
  echo "https://dl.google.com/dl/zynamics/bindiff420-win-pluginsonly.zip"
}

post_upgrade() {
  post_install
}

post_remove() {
  update-desktop-database -q
}
