post_install() {
	# lpr
	/opt/brother/Printers/dcpj315w/inf/setupPrintcapij dcpj315w -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj315w/cupswrapper/cupswrapperdcpj315w
	
	systemctl restart org.cups.cupsd.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj315w/inf/setupPrintcapij dcpj315w -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj315w/cupswrapper/cupswrapperdcpj315w -e
}

op=$1
shift

$op "$@"

