post_install() {
	# lpr
	/opt/brother/Printers/dcpj100/inf/setupPrintcapij dcpj100 -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj100/cupswrapper/cupswrapperdcpj100
	
	systemctl restart org.cups.cupsd.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj100/inf/setupPrintcapij dcpj100 -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj100/cupswrapper/cupswrapperdcpj100 -e
}

op=$1
shift

$op "$@"

