post_install() {
	# lpr
	/opt/brother/Printers/dcpj552dw/inf/setupPrintcapij dcpj552dw -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj552dw/cupswrapper/cupswrapperdcpj552dw
	
	systemctl restart org.cups.cupsd
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj552dw/inf/setupPrintcapij dcpj552dw -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj552dw/cupswrapper/cupswrapperdcpj552dw -e
}

op=$1
shift

$op "$@"

