post_install() {
	mkdir -p $pkgdir/var/spool/lpd

	# lpr
	/opt/brother/Printers/dcpj1140dw/inf/setupPrintcapij dcpj1140dw -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj1140dw/cupswrapper/cupswrapperdcpj1140dw
	
	systemctl restart cups.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj1140dw/inf/setupPrintcapij dcpj1140dw -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj1140dw/cupswrapper/cupswrapperdcpj1140dw -e
}

op=$1
shift

$op "$@"
