post_install() {
	# lpr
	/opt/brother/Printers/dcpj972n/inf/setupPrintcapij dcpj972n -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj972n/cupswrapper/cupswrapperdcpj972n
	
	systemctl restart org.cups.cupsd.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj972n/inf/setupPrintcapij dcpj972n -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj972n/cupswrapper/cupswrapperdcpj972n -e
}

op=$1
shift

$op "$@"

