post_install() {
	# lpr
	/opt/brother/Printers/mfcj245/inf/setupPrintcapij mfcj245 -i
	
	# cupswrapper
	/opt/brother/Printers/mfcj245/cupswrapper/cupswrappermfcj245
	
	systemctl restart org.cups.cupsd.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/mfcj245/inf/setupPrintcapij mfcj245 -e
	
	# cupswrapper
	/opt/brother/Printers/mfcj245/cupswrapper/cupswrappermfcj245 -e
}

op=$1
shift

$op "$@"

