post_install() {
	# lpr
	/opt/brother/Printers/dcpj4110dw/inf/setupPrintcapij dcpj4110dw -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj4110dw/cupswrapper/cupswrapperdcpj4110dw
	
	systemctl restart org.cups.cupsd.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj4110dw/inf/setupPrintcapij dcpj4110dw -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj4110dw/cupswrapper/cupswrapperdcpj4110dw -e
}

op=$1
shift

$op "$@"

