post_install() {
	# lpr
	/opt/brother/Printers/dcpj132w/inf/setupPrintcapij dcpj132w -i
	
	# cupswrapper
	/opt/brother/Printers/dcpj132w/cupswrapper/cupswrapperdcpj132w
	
	systemctl restart org.cups.cupsd.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpj132w/inf/setupPrintcapij dcpj132w -e
	
	# cupswrapper
	/opt/brother/Printers/dcpj132w/cupswrapper/cupswrapperdcpj132w -e
}

op=$1
shift

$op "$@"

