post_install() {
  # lpr
  /opt/brother/Printers/dcpj772dw/inf/setupPrintcapij dcpj772dw -i

  # cupswrapper
  /opt/brother/Printers/dcpj772dw/cupswrapper/cupswrapperdcpj772dw

  systemctl restart cups.service
}

post_upgrade() {
  /bin/true
}

pre_remove() {
  # lpr
  /opt/brother/Printers/dcpj772dw/inf/setupPrintcapij dcpj772dw -e

  # cupswrapper
  /opt/brother/Printers/dcpj772dw/cupswrapper/cupswrapperdcpj772dw -e
}

op=$1
shift

$op "$@"

