post_install() {
	# lpr
	/opt/brother/Printers/dcpt300/inf/setupPrintcapij dcpt300 -i
	
	# cupswrapper
	/opt/brother/Printers/dcpt300/cupswrapper/cupswrapperdcpt300
	
	systemctl restart cups.service
}

post_upgrade() {
	/bin/true
}

pre_remove() {
	# lpr
	/opt/brother/Printers/dcpt300/inf/setupPrintcapij dcpt300 -e
	
	# cupswrapper
	/opt/brother/Printers/dcpt300/cupswrapper/cupswrapperdcpt300 -e
}

op=$1
shift

$op "$@"

