post_install() {
    xdg-desktop-menu install /opt/btrustbiss/lib/btrustbiss-BISS.desktop
    sudo cp /opt/btrustbiss/lib/btrustbiss-BISS.desktop /etc/xdg/autostart
    systemctl enable --now pcscd
}

post_upgrade() {
    xdg-desktop-menu install /opt/btrustbiss/lib/btrustbiss-BISS.desktop
    sudo cp /opt/btrustbiss/lib/btrustbiss-BISS.desktop /etc/xdg/autostart
    systemctl enable --now pcscd
}
