# vim: ft=sh ts=4 sw=4 et

post_install () {
    echo "== The /usr/bin/bwrap binary has been installed setuid root."
    echo "   If you will be using a kernel with the USER_NS option enabled,"
    echo "   you may want to use disable the setuid bit. For this, run:"
    echo ""
    echo "    # chmod u-s /usr/bin/bwrap"
    echo ""
    chmod u+s /usr/bin/bwrap
}

post_upgrade () {
    post_install
}
