#!/bin/bash
# default config
# default build arches
CPU_ARCHES=(sandybridge skylake broadwell silvermont)
# load local build script if found to apply gpg settings or alike, if existing
if [ -e build_pkgs.local ] ; then
    source build_pkgs.local
fi
# FIXME maybe check for local changes
# build generic first
git checkout .
echo 'source+=(batch_opts)' >> PKGBUILD
touch batch_opts
updpkgsums
makepkg -f --cleanbuild

for cpu in ${CPU_ARCHES[*]} ; do
   git checkout PKGBUILD
   cat >> PKGBUILD <<EOF
source+=(batch_opts)
pkgname=(linux-pf-$cpu)
eval "package_linux-pf-$cpu() {
     \$(declare -f _package)
     _package
     }"
EOF
    echo "CPU=$cpu" > batch_opts
    updpkgsums
    makepkg -f --cleanbuild
done
git checkout .
