#!/bin/bash -e
# default config
# default build arches
DEFAULT_CPU_ARCHES=(generic generic-v2 generic-v3 generic-v4
                    zen2 zen3
                    skylake broadwell rocketlake alderlake
                   )


build_pkg()
{
    echo 'source+=(batch_opts)' >> PKGBUILD
    updpkgsums
    makepkg --cleanbuild
}

# FIXME maybe check for local changes
if ! git diff-index --quiet HEAD -- ; then
    echo 'local changes found, please commit first' >&2
    echo 'exit'
    exit 1
fi

# load local build script if found to apply gpg settings or alike, if existing
if [ -e build_pkgs.local ] ; then
    source build_pkgs.local
fi

git checkout .

for cpu in ${*:-${DEFAULT_CPU_ARCHES[*]}} ; do
    git checkout PKGBUILD
    case $cpu in
        generic)
            cat >> PKGBUILD <<EOF
pkgname=(linux-pf-$cpu linux-pf-headers-variant-$cpu linux-pf-headers)
EOF
            ;;
        *)
            cat >> PKGBUILD <<EOF
pkgname=(linux-pf-$cpu linux-pf-headers-variant-$cpu)
EOF
            ;;
    esac

    cat >> PKGBUILD <<EOF
eval "package_linux-pf-headers-variant-$cpu() {
     \$(declare -f "_package-headers-variant")
     _package-headers-variant
     }"
eval "package_linux-pf-$cpu() {
     \$(declare -f "_package")
     _package
     }"
EOF
    echo "LCPU=$cpu" > batch_opts

    build_pkg

    git checkout .
done

# eval "package_linux-pf-$cpu() {
#      \$(declare -f _package)
#      _package
#      }"
