#!/usr/bin/bash

if [ -n "$CAJVIEWER_WINEPREFIX" ]; then
    export WINEPREFIX="$CAJVIEWER_WINEPREFIX"
fi

XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME/.local/share"}

prog=$(winepath -u "C:\\Program Files\\TTKN\\CAJViewer 7.2\\CAJVieweru.exe")
installer="/usr/share/cajviewer/installer.exe"

function install() {
    winetricks -q mdac28 mfc42
    tmpdir="$(mktemp -d)"
    wine "$installer" /Q /T:$(winepath -w "$tmpdir") /C
    msiexec /i "${tmpdir}/CAJViewer 7.2.msi" /qb-
    rm -rf "$tmpdir"
    rm -rf "$XDG_DATA_HOME/applications/wine/Programs/同方知网/CAJViewer"
}

if [ ! -e "$prog" ]; then
    install
fi

exec wine "$prog" $@
