#!/usr/bin/env sh

export WINEARCH='win32'
export WINEPREFIX="$HOME/.wine32"
export WINEDEBUG=fixme-all

if [ ! -d "$HOME/.captvty" ]; then
  mkdir -p "$HOME/.captvty"
  ln -s /usr/share/captvty/Captvty.exe "$HOME/.captvty/"
  ln -s /usr/share/captvty/Captvty.exe.config "$HOME/.captvty/"
  ln -s /usr/share/captvty/tools "$HOME/.captvty/tools"
fi

winetricks -q dotnet45 comctl32
if [ $(uname -m) = 'x86_64' ]; then
  LD_PRELOAD='/usr/lib32/libjpeg.so.62' wine "$HOME/.captvty/Captvty.exe"
else
  wine "$HOME/.captvty/Captvty.exe"
fi


