post_install() {
	cat <<-EOF

To start Cardano node on mainnet, enable the service:
  systemctl enable --now cardano-node@mainnet.service

(Optional) To run a testnet, enable the testnet service instance:
  systemctl enable --now cardano-node@preview.service

Valid networks are 'mainnet', 'preview' and 'preprod'

EOF
}

post_remove() {
	cat <<-EOF

NOTE: the "cardano" user, and any files in its home directory, likely still
remain on disk! If you wish to clean this up, run "userdel -r cardano".

EOF
}
