#!/bin/sh

. /usr/share/makepkg/util/message.sh
colorize

post_install() {
	msg 'Mods will be stored in the user-specific data directory (XDG_DATA_HOME)'
	msg 'Settings will be stored in the user-specific configuration directory (XDG_CONFIG_HOME)'
}

post_upgrade() {
	set -- "${1}" "${2}" "${1#*:}" "${2#*:}"
	set -- "${1}" "${2}" "${3%%-*}" "${4%%-*}"
	set -- "${1}" "${2}" "${3%%.*}" "${4%%.*}"

	set -- "${1}" "${2}" "$(("${3}" - "${4}" - 1))"
	if [ "${3}" -gt 0 ]; then
		warning 'Upgraded from %s to %s, skipping %s major version(s).' "${2}" "${1}" "${3}"
		plainerr 'This may result in error loss. You have been warned.'
	fi
}

post_remove() {
	msg 'Mods will remain in the user-specific data directory (XDG_DATA_HOME)'
	msg 'Settings will remain in the user-specific configuration directory (XDG_CONFIG_HOME)'
}
