signa(){
    #get rid of Testing use only watermark
    echo "3249c5b75bccae3ce4f3a65e88154133:037beb866bf8830dd7c3956cb0746c02077cfc8e628f837db0ba8666b127700b07:027af2d53eae960ad291c066b0267157567ea68462f9985f86c3916abe767101027ef2d43daf9659d2c19e38b02676575079a7d663fa980a86c29469bf257151027e" > etc/ati/signature
}

whisperer(){
    echo "----------------------------------------------------------------"
    echo "Note: hook was replaced by dkms"
    echo "----------------------------------------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
    echo "kernel /boot/vmlinuz-linux root=/dev/sda1 ro nomodeset"
    echo "Note: don't do this if you have pxp/hybrid"
    echo "----------------------------------------------------------------"
    echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
    echo "--------------------- ^^^^^^^^^ --------------------------------"
    echo "fglrx was added into /etc/modules-load.d/catalyst.conf"
    echo "----------------------------------------------------------------"
    echo "	atieventsd (needs acpid pkg) on systemd:"
    echo "systemctl enable atieventsd"
    echo "systemctl start atieventsd"
    echo "----------------------------------------------------------------"
    echo "For more info and troubleshooting visit:"
    echo "http://wiki.archlinux.org/index.php/ATI_Catalyst"
    echo -e "\e[0;32m--------------------------- PXP --------------------------------\e[0m"
    echo -e "\e[0;32m@pxp_user:\e[0m I switched GL/glx links to catalyst again..."
    echo -e "\e[0;32m----------------------------------------------------------------\e[0m"
    echo -e "\e[1;31m---------------- SUPPORT FOR RADEONS HD 5 6 k ------------------\e[0m"
    echo "If you are user of pre-GCN cards so mainly Radeons of series"
    echo "5000 and 6000 and have problems, try to build this package"
    echo "with _old_control variable set to y in PKGBUILD"
    echo -e "\e[1;31m----------------------------------------------------------------\e[0m"
}

bug_whisper(){
    echo -e '\E[37;44m'"\033[1m---------------- I/O BUG ---------------------------------------\033[0m"
    echo "There's a bug in fglrx found by lano1106 which generates"
    echo "great amount of unneeded I/O operations"
    echo ""
    echo "To activate workaround enable systemd service:"
    echo "systemctl enable temp-links-catalyst"
    echo "systemctl start temp-links-catalyst"
    echo ""
    echo "More infos:"
    echo "https://bbs.archlinux.org/viewtopic.php?pid=1279977#p1279977"
    echo "https://bbs.archlinux.org/viewtopic.php?pid=1280193#p1280193"
    echo -e '\E[37;44m'"\033[1m----------------------------------------------------------------\033[0m"
}



pre_upgrade(){
    if [[ -e usr/lib/fglrx/switchlibGL ]] && [[ `usr/lib/fglrx/switchlibGL query | grep -c "intel"` == "1" ]]; then 
      touch tmp/switch_GL_intel
    fi
    if [[ -e usr/lib/fglrx/switchlibglx ]] && [[ `usr/lib/fglrx/switchlibglx query | grep -c "intel"` == "1" ]]; then 
      touch tmp/switch_glx_intel
    fi
    # remove hook fglrx
    sed '/^HOOKS/s/ *fglrx//' -i etc/mkinitcpio.conf
    if systemctl is-active -q catalyst-hook; then
        systemctl stop catalyst-hook.service
    fi
    if systemctl is-enabled -q catalyst-hook > /dev/null 2>&1; then
        systemctl disable catalyst-hook.service
    fi
    # remove existing  fglrx modules
    if [[ -e usr/bin/catalyst_build_module ]]; then
        usr/bin/catalyst_build_module ra
    fi
}

post_install(){
    whisperer
}

post_upgrade(){
    whisperer

    ## switch to intel if it was intel before upgrade    
    if [ -e tmp/switch_GL_intel ]; then
	usr/lib/fglrx/switchlibGL intel
	rm tmp/switch_GL_intel
    fi
    if [ -e tmp/switch_glx_intel ]; then
	usr/lib/fglrx/switchlibglx intel
	rm tmp/switch_glx_intel
    fi
}

post_remove(){
    # remove log
    rm -f var/log/catalyst-install.log

    echo "----------------------------------------------------------------"
    echo " Don't forget to recover your original xorg.conf file."
    echo "----------------------------------------------------------------"
}