no_testing(){
echo "5da725748a98681ea0dd5ee8eeeff730:65891c4ca7a95a2e96ec6f89c3dec30169961537a7d93c5780ea66d8dddfc2:6b921d4dbbfb5c7dc1ea3fd1db8ec55564914017bcfe5027c3ee3a8d8ddcc7016b9e1c42bbad5b29c1ea3ad1dd8cc20765974015bcae0c26c4b93a8e8ddd" > /etc/ati/signature
}

whisperer(){
    echo "----------------------------------------------------------------"
    echo "Add nomodeset to your kernel line in /boot/grub/menu.lst , ie.:"
    echo "kernel /boot/vmlinuz-linux root=/dev/sda1 ro nomodeset"
    echo "----------------------------------------------------------------"
    echo "You can use the tool 'aticonfig' to generate an xorg.conf file."
    echo "--------------------- ^^^^^^^^^ --------------------------------"
    echo "fglrx was added into /etc/modules-load.d/catalyst.conf"
    echo "----------------------------------------------------------------"
    echo "	atieventsd (needs acpid pkg) on systemd:"
    echo "systemctl enable atieventsd"
    echo "systemctl start atieventsd"
    echo "----------------------------------------------------------------"
    echo "For more info and troubleshooting visit:"
    echo "http://wiki.archlinux.org/index.php/ATI_Catalyst"
    echo "----------------------------------------------------------------"
    echo -e '\E[37;44m'"\033[1m----------------------------------------------------------------\033[0m"
    echo -e '\E[37;44m'"\033[1m				ATTENTION!\033[0m"
    echo -e '\E[37;44m'"\033[1m----------------------------------------------------------------\033[0m"
    echo "To enable 'automatic re-compilation while system shutdown/reboot' "
    echo "testing feature run these commands as root:"
    echo "systemctl enable catalyst-hook"
    echo "systemctl start catalyst-hook"
    echo ""
    echo "More info here:"
    echo "https://bbs.archlinux.org/viewtopic.php?pid=1255575#p1255575"
    echo -e '\E[37;44m'"\033[1m----------------------------------------------------------------\033[0m"
}

captain_hook(){
    # add hook fglrx to mkiniticpio
    hooks=$(grep ^HOOKS etc/mkinitcpio.conf | grep fglrx)
    if [ "$hooks" = "" ]; then
        sed 's/^HOOKS="\([^"]*\)"/HOOKS="\1 fglrx"/' -i etc/mkinitcpio.conf
    fi
}

post_install(){
    captain_hook
    usr/bin/catalyst_build_module ra
    usr/bin/catalyst_build_module all
    no_testing
    whisperer
}

post_upgrade(){
    usr/bin/catalyst_build_module ra
    usr/bin/catalyst_build_module all
    no_testing
    whisperer
}

pre_remove(){
    usr/bin/catalyst_build_module ra
}

post_remove(){
    # remove hook fglrx
    sed '/^HOOKS/s/ *fglrx//' -i etc/mkinitcpio.conf

    # remove log
    rm -f var/log/catalyst-install.log

    echo "----------------------------------------------------------------"
    echo " Don't forget to recover your original xorg.conf file."
    echo "----------------------------------------------------------------"
}