## arg 1:  the new package version
post_install() {
	echo "--"
	echo "You may have to enable and start pcscd (pcsclite) service, e.g."
	echo "  $ systemctl enable pcscd"
	echo "  $ systemctl start pcscd"
	echo "If it's already running then you need restart it."
	echo "  $ systemctl restart pcscd"
	echo "--"
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
	post_install
}

