post_install() {
	cat <<-EOF
	---------------------------------------------------
	OnlineFotoservice ist ein Produkt und Eigentum der
	CEWE Stiftung & Co. KGaA. Die Nutzungsbedingen sind
	in /usr/share/licenses/cewe-fotoservice/EULA.txt.
	WENN SIE DIESE SOFTWARE INSTALLIEREN, ERKLÄREN SIE
	SICH MIT DEN BEDINGUNGEN DIESES LIZENZABKOMMENS
	EINVERSTANDEN
	---------------------------------------------------
	EOF

}
