post_install() {
  echo '--------------------------------------------------'
  echo 'You *MUST* read and agree to the license stored in'
  echo '/usr/share/cewe-monlivrephoto-fr/EULA.txt before'
  echo 'you start using it'
  echo '--------------------------------------------------'

  chmod 775 /usr/share/cewe-monlivrephoto-fr
  /bin/true
}

post_upgrade() {
/bin/true
}

pre_remove() {
/bin/true
}
