post_install() {

	local eula=/usr/share/licenses/CEWE/EULA.txt

	if [ -n "$DISPLAY" ]
	then
		setsid xterm -title "$eula" -sb -rightbar -u8 -geometry 120x80 -e "cat $eula ; sleep 32000000" &> /dev/null \
		&& return
	fi

	echo -e "${eula//?/=}\n$eula\n${eula//?/=}"
	head -n 8 $eula
	echo -e "...\n${eula//?/=}\n$eula\n${eula//?/=}"

	read -p "Show rest of EULA.txt? (y/N)"
	[ "${REPLY#y}" != "$REPLY" ] && less -e $eula

	true
}
