#!/bin/bash

BRIGHTORANGE="\e[0;38;2;175;104;76m"
BRIGHTPINK="\e[0;38;2;245;88;89m"
BROWN="\e[0;38;2;175;104;76m"
DARKRED="\e[0;38;2;124;22;34m"
PINK="\e[0;38;2;213;38;57m"
SHAMROCK="\e[0;38;2;46;194;126m"
SKYBLUE="\e[0;38;2;37;178;238m"
YELLOW="\e[0;38;2;254;209;75m"

BOLD="\033[1m"

NC='\033[0m' # No Color

echo -e "${BRIGHTPINK}${BOLD}From the version 3.0, the Yaru++ versions will be named after a cupcake randomly in Italian or Brazilian Portuguese.${NC}"
echo -e " "

echo -e "${BRIGHTORANGE}#${NC} ${BRIGHTPINK}3.0${NC} – ${BROWN}${BOLD}Fragola Coco${NC}" 
echo -e "${PINK}➡${NC} Fixed the Popcorn Time icon (${YELLOW}#15${NC}). Thanks to ${SKYBLUE}@btd1337${NC}!"
echo -e "${PINK}➡${NC} Optimised the whole Yaru++;"
echo -e "${PINK}➡${NC} Corrected the whole Yaru++, recovering more than missed 2k icons erased from the future;"
echo -e "${PINK}➡${NC} ${SHAMROCK}${BOLD}Increased from 818 to 3104 apps icons and expanded to be supported in KDE and other distributions (only apps is complete, soon everything will be complete);${NC}"
echo -e "${PINK}➡${NC} Added Yaru++'s dark mode for dark environments;"
echo -e "${PINK}➡${NC} Replaced the colours of monochromatic icons with the Apple's standard colours."
echo -e "${PINK}➡${NC} Removed the pan icons to fix the wrong arrows of calendar and wifi list pop-up (${YELLOW}#13${NC}). Thanks to ${SKYBLUE}@DarthWound${NC}!"
echo -e "${PINK}➡${NC} Added Postman icon (${YELLOW}#26${NC}). Thanks to ${SKYBLUE}@btd1137${NC}!"
echo -e "${PINK}➡${NC} We provide an AUR and a XBS (Void Linux) for installing and updating Yaru++!"
echo -e " "
echo -e "${BRIGHTORANGE}#${NC} ${BRIGHTPINK}4.0${NC} – ${BROWN}${BOLD}Abacaxi al Coco${NC}"
echo -e "${PINK}➡${NC} We have just released a new version of Yaru++ with new than 35 icons of apps, 54 of devices, 153 of mimetypes and 1646 of places!"
echo -e "${PINK}➡${NC} 158 apps have been modified and updated for improvements."
echo -e "${PINK}➡${NC} Numberous broken symlinks have been corrected."
echo -e "${PINK}➡${NC} Fixed misspelling of emmoltes/emotes at the file index.theme (${YELLOW}#39${NC})."
echo -e "${PINK}➡${NC} Corrected KDE-unsupported SVG functions in the icons."
echo -e "${PINK}➡${NC} Fixed inheritance of Yaru++ (${YELLOW}#44${NC})."
echo -e "${PINK}➡${NC} Added 67 new folder categories (${YELLOW}#25${NC}), including 32px and 48px."
echo -e "${PINK}➡${NC} Added 15 new folder colours (${YELLOW}#25${NC}), including 32px and 48px."
echo -e "${PINK}➡${NC} New icons themes: kYaru++, Yaru++ Color, Yaru++ Minimal and Yaru++ Smooth."
echo -e " "
echo -e "${BRIGHTORANGE}#${NC} ${BRIGHTPINK}4.1${NC} – ${BROWN}${BOLD}Arachidi Von Hunty${NC}"
echo -e "${PINK}➡${NC} New folders style – Synthwave ‘84."
echo -e "${PINK}➡${NC} Added 9 new apps icons and 4 new emblems icons."
echo -e "${PINK}➡${NC} Upgraded mimetypes icons."
echo -e " "
