# Colored makepkg-like functions
note() {
    printf "${_blue}==>${_yellow} NOTE:${_bold} %s${_all_off}\n" "$1"
}

_all_off="$(tput sgr0)"
_bold="${_all_off}$(tput bold)"
_blue="${_bold}$(tput setaf 4)"
_yellow="${_bold}$(tput setaf 3)"

post_install() {
    note "Extension was installed to: /usr/share/chromium/bypass-paywalls-chrome-clean"
    note "Load the extension by the path above in developer mode using 'Load unpacked'"
}
