.\" Manpage for citeorder
.TH CITEORDER 1 "2025-10-02" "1.1" "citeorder manual"
.SH NAME
citeorder \- reorder footnotes in Markdown files
.SH SYNOPSIS
.B citeorder
[\-r|\-\-relaxed-quotes] input.md
.SH DESCRIPTION
Reorders the footnotes in the input Markdown file and produces a new file, 'input-fixed.md'. If an error occurs, an error message is printed.
.SH OPTIONS
.TP
\-r, \-\-relaxed-quotes
Enable relaxed quote handling.

.TP
\-h, \-\-help
Show help message and exit.

.TP
\-v, \-\-version
Print version information and exit.
.SH AUTHOR
Dhanushka Jayagoda


