# arg 1:  the new package version

post_install() {
	echo "See http://thewalter.net/stef/software/clamsmtp/postfix.html for configuration instruction."
	echo "Edit /etc/conf.d/clamsmtp."
	echo "Configfile is /etc/clamav/clamsmtpd.conf."
	/bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  /bin/true
}

# arg 1:  the old package version
pre_remove() {
  /bin/true
}

op=$1
shift
$op $*
