_create_latest_symlink() {
  echo "Creating latest symlink for /opt/clang/23.1.0"

  cd /opt/clang
  rm -f latest
  ln -fs 23.1.0 latest
}

## arg 1:  the new package version
pre_install() {
    echo ""
}

## arg 1:  the new package version
post_install() {
    echo ""
	_create_latest_symlink
}
#post_install

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
    echo ""
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
    echo ""
	_create_latest_symlink
}

## arg 1:  the old package version
pre_remove() {
    echo ""
}
#pre_remove

## arg 1:  the old package version
post_remove() {
    echo ""
}
