#!/bin/bash

post_install() {
	echo "Use 'clonehero' or the desktop file to run the game and place your "\
"songs/customs in '~/.clonehero/{Songs,Custom}'."
}

post_upgrade() {
	previous=$2
	older=$(printf "$previous\nv1.0.0.4080" | sort -V | head -n1)

	if [[ "$older" = "$previous" ]]; then
		echo "The folder where Clone Hero looks for songs/customs has "\
"been changed to '~/.clonehero/' so you will need to move your files."
	fi
}
