#!/usr/bin/env sh

TARGET=aarch64-linux-gnu

PREFIX=/usr/$TARGET

source $TARGET-environment

PATH=$PREFIX/bin:$PATH cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=${PREFIX} \
  -DCMAKE_INSTALL_LIBDIR:PATH=lib \
  -DINCLUDE_INSTALL_DIR:PATH=${PREFIX}/include \
  -DLIB_INSTALL_DIR:PATH=${PREFIX}/lib \
  -DSYSCONF_INSTALL_DIR:PATH=${PREFIX}/etc \
  -DSHARE_INSTALL_DIR:PATH=${PREFIX}/share \
  -DCMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES:PATH=${PREFIX}/include \
  -DCMAKE_C_IMPLICIT_INCLUDE_DIRECTORIES:PATH=${PREFIX}/include \
  -DBUILD_SHARED_LIBS:BOOL=ON \
  -DCMAKE_TOOLCHAIN_FILE=/usr/share/aarch64/toolchain.cmake \
  "$@"
