post_install(){
echo -e "#!/bin/bash\n/opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/bookworm-run \$@">/usr/bin/bookworm-run
echo -e "#!/bin/bash\n/opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/ace-uninstall-helper \$@">/usr/bin/ace-uninstall-helper
echo -e "#!/bin/bash\n/opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/ace-uninstall-helper-gui \$@">/usr/bin/ace-uninstall-helper-gui
chmod a+x /usr/bin/bookworm-run
chmod a+x /usr/bin/ace-uninstall-helper
chmod a+x /usr/bin/ace-uninstall-helper-gui
}

post_upgrade(){
pkexec bash /opt/apps/cn.flamescion.bookworm-compatibility-mode/files/bin/bookworm-init
}

post_remove(){
rm -f /usr/bin/bookworm-run
rm -f /usr/bin/ace-uninstall-helper
rm -f /usr/bin/ace-uninstall-helper-gui

rm -rf /opt/apps/cn.flamescion.bookworm-compatibility-mode
}
