post_install() {
    update-desktop-database -q
    
    update-mime-database /usr/share/mime &> /dev/null
    
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor &> /dev/null
}

post_upgrade() {
    post_install
}

post_remove() {
    update-desktop-database -q
    
    update-mime-database /usr/share/mime &> /dev/null
    
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor &> /dev/null
}