post_install() {
    echo -e "\nCreating /usr/bin/berg symlink from /usr/bin/codeberg-cli \n"
    ln -s /usr/bin/codeberg-cli /usr/bin/berg
}

post_upgrade() {
    echo -e "\nUpdating /usr/bin/berg symlink to /usr/bin/codeberg-cli \n"
    [[ -s /usr/bin/berg ]] || rm -f /usr/bin/berg && ln -s /usr/bin/codeberg-cli /usr/bin/berg
}

post_remove() {
    echo -e "\nRemoving /usr/bin/berg > /usr/bin/codeberg-cli symlink \n"
    [[ -s /usr/bin/berg ]] || rm -f /usr/bin/berg
}
