post_remove() {
    echo "Removing colordesktop desktop icon..."
    rm -f /usr/share/icons/colordesktop.png
    rm -f /usr/share/applications/ColorDesktop.desktop
}

post_install() {
    chmod a+x /usr/share/applications/ColorDesktop.desktop
    chmod a+x /usr/share/ColorDesktop/ColorDesktop.Launcher
    rm /usr/bin/ColorDesktop.Launcher
    ln -s /usr/share/ColorDesktop/ColorDesktop.Launcher /usr/bin/
}

post_upgrade() {
    post_install
}
