#!/bin/bash
# ComfyUI launcher
# Generated by the comfyui PKGBUILD

_prefix="_PREFIX_"

# Verify that the venv exists
if [ ! -f "$_prefix/venv/bin/python" ]; then
    echo "Error: Python venv not found at $_prefix/venv"
    echo "The post-install setup may have failed."
    echo "Try reinstalling: sudo pacman -S comfyui"
    exit 1
fi

# Verify that PyTorch is installed
if ! "$_prefix/venv/bin/python" -c "import torch" 2>/dev/null; then
    echo "Error: PyTorch is not installed in the venv."
    echo "The post-install setup may have failed or was interrupted."
    echo ""
    echo "To retry, reinstall the package:"
    echo "  sudo pacman -S comfyui"
    exit 1
fi

source "$_prefix/venv/bin/activate"
exec python "$_prefix/main.py" \
    --output-directory /var/lib/comfyui/output \
    --input-directory /var/lib/comfyui/input \
    --extra-model-paths-config /etc/comfyui/extra_model_paths.yaml \
    "$@"
