post_install() {
cat <<-EndOfMessage
==> How to use a pipeitem:
Insert <item type="launcher><command mode2="pipe">/path/to/the/script.extifany</command></item> into your menu via
a text editor. You can also add this by opening the editor, select
New, then click on pipeitem. Then type in the command for your pipeitem.
Be sure to also read the README in /usr/share/docs/compiz-pipes/README!
EndOfMessage
/bin/true
}

post_upgrade() {
	post_install
}
