#!/bin/bash

if [ -f /usr/bin/xfconf-query ]; then
    xfconf-query -c xfce4-session -p /sessions/Failsafe/Client0_Command -a -s compiz
fi

mkdir -p ~/.config/autostart
rm ~/.config/autostart/compiz-xfce-autostart.desktop
cp /etc/xdg/autostart/compiz-xfce-autostart.desktop ~/.config/autostart/
sed -i 's|Hidden=false|Hidden=true|' ~/.config/autostart/compiz-xfce-autostart.desktop

## This first-time run when it's replacing a running xfwm4, we run it twice cause of bugs
compiz --replace ; exec compiz --replace
