post_install() {
	echo
	echo -e "\e[1;34m]****** Concurrent installed ******\e[0m"
	echo -e "Please configure concrnt in \e[1;32m/etc/concrnt/config/config.yaml"
	echo -e "and gateway config in \e[1;32m/etc/concrnt/config/gateway.yaml\e[0m before starting"
	echo -e "You can start concrnt with \"sudo systemctl start concrnt-gateway\""
	echo -e "\e[1;34m]**********************************\e[0m"
	echo
}
