socks5_listen: 127.0.0.1:9909
http_proxy_listen: 127.0.0.1:9910

passthrough_china: false

exit_constraint: auto

# exit_constraint:
#  country: NL

broker:
  race:
    - fronted:
        front: https://www.cdn77.com/
        host: 1826209743.rsc.cdn77.org
    - fronted:
        front: https://vuejs.org/
        host: svitania-naidallszei-2.netlify.app
        
credentials:
  secret: 'your-account-secret'

# For legacy username and password
# credentials:
#   legacy_username_password:
#     username: your_username
#     password: your_password

sess_metadata:
  filter:
    ads: true     # Enable ad filtering.
    nsfw: false    # Enable NSFW content filtering.

vpn: false
