[version]
version=1.0.2
config_version=2

[settings]
default_editor_file=nano
default_editor_folder=code
auto_select_first_found_item=false
config_path=[~/.config, ~/.local/share]
root_config_path=[/etc]
use_fzf=true
smart_search=true
max_results=20

[aliases]
hyprland=[hypr]
neovim=[nvim]

[targets]
ssh=~/.ssh/config
cf=~/.config/easy-config/config.conf
fish=~/.config/fish/config.fish
hyprland=~/.config/hypr/*
kitty=~/.config/kitty/kitty.conf
neovim=~/.config/nvim/*
zsh=~/.zshrc
bash=~/.bashrc
tmux=~/.tmux.conf
starship=~/.config/starship.toml
fastfetch=~/.config/fastfetch/config.jsonc
git=~/.gitconfig
btop=~/.config/btop/btop.conf
mpv=~/.config/mpv/*
cava=~/.config/cava/config

[cache]
enabled=true
cache_path=~/.config/easy-config/cache.conf
