# Default config file for 'fetter'
# Originial

mode: audit
audit:
  mode: override

name: fetter

logging:
  file: /tmp/fetter.log
  level: info

rules:
  fetter:
    paths: [/usr/bin/fetter]
    action: execute
    group: fetter
    trigger: journal

groups:
  fetter:

triggers:
  journal:
    run: systemd-cat
    args: ['echo', 'FETTER was executed!']
    user: nobody
