#!/bin/sh
FNMTPATH="/usr/share/java/configuradorfnmt"
JAR="configuradorfnmt.jar"
BC="bc-fips.jar"
BCUTIL="bcutil-fips.jar"
BCPKIX="bcpkix-fips.jar"
CLASSPATH="${FNMTPATH}/${JAR}:${FNMTPATH}/${BC}:${FNMTPATH}/${BCUTIL}:${FNMTPATH}/${BCPKIX}"
/usr/bin/java -classpath "${CLASSPATH}" es.gob.fnmt.cert.certrequest.CertRequest "$@"
