# bash completion for context
# Generated by context completions bash. Do not edit by hand.

_context() {
  local cur prev cword command opts choices
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}
  cword=$COMP_CWORD
  command=${COMP_WORDS[1]-}

  if (( cword == 1 )); then
    COMPREPLY=( $(compgen -W 'git stack mcp completions help -h --help' -- "$cur") )
    return
  fi

  case $command in
    git)
      opts='--json --comments --reviews --labels --checks --no-description --no-pr --remotes --no-branch-metadata --no-status --no-work-scope --diff --branch-diff --since --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    stack)
      opts='--json --plain --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    mcp)
      opts='--help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    completions)
      if (( cword == 2 )) && [[ $cur != -* ]]; then
        COMPREPLY=( $(compgen -W 'bash fish zsh' -- "$cur") )
        return
      fi
      opts='--help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    help)
      if (( cword == 2 )) && [[ $cur != -* ]]; then
        COMPREPLY=( $(compgen -W 'git stack mcp completions' -- "$cur") )
        return
      fi
      opts='--help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
  esac
}

complete -F _context context
