## Runtime
NODE_ENV=production

## Data Directory
DATA_DIR="/var/lib/cookiecloud-api"

## API Subpath
#API_ROOT=""

## Listening Port
PORT=8088

## Log Save Directory
LOG_DIR="/var/log/cookiecloud-api"

## Log Level
#LOG_LEVEL=info
