post_install() {
echo ">>> The version of settings file is:"
echo ">>> ~/.secondlife/user_settings/settings_coolvlviewer_12680.xml."
echo ">>> You must also add your user to the 'games' group."
echo ">>>  # gpasswd -a USERNAME games"
echo ">>> Remember to logout and log back in for the changes to take effect."
}

#post_upgrade() {
echo ">>> New version of settings file is:"
echo ">>> ~/.secondlife/user_settings/settings_coolvlviewer_12800.xml."
}

op=$1
shift

$op $*
