post_install() {
  echo 'You must now edit the configuration file at /etc/webapps/cops/local.php'
  echo 'You must also configure a PHP-enabled webserver to serve COPS'
  echo 'from, out of the folder: /usr/share/webapps/cops/.'
  echo 'Remember to change permission of that folder as appropriate'
  echo '(maybe something like: chown -R http:http /usr/share/webapps/cops)'
}

post_upgrade() {
  post_install
}
