#!/bin/execlineb -P
envfile /etc/s6/config/coredns.conf
importas -sCuD "n3 s2000000 T" DIRECTIVES DIRECTIVES
ifelse { test -w /var/log } {
	foreground { install -d -o s6log -g s6log /var/log/coredns }
	s6-setuidgid s6log exec -c s6-log -d3 -b -- ${DIRECTIVES} /var/log/coredns
}
foreground { install -d -o s6log -g s6log /run/log/coredns }
s6-setuidgid s6log exec -c s6-log -d3 -b -- ${DIRECTIVES} /run/log/coredns
