post_install() {
    echo "==========================================================="
    echo "Thank you for installing Flux!"
    echo " "
    echo "Please run the following command to initialize the service:"
    echo "  systemctl --user enable --now cosmic-ext-flux-daemon"
    echo " "
    echo "Next, add the Flux applet to your COSMIC panel via:"
    echo "  Settings > Desktop > Panel > Applets"
    echo "==========================================================="
}

post_remove() {
    echo "==========================================================="
    echo "Thank you for using Flux!"
    echo " "
    echo "Please run the following command to uninitialize the service:"
    echo "  systemctl --user disable --now cosmic-ext-flux-daemon"
    echo "==========================================================="
}

