post_install() {
  systemd-sysusers cpcache.conf
  chown cpcache:cpcache "/var/lib/cpcache"
  mkdir -p /var/cache/cpcache/x86/{core,extra,multilib,testing,community}/os/{i686,x86_64}/downloads
  mkdir -p /var/cache/cpcache/arm/{aarch64,arm,armv6h,armv7h}/{alarm,aur,community,extra,core}/downloads
  chown -R cpcache:cpcache "/var/cache/cpcache"
}

post_upgrade() {
  systemd-sysusers cpcache.conf
}
