post_install() {
	instructions_install
}

post_upgrade() {
	instructions_upgrade
}

post_remove() {
	instructions_remove
}

instructions_install() {
	cat <<-EOT

	Restart GNOME Shell ([Alt]+[F2], r).
	Activate the extension with gnome-tweak-tool.

	EOT
}

instructions_upgrade() {
	cat <<-EOT

	Restart GNOME Shell ([Alt]+[F2], r) to load the upgraded extension.

	EOT
}

instructions_remove() {
	cat <<-EOT

	Restart GNOME Shell ([Alt]+[F2], r) to unload the removed extension.

	EOT
}
