post_install () {
  INOTIFY_WATCHES=`cat /proc/sys/fs/inotify/max_user_watches`
  if [[ $INOTIFY_WATCHES -le 8192 ]]; then
    echo ""
    echo "Your system is currently configured to watch $INOTIFY_WATCHES files in real time."
    echo "CrashPlan recommends using a larger value; see the CrashPlan support site for details."
    echo "e.g. add the following line to /etc/sysctl.conf "
    echo "  fs.inotify.max_user_watches=1048576"
    echo ""
  fi
}
