post_install() {
  cat << "EOF"
-------------------------------------------------
To use cups-ocr, restart cups and visit the cups
web interface at http://localhost:631/

You can now add a "Virtual Printer (OCR Printer)"
and use the Postscript/Generic postscript color
printer driver.

Note that cups-ocr has a configuration
file in /etc/cups. The default location for
pdf output is /var/spool/cups-ocr/$username.
-------------------------------------------------
EOF
}
