#
#
# >>> DO NOT EDIT THIS FILE. <<<
#
# The file:
#
#     .bash_it/lib/custom.bash
#
# is NOT safe to use. It will be overwritten by the package manager.
# Instead, place your custom libraries anywhere inside the
#
#     ~/.bash_it/custom/lib/
#
# directory.
#
#
