all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

note() {
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

post_install() {
    ln -sf /usr/local/cyberghost/cyberghostvpn /usr/bin/cyberghostvpn
    note "Setup your account: cyberghostvpn --setup"
}

post_upgrade() {
    post_install
}

post_remove() {
    unlink /usr/bin/cyberghostvpn
    rm -rf /usr/local/cyberghost
}
