all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

note() {
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

post_install() {
    note "Enable systemd-resolved: systemctl enable systemd-resolved.service"
    note "Setup your account: cyberghostvpn --setup"
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -rf /usr/local/cyberghost
}
