post_install() {
  echo "--------------------------------------------------"
  echo "NOTE: DansGuardian is NOT free for commercial use."
  echo "      See http://dansguardian.org for details on  "
  echo "      setup, configuration, and licensing.        "
  echo "--------------------------------------------------"
  echo "NOTE: You must install a proxy server such as     "
  echo "      Squid or Tinyproxy or Polipo etc. to use    "
  echo "      DansGuardian.                               "
  echo "--------------------------------------------------"
  chown -R proxy:proxy /var/log/dansguardian
}
