list_conf_files(){
  ls \
  /usr/share/dbeaver/dbeaver.ini \
  /usr/lib/dbeaver/dbeaver.ini \
  /opt/dbeaver/dbeaver.ini \
  /usr/share/dbeaver-ce/dbeaver.ini \
  /usr/lib/dbeaver-ce/dbeaver.ini \
  /opt/dbeaver-ce/dbeaver.ini \
  /usr/share/dbeaver-ee/dbeaver.ini \
  /usr/lib/dbeaver-ee/dbeaver.ini \
  /opt/dbeaver-ee/dbeaver.ini \
  /usr/share/dbeaver-le/dbeaver.ini \
  /usr/lib/dbeaver-le/dbeaver.ini \
  /opt/dbeaver-le/dbeaver.ini \
  /usr/share/dbeaver-ue/dbeaver.ini \
  /usr/lib/dbeaver-ue/dbeaver.ini \
  /opt/dbeaver-ue/dbeaver.ini \
  2>/dev/null
}

post_install() {
  list_conf_files | /usr/share/libalpm/scripts/dbeaver-jvm-setting.sh ;
}

post_upgrade() {
  post_install
}