# The install script source is from rpm and deb packet, control.tar.gz
#
# NOTE:
# since Arch Linux doesn't have SELinux enabled by default,
# some parts of this script have been commented out.
# if you've manually enabled SELinux, you can uncomment
# these lines before installing this package
#
#
install_script () {
  #postinst part
  ln -s /opt/brother/Printers/dcpt430w/lpd/x86_64/brdcpt430wfilter           /opt/brother/Printers/dcpt430w/lpd/brdcpt430wfilter

  /opt/brother/Printers/dcpt430w/inf/setupPrintcapij dcpt430w -i
  /opt/brother/Printers/dcpt430w/cupswrapper/cupswrapperdcpt430w
  chmod 755 /opt/brother/Printers/dcpt430w/cupswrapper

  # SELinux lines
  #if [ "$(which semanage 2> /dev/null)" != '' ];then
  #  semanage fcontext -d -t cupsd_rw_etc_t '/opt/brother/Printers/dcpt430w/inf(/.*)?'
  #  semanage fcontext -d -t bin_t          '/opt/brother/Printers/dcpt430w/lpd(/.*)?'
  #  semanage fcontext -d -t bin_t          '/opt/brother/Printers/dcpt430w/cupswrapper(/.*)?'
  #  if [ "$(which restorecon 2> /dev/null)" != '' ];then
  #    restorecon -R /opt/brother/Printers/dcpt430w
  #  fi
  #fi
}

post_install () {
  install_script

  echo ""
  echo "### POST INSTALLATION MESSAGE ### "
  echo ""
  echo "FUTHER STEPS: "
  echo ""
  echo "   1- After installation/upgrade, it's recommended to restart cups, "
  echo "      If you didn't start it yet, then enable cups service/socket with: "
  echo "        systemctl enable cups.service (or cups.socket) "
  echo "      OR "
  echo "      restart cups with: "
  echo "        systemctl restart cups.service "
  echo ""
  echo "   2- To configure wireless connection or USB connection: "
  echo "      Open CUPS in your browser by accessing the localhost cups port: "
  echo "      http://localhost:631 "
  echo "      OR "
  echo "      install the optional system-config-printer package "
  echo ""
  echo ""
  echo "NOTE: "
  echo "  If you want to use wireless network, setup the WiFi connection on the printer "
  echo "  AND "
  echo "  change connection type in CUPS. Connection string: "
  echo "    lpd://xxx.xxx.xxx.xxx/BINARY_P1 "
  echo "  where xxx.xxx.xxx.xxx is printer IP address "
  echo ""
  echo ""
  echo "NOTE: "
  echo "  Setup sane-airscan package to make the scanner avaliable for the SANE "
  echo "  OR "
  echo "  setup brscan5 packege and run command: "
  echo "    brsaneconfig5 -a name="Brother DCP-t430w" model=DCP-t430w ip=xxx.xxx.xxx.xxx "
  echo "  where xxx.xxx.xxx.xxx is printer IP address "
  echo ""
}

post_upgrade () {
  install_script
}

pre_remove() {
  #prerm part
  /opt/brother/Printers/dcpt430w/cupswrapper/cupswrapperdcpt430w -e
  /opt/brother/Printers/dcpt430w/inf/setupPrintcapij dcpt430w -e
  unlink /opt/brother/Printers/dcpt430w/lpd/brdcpt430wfilter
}

post_remove() {
  #postrm part
  if [[ -f "/tmp/dcpt430w_latest_print_info" ]] ; then
    rm -f /tmp/dcpt430w_latest_print_info
  fi

  # SELinux lines
  #if [ "$(which semanage 2> /dev/null)" != '' ];then
  #  semanage fcontext -d -t cupsd_rw_etc_t '/opt/brother/Printers/dcpt430w/inf(/.*)?'
  #  semanage fcontext -d -t bin_t          '/opt/brother/Printers/dcpt430w/lpd(/.*)?'
  #  semanage fcontext -d -t bin_t          '/opt/brother/Printers/dcpt430w/cupswrapper(/.*)?'
  #  if [ "$(which restorecon 2> /dev/null)" != '' ];then
  #   restorecon -R /opt/brother/Printers/dcpt430w
  #  fi
  #fi
}
