post_upgrade() {
  echo '--------------------------------------------------'
  echo 'Config file is located at /etc/ddns-go/ddns-go.yaml, instead of /etc/ddns-go.yaml.'
  echo 'Consider edit the config file manually to reuse old tokens:'
  echo 'sudo mkdir /etc/ddns-go && sudo mv /etc/ddns-go.yaml /etc/ddns-go/ && sudo chmod 700 /etc/ddns-go'
  echo '--------------------------------------------------'
}
