post_install() {
cat << EOF
----------------------------------------------
1. Set up start and enable on boot using systemd:
  Root privileges: systemctl enable --now deeplx.service
2. Check the status using systemd:
  Root privileges: systemctl status deeplx.service
3. Listening at:
  Recommended: http://localhost:1188
  IPv4: http://127.0.0.1:1188
  IPv6: http://[::]:1188
-----------------------------------------------
EOF

}

post_upgrade() {
  post_install
}

