echo ""
echo "hint:"
echo "  create an executable"
echo "    $HOME/.xrandr-changed to handle xrandr changed events"
echo "  and restart service:"
echo "    systemctl restart --user xrandr-watcher.service"
echo "  to handle xrandr changed events"
