// SPDX-License-Identifier: GPL-2.0-or-later
/*
 * Dell XPS L702X EC Hardware Brightness Keys Driver
 *
 * Intercepts ACPI Embedded Controller Query 0x80 (Brightness Up) and
 * Query 0x81 (Brightness Down) generated by hardware Fn+F5 / Fn+F4 keys
 * and reports standard KEY_BRIGHTNESSUP / KEY_BRIGHTNESSDOWN input events.
 *
 * Copyright (C) 2026 Twilight0
 */

#include <linux/module.h>
#include <linux/init.h>
#include <linux/acpi.h>
#include <linux/input.h>
#include <linux/input/sparse-keymap.h>
#include <linux/dmi.h>

MODULE_LICENSE("GPL");
MODULE_AUTHOR("Twilight0");
MODULE_DESCRIPTION("Dell XPS L702X Hardware Brightness Keys Driver");
MODULE_VERSION("1.0.1");

extern struct acpi_ec *first_ec;
typedef u32 (*acpi_ec_query_func)(void *data);
extern int acpi_ec_add_query_handler(struct acpi_ec *ec, u8 query_bit,
                                     acpi_handle handle, acpi_ec_query_func func,
                                     void *data);
extern void acpi_ec_remove_query_handler(struct acpi_ec *ec, u8 query_bit);

static struct input_dev *xps_input_dev;
static bool query_80_registered;
static bool query_81_registered;

static const struct key_entry dell_xps_keymap[] = {
    { KE_KEY, 0x80, { KEY_BRIGHTNESSUP } },
    { KE_KEY, 0x81, { KEY_BRIGHTNESSDOWN } },
    { KE_END, 0 }
};

static u32 xps_brightness_up_handler(void *data)
{
    if (xps_input_dev) {
        sparse_keymap_report_event(xps_input_dev, 0x80, 1, true);
        pr_info("dell_xps_brightness: Fn+F5 (Brightness Up) -> sparse_keymap event reported\n");
    }
    return 0;
}

static u32 xps_brightness_down_handler(void *data)
{
    if (xps_input_dev) {
        sparse_keymap_report_event(xps_input_dev, 0x81, 1, true);
        pr_info("dell_xps_brightness: Fn+F4 (Brightness Down) -> sparse_keymap event reported\n");
    }
    return 0;
}

static const struct dmi_system_id dell_xps_dmi_table[] __initconst = {
    {
        .ident = "Dell XPS L702X",
        .matches = {
            DMI_MATCH(DMI_SYS_VENDOR, "Dell Inc."),
            DMI_MATCH(DMI_PRODUCT_NAME, "Dell System XPS L702X"),
        },
    },
    {
        .ident = "Dell XPS Generic",
        .matches = {
            DMI_MATCH(DMI_SYS_VENDOR, "Dell Inc."),
            DMI_MATCH(DMI_CHASSIS_TYPE, "10"), /* Notebook */
        },
    },
    { }
};
MODULE_DEVICE_TABLE(dmi, dell_xps_dmi_table);

static int __init dell_xps_brightness_init(void)
{
    int ret;

    if (!first_ec) {
        pr_warn("dell_xps_brightness: ACPI Embedded Controller not found\n");
        return -ENODEV;
    }

    xps_input_dev = input_allocate_device();
    if (!xps_input_dev)
        return -ENOMEM;

    xps_input_dev->name = "Dell XPS Hardware Hotkeys";
    xps_input_dev->phys = "dell_xps/input0";
    xps_input_dev->id.bustype = BUS_HOST;

    ret = sparse_keymap_setup(xps_input_dev, dell_xps_keymap, NULL);
    if (ret) {
        pr_err("dell_xps_brightness: Failed to setup sparse keymap: %d\n", ret);
        input_free_device(xps_input_dev);
        xps_input_dev = NULL;
        return ret;
    }

    ret = input_register_device(xps_input_dev);
    if (ret) {
        pr_err("dell_xps_brightness: Failed to register input device: %d\n", ret);
        input_free_device(xps_input_dev);
        xps_input_dev = NULL;
        return ret;
    }

    ret = acpi_ec_add_query_handler(first_ec, 0x80, NULL, xps_brightness_up_handler, NULL);
    if (!ret) {
        query_80_registered = true;
    } else {
        pr_warn("dell_xps_brightness: Query 0x80 registration returned %d\n", ret);
    }

    ret = acpi_ec_add_query_handler(first_ec, 0x81, NULL, xps_brightness_down_handler, NULL);
    if (!ret) {
        query_81_registered = true;
    } else {
        pr_warn("dell_xps_brightness: Query 0x81 registration returned %d\n", ret);
    }

    pr_info("dell_xps_brightness: Dell XPS brightness hotkeys driver loaded (sparse-keymap)\n");
    return 0;
}

static void __exit dell_xps_brightness_exit(void)
{
    if (first_ec) {
        if (query_80_registered)
            acpi_ec_remove_query_handler(first_ec, 0x80);
        if (query_81_registered)
            acpi_ec_remove_query_handler(first_ec, 0x81);
    }

    if (xps_input_dev) {
        input_unregister_device(xps_input_dev);
        xps_input_dev = NULL;
    }

    pr_info("dell_xps_brightness: Driver unloaded\n");
}

module_init(dell_xps_brightness_init);
module_exit(dell_xps_brightness_exit);
