#
# Demuxer config file
#   Note that command line will override settins set here.
#
#bind/listen to endpoint for muxer connections on:   (default to 127.0.0.1:5999)
# we want to bind to 65535 by default
bind_port 65535
#
# Target Host   (default 127.0.0.1) can be IP or hostname
#
target_host 127.0.0.1
#
# UDP port expire time in seconds (default 120) UDP mappings expire if no packets flow in this many seconds
#
udp_expire_time 240