# Autogenerated by ./makedeps.py
cdc.o coulfg.o fresco.o frxx0.o frxx1.o frxx10.o frxx11.o frxx16.o frxx17.o frxx2.o frxx3.o frxx4.o frxx5.o frxx6.o frxx7a.o frxx7b.o frxx8.o frxx9.o sfresco.o: globx7.o
