post_install() {
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
    if which update-icon-caches >/dev/null 2>&1 ; then
    	update-icon-caches /usr/share/icons/desktime.png
    fi
    update-desktop-database -q
}

post_upgrade() {
    post_install
}

post_remove() {
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
    if which update-icon-caches >/dev/null 2>&1 ; then
    	update-icon-caches /usr/share/icons/desktime.png
    fi
    update-desktop-database -q
}
