# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

reload_resolved() {
  /usr/bin/systemctl reload-or-try-restart systemd-resolved
}

## arg 1:  the new package version
pre_install() {
    :
}

## arg 1:  the new package version
post_install() {
  reload_resolved
}

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
    :
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
    reload_resolved
}

## arg 1:  the old package version
pre_remove() {
    :
}

## arg 1:  the old package version
post_remove() {
    reload_resolved
}
