AUTOINSTALL="yes"
PACKAGE_NAME="@_PKGNAME@"
PACKAGE_VERSION="@PKGVER@"

BUILT_MODULE_NAME[0]="@_KERNELMODULE@"
DEST_MODULE_LOCATION[0]="/kernel/drivers/misc"

CC_IS_CLANG=""
if [[ -f "${kernel_source_dir}/.config" ]]; then
    if grep --ignore-case --silent '^CONFIG_CC_IS_CLANG=y\$' "$kernel_source_dir/.config" 2>/dev/null; then
CC_IS_CLANG="LLVM=1"
    fi
fi

MAKE[0]="make V=1 KDIR=$kernel_source_dir $CC_IS_CLANG"

POST_INSTALL="./dkms-post-install"
