PACKAGE_NAME="kernelsu"
PACKAGE_VERSION="@PKGVER@"

BUILT_MODULE_NAME[0]="kernelsu"
DEST_MODULE_LOCATION[0]="/extra"

AUTOINSTALL="yes"

MAKE[0]="env KVERSION=${kernelver} KBUILD_MODPOST_WARN=1 KSU_GIT_VERSION=@KSU_GIT_VERSION@ CONFIG_KSU_X86_PATCH_SYSCALL_DISPATCHER=y CONFIG_KSU_NON_ANDROID=y CONFIG_KSU_SELINUX=n CONFIG_KSU_DEBUG=n make KDIR=${kernel_source_dir}"
