PACKAGE_VERSION="@_PKGVER@"
PACKAGE_NAME="@_PKGBASE@"
MAKE[0]="export KVER=${kernelver} KDIR=${kernel_source_dir} && scst/smart-build && make -j$(nproc) -s"
#CLEAN="make clean; rm -f scst-Module.symvers"
CLEAN="true" # The build directory is removed anyway
BUILT_MODULE_NAME[0]="ib_srpt"
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
