PACKAGE_VERSION="@_PKGVER@"
PACKAGE_NAME="@_PKGBASE@"
MAKE[0]="export KVER=${kernelver} KDIR=${kernel_source_dir} && ./smart-build modules"
#CLEAN="rm -f *.ko dev_handlers/*.ko"
CLEAN="true" # The build directory is removed anyway
BUILT_MODULE_NAME[0]="scst"
DEST_MODULE_LOCATION[0]="/extra"
BUILT_MODULE_LOCATION[1]="dev_handlers/"
BUILT_MODULE_LOCATION[2]="dev_handlers/"
BUILT_MODULE_LOCATION[3]="dev_handlers/"
BUILT_MODULE_LOCATION[4]="dev_handlers/"
BUILT_MODULE_LOCATION[5]="dev_handlers/"
BUILT_MODULE_LOCATION[6]="dev_handlers/"
BUILT_MODULE_LOCATION[7]="dev_handlers/"
BUILT_MODULE_LOCATION[8]="dev_handlers/"
BUILT_MODULE_LOCATION[9]="dev_handlers/"
BUILT_MODULE_NAME[1]="scst_cdrom"
BUILT_MODULE_NAME[2]="scst_changer"
BUILT_MODULE_NAME[3]="scst_disk"
BUILT_MODULE_NAME[4]="scst_modisk"
BUILT_MODULE_NAME[5]="scst_processor"
BUILT_MODULE_NAME[6]="scst_raid"
BUILT_MODULE_NAME[7]="scst_tape"
BUILT_MODULE_NAME[8]="scst_user"
BUILT_MODULE_NAME[9]="scst_vdisk"
DEST_MODULE_LOCATION[1]="/extra/dev_handlers"
DEST_MODULE_LOCATION[2]="/extra/dev_handlers"
DEST_MODULE_LOCATION[3]="/extra/dev_handlers"
DEST_MODULE_LOCATION[4]="/extra/dev_handlers"
DEST_MODULE_LOCATION[5]="/extra/dev_handlers"
DEST_MODULE_LOCATION[6]="/extra/dev_handlers"
DEST_MODULE_LOCATION[7]="/extra/dev_handlers"
DEST_MODULE_LOCATION[8]="/extra/dev_handlers"
DEST_MODULE_LOCATION[9]="/extra/dev_handlers"
AUTOINSTALL="yes"
