PACKAGE_VERSION="@_PKGVER@"
PACKAGE_NAME="@_PKGBASE@"
MAKE[0]="export KVER=${kernelver} KDIR=${kernel_source_dir} BUILD_2X_MODULE=y CONFIG_SCSI_QLA_FC=y CONFIG_SCSI_QLA2XXX_TARGET=y && scst/smart-build && make -j$(nproc) -sC qla2x00-target"
#CLEAN="make clean; rm -f scst-Module.symvers"
CLEAN="true" # The build directory is removed anyway
BUILT_MODULE_LOCATION[0]="qla2x00-target/"
BUILT_MODULE_NAME[0]="qla2x00tgt"
BUILT_MODULE_NAME[1]="qla2xxx_scst"
DEST_MODULE_LOCATION[0]="/extra"
DEST_MODULE_LOCATION[1]="/extra"
AUTOINSTALL="yes"
