post_install () {
	chmod 666 /dev/net/tun

	if [ -x /sbin/setcap ]
	then
		setcap cap_net_bind_service,cap_net_admin=ep /usr/bin/dnc
	else
		echo "setcap(8) not installed. You need to set CAP_NET_BIND and CAP_NET_ADMIN \
		to be able to run dynvpn without root privileges."
	fi
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade () {
	post_install
}

post_remove() {
	post_install
}
