post_install() {
    echo "Creating dnrs user and group..."
    getent group dnrs >/dev/null 2>&1 || groupadd -r dnrs
    getent passwd dnrs >/dev/null 2>&1 || useradd -r -g dnrs -d /etc/dnrs -s /bin/false -c "DNRS user" dnrs
    echo "User and group dnrs created."
}

pre_remove() {
    echo "Removing dnrs user and group..."
    userdel dnrs >/dev/null 2>&1 || true
    groupdel dnrs >/dev/null 2>&1 || true
    echo "User and group dnrs removed."
}

post_upgrade() {
    post_install
}
