ARG REGISTRY

FROM "$REGISTRY/common/gitlab-helper/archlinux-yay:master"

RUN (\
    yay -Syuq --noconfirm --needed python-numpy eigen plplot gsl hdf4 hdf5 wxgtk3 fftw pslib eccodes udunits graphicsmagick libgeotiff glpk shapelib openssh xorg-server-xvfb \
    && yes | yay -Scc --noconfirm \
    && rm -rf ~/.cache/yay \
    && sudo rm -rf /var/cache/pacman/pkg/* \
)
