post_install() {
	chown -R http:http /var/lib/dolibarr
	chown http:http /etc/webapps/dolibarr/conf.php
	echo 'Please configure your webserver. Example files are provided in /etc/webapps/dolibarr'
	echo 'It could be necessary to add /var/lib/dolibarr/ to open_basedir in php.ini'
	echo 'Finish installation by pointing your webbrowser to http://dolibarr.localdomain/install'
}

post_upgrade() {
	rm /var/lib/dolibarr/install.lock
}
