#!/bin/sh

set -e

exec editor --game-wad /usr/share/doom2df/data/game.wad --editor-wad /usr/share/doom2df/data/editor.wad --wads-dir /usr/share/doom2df/wads --config ~/.doom2df/Editor.cfg --log-file ~/.doom2df/Editor.log
