note() {
    all_off="$(tput sgr0)"
    bold="${all_off}$(tput bold)"
    blue="${bold}$(tput setaf 4)"
    yellow="${bold}$(tput setaf 3)"
    echo "${blue}==>${yellow} NOTE:${bold} ${1}${all_off}"
}    
post_install() {
    note '** /usr/lib/doom_ascii is where wads can be placed'
    note '   /usr/lib/doom_ascii/.default.cfg is the config file'
    note ' https://github.com/wojciech-graj/doom-ascii/tree/master for updated instructions'

}
post_upgrade() {
    post_install
}
