#!/bin/bash

#[[ -n "$1" ]] && interval="$1" || interval="4"
interval=$(( $# ? ${1:-0} : 4))

while true; do

  while read -r line; do

    [[ ! "${line}" == "\n" ]] && echo "${line}"

  done <<< "$(ss -tun | sed -n '2,$s/.* \([0-9\.]*\):\([0-9]*\) *\([0-9\.]*\):\([0-9]*\)/\1 \3 \2/p')"

  sleep "${interval}"

done
