#!/bin/sh
home_dir_user=$USER

if [ ! -d "/home/${home_dir_user}/.config/5db5/PluginData/DoubleTake/Presets" ]; then
    mkdir -p /home/${home_dir_user}/.config/5db5/PluginData/DoubleTake
    ln -sf /usr/lib/5db5/DoubleTake/Presets /home/${home_dir_user}/.config/5db5/PluginData/DoubleTake/Presets
else
    rm -r /home/${home_dir_user}/.config/5db5/PluginData/DoubleTake/Presets
    ln -sf /usr/lib/5db5/DoubleTake/Presets /home/${home_dir_user}/.config/5db5/PluginData/DoubleTake/Presets
fi
