post_install() {
    echo "##########################################"
    echo "# dpsprep-git package deprecation notice #"
    echo "##########################################"
    echo "#"
    echo "# The `dpsprep-git` AUR package will be abandoned soon. Consider the fixed-version `dpsprep` package instead."
    echo "# VCS packages are more fragile and the upstream project does not accumulate enough changes to justify both AUR packages."
    echo "#"
}

post_upgrade() {
    post_install
}
