#!/bin/bash

set -euo pipefail

kernel_versions=()
rebuild_all=0

extract_kernel_version() {
    local heads
    heads="${1%/pkgbase}"
    echo "${heads##*/}"
}

while read -r line; do
    case "$line" in
    usr/lib/modules/*/pkgbase)
        kernel_versions+=("$(extract_kernel_version "$line")")
        ;;
    *)
        rebuild_all=1
        break;
        ;;
    esac
done

if ((rebuild_all)); then
    kernel_versions=()
    for file in /lib/modules/*/pkgbase; do
        kernel_versions+=("$(extract_kernel_version "$file")")
    done
fi

for version in "${kernel_versions[@]}"; do
    echo ":: Building unified kernel image for $version"
    dracut -q -f --uefi --kver "${version}"
done
