#!/usr/bin/env bash

args=('--force' '--quiet')

disk=$(lsblk /dev/nvme0n1 -o MODEL | awk '{print $2;}' | xargs)
subvolid=$(btrfs sub show / | grep 'Subvolume ID:' | awk '{print $3;}' | sed -r 's/\s+//g')



while read -r line; do
	if [[ "$line" == 'usr/lib/modules/'+([^/])'/pkgbase' ]]; then
		read -r pkgbase < "/${line}"
		kver="${line#'usr/lib/modules/'}"
		kver="${kver%'/pkgbase'}"

		dracut "${args[@]}" --hostonly "/boot/EFI/Linux/$kver-$disk-$subvolid-dracut.efi" --kver "$kver"
	fi
done
