post_install() {
  cat << EOF

To complete the installation, place the following line in your shell config:

  For zsh, place in ~/.zshrc:

    command -v dtags > /dev/null 2>&1 && . <(dtags shell zsh)

  For bash, place in ~/.bashrc

    command -v dtags > /dev/null 2>&1 && . <(dtags shell bash)

  For fish, place in ~/.config/fish/config.fish:

    command -v dtags > /dev/null 2>&1; and dtags shell fish | source

EOF
}
