post_install() {
  echo "Remember to place DUNE II data files in '~/.local/share/dunedynasty/data',"
  echo "or the system-wide data directory '/usr/share/dunedynasty/data'."
  echo "For MIDI music start 'timidity -iA -B 4,8', or set a soundfont path"
  echo "for use with FluidSynth in '~/.config/dunedynasty/dunedynasty.cfg'"
  echo "For an example config file, see '/usr/share/doc/dunedynasty/dunedynasty.cfg-sample'."
}
