# SPDX-FileCopyrightText: 2012 Kjell M. Myksvoll
# SPDX-FileComment: Relicensing requested on 2025-07-26 by Claudia Pellegrino <aur ät cpellegrino.de> via email
# SPDX-FileComment: Relicensing confirmed on 2025-08-25 by Kjell M. Myksvoll via email
# SPDX-License-Identifier: 0BSD

# Dymo LabelManager PnP

DefaultVendor= 0x0922
DefaultProduct=0x1001

TargetVendor=  0x0922
TargetProduct= 0x1002

MessageEndpoint= 0x01
ResponseEndpoint=0x01

MessageContent="1b5a01"
