post_install() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

	# Link to the binary
	ln -sf '/opt/EasyMC Launcher/easymc-launcher' '/usr/bin/easymc-launcher'

	# SUID chrome-sandbox for Electron 5+
	chmod 4755 '/opt/EasyMC Launcher/chrome-sandbox' || true

	update-mime-database /usr/share/mime || true
	update-desktop-database /usr/share/applications || true
	update-desktop-database -q
}

post_upgrade() {
	post_install
}

post_remove() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

	# Delete the link to the binary
	rm -f '/usr/bin/easymc-launcher'
	update-desktop-database -q
}
