post_install() {
  echo ">>> Compile-time configuration"
  echo "    You may want to tune the compile-time configuration:"
  echo "        * config.h: system-specific configuration"
  echo "        * libhed/config.h: low-level tweaks if you want to enable experimantal"
  echo "          features, or disable standard features to reduce code size."
  echo "        * src/term/term.c: default colors (see the definition of colordefs[])."
}

post_upgrade() {
    post_install
}  

