# Check if LanguageTool service is running (0 if active, 3 if stopped)
_check_languagetool_service() {
  systemctl is-active --quiet languagetool
  if [ $? -ne 0 ]; then
    echo "Eloquent's spellchecking mechanism needs LanguageTool standalone server running, please start the service:"
    echo "    # systemctl start languagetool"
  fi
}

post_install() {
  _check_languagetool_service	
}

post_upgrade() {
  _check_languagetool_service
}
