post_install() {
cat << EOF

>>>  To enable by default on all text files in a Pelican site:
>>>  (require 'pelican-mode)
>>>  (pelican-global-mode)
>>>
>>>  Or with use-package and deferred loading:
>>>  (use-package pelican-mode
>>>    :demand :after (:any org rst markdown-mode adoc-mode)
>>>    :config
>>>    (pelican-global-mode))
>>>
>>>  Or, register pelican-mode or pelican-mode-enable-if-site
>>>  as hook functions for more direct control.

EOF
}

post_upgrade() {
        post_install
}