post_install () {

cat << EOF

==> Add this code to your .emacs file to use the mode:

(require 'anzu)
(global-anzu-mode +1)

==> If you are using spaceline or another modeline modifier that
    references anzu internally:

(setq anzu-cons-mode-line-p nil))

==> Or do the above with use-package:

(use-package anzu
  :config
  (global-anzu-mode +1)
  (setq anzu-cons-mode-line-p nil)) ;If using spaceline or the like

EOF
}

post_upgrade () {
	post_install $1
}
