post_install () {

cat << EOF

==> Add this code to your .emacs file to use the mode:

(require 'linum-off)

==> If you want to add, say, term-mode to the list of disabled linum modes:

(add-to-list 'linum-disabled-modes-list 'term-mode)

==> Or do the above with use-package:

(use-package linum-off
  :config
  (add-to-list 'linum-disabled-modes-list 'term-mode)) ; To deactivate linum-mode in term-mode

EOF
}

post_upgrade () {
	post_install $1
}
