infodir=/usr/share/info
filelist=(riece-en.info.gz riece-ja.info.gz)

post_install() {
  for file in ${filelist[@]}
  do
    install-info $infodir/$file $infodir/dir 2> /dev/null
  done

  cat <<EOF
==> Add this to your .emacs to use riece:
==> (add-to-list 'load-path "/usr/share/emacs/site-lisp/riece")
==> (require 'riece)
EOF
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  for file in ${filelist[@]}
  do
    install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

