post_install () {

cat << EOF

==> Add this code to your .emacs file to use the mode:

(require 'evil-magit)
(setq evil-magit-state 'normal) ; This is probably default

==> Optional: disable additional bindings for yanking text
(setq evil-magit-use-y-for-yank nil) ; This might also be default

==> Or, with use-package:

(use-package evil-magit
  :config
  (setq evil-magit-state 'normal)
  (setq evil-magit-use-y-for-yank nil)) ; For yank bindings

EOF
}

post_upgrade () {
	post_install $1
}
