post_install () {

cat << EOF

==> Add this code to your .emacs file to use the mode:

(require 'top-mode)

==> Or, with use-package:

(use-package top-mode)

==> A function to auto-refresh:

(defun top-auto-refresh (rate)
  (interactive "nTop refresh rate (seconds): ")
  (progn
    (cancel-function-timers 'top)
    (if (not (zerop rate))
        (setq *top-refresh-timer*
              (run-with-timer 2 rate 'top)))))

EOF
}

post_upgrade () {
	post_install $1
}
