post_install() {
  cat << EOF
==> Put this in your ~/.emacs file to enable autoloading of
==> vala-mode and auto-recognition of vala files:

(autoload 'vala-mode "vala-mode" "Major mode for editing Vala code." t)
(add-to-list 'auto-mode-alist '("\\.vala$" . vala-mode))
(add-to-list 'auto-mode-alist '("\\.vapi$" . vala-mode))
(add-to-list 'file-coding-system-alist '("\\.vala$" . utf-8))
(add-to-list 'file-coding-system-alist '("\\.vapi$" . utf-8))
EOF
}

post_upgrade() {
  post_install $1
}
