emoticons = {'3m_sie.gif': ['<3m sie>'],
 '8p.gif': ['<pokazal jezyk>'],
 'aniolek.gif': ['<aniol>', '<aniolek>'],
 'aparat.gif': ['<fotka>'],
 'beczy.gif': ['<beczy>', '<beksa>'],
 'bezradny.gif': ['<bezradny>'],
 'bije.gif': ['<bije>'],
 'boisie.gif': ['<boisie>', '<boje sie>'],
 'boks.gif': ['<boks>'],
 'bomb.gif': ['@='],
 'buja_w_oblokach.gif': ['<marzyciel>', '<buja w oblokach>'],
 'bukiet.gif': ['<bukiet>'],
 'buziak.gif': ['<buziak>', '<calus>'],
 'buzki.gif': ['<buzki>'],
 'chatownik.gif': ['<pisze>', '<chatownik>'],
 'chytry.gif': [':>', ';>', ':->', ';->'],
 'cisza.gif': ['<cisza>'],
 'cmok.gif': [';*', ':*', ':-*', ';-*', '<cmok2>', '<cmok>'],
 'co.gif': ['<co?>', '<co>'],
 'co_jest.gif': ['<co jest?>', '<co jest>'],
 'cwaniak.gif': ['<cfaniak>', '<cwaniak2>', '<cwaniak>'],
 'czarodziej.gif': ['<czarodziej>'],
 'czytaj.gif': ['<czytaj>'],
 'diabelek.gif': [']:->'],
 'dobani.gif': ['<blee>', '<do bani>'],
 'dokuczacz.gif': ['<dokuczacz>'],
 'dostal.gif': ['<bija>'],
 'dresiarz.gif': ['<dresik>'],
 'drink.gif': ['<drinkuje>'],
 'dupa.gif': ['<dupa>'],
 'figielek.gif': ['<figielek>'],
 'foch.gif': ['<foch>'],
 'gafa.gif': ['<gafa>'],
 'ganja.gif': ['<ganja>'],
 'gazeta.gif': ['<czyta gazete>'],
 'glaszcze.gif': ['<glaszcze>'],
 'glupek.gif': ['<idiota>', '<glupek>'],
 'glupek2.gif': ['<jestem z glupkiem>'],
 'gool.gif': ['<gool>'],
 'gra.gif': ['<gra>'],
 'haha.gif': ['<lol>'],
 'hahaha.gif': ['<hahaha>'],
 'hejka.gif': ['<heej>', '<hejka>'],
 'hura.gif': ['<jupi>', '<hura>'],
 'jablko.gif': ['<jablko>'],
 'je_pizze.gif': ['<je_pizze>'],
 'jem.gif': ['<jem>'],
 'jezyk.gif': [':PPPPPPP',
               ':PPP',
               ':-PPPPP',
               ':-PPPPPPPPP',
               ':PPPPPPPPP',
               ':-PP',
               ':-PPPPPPPPPP',
               ':PPPP',
               ':PPPPPPPPPP',
               ':P',
               ':-PPPP',
               ':-P',
               ':PP',
               ':-PPPPPPP',
               ':-PPPPPP',
               ':PPPPPP',
               ':-PPP',
               ':PPPPPPPP',
               ':PPPPP',
               ':-PPPPPPPP'],
 'jezyk_oko.gif': [';-PP',
                   ';-PPPP',
                   ';-PPPPP',
                   ';PPP',
                   ';PP',
                   ';PPPPPPPP',
                   ';P',
                   ';-P',
                   ';PPPPPPPPP',
                   '<z jezorem>',
                   ';-PPPPPPPPP',
                   ';PPPPPPPPPP',
                   ';PPPPPPP',
                   ';PPPPP',
                   ';-PPP',
                   ';-PPPPPPPPPP',
                   ';PPPPPP',
                   ';PPPP',
                   ';-PPPPPPP',
                   ';-PPPPPP',
                   ';-PPPPPPPP'],
 'kawa.gif': ['<kawa>'],
 'killer.gif': ['<killer>'],
 'klotnia.gif': ['<halas>', '<klotnia>'],
 'kotek.gif': ['<kot>'],
 'krecka_dostal.gif': ['<urwanie glowy>'],
 'krzyk.gif': ['<krzyk>'],
 'krzywy.gif': [';]', ':]', ':-]', ';-]'],
 'kwiatek.gif': ['<kwiatek>', '<kwiatuszek>'],
 'list.gif': ['<list>'],
 'lol2.gif': ['<lol2>'],
 'luzik.gif': ['<luzik>'],
 'milczek.gif': ['<milczek>'],
 'milosc.gif': ['<milosc>'],
 'mniam.gif': ['<mniam>'],
 'muza.gif': ['<muza>'],
 'mysli.gif': ['<hmmm>', '<mysli>', '<mysli2>'],
 'nauka.gif': ['<nauka>'],
 'nerwus.gif': ['<nerwus>'],
 'nie.gif': ['<nie>', 'niee', '<no>'],
 'nie_powiem.gif': ['<nie powiem>'],
 'obiad.gif': ['<obiad>'],
 'oczko.gif': [';)))',
               ';-))',
               ';))',
               ';))))',
               ';-)))',
               ';)',
               ';-))))))))',
               ';-))))',
               '<mruga>',
               ';-)))))',
               ';-))))))',
               ';-)))))))))',
               ';-)))))))',
               ';-)',
               ';-))))))))))'],
 'oklasky.gif': ['<oklaski>', '<brawo>'],
 'okok.gif': ['<ok>', '<okok>', '<spoko>', '<spox>'],
 'okularnik.gif': ['<okularnik>'],
 'olaboga.gif': ['<olaboga>'],
 'onajego.gif': ['<onajego>'],
 'pada.gif': ['<leje>'],
 'paker.gif': ['<paker>'],
 'palacz.gif': ['<palacz>', '<faja>'],
 'paluszkiem.gif': ['<nono>', '<nonono>'],
 'papa.gif': ['<papa>'],
 'papa2.gif': ['<lapka>', '<papa2>', '<papapa>'],
 'peace.gif': ['<peace>'],
 'pies.gif': ['<pies>'],
 'piwko2.gif': ['<piwosz>'],
 'piwo.gif': ['<piwo>'],
 'placze.gif': [';((((((',
                ';-((',
                ':,(',
                ';(',
                ';((',
                ':,-(',
                ';((((',
                ';(((',
                ';-((((',
                ';(((((',
                ';-(((',
                ';-(',
                '<placze>'],
 'plask.gif': ['<plask>'],
 'plotki.gif': ['<plotki>'],
 'pocieszacz.gif': ['<pocieszacz>', '<przytul>'],
 'pomocy.gif': ['<pomocy>'],
 'prezent.gif': ['<prezent>'],
 'prosi.gif': ['<prosi>'],
 'prysznic.gif': ['<prysznic>'],
 'puknijsie.gif': ['<niedowiarek>'],
 'pytajnik.gif': ['[?]', '[??]', '??'],
 'rotfl.gif': ['<rotfl3>', '<rotfl>', '<rotfl2>', '*ROFL*', '*ROTFL*'],
 'roza.gif': ['<roza>'],
 'rzygi.gif': [':-!', ':*)', '<rzygi>'],
 'sciana.gif': ['<sciana>'],
 'serducho.gif': ['<serce>', '<serducho>'],
 'serduszka.gif': ['<serduszka2>', '<serduszka>'],
 'sex.gif': ['<sex>'],
 'slonko.gif': ['<slonko>'],
 'smutny.gif': [':(', ':((((', ':-(', '<smutny>', ':(((', ':(('],
 'snieg.gif': ['<snieg>'],
 'soczek.gif': ['<soczek>'],
 'spadaj.gif': ['<spadowa>', '<spadaj>'],
 'spie.gif': ['<ziewa>', '<spie>'],
 'spioch.gif': ['<spioch>'],
 'stop.gif': ['<stop>'],
 'stres.gif': ['<stres>'],
 'szampan.gif': ['<winko>'],
 'szok.gif': ['<wow>', '<szok>', '<zdziwiony>'],
 'tak.gif': ['tiaaa', 'yes', '<tak>', '<yes>'],
 'tancze.gif': ['<tancze>'],
 'telefon.gif': ['<telefon2>', '<telefon>'],
 'tort.gif': ['<urodziny>'],
 'tuptup.gif': ['<tuptup>'],
 'uczen.gif': ['<uczen>'],
 'uoeee.gif': [':/', '<uoee>', ';/', ':-/', ';-/'],
 'uscisk.gif': ['<uscisk>'],
 'usmiech.gif': [':)',
                 ':-))))))',
                 ':-))))',
                 ':-))',
                 ':)))',
                 ':-)',
                 ':-)))))',
                 ':-)))))))',
                 '<wesoly>',
                 ':-))))))))))',
                 ':-))))))))',
                 ':-)))))))))',
                 ':-)))',
                 ':))))',
                 ':))'],
 'usta.gif': ['<usta>'],
 'w8.gif': ['<w8>'],
 'wanna.gif': ['<wanna>'],
 'wc.gif': ['<wc>'],
 'wnerw.gif': [':-W', ':-w', '<wsciekly>', '<wnerw>', '~x', '~X'],
 'wykrzyknik.gif': ['!!', '[!]', '[!!]'],
 'wysmiewacz.gif': ['<wysmiewacz>'],
 'yyyy.gif': [':-|', ':|', ';|', ';-|'],
 'zab.gif': ['<zab>'],
 'zacieszacz.gif': ['<radocha>'],
 'zakochany.gif': ['<zakochany>'],
 'zakupy.gif': ['<zakupy>'],
 'zalamka.gif': ['<zalamka>'],
 'zawstydzony.gif': ['<zawstydzony>', '<wstydnis>', '<skromny>'],
 'zeby.gif': [':d', ':D', ':-D', ';d', ':-d', ';D', '<haha>', ';-D', ';-d'],
 'zegar.gif': ['<czas>', '<zegar>'],
 'ziew.gif': ['<ziewa2>'],
 'zlezkawoku.gif': ['<zlezka>'],
 'zly.gif': [':[', 'wrrrr!', '<zly>', '<zdenerwowany>'],
 'zmeczony.gif': ['<zmeczony>'],
 'zniesmaczony.gif': ['<zniesmaczony>']}
