pre_install() {
	echo
	echo "ATTENTION"
	echo
	echo "The 'enchant-hspell' and 'enchant-pure' packages are to be removed"
	echo "due to being superfluous duplicates of Arch repo's 'enchant'."
	echo
	echo "'enchant-hspell' is now a metapackage and is no longer needed on your system."
	echo
	echo "Please uninstall it and migrate to using 'enchant' by running the following:"
	echo
	echo "pacman -R enchant-hspell"
	echo "pacman -Syu --asdeps enchant"
	echo
}

pre_upgrade() {
	pre_install
}
