post_install() {
	ln -s /usr/share/ente_auth/ente_auth /usr/bin/ente_auth
	chmod +x /usr/bin/ente_auth
    ln -s /usr/share/ente_auth/data/flutter_assets/assets/icons/auth-icon.png /usr/share/icons/hicolor/256x256/apps/ente_auth.png
    ln -s /usr/share/ente_auth/data/flutter_assets/assets/icons/auth-icon.png /usr/share/icons/hicolor/128x128/apps/ente_auth.png
}

post_upgrade() {
	post_install
}

post_remove() {
	rm /usr/bin/ente_auth
	rm /usr/share/icons/hicolor/256x256/apps/ente_auth.png
	rm /usr/share/icons/hicolor/128x128/apps/ente_auth.png
}