post_install() {

    echo "Set up mysql database"
    mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
    chown -R mysql:mysql /var/lib/mysql

    echo "Creating MariaDB configuration..."
    cat > /etc/my.cnf.d/ethoscope.cnf <<EOF
[server]
# Binary logging configuration for replication/backup
log-bin          = mysql-bin
binlog_format    = mixed
expire_logs_days = 10
max_binlog_size  = 100M

    systemctl enable --now mariadb && sleep 2
    mysql -u root -e "CREATE USER 'ethoscope'@'localhost' IDENTIFIED BY 'ethoscope'"
    mysql -u root -e "CREATE USER 'node'@'%' IDENTIFIED BY 'node'"
    mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'ethoscope'@'localhost' WITH GRANT OPTION";
    mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'node'@'%' WITH GRANT OPTION";

    #create the python package for the ethoscope
    cd /opt/ethoscope/src/ethoscope
    pip install -e . --break-system-packages

    echo "enable the virtuascope service"
    ln -s /opt/ethoscope/services/virtuascope.service ./

    systemctl enable --now virtuascope
}

pre_remove() {
    echo "disabling systemd service files"
    systemctl stop ethoscope_virtuascope
    systemctl disable ethoscope_virtuascope
}
