#!/bin/sh

set -e

# WIP use at own risk

. /opt/evesetup/lib/evelauncher.shlib

SHAREDIR=$(grep SharedCacheFolder $EVECONF | cut -d= -f2)
BCKUPDIR=$(xdg-user-dir DOCUMENTS 2>/dev/null || true)/EVE
[ -d "$BCKUPDIR" ] || BCKUPDIR=$HOME

USERCONF=wineenv/drive_c/users/$(whoami)/Local\ Settings/Application\ Data/CCP/EVE

cd $SHAREDIR
tar czf $BCKUPDIR/eve_userconf_$(date +%F).tar.gz --exclude=cache --exclude=Browser "$USERCONF"

desktop_msg "User configuration in $BCKUPDIR stored."
