#!/bin/sh

. /opt/evesetup/lib/evelauncher.shlib

check_wine

if [ -x "$WINEPATH/${0#*eve}" ] ;then
    WINECMD=$WINEPATH/${0#*eve}
else
    WINECMD=$CUSTOMWP\ ${0#*eve}
fi

env WINEPREFIX=$WINEPREFIX \
    WINEDEBUG=-all \
    WINEDLLOVERRIDES="mscoree,mshtml,winemenubuilder.exe=d" \
    $WINECMD "$@"
