#!/bin/sh

EVECONF=$HOME/.config/CCP/EVE.conf
UCW=$(grep UseCustomWine $EVECONF | cut -d= -f2)
if [ "x$UCW" = "xtrue" ] ;then
    CUSTOMWP=$(grep CustomWinePath $EVECONF | cut -d= -f2)
    WINEPATH=${CUSTOMWP%/*}
    SHAREDIR=$(grep SharedCacheFolder $EVECONF | cut -d= -f2)
    WINEPREFIX=${SHAREDIR}wineenv
else
    echo "$(basename $0): ERROR: \"Use Custom Wine\" not set!"
    exit 1
fi
if [ ! -x "$WINEPATH/wine" ] ;then
    echo "$(basename $0): ERROR: \"$CUSTOMWP\" in \"Custom Wine path\" not found!"
    exit 1
fi

env WINEPREFIX=$WINEPREFIX \
    WINE=$WINEPATH/wine $(which winetricks) "$@"
