# At least one is required
listener = 0.0.0.0:53
listener = [::]:53

# At least one is required
upstream = 9.9.9.9:53
upstream = tls 9.9.9.9:853 dns.quad9.net

# Optional (default: none)
host = .bad.com        # Return 0.0.0.0 (implicit) for "bad.com"
host = bad.com         # Return 0.0.0.0 (implicit) for "bad.com" and any subdomain
host = 127.0.0.1 .home # Return 127.0.0.1 for the domain name "home"
host = ./hosts         # Read from a file (must include "/" to distinguish from a domain name)

# Optional (default: info)
log_level = info # Can be debug, info, warn, or err
