.TH "failsafewm" 1

.SH NAME
failsafewm \- a frameless, low-footprint window manager

.SH DESCRIPTION
\fBfailsafewm\fR is a frameless window manager designed for very little memory consumption and failsafe sessions.  It is at a very early development stage, and as such, may still be unstable.

.SH USAGE
.TP
.B Alt\-Tab
cycles windows

.TP
.B Alt\-F2
window under mouse can be moved until a mouse button is pressed

.TP
.B Alt\-F3
window under mouse can be resized until a mouse button is pressed

.TP
.B Alt\-F4
currently does nothing

.TP
.B Alt\-F5
raise window under mouse cursor

.SH AUTHOR
.TP
.B failsafewm
written by Robert Sperling <sperling@small-window-manager.de>


.TP
.B failsafewm(1)
written by TDY <tdy@gmx.com>
.PP

.SH COPYRIGHT
.PP
Copyright \(co 2001 Robert Sperling

.PP
This program may be freely redistributed under the terms of the GNU General Public License.
