post_install() {
  echo ""
  echo "Enable falcond service:"
  echo "systemctl enable --now falcond"
  echo ""
  echo "You must add your user to the falcond group in order to add/remove/edit"
  echo "profiles and perform a full reboot:"
  echo "sudo groupadd falcond"
  echo "sudo gpasswd -a $(whoami) falcond"
  echo ""
  echo "The configuration file will be generated automatically on first run "
  echo "located at /etc/falcond/config.conf"
  echo ""
}
