post_remove() {
    echo "Reverting memlock system fixes..."
    [ -f /etc/security/limits.conf ] && sed -i '/^\* soft memlock unlimited$/d' /etc/security/limits.conf
    [ -f /etc/security/limits.conf ] && sed -i '/^\* hard memlock unlimited$/d' /etc/security/limits.conf
    [ -f /etc/systemd/system.conf ] && sed -i 's/^DefaultLimitMEMLOCK=infinity/#DefaultLimitMEMLOCK=infinity/' /etc/systemd/system.conf || true
}
