pre_install() {
    getent group foundationdb > /dev/null || groupadd -r foundationdb > /dev/null
    getent passwd foundationdb > /dev/null || useradd -C "FoundationDB" -g foundationdb -s /bin/false -r -d /var/lib/foundationdb foundationdb > /dev/null
}

post_install() {
    if [ ! -f /etc/foundationdb/fdb.cluster ]; then
        description=$(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | head -c 8)
        random_str=$(LC_CTYPE=C tr -dc A-Za-z0-9 < /dev/urandom | head -c 8)
        echo $description:$random_str@127.0.0.1:4500 > /etc/foundationdb/fdb.cluster
        chown foundationdb:foundationdb /etc/foundationdb/fdb.cluster
        chmod 0664 /etc/foundationdb/fdb.cluster
    fi

    printf '> To start the FoundationDB service, run:\n'
    printf '  systemctl enable --now foundationdb.service\n\n'
}

pre_remove() {
    systemctl stop foundationdb.service > /dev/null 2>&1
    systemctl disable foundationdb.service > /dev/null 2>&1
}
