post_install() {

	systemctl unmask ffplayout.service >/dev/null || true
	systemctl --system daemon-reload >/dev/null || true

	sysUser="ffpu"
	IP=$(ip route get 1.2.3.4 | awk '{if($7 !~ /^[[:space:]]*$/) print $7}')

	if [ -f /run/.containerenv ] || [ -f /run/.dockerenv ] || [ -f /.dockerenv ] || [ -f /.dockerinit ]; then
	    sysUser="root"
	fi

	if [ ! $(id -u $sysUser 2>/dev/null || echo -1) -ge 0 ]; then
	    useradd -m --system $sysUser || adduser --system --create-home $sysUser > /dev/null || adduser --system --home "/home/$sysUser" $sysUser
	fi

	if [ ! -d "/usr/share/ffplayout/db" ]; then
	    mkdir "/usr/share/ffplayout/db"
	    mkdir -p "/var/lib/ffplayout/playlists"
	    mkdir -p "/var/lib/ffplayout/tv-media"
		
		/usr/bin/ffplayout -d "${IP}:8787" --log-path=/var/log/ffplayout --hls-path=/usr/share/ffplayout/public --storage-path=/var/lib/ffplayout/tv-media --shared-storage -u admin -p admin -m ffplayout@example.org

	    chown -R ${sysUser}: "/usr/share/ffplayout"
	    chown -R ${sysUser}: "/var/lib/ffplayout"
	else
	    chown -R ${sysUser}: "/usr/share/ffplayout"
	    chown -R ${sysUser}: "/var/lib/ffplayout"
	fi

	if [ ! -d "/var/log/ffplayout" ]; then
	    mkdir "/var/log/ffplayout"

	    chown ${sysUser}: "/var/log/ffplayout"
	else
	    chown ${sysUser}: "/var/log/ffplayout"
	fi

	echo "1. activate systemd service:"
	echo "   $ systemctl enable --now ffplayout"
	echo "2. use a reverse proxy for SSL, Port is **8787**."
	echo "3. login with your browser, address without proxy would be: **http://${IP}:8787**"
	echo "5. Login using the default "admin" account and the default "admin" password with your web browser; the address without a proxy would be: **http://${IP}:8787**"
	echo "4. Default location for playlists and media files are: **/var/lib/ffplayout/**."
	echo "6. If you want to change the default global settings:"
	echo "	 $ sudo rm -rv /usr/share/ffplayout/db/*"
	echo "   $ ffplayout -i -d "${IP}:8787"

}

post_upgrade() {
	post_install
}

pre_remove() {

	if [ -d /run/systemd/system ]; then
		for service in $(systemctl list-units --type service --all --no-legend | grep 'ffplayout' | awk '{print $1}'); do
            systemctl stop "$service" >/dev/null || true
        done
	fi

}

post_remove() {

	systemctl --system daemon-reload >/dev/null || true
	systemctl unmask ffplayout.service >/dev/null || true

	sysUser="ffpu"

	if [ $(id -u $sysUser 2>/dev/null || echo -1) -ge 0 ]; then
	    userdel -r -f $sysUser
	fi

	rm -rf /var/log/ffplayout

}
