post_install() {
    printf "Getting started with file warden:\n\n"
    echo "Copy the example configuration using:" 
    echo "cp /usr/share/file-warden/config ~/.config/file-warden/config"
    printf "\nOpen the config file and plug in your watch paths and file system events\n"

    printf "\nTo start file-warden, run:\n"
    echo "systemctl --user start file-warden.service"

    printf "\nTo check status of file-warden, run:\n"
    echo "systemctl --user status file-warden.service"

    printf "\nTo start file-warden on boot, run:\n"
    echo "systemctl --user enable file-warden.service"

    printf "\nTo stop file-warden, run:\n"
    echo "systemctl --user stop file-warden.service"

    printf "\nTo view file-warden logs, run:\n"
    echo "journalctl --user -u file-warden"
}

post_upgrade() {
    echo "file-warden has been upgraded."
    echo "If file-warden is active, please run:"
    echo "systemctl --user restart file-warden.service"
}

post_remove() {
    echo "file-warden has been removed."
    echo "You may wish to manually remove leftover user configuration files."
    echo "rm -rf ~/.config/file-warden"
}

