#!/bin/bash
if [ ! -d "/home/$USER/.firefox-nightly-updater" ];then
	mkdir -p /home/$USER/.firefox-nightly-updater
fi

if [ ! -d "/home/$USER/.firefox-nightly-updater/tmp" ];then
	mkdir -p /home/$USER/.firefox-nightly-updater/tmp
fi

cd /home/$USER/.firefox-nightly-updater/tmp/

if [ -d /home/$USER/.firefox-nightly-updater/tmp/firefox-nightly-hg ];then
	rm -rf /home/$USER/.firefox-nightly-updater/tmp/firefox-nightly-hg
fi

git clone https://aur.archlinux.org/firefox-nightly-hg.git

cd firefox-nightly-hg/

if [ -e /home/$USER/.firefox-nightly-updater/firefox.install ];then
	rm /home/$USER/.firefox-nightly-updater/firefox.install
fi

if [ -e /home/$USER/.firefox-nightly-updater/firefox-nightly.desktop ];then
	rm /home/$USER/.firefox-nightly-updater/firefox-nightly.desktop
fi

if [ -e /home/$USER/.firefox-nightly-updater/vendor.js ];then
	rm /home/$USER/.firefox-nightly-updater/vendor.js
fi

if [ -e /home/$USER/.firefox-nightly-updater/PKGBUILD ];then
	rm /home/$USER/.firefox-nightly-updater/PKGBUILD
fi

if [ -e /home/$USER/.firefox-nightly-updater/firefox-nightly-hg-???????.????????????-?-x86_64.pkg.tar.zst ];then
	rm /home/$USER/.firefox-nightly-updater/firefox-nightly-hg-???????.????????????-?-x86_64.pkg.tar.zst
fi

cp firefox.install /home/$USER/.firefox-nightly-updater/
cp firefox-nightly.desktop /home/$USER/.firefox-nightly-updater/
cp vendor.js /home/$USER/.firefox-nightly-updater/
cp PKGBUILD /home/$USER/.firefox-nightly-updater/

rm firefox.install
rm firefox-nightly.desktop
rm vendor.js
rm PKGBUILD

cd /home/$USER/.firefox-nightly-updater

echo 'The compilation will start now ...';
makepkg -s

if [ -e firefox-nightly-hg-???????.????????????-?-x86_64.pkg.tar.zst ];then
	echo 'Successful compilation !';
else
	echo 'Echec compilation';
	exit 1
fi

read -r -p "Do you want to apply the update ? [y/N] " input
case $input in
	[yY]|[yY])
		sudo pacman -U firefox-nightly-hg-???????.????????????-?-x86_64.pkg.tar.zst
		echo 'Update complete'
		;;
	[nN]|[nN])
		echo "Echec"
		;;
	*)
		echo "Invalid input..."
		exit 1
		;;
esac
