msg() {
    ALL_OFF="\e[1;0m"
    BOLD="\e[1;1m"
    RED="${BOLD}\e[1;31m"
	local mesg=$1; shift
	printf "${RED}==>${ALL_OFF}${BOLD} ${mesg}${ALL_OFF}" "$@" >&2
}

post_install() {
    post_upgrade
}

post_upgrade() {
    msg "Included are profiles for Firejail and profile-sync-daemon."
    echo ""
    msg "To use psd add firedragon to ~/.config/psd/psd.conf"
    echo ""
    msg "Enjoy the Firedragon 🔥🐉"
    echo ""
}
