post_install() {
  echo ""
  echo "Install Firefox theme - copy from /usr/share/doc/fluent-gtk-theme/firefox/:"
  echo "https://github.com/vinceliuice/Fluent-gtk-theme/blob/master/src/firefox"
  echo ""
  echo "Fix for Dash to panel:"
  echo "cd /usr/share/doc/fluent-gtk-theme/dash-to-panel"
  echo "sudo ./install.sh "
  echo ""
  echo "Restore original styesheet.css before updating Dash to panel:"
  echo "cd /usr/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com"
  echo "sudo mv stylesheet.css.back stylesheet.css"
  echo ""
}

post_upgrade() {
   post_install
}
