ADD_LIBRARY(FMT::FMT SHARED IMPORTED GLOBAL)
SET(_libname
    ${CMAKE_SHARED_LIBRARY_PREFIX}fmt${CMAKE_SHARED_LIBRARY_SUFFIX}
)
SET_PROPERTY(
    TARGET FMT::FMT
    PROPERTY IMPORTED_LOCATION /usr/lib/${_libname}
)
SET_PROPERTY(
    TARGET FMT::FMT
    PROPERTY IMPORTED_SONAME ${_libname}
)
TARGET_INCLUDE_DIRECTORIES(
    FMT::FMT
    INTERFACE /usr/include/fmt
)
LIST(APPEND RV_DEPS_LIST FMT::FMT)
