# vim: ft=sh

# libevent-openssl holding directory
CUSTOM_LIBRARY="/usr/lib/forcepoint-client"

# vpn address (ip or domain)
VPN_GATEWAY=""

# vpn credentials
USERNAME=""
PASSWORD="" # password will be visible in logs! PASSCMD is preffered

# command for password lookup
# TIP: you can generate entry in keyring by running
# secret-tool store --label forcepoint-client FOV-VPN $USERNAME
# and entering your password
PASSCMD='su '"$USER"' -c "secret-tool lookup FOV-VPN '"$USERNAME"'"'

# program in charge of dns
RESOLVER="/usr/bin/nmcli"

# XML config, can be found in ~/.config/forcepoint/sslvpn after first connection
CONFIG=""
