FREESURFER_HOME=/opt/freesurfer
source $FREESURFER_HOME/FreeSurferEnv.sh
export FREESURFER_HOME
export FSFAST_HOME
export SUBJECTS_DIR
export MINC_BIN_DIR
export MINC_LIB_DIR
export PATH=$PATH:${FREESURFER_HOME}/bin
export LD_LIBRARY_PATH=${FREESURFER_HOME}/lib:$LD_LIBRARY_PATH
