post_install()
{
    echo "
    For dictd to notice the new dictionary, add
      database hun-eng
      {
        data  /usr/share/dictd/hun-eng.dict.dz
        index /usr/share/dictd/hun-eng.index
      }
    to /etc/dict/dictd.conf, and restart dictd.
      systemctl restart dictd
    "
}

post_upgrade()
{
    echo "
    Dictd must be restarted in order to detect the new dictionary:
      systemctl restart dictd
    "
}

