post_install() {
  echo "Additional setup is needed, as freeablo only searches for resources in the"
  echo "current directory:"
  echo "You will need to put the files 'DIABDAT.MPQ' and 'Diablo.exe'"
  echo "in /opt/freeablo."
  echo ""
  echo "This will not work well on multi-user systems. I need to"
  echo "figure out how to allow multiple users to use multiple save files"
}
post_upgrade() {
  post_install
}
