appID=com.futunn.ftnn-desktop
friendlyName=FTNN
stateDirectory=FTNN_Desktop_Data
launchTarget=/opt/FTNN/FTNN
bindNetwork=true
terminateImmediately=false
useZink=false
qt5Compat=true
waylandOnly=false
gameMode=false
mprisName=""
bindCameras=false
bindPipewire=false
bindInputDevices=false
allowInhibit=false
allowGlobalShortcuts=false
dbusWake=false
