post_install() {
    echo "Checking for missing lcdproc drivers..."
    ln -sf /usr/lib/lcdproc-g15/g15.so /usr/lib/lcdproc/g15.so
    ln -sf /usr/lib/lcdproc-g15/linux_input.so /usr/lib/lcdproc/linux_input.so
    if [ ! -f /usr/lib/systemd/system/ydotoold.service ]; then
        install -m 644 /usr/share/g15ctrld/ydotoold.service /usr/lib/systemd/system/ydotoold.service
        systemctl daemon-reload
        echo "Systemd daemon reloaded."
    fi
}

    echo -e "\033[1;32m*************************************************************************\033[0m"
    echo -e "\033[1;32m**      _____   __ _____    _____ _______ _____  _      _____          **\033[0m"
    echo -e "\033[1;32m**     / ____| /_ | ____|  / ____|__   __|  __ \ | |    |  __ \        **\033[0m" 
    echo -e "\033[1;32m**     | |  __   | | |__   | |       | |  | |__) | |    | |  | |       **\033[0m"
    echo -e "\033[1;32m**     | | |_ |  | |___ \  | |       | |  |  _  /| |    | |  | |       **\033[0m"
    echo -e "\033[1;32m**     | |__| |  | |___) | | |____   | |  | | \ \| |____| |__| |       **\033[0m"
    echo -e "\033[1;32m**      \_____|  |_|____/   \_____|  |_|  |_|  \_\______|_____/        **\033[0m"
    echo -e "\033[1;32m**                                                                     **\033[0m"
    echo -e "\033[1;32m**         \033[1;36m#LCDproc G15 driver installed successfully                  \033[1;32m**\033[0m"
    echo -e "\033[1;32m**         #Change drivers in LCDd.conf file like                      **\033[0m"
    echo -e "\033[1;32m**         driver=g15                                                  **\033[0m"
    echo -e "\033[1;32m**         driver=linux_input                                          **\033[0m"
    echo -e "\033[1;32m**         #or do a                                                    **\033[0m"
    echo -e "\033[1;32m**         sudo mv /etc/LCDd.conf.pacnew /etc/LCDd.conf                **\033[0m"
    echo -e "\033[1;32m**         sudo mv /etc/lcdproc.conf.pacnew /etc/lcdproc.conf          **\033[0m"
    echo -e "\033[1;32m**         #if you want the menu to work, copy LCDd-menu to LCDd       **\033[0m"
    echo -e "\033[1;32m**         sudo cp /usr/bin/LCDd-menu /usr/bin/LCDd                    **\033[0m"
    echo -e "\033[1;32m**         #then do a                                                  **\033[0m"
    echo -e "\033[1;32m**         sudo systemctl enable --now lcdd                            **\033[0m"
    echo -e "\033[1;32m**         sudo systemctl enable --now lcdproc                         **\033[0m"
    echo -e "\033[1;32m**         sudo systemctl enable --now g15ctrld                        **\033[0m"
    echo -e "\033[1;32m**         sudo systemctl enable --now ydotool                         **\033[0m"
    echo -e "\033[1;32m**         sudo shutdown -r now                                        **\033[0m"
    echo -e "\033[1;32m*************************************************************************\033[0m"

post_upgrade() {
    ln -sf /usr/lib/lcdproc-g15/g15.so /usr/lib/lcdproc/g15.so
    ln -sf /usr/lib/lcdproc-g15/linux_input.so /usr/lib/lcdproc/linux_input.so
}

post_remove() {
    rm -f /usr/lib/lcdproc/g15.so
    rm -f /usr/lib/lcdproc-g15/g15.so
    rm -f /usr/lib/lcdproc/linux_input.so
    rm -f /usr/lib/lcdproc-g15/linux_input.so
}
