post_install() {
    if [[ -f /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo ]]; then
        install -Dm644 /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo{,.bak}
    fi

    install -Dm644 /usr/share/locale/zh_CN/LC_MESSAGES/gcc{-kawaii,}.mo

    # note "Please run 'echo export LANG=zh_CN.UTF-8 > /etc/locale.conf'"
    echo -e "\e[34m::\e[0m Please run 'echo "export LANG=zh_CN.UTF-8" > /etc/locale.conf'"
}

post_upgrade() {
    install -Dm644 /usr/share/locale/zh_CN/LC_MESSAGES/gcc{-kawaii,}.mo
}

pre_remove() {
    install -Dm644 /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo{.bak,}
}
