post_install() {
    if [[ -f /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo ]]; then
        cp /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo \
            "/usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo.bak"
    fi

    cp /usr/share/locale/zh_CN/LC_MESSAGES/gcc-kawaii.mo /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo

    # note "Please run 'echo export LANG=zh_CN.UTF-8 > /etc/locale.conf'"
    echo -e "\a Please run 'echo "export LANG=zh_CN.UTF-8" > /etc/locale.conf'"
}

post_upgrade() {
    cp /usr/share/locale/zh_CN/LC_MESSAGES/gcc-kawaii.mo /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo
}

pre_remove() {
    cp /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo.bak /usr/share/locale/zh_CN/LC_MESSAGES/gcc.mo
}
