package main

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/google/go-github/v72/github"
	"github.com/liujed/goutil/sets"
	"golang.org/x/mod/semver"
)

var topDir = "."

const packageHistoryFilename = "package_history.toml"

const repoOwner = "liujed"
const repoName = "dns01proxy"
const buildsPath = "internal/builds"

//go:generate go run .
func main() {
	err := mainWithErr()
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}
}

func mainWithErr() error {
	gh := github.NewClient(nil)
	ctx := context.Background()

	// Get the latest release tag from the dns01proxy GitHub repository.
	curVer, err := getLatestReleaseTag(ctx, gh)
	if err != nil {
		return fmt.Errorf("unable to get latest release: %w", err)
	}

	// Get a list of builds from the dns01proxy GitHub repository.
	builds, err := getBuildsForRelease(ctx, gh, curVer)
	if err != nil {
		return fmt.Errorf("unable to get builds for release %q: %w", curVer, err)
	}

	// Get the list of all packages we've ever produced.
	allPackages, err := updatePackageHistory(builds)
	if err != nil {
		return err
	}

	templateData := TemplateData{
		Builds:      builds,
		Version:     strings.ReplaceAll(strings.TrimPrefix(curVer, "v"), "-", "_"),
		AllPackages: allPackages,
	}

	// Write the PKGBUILD.
	f, err := os.Create(filepath.Join(topDir, "PKGBUILD"))
	if err != nil {
		return fmt.Errorf("unable to create PKGBUILD: %w", err)
	}
	func() {
		defer f.Close()
		err = generatePKGBUILD(f, templateData)
	}()
	if err != nil {
		return fmt.Errorf("unable to write PKGBUILD: %w", err)
	}

	return nil
}

func getLatestReleaseTag(
	ctx context.Context,
	gh *github.Client,
) (string, error) {
	result := ""
	for nextPage := 0; ; {
		tags, resp, err := gh.Repositories.ListTags(
			ctx,
			repoOwner,
			repoName,
			&github.ListOptions{
				Page:    nextPage,
				PerPage: 100,
			},
		)
		if err != nil {
			return "", err
		}

		for _, tag := range tags {
			curName := tag.GetName()
			if semver.Prerelease(curName) != "" {
				// Ignore prerelease.
				continue
			}

			if result == "" || semver.Compare(result, curName) < 0 {
				result = curName
			}
		}

		if resp.NextPage == 0 {
			if result == "" {
				return "", fmt.Errorf("no releases found")
			}
			return result, nil
		}

		nextPage = resp.NextPage
	}
}

func getBuildsForRelease(
	ctx context.Context,
	gh *github.Client,
	ver string,
) ([]string, error) {
	// XXX This returns at most 1,000 directory objects, which should work for the
	// foreseeable future.
	_, contents, _, err := gh.Repositories.GetContents(
		ctx,
		repoOwner,
		repoName,
		buildsPath,
		&github.RepositoryContentGetOptions{
			Ref: ver,
		},
	)
	if err != nil {
		return nil, err
	}

	if len(contents) == 1000 {
		// We've reached the limits of the GitHub API endpoints that we're using. If
		// this happens, we should switch to the "Get a tree" endpoint:
		// https://docs.github.com/en/rest/git/trees?apiVersion=2022-11-28#get-a-tree
		return nil, fmt.Errorf("reached limit of GitHub 'Get repository content'")
	}

	result := []string{}
	for _, content := range contents {
		if content.GetType() != "dir" {
			continue
		}
		result = append(result, content.GetName())
	}

	return result, nil
}

func generatePKGBUILD(w io.Writer, templateData TemplateData) error {
	_, err := io.WriteString(w, `# Code generated by generate.go. DO NOT EDIT.
`)
	if err != nil {
		return fmt.Errorf("unable to write header: %w", err)
	}
	err = pkgbuildTemplate.Execute(w, templateData)
	if err != nil {
		return fmt.Errorf("unable to execute PKGBUILD template: %w", err)
	}

	return nil
}

// Given the list of builds for the current version, updates
// package_history.toml and returns the resulting catalogue of all packages ever
// produced by the split package.
func updatePackageHistory(builds []string) ([]string, error) {
	var hist struct {
		PackageNames []string
	}

	// Read in the package history.
	_, err := toml.DecodeFile(packageHistoryFilename, &hist)
	if err != nil {
		return nil, fmt.Errorf("unable to read package history: %w", err)
	}

	// Add the current set of builds.
	packageNames := sets.NewHashSet(hist.PackageNames...)
	for _, build := range builds {
		packageNames.Add("dns01proxy-" + build)
	}
	hist.PackageNames = packageNames.ToSlice()
	slices.Sort(hist.PackageNames)

	// Update the package history.
	f, err := os.Create(packageHistoryFilename)
	if err != nil {
		return nil, fmt.Errorf("unable to update package history: %w", err)
	}
	defer f.Close()
	f.WriteString(`# Code generated by generate.go. DO NOT EDIT.

# Catalogues the names of all dns01proxy packages ever created by this split
# package.
`)
	enc := toml.NewEncoder(f)
	enc.Encode(hist)

	return hist.PackageNames, nil
}
