post_install() {

cat <<- 'EOF'

#--------------------------------------------------------------------------------------------------

    USAGE:
        after install, you can enable it:
        A. globaly:
            1. in users: ~/.bashrc and /etc/skel/.bashrc remove\comment var PS1 or empty this files
            2. add line:
                   source /usr/share/gentoo-color-bash/10-gentoo-color.bash
               to global: /etc/bash.bashrc
        B. localy:
               add line:
                   source /usr/share/gentoo-color-bash/10-gentoo-color.bash
               to users: ~/.bashrc and /etc/skel/.bashrc

        Now you can add (if needed) you own ~/.dir_colors or /etc/DIR_COLORS for perfect ls.
        See arch wiki or github for examples.

#--------------------------------------------------------------------------------------------------
EOF

}

post_upgrade() {
  post_install ${1}
}
