post_install() {
	chown -R http:http var/lib/gestimag
	chown http:http etc/gestimag/conf.php
	systemctl daemon-reload
	systemctl restart php-fpm-legacy.service
	echo 'Please configure your webserver. Example configuration files for nginx and apache are provided in /etc/gestimag/contrib'
	echo 'We restarted php-fpm-legacy.service for you at it was necessary to give write permission to /usr/share/dolibarr and /etc/gestimag'
	echo 'Finish installation by pointing your browser to https://erp.example.com where example.com will be replaced by the domain name you use'
}

post_upgrade() {
	old=`expr $2 : '\([0-9]*\.[0-9]*\.\)'`"0"
	new=`expr $1 : '\([0-9]*\.[0-9]*\.\)'`"0"
	if [ $old == $new ]
	then
		if [ $old == '0.0.1' ]
		then
			old='0.0.0'
		fi	
	fi
	rm /var/lib/gestimag/install.lock
	cd /usr/share/gestimag/htdocs/install
	echo 'upgrade.php' $old $new
	php upgrade.php $old $new > /dev/null
	echo 'upgrade2.php' $old $new
	php upgrade2.php $old $new > /dev/null
	php step5.php $old $new > /dev/null
	cd /
	touch /var/lib/gestimag/install.lock
	chmod 444 /var/lib/gestimag/install.lock
}
