#!/usr/bin/env bash
#
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail
#set -x
#set -x 将在命令执行前打印出命令 方便调试

set -e
# -e 遇到错误将停止 
set -o pipefail
# pipefail set -e有一个例外情况，就是不适用于管道命令。所谓管道命令，就是多个子命令通过管道运算符（|）组合成为一个大的命令。Bash 会把最后一个子命令的返回值，作为整个命令的返回值。也就是说，只要最后一个子命令不失败，管道命令总是会执行成功，因此它后面命令依然会执行，set -e就失效了。

set  -u
# -u 遇到不存在的变量 将报错

## 写法一
#set -euxo pipefail
## 写法二
#set -eux
#set -o pipefail
#这两种写法建议放在所有 Bash 脚本的头部。另一种办法是在执行 Bash 脚本的时候，从命令行传入这些参数。
#$ bash -euxo pipefail script.sh
dev=wg
gfwPathName=/var/tmp/gfwlist-route/927fe1ad-ade4-485a-ad71-7acb1dc5e1ac/
if [ ! -d $gfwPathName ]; then
	echo mkdir $gfwPathName
  mkdir -pv $gfwPathName
fi
set +e
echo down google ip ....
curl http://vps.aihlp.com/gfw/google-ip -o $gfwPathName/google-ip-tmp
err=$?
if [ $err -ne 0 ]
then
	compare-file-by-sha512 $gfwPathName/google-ip-tmp $gfwPathName/google-ip
   err=$?
	if [ $err -ne 0 ]
	then
		mv $gfwPathName/google-ip-tmp $gfwPathName/google-ip
		echo update google-ip
		iproutefile $gfwPathName/google-ip $dev
	fi
else 
   iproutefile $gfwPathName/google-ip $dev
fi	

echo down github ip 
curl http://vps.aihlp.com/gfw/github-ip -o $gfwPathName/github-ip-tmp
err=$?
if [ $err -ne 0 ]
then
	compare-file-by-sha512 $gfwPathName/github-ip-tmp $gfwPathName/github-ip
	err=$?
	if [ $err -ne 0 ]
	then
		mv $gfwPathName/github-ip-tmp $gfwPathName/github-ip
		echo update github-ip    
		iproutefile $gfwPathName/github-ip $dev
	fi
else
		iproutefile $gfwPathName/github-ip $dev
fi

echo down gfwlist ip 
curl http://vps.aihlp.com/gfw/gfwlist-ip -o $gfwPathName/gfwlist-ip-tmp
err=$?
if [ $err -ne 0 ]
then
	compare-file-by-sha512 $gfwPathName/gfwlist-ip-tmp $gfwPathName/gfwlist-ip
	err=$?
	if [ $err -ne 0 ]
	then
		echo update gfwlist-ip
		mv $gfwPathName/gfwlist-ip-tmp $gfwPathName/gfwlist-ip
		iproutefile $gfwPathName/gfwlist-ip $dev
	fi
else
      iproutefile $gfwPathName/gfwlist-ip $dev
fi


echo down dnsmasq  
curl http://vps.aihlp.com/gfw/dnsmasq_gfwlist -o $gfwPathName/dnsmasq_gfwlist_Client-tmp.conf
err=$?
if [ $err -ne 0 ]
then
	compare-file-by-sha512 $gfwPathName/dnsmasq_gfwlist_Client-tmp.conf $gfwPathName/dnsmasq_gfwlist_Client.conf
	err=$?
	if [ $err -ne 0 ]
	then
		echo update dnsmasq
		mv $gfwPathName/dnsmasq_gfwlist_Client-tmp.conf $gfwPathName/dnsmasq_gfwlist_Client.conf
		echo restart dnsmasq
		systemctl restart dnsmasq
	fi
fi
echo exe over