pre_upgrade() {
  echo '==> Unregistering cabalized packages...'
  [[ -d /usr/share/haskell-ghc-9.4 ]] && find /usr/share/haskell-ghc-9.4 -maxdepth 2 -name 'unregister.sh' -exec {} \;
  echo '==> Done.'
}

post_upgrade() {
  echo '==> All cabalized packages need to be reinstalled now.'
  echo '==> See /usr/share/haskell-ghc-9.4/ and ghc-pkg-9.4 list --user for a tentative list of affected packages.'
}
