post_install() {
 echo ""
 echo "Run the folloing to configure the application:"
 echo "git-credential-manager configure"
 echo ""
 echo "And see the following url for backend configuration:"
 echo "https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/credstores.md"
 echo ""
}

post_remove() {
  echo ""
  echo "Remove the credential helper from the git configuration:"
  echo "git-credential-manager unconfigure"
  echo ""
}
