## arg 1:  the new package version
post_install() {
    echo "Remember to execute:"
    echo
    echo "  git-credential-manager-core configure"
    echo
    echo "In order to use Git-Credential-Manager-Core."
    echo
    echo "Additionally, follow the guide here:"
    echo
    echo "  https://aka.ms/gcmcore-linuxcredstores"
    echo
}

post_remove() {
    echo "Control your 'git config' and remove all the informations related to Git-Credential-Manager-Core"
}
