// 0
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "g2.0.04"
#define GIT_HASH "8fabd17c56995dc0611908554e13fbf036d5fd58"
#define GIT_TIME "2014-12-21 14:58:11 +0100"
