// 0
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "1.8.10"
#define GIT_HASH "1db064b3b301680b1ce8e304bcdd5ed1398c1c7f"
#define GIT_TIME "2014-12-27 16:05:07 +0100"
