// 0
//
// This file was automatically generated by the
// updaterevision tool. Do not edit by hand.

#define GIT_DESCRIPTION "g1.8.09"
#define GIT_HASH "cd44dafd15612d78be4c96f6ad70b1aa2c8ee991"
#define GIT_TIME "2014-10-14 08:54:08 +0200"
