tcp {
    host = "127.0.0.1"
    port = 8234
}
upstream {
    local {
        root = "/srv/gemini/root"
        types {
            include = "/usr/share/gmlghd/mime.types"
        }
    }
}
converter {
    allow-empty-lines = true
}
