post_install() {
	     echo "       ______________________________________________________ "
	     echo " ==>  /                                                      \\"
  	     echo " ==> /          Don't forget to Restart GNOME Shell           \\"
  	     echo " ==> \                   (Alt+F2, type r)                     /"
	     echo "      \______________________________________________________/"
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
