post_install() {
  ln -s "/usr/share/gnome-shell-google-calendar/gnome-shell-google-calendar.py" "/usr/bin/gnome-shell-google-calendar"
  chmod 755 "/usr/bin/gnome-shell-google-calendar"
  echo "Run manually first time to identify vs gnome-keyring or set anual details at ~/.config/gnome-shell-google-calendar/config.json"
}

post_remove() {
 rm "/usr/bin/gnome-shell-google-calendar"
}

post_upgrade() {
  if [ ! -f "/usr/bin/gnome-shell-google-calendar" ];
  then
    ln -s "/usr/share/gnome-shell-google-calendar/gnome-shell-google-calendar.py" "/usr/bin/gnome-shell-google-calendar"
    chmod 755 "/usr/bin/gnome-shell-google-calendar"
  fi
  echo "If you are using gnome-shell-google-calendar behind a proxy, then configure the file /usr/share/gnome-shell-google-calendar/gnome-shell-google-calendar-startup.sh."
  echo "Run manually first time to identify vs gnome-keyring or set manual details at ~/.config/gnome-shell-google-calendar/config.json"
}
