post_install() {
	echo ""
	echo "*********************************************************"
  	echo "* Don't forget to enable this extension in GNOME Tweaks *"
  	echo "*                         and                           *"
  	echo "*         restart GNOME Shell ([Alt]+[F2], r)           *"
  	echo "*********************************************************"
  	echo ""
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
