_gnunet_setuid() {
	local GNUNETDNS_GROUP="$(getent group gnunetdns | cut -d: -f3)"
	chown root:root /usr/lib/gnunet/libexec/gnunet-helper-vpn
	chmod u+s /usr/lib/gnunet/libexec/gnunet-helper-vpn
	# chown root:root /usr/lib/gnunet/libexec/gnunet-helper-transport-wlan
	# chmod u+s /usr/lib/gnunet/libexec/gnunet-helper-transport-wlan
	# chown root:root /usr/lib/gnunet/libexec/gnunet-helper-transport-bluetooth
	# chmod u+s /usr/lib/gnunet/libexec/gnunet-helper-transport-bluetooth
	chown root /usr/lib/gnunet/libexec/gnunet-helper-dns
	chgrp "${GNUNETDNS_GROUP}" /usr/lib/gnunet/libexec/gnunet-helper-dns
	chmod 4750 /usr/lib/gnunet/libexec/gnunet-helper-dns
	chgrp "${GNUNETDNS_GROUP}" /usr/lib/gnunet/libexec/gnunet-helper-dns
	chown gnunet:"${GNUNETDNS_GROUP}" /usr/lib/gnunet/libexec/gnunet-helper-dns
	chmod 2750 /usr/lib/gnunet/libexec/gnunet-helper-dns
	chown root:root /usr/lib/gnunet/libexec/gnunet-helper-exit
	chmod u+s /usr/lib/gnunet/libexec/gnunet-helper-exit
	chown root:root /usr/lib/gnunet/libexec/gnunet-helper-nat-server
	chown root:root /usr/lib/gnunet/libexec/gnunet-helper-nat-client
	chmod u+s /usr/lib/gnunet/libexec/gnunet-helper-nat-server
	chmod u+s /usr/lib/gnunet/libexec/gnunet-helper-nat-client
}

post_install() {
	echo '  -> Setting `setuid` permissions...'
	_gnunet_setuid
}

post_upgrade() {
	echo '  -> Updating `setuid` permissions...'
	_gnunet_setuid
}
