
post_install() {
	echo "This package ships a 'goatcounter.service' systemd service, which uses"
	echo "the sqlite database in the home directory '/var/lib/goatcounter'"
	echo "and expects a reverse proxy for port 5000 by default."
	echo "If you want to use a different database (e.g. PostgreSQL) or another"
	echo "port (e.g. for ACME/HTTPS), you can use a service dropin file."
}

post_remove() {
	echo "You may want to remove the database in '/var/lib/goatcounter' manually."
}
