post_install() {
        if [ ! -f /etc/gingertechengine/checks.json ]; then
                echo "Making default check file"
                mv /etc/gingertechengine/example.json /etc/gingertechengine/checks.json
        fi
        
        echo "Start gogios and gogios-web for the system to run."
}

post_upgrade() {
        post_install()
}

pre_remove() {
        systemctl stop gogios-web
        systemctl stop gogios
        systemctl disable gogios-web
        systemctl disable gogios
}
