post_install() {
  echo "Updating font cache... " 
  mkfontscale /usr/share/fonts/misc
  mkfontdir /usr/share/fonts/misc
  xset fp rehash >/dev/null 2>&1
  echo "Make sure that the line"
  echo "FontPath     \"/usr/share/fonts/misc\""
  echo "is present in xorg.conf under the \"Files\" section"
}

post_upgrade() {
  post_install
}

post_remove() {
  mkfontscale /usr/share/fonts/misc
  mkfontdir /usr/share/fonts/misc
  xset fp rehash >/dev/null 2>&1
}

