#!/bin/sh
# Script to start Pale Moon with a temporary empty profile

RANDOMPM=$(mktemp -d --suffix .pm)

if [ -z "$1" ]; then
	palemoon --new-instance --profile "$RANDOMPM"
else
	palemoon --new-instance --profile "$RANDOMPM" "$1"
fi

rm -rf "$RANDOMPM"