post_install() {
    systemctl daemon-reload

    echo "You find an example in /etc/gonsupdate/gonsupdate_sample.toml"
    echo "After adding gonsupdate in systemctl:"
    echo "  systemctl enable gonsupdate.timer"
    echo "  systemctl start gonsupdate.timer"

    true
}

post_upgrade() {
    systemctl daemon-reload

    true
}

pre_remove() {
    systemctl disable gonsupdate.timer
    systemctl stop gonsupdate.timer

    true
}
