post_install() {
  cat <<HERE
Quick howto:
 Type MGLD 00 into Emulator window
 Press Alt-T, select Pexeso using arrow keys and Space
 Press to play the tape loading the game into memory

Emulator shortcuts:
 AltGr + F1   main menu
 AltGr + F2   open tape file (.ptp)
 AltGr + F5   restart
 AltGr + 1-4  scaling modes
 Alt + F4     exit dialog
 AltGr + T    tape browser
HERE
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
