post_install() {
    setcap cap_sys_admin+ep usr/bin/gsr-global-hotkeys
    echo "You can start the overlay UI at system startup by running 'systemctl enable --now --user gpu-screen-recorder-ui' and press Alt+Z to show/hide the UI"
}

post_upgrade() {
    post_install "$1"
    echo "GPU Screen Recorder UI has updated. Run 'systemctl restart --user gpu-screen-recorder-ui' to use the new version of the software without rebooting"
}
