#conduit_compat = false
server_name = "your-hostname-here.example"

max_request_size = 100_000_000
#allow_registration = false
#registration_token = ""

#[tls]
#certs = "/path/to/fullchain.pem"
#key = "/path/to/privkey.pem"

[[listen]]
type = "tcp"
#tls = false
port = 8448
address = "::"

[server_discovery.server]
authority = "your-hostname-here.example:99999"

[server_discovery.client]
base_url = "https://your-hostname-here.example:99999"

[federation]
enable = true
trusted_servers = ["matrix.org"]

[media]
#allow_unauthenticated_access = false
[media.backend]
type = "filesystem"
path = "/var/lib/grapevine/media/"

[database]
backend = "rocksdb"
path = "/var/lib/grapevine/database/"
