# SPDX-FileCopyrightText: 2026 Fomalhaut contributors
# SPDX-License-Identifier: 0BSD

[terminal]
vt = 1

[default_session]
command = "dbus-run-session cage -s -m last -d -- fomalhaut"
user = "greeter"
