#!/bin/sh
java -Dawt.useSystemAAFontSettings=on \
        -cp /opt/greenfoot/bluej.jar bluej.Boot \
        -greenfoot=true \
        -bluej.compiler.showunchecked=false \
        -greenfoot.url.javadoc=file:///usr/share/doc/greenfoot/API \
        "$@"
