#!/bin/sh
unset JFXPATH

if [ -e /usr/lib/jvm/java-21-openjfx/lib/javafx.base.jar ]; then
        JFXPATH=/usr/lib/jvm/java-21-openjfx/lib
else
        JFXPATH=/usr/lib/jvm/java-21-openjdk/lib
fi

CP="/opt/greenfoot/boot.jar"
JAVAFXJARS=`ls -1 $JFXPATH/javafx* | paste -sd ":" -`
CP="$CP:$JAVAFXJARS"

#archlinux-java-run -a 21 -b 21 -- -Djavafx.embed.singleThread=true \
archlinux-java-run -a 21 -b 21 -- \
        -Xmx512M \
        -cp "$CP" bluej.Boot \
        -greenfoot=true \
        -bluej.compiler.showunchecked=false \
        -greenfoot.url.javadoc=file:///usr/share/doc/greenfoot/API \
        "$@"
