node_id = 0
mode = 'standalone'
wal_dir = "/var/lib/greptimedb/wal/"
enable_memory_catalog = false

[storage]
type = 'File'
data_dir = '/var/lib/greptimedb/data/'

[http_options]
addr = '0.0.0.0:4000'
timeout = "30s"

[grpc_options]
addr = '0.0.0.0:4001'
runtime_size = 8

[mysql_options]
addr = '0.0.0.0:4002'
runtime_size = 2

[influxdb_options]
enable = true

[opentsdb_options]
addr = "0.0.0.0:4242"
enable = true
runtime_size = 2

[prometheus_options]
enable = true

[postgres_options]
addr = '0.0.0.0:4003'
runtime_size = 2
check_pwd = false
