post_install() {
    echo -ne "Updating icon cache ...\n\e[1A\e[23C"
    xdg-icon-resource install --novendor --size 48 /usr/share/pixmaps/grisbi/grisbi.png
    echo " done."
    echo -ne "Updating MIME database ...\n\e[1A\e[26C"
    update-mime-database usr/share/mime
    echo " done."
    echo -ne "Updating desktop database ...\n\e[1A\e[29C"
    update-desktop-database -q 2>&1
    echo " done."
}

post_upgrade() {
    post_install $1
}

post_remove() {
    post_install $1
}
