post_install() {
    echo ":: Updating icon cache ..."
    xdg-icon-resource install --novendor --size 48 /usr/share/pixmaps/grisbi/grisbi.png
    echo ":: Updating MIME database ..."
    update-mime-database usr/share/mime
    echo "Updating desktop database ..."
    update-desktop-database -q 2>&1
    echo " done."
}

post_upgrade() {
    post_install $1
}

post_remove() {
    post_install $1
}
