post_install() {
  cat << _EOF 
==> Please set some variables in /etc/default/grub
==> GRUB_THEME="/usr/share/grub/themes/midna/theme.txt
==> GRUB_GFXMODE=1024x768
==> Now update grub:# grub-mkconfig -o /boot/grub/grub.cfg
==> to activate it

_EOF
}

post_upgrade() {

    if [ ! -f /boot/loader/loader.conf ] && ! grep -q NotoSans-Bold-14.pf2 /boot/grub/grub.cfg; then
      grub-mkconfig -o /boot/grub/grub.cfg
    fi
  
}
