post_install() {
	cat << EOF
 ***** NOTICE *****
 *
 * Read the GRUB2 ArchWiki page at https://wiki.archlinux.org/index.php/GRUB2
 * for instructions on updating GRUB modules and core image at /boot/grub/*/
 * This step is not done automatically during package installation.
 *
 * Generate a new GRUB config file /boot/grub/grub.cfg by running:
 *
 *   grub-mkconfig -o /boot/grub/grub.cfg
 *
EOF
}

post_upgrade() {
	post_install
}
