post_install() {
	cp /usr/lib/syslinux/bios/memdisk /boot/
	
	echo "------------------------------------------------------------"
	echo "> Place live iso images you want to boot in /boot/images/"
	echo "> To have them added to grub automatically, run"
	echo "> grub-mkconfig -o /boot/grub/grub.cfg"
	echo "------------------------------------------------------------"
}

post_upgrade() {
	post_install
}

post_remove() {
	rm /boot/memdisk
	grub-mkconfig -o /boot/grub/grub.cfg

	echo "------------------------------------------------------------"
	echo "> You may want to remove your iso images in /boot/images/"
	echo "------------------------------------------------------------"
}

# vim:set ts=2 sw=2 et:
