#!/bin/bash

# When running a script with the Commands plugin, several environment variables are available to ease scripting:
# $GSCONNECT;             # Path to the application (`daemon.js`)
# $GSCONNECT_DEVICE_DBUS; # DBus object path, useful for Python, GJS or other script
# $GSCONNECT_DEVICE_ID;   # The id of the device executing the command
# $GSCONNECT_DEVICE_NAME; # The display name of the device (eg. Google Pixel)
# $GSCONNECT_DEVICE_ICON; # The themed icon name of the device (eg. smartphone-symbolic)

# Screenshot example
filename=/tmp/$(date).png
gnome-screenshot --file=${filename}

${GSCONNECT} --device ${GSCONNECT_DEVICE_ID} --share-file ${filename}
