info_dir=/usr/share/info

post_install() {
    install-info ${info_dir}/guile-xcb.info.gz ${info_dir}/dir 2>/dev/null
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor	     
}

post_upgrade() {
  post_install $1
}

pre_remove() {
    install-info --delete ${info_dir}/guile-xcb.info.gz ${info_dir}/dir 2>/dev/null
}

post_remove() {
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

