post_install() {
    echo ""
    echo "PLEASE READ THIS!"
    echo "Image at: https://gitgud.io/atmk/gwenview-aero"
    echo "Note: If it doesn't show up right (i.e the window isn't properly inset/blurred)"
    echo "you may need to manually set your window decorations to SMOD's window"
    echo "decorations. Once that is done, go into the SMOD settings panel and"
    echo "remove the inner border from the Gwenview window. You will then have to"
    echo "force blur the Gwenview window within the window color settings. Enjoy!"
    echo ""
}
