post_install() {
  groupadd -f gyroflow_users
  setfacl -R -m "g:gyroflow_users:rwX" opt/gyroflow/camera_presets

  echo "Add users to the 'gyroflow_users' group:"
  echo "   sudo usermod -a -G gyroflow_users [username]"
  echo
  echo "Warning: Do not store important data in '/opt/gyroflow'"
}

post_upgrade() {
  post_install
}

pre_install() {
  chmod -R u+rwX,go+rX,go-w opt/gyroflow
}

pre_upgrade() {
  chmod -R u+rwX,go+rX,go-w opt/gyroflow
}

pre_remove() {
  chmod -R u+rwX,go+rX,go-w opt/gyroflow
}

post_remove() {
  rm -rf opt/gyroflow

  echo "If no longer needed, remove the 'gyroflow_users' group:"
  echo "   sudo groupdel gyroflow_users"
}
