HASS_USER=hass

post_install() {
  getent passwd ${HASS_USER} > /dev/null || useradd -U -s /bin/false -r ${HASS_USER} > /dev/null
  mkdir -p /var/lib/hass
  chown -R ${HASS_USER} /var/lib/hass
}

post_upgrade() {
  post_install
  systemctl daemon-reload
  echo "Will now restart home-assistant (if started)"
  systemctl is-enabled home-assistant.service > /dev/null && systemctl restart home-assistant.service
}

post_remove() {
  userdel -f ${HASS_USER}
}
