#!/bin/bash

if test -f "$HOME/.haur_cache"; then

echo "Clearing cache..."

while IFS= read -r line || [[ -n "$line" ]]; do
    echo "Removing $line"
    rm -rf $HOME/.haur/$line
done < "$HOME/.haur_cache"

rm ~/.haur_cache
else
echo "Nothing to clear"
fi
