pre_upgrade() {
	echo "Quitting Heimdall"
	heimdall stop
}

pre_remove() {
	echo "Quitting Heimdall"
	heimdall stop
}

post_install() {
	echo "================================================================="
	echo "The Heimdall software can be launched using 'heimdall start'."
	echo "Alternatively enable the 'heimdall' service to run it on startup."
	echo "================================================================="
}
