#!/usr/bin/bash
source /etc/@_PKGBASE@-helper.conf
if [ -n "$LOG" ]; then
	PROG="$(basename $0)"
	eval "$LOG"
	echo "###### $PROG $@"
fi

stop(){
	modprobe -r @_PKGBASE@
	killall @_PKGBASE@-daemon
	rm -rf /dev/input/by-path/platform-pcspkr-event-spkr
}

case "$1" in
	(start)
		stop
		echo "##### modprobe @_PKGBASE@ debug=${@_PKGBASE@_debug:0}"
		modprobe @_PKGBASE@ debug="${@_PKGBASE@_debug:0}"

		if lsmod | grep -sq @_PKGBASE@; then
			for x in $(find /sys/devices/virtual/input -name name); do
				if [ "$(cat $x)" = "@_PKGBASE@" ]; then
					#we found our device
					d="$(dirname $x)"
					d=$(ls -d $d/event*)
					[ -n "$d" ] && r="-r/dev/input/$(basename $d)"
					break
				fi
			done
			if [ -z "$r" ]; then
				echo "!!!!! cannot find @_PKGBASE@ /dev/input/ device"
				exit 1
			fi
		else
			echo "!!!!! failed to load @_PKGBASE@"
			exit 1
		fi

		echo "# about to exec
${exe} $r $LFLAG"
		eval "exec $exe $r $LFLAG"
		;;
	(stop)
		stop
		;;
	(status)
		if [ -d "/sys/module/@_PKGBASE@" ]; then
			echo "@_PKGBASE@ is loaded"
		else
			echo "@_PKGBASE@ is not loaded"
		fi
		for x in $(pidof @_PKGBASE@-daemon); do
			ps -hp $x
		done
		;;
esac
