# old version (without -$pkgrel): ${1%%-*}
# new version (without -$pkgrel): ${2%%-*}

post_install() {
    export KVERSION="$(pacman -Q | grep "^linux " | cut -d " " -f 2)-ARCH"
    dkms install hid-lg-g710-plus/${1%%-*} -k $KVERSION
}

pre_upgrade() {
    pre_remove ${2%%-*}
}

post_upgrade() {
    post_install ${1%%-*}
}

pre_remove() {
    dkms status | grep "^hid-lg-g710-plus, ${1%%-*}"
    if [ $? -eq 0 ]; then
        dkms remove hid-lg-g710-plus/${1%%-*} --all
    fi
}
