# Blacklisting hid_thrustmaster is a suggested step for this kernel module, due to "hid-tminit not being upstreamed".
# Source (up to date/as of writing this note):
# https://github.com/Kimplul/hid-tmff2?tab=readme-ov-file#common-issues-and-notes
# https://github.com/Kimplul/hid-tmff2/tree/11cca6d4e9b49ec3779573f68917e362e4d65d36?tab=readme-ov-file#common-issues-and-notes
#
# The developer explained this further here:
# https://github.com/Kimplul/hid-tmff2/issues/130#issuecomment-2509364511
#
# I have found this to be an issue under Arch, so I have included this.
# This may (eventually... it has been already years) change, at which point you may remove this blacklist
blacklist hid_thrustmaster
