#!/bin/sh
# Thanks to https://github.com/archlinuxcn/repo/blob/1a86208eabc5ab90ab8381776de12619e152dcdd/hmcl/hmcl-launch-script
WORKDIR=${XDG_CONFIG_HOME:-$HOME/.config}
mkdir -p "$WORKDIR"
cd "$WORKDIR" || return 0
exec /usr/bin/java -jar '/usr/share/java/hmcl-beta-bin/hmcl-beta-bin.jar' "$@"
