#!/usr/bin/env sh
set -eu

print_usage() {
  cat <<EOF
usage: $(basename "$0") [-h/-p] [args passed to java]

Options:
  -h  --help:
    Print this message
  --hmcl-global:
    Use "\${XDG_DATA_HOME:-\$HOME/.local/share}/hmcl" as working directory
EOF
  exit 0
}

args=''
for arg in "$@" ; do
  case "$arg" in
  -h|--help)
    print_usage
    ;;
  --hmcl-global)
    printf 'Global mode\n\n'
    WORKDIR=${XDG_DATA_HOME:-$HOME/.local/share}/hmcl
    mkdir -p "$WORKDIR"
    cd "$WORKDIR" || exit 2
    ;;
  *)
    args="$args $arg"
    ;;
  esac
done

env GDK_CORE_DEVICE_EVENTS=1 archlinux-java-run -f 'javafx' -a '%JAVA_VERSION%' -- -jar '%JAR_PATH%' "$args"
