# bash completion for home-assistant-tui
# Generated by home-assistant-tui completions bash.

_home_assistant_tui() {
  local cur cword
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  cword=$COMP_CWORD

  if [[ $cur == -* ]]; then
    if [[ ${COMP_WORDS[1]-} == todo ]]; then
      COMPREPLY=( $(compgen -W '-h --help --bar-json --count --all' -- "$cur") )
      return
    fi
    COMPREPLY=( $(compgen -W '-h --help' -- "$cur") )
    return
  fi

  case ${COMP_WORDS[1]-} in
    settings)
      if (( cword == 2 )); then
        COMPREPLY=( $(compgen -W 'connection' -- "$cur") )
      fi
      return
      ;;
    completions)
      if (( cword == 2 )); then
        COMPREPLY=( $(compgen -W 'bash fish zsh' -- "$cur") )
      fi
      return
      ;;
  esac

  if (( cword == 1 )); then
    COMPREPLY=( $(compgen -W 'dashboard entities todo settings test-connection test-view completions -h --help' -- "$cur") )
  fi
}

complete -F _home_assistant_tui home-assistant-tui
