
post_upgrade() {
  if [ $(vercmp $2 1:2026.7.1-2 ) -le 0 ]; then
    echo "==> Note: To prevent errors caused by stale dependencies, the systemd"
    echo "==> service will now automatically recreate the Python virtual"
    echo "==> environment (/var/lib/hass/.venv) upon major Home Assistant"
    echo "==> version upgrades (YYYY.MM). The first startup after a major"
    echo "==> upgrade may take slightly longer to download dependencies."
  fi
}
