post_install() {
	cat <<-EOF

	Start homebridge + UI with systemd:

	$ systemctl enable --now homebridge

	Caveats:

	1) /usr/bin/hb-service places files all over the system, and it will
	also modify /etc/sudoers. It is also capable of installing an
	alternative binary of Node.js. It is recommended to *avoid* using it with an AUR install.

	2) Installing or upgrading plugins from the web UI invokes npm install
	globally (/usr/lib/node_modules). This can pose supply chain attack risks.
	Sticking with verified plugins will provide a higher level of
	security.
	See: https://github.com/homebridge/homebridge/wiki/Verified-Plugins

	3) To give permissions to the web UI to poweroff/reboot the machine and
	install plugins, create a drop-in file in /etc/sudoers.d similar to:

	homebridge ALL=(ALL) NOPASSWD:SETENV: /usr/bin/npm, /usr/bin/shutdown, /usr/local/bin/npm

	4) The web UI runs commands with sudo in various places.
	You have been warned.

	5) It is recommended to run homebridge with a supported Node.js LTS version.
	Currently nodejs-lts-krypton (Node.js 24) is the recommended version.

	6) Note: This feature is broken due to upstream systemd bugs. Use Ciao in the meantime.
	https://github.com/systemd/systemd/pull/41342
	To use systemd-resolved as the mDNS resolver, set up systemd-resolved mDNS
	and then follow these instructions:
	https://github.com/homebridge/homebridge/wiki/mDNS-Options#systemd-resolved-linux-only-experimental

	EOF
}

post_upgrade() {
	post_install
}
