# fish completion for home-assistant-tui
# Generated by home-assistant-tui completions fish.

complete -c home-assistant-tui -f
complete -c home-assistant-tui -s h -l help -d 'Show help message'
complete -c home-assistant-tui -n '__fish_seen_subcommand_from todo' -l bar-json -d 'Print todo status-bar JSON'
complete -c home-assistant-tui -n '__fish_seen_subcommand_from todo' -l count -d 'Print todo item count'
complete -c home-assistant-tui -n '__fish_seen_subcommand_from todo' -l all -d 'Include completed todo items'
complete -c home-assistant-tui -n '__fish_use_subcommand' -a 'dashboard' -d 'Overview of your Home Assistant instance'
complete -c home-assistant-tui -n '__fish_use_subcommand' -a 'entities' -d 'Browse and search all entities'
complete -c home-assistant-tui -n '__fish_use_subcommand' -a 'todo' -d 'View and manage todo lists'
complete -c home-assistant-tui -n '__fish_use_subcommand' -a 'settings' -d 'Configure connection and preferences'
complete -c home-assistant-tui -n '__fish_seen_subcommand_from settings; and not __fish_seen_subcommand_from connection' -a 'connection' -d 'Change Home Assistant URL or access token'
complete -c home-assistant-tui -n '__fish_use_subcommand' -a 'test-connection' -d 'Diagnose Home Assistant connectivity'
complete -c home-assistant-tui -n '__fish_use_subcommand' -a 'test-view' -d 'Open the TUI sandbox view'
complete -c home-assistant-tui -n '__fish_use_subcommand' -a 'completions' -d 'Print shell completions'
complete -c home-assistant-tui -n '__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash fish zsh' -a 'bash' -d 'Bash'
complete -c home-assistant-tui -n '__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash fish zsh' -a 'fish' -d 'Fish'
complete -c home-assistant-tui -n '__fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from bash fish zsh' -a 'zsh' -d 'Zsh'
