post_install () {
mkdir -p /var/lib/hqplayer/home
chown -R root:root /var/lib/hqplayer
chown -R root:root /etc/hqplayer
cd /usr/lib
if [ ! -f "libomp.so.5" ]; then
ln -s libomp.so libomp.so.5
fi
if [ ! -f "/etc/pki/tls/certs/ca-bundle.crt" ]; then
mkdir -p /etc/pki/tls/certs
ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt
fi
}

post_upgrade() {
mkdir -p /var/lib/hqplayer/home
chown -R root:root /var/lib/hqplayer
chown -R root:root /etc/hqplayer
cd /usr/lib
if [ ! -f "libomp.so.5" ]; then
ln -s libomp.so libomp.so.5
fi
if [ ! -f "/etc/pki/tls/certs/ca-bundle.crt" ]; then
mkdir -p /etc/pki/tls/certs
ln -s /etc/ssl/certs/ca-certificates.crt /etc/pki/tls/certs/ca-bundle.crt
fi
}
