#!/bin/bash

while true; do
  choice=$(printf "Next video\nExit\n" | fzf --prompt="hub-rand > ")

  case "$choice" in
    "Next video")
      url=$(curl -s https://example.com/list.txt | shuf -n1)
      xdg-open "$url"
      ;;
    *)
      exit 0
      ;;
  esac
done
