#!/bin/sh

FABRIC_CFG_PATH="/etc/hyperledger/fabric"
CORE_PEER_MSPCONFIGPATH="$FABRIC_CFG_PATH/msp"
CORE_LOGGING_LEVEL=DEBUG

export FABRIC_CFG_PATH
export CORE_PEER_MSPCONFIGPATH
export CORE_LOGGING_LEVEL
