$runner = walker
$lock = hyprlock
$special = special:special

corner = 8
edge = 8

zone = , , bottom left, 200, workspace, -1
zone = , , bottom right, 200, workspace, +1

zone = , , top right, 2000, exec, $lock

zone = , , top left, 500, exec, $runner
zone = , $special, top left, 500, exec, $runner

zone = , , bottom, 1000, togglespecialworkspace
zone = , $special, bottom, 1000, workspace, +0
