#!/bin/bash
cd /usr/share/java/ib-tws
/usr/lib/jvm/java-8-jre/jre/bin/java -cp \* \
                                     -Xmx768m -Dsun.awt.nopixfmt=true -Dsun.java2d.noddraw=true -Dswing.boldMetal=false -Dsun.locale.formatasdefault=true \
                                     jclient.LoginFrame $HOME/.ib-tws
