post_install() {
  cat << EOM
  Put this code into your ~/.emacs
  (setq load-path (cons "/usr/share/emacs/site-lisp/icicles" load-path))
  (require 'icicles)

  Documentation can be found at http://www.emacswiki.org/emacs/Icicles

  The file ring+.el should be loaded after loading the standard 
  GNU file ring.el.  So, in your ~/.emacs file, do this:
  (eval-after-load "ring" '(progn (require 'ring+)))
EOM
}
post_upgrade() {
  post_install
}