/**
 * Icon Replacer - Replaces (nf-*-*) patterns with Unicode characters
 *
 * Auto-generated by fetch-icons.ts - DO NOT EDIT MANUALLY!
 * Total unique nf-names: 896
 * Total icon keys: 954
 */

// Reverse mapping: nf-name → Unicode character
const nfNameToUnicode: Record<string, string> = {
  'nf-cod-chrome_maximize': '', // ICON_MAXIMIZE
  'nf-cod-chrome_minimize': '', // ICON_MINIMIZE
  'nf-cod-symbol_namespace': '', // ICON_NAMESPACE
  'nf-custom-c': '', // ICON_C
  'nf-custom-cpp': '', // ICON_CPP
  'nf-dev-angular': '', // ICON_ANGULAR
  'nf-dev-csharp': '', // ICON_CSHARP
  'nf-dev-docker': '', // ICON_DOCKER
  'nf-dev-git_branch': '', // ICON_BRANCH
  'nf-dev-git_commit': '', // ICON_COMMIT
  'nf-dev-git_merge': '', // ICON_MERGE
  'nf-dev-git_pull_request': '', // ICON_PULL_REQUEST
  'nf-dev-go': '', // ICON_GO
  'nf-dev-java': '', // ICON_JAVA
  'nf-dev-javascript': '', // ICON_JAVASCRIPT
  'nf-dev-kotlin': '', // ICON_KOTLIN
  'nf-dev-nodejs': '', // ICON_NODEJS
  'nf-dev-nodejs_small': '', // ICON_NODEJS_SMALL
  'nf-dev-npm': '', // ICON_NPM
  'nf-dev-php': '', // ICON_PHP
  'nf-dev-python': '', // ICON_PYTHON
  'nf-dev-rabbitmq': '', // ICON_RABBITMQ
  'nf-dev-react': '', // ICON_REACT
  'nf-dev-ruby': '', // ICON_RUBY
  'nf-dev-rust': '', // ICON_RUST
  'nf-dev-safari': '', // ICON_SAFARI
  'nf-dev-ssh': '', // ICON_SSH
  'nf-dev-swift': '', // ICON_SWIFT
  'nf-dev-terminal': '', // ICON_TERMINAL
  'nf-dev-typescript': '', // ICON_TYPESCRIPT
  'nf-fa-adjust': '', // ICON_ADJUST
  'nf-fa-align_left': '', // ICON_ALIGN_LEFT
  'nf-fa-amazon': '', // ICON_AMAZON
  'nf-fa-ambulance': '', // ICON_AMBULANCE
  'nf-fa-anchor': '', // ICON_ANCHOR
  'nf-fa-android': '', // ICON_ANDROID
  'nf-fa-angellist': '', // ICON_ANGELLIST
  'nf-fa-angle_double_left': '', // ICON_ANGLE_DOUBLE_LEFT
  'nf-fa-angle_double_right': '', // ICON_ANGLE_DOUBLE_RIGHT
  'nf-fa-angle_down': '', // ICON_ANGLE_DOWN
  'nf-fa-angle_left': '', // ICON_ANGLE_LEFT
  'nf-fa-angle_right': '', // ICON_ANGLE_RIGHT
  'nf-fa-angle_up': '', // ICON_ANGLE_UP
  'nf-fa-apple': '', // ICON_APPLE
  'nf-fa-archive': '', // ICON_ARCHIVE
  'nf-fa-area_chart': '', // ICON_AREA_CHART
  'nf-fa-arrow_down': '', // ICON_ARROW_DOWN, ICON_ARROW_DOWN_ALT
  'nf-fa-arrow_left': '', // ICON_ARROW_LEFT, ICON_ARROW_LEFT_ALT
  'nf-fa-arrow_right': '', // ICON_ARROW_RIGHT, ICON_ARROW_RIGHT_ALT
  'nf-fa-arrow_up': '', // ICON_ARROW_UP, ICON_ARROW_UP_ALT
  'nf-fa-arrows': '', // ICON_ARROWS
  'nf-fa-arrows_alt': '', // ICON_ARROWS_ALT
  'nf-fa-arrows_h': '', // ICON_ARROWS_H
  'nf-fa-arrows_v': '', // ICON_ARROWS_V
  'nf-fa-asterisk': '', // ICON_ASTERISK
  'nf-fa-atom': '', // ICON_ATOM
  'nf-fa-balance_scale': '', // ICON_BALANCE_SCALE
  'nf-fa-ban': '', // ICON_CANCEL
  'nf-fa-bank': '', // ICON_BANK
  'nf-fa-bar_chart': '', // ICON_CHART
  'nf-fa-barcode': '', // ICON_BARCODE
  'nf-fa-bars': '', // ICON_HAMBURGER, ICON_MENU
  'nf-fa-battery_full': '', // ICON_BATTERY_FULL
  'nf-fa-battery_half': '', // ICON_BATTERY_HALF
  'nf-fa-battery_quarter': '', // ICON_BATTERY_QUARTER
  'nf-fa-bed': '', // ICON_BED
  'nf-fa-bell': '', // ICON_BELL
  'nf-fa-bell_slash': '', // ICON_BELL_SLASH
  'nf-fa-bicycle': '', // ICON_BICYCLE
  'nf-fa-binoculars': '', // ICON_BINOCULARS
  'nf-fa-biohazard': '', // ICON_BIOHAZARD
  'nf-fa-black_tie': '', // ICON_BLACK_TIE
  'nf-fa-bold': '', // ICON_BOLD
  'nf-fa-bolt': '', // ICON_BOLT
  'nf-fa-bomb': '', // ICON_BOMB
  'nf-fa-book': '', // ICON_DOCS
  'nf-fa-bookmark': '', // ICON_BOOKMARK
  'nf-fa-brain': '', // ICON_BRAIN
  'nf-fa-briefcase': '', // ICON_BRIEFCASE
  'nf-fa-bug': '', // ICON_BUG
  'nf-fa-building': '', // ICON_BUILDING
  'nf-fa-building_o': '', // ICON_BUILDING_O
  'nf-fa-bullhorn': '', // ICON_BULLHORN
  'nf-fa-bullseye': '', // ICON_BULLSEYE
  'nf-fa-calculator': '', // ICON_CALCULATOR
  'nf-fa-calendar': '', // ICON_CALENDAR
  'nf-fa-calendar_check_o': '', // ICON_CALENDAR_CHECK, ICON_CALENDAR_CHECK_ALT
  'nf-fa-calendar_o': '', // ICON_CALENDAR_O
  'nf-fa-calendar_times_o': '', // ICON_CALENDAR_TIMES_O
  'nf-fa-car': '', // ICON_CAR
  'nf-fa-caret_down': '', // ICON_CARET_DOWN
  'nf-fa-caret_left': '', // ICON_CARET_LEFT
  'nf-fa-caret_right': '', // ICON_START, ICON_CARET_RIGHT_ALT
  'nf-fa-caret_up': '', // ICON_CARET_UP
  'nf-fa-certificate': '', // ICON_CERTIFICATE
  'nf-fa-chain': '', // ICON_CHAIN
  'nf-fa-chain_broken': '', // ICON_DISCONNECTED, ICON_CHAIN_BROKEN_ALT
  'nf-fa-check': '', // ICON_CHECK
  'nf-fa-check_circle': '', // ICON_SUCCESS, ICON_CHECK_CIRCLE_ALT
  'nf-fa-check_square': '', // ICON_CHECK_SQUARE
  'nf-fa-check_square_o': '', // ICON_CHECK_SQUARE_O
  'nf-fa-chess': '', // ICON_CHESS
  'nf-fa-chess_board': '', // ICON_CHESS_BOARD
  'nf-fa-chess_queen': '', // ICON_CHESS_QUEEN
  'nf-fa-chevron_down': '', // ICON_CHEVRON_DOWN
  'nf-fa-chevron_left': '', // ICON_CHEVRON_LEFT
  'nf-fa-chevron_right': '', // ICON_CHEVRON_RIGHT
  'nf-fa-chevron_up': '', // ICON_CHEVRON_UP
  'nf-fa-child': '', // ICON_CHILD
  'nf-fa-chrome': '', // ICON_CHROME
  'nf-fa-circle': '', // ICON_CIRCLE
  'nf-fa-circle_o': '', // ICON_CIRCLE_O, ICON_CIRCLE_EMPTY
  'nf-fa-circle_thin': '', // ICON_CIRCLE_THIN
  'nf-fa-clipboard': '', // ICON_CLIPBOARD
  'nf-fa-clock': '', // ICON_CLOCK_FA
  'nf-fa-clock_o': '', // ICON_CLOCK, ICON_CLOCK_OUTLINE
  'nf-fa-clone': '', // ICON_CLONE
  'nf-fa-cloud': '', // ICON_CLOUD
  'nf-fa-cloud_upload': '', // ICON_CLOUD_UPLOAD
  'nf-fa-code': '', // ICON_CODE
  'nf-fa-code_fork': '', // ICON_CODE_FORK
  'nf-fa-coffee': '', // ICON_COFFEE
  'nf-fa-cog': '', // ICON_SETTINGS
  'nf-fa-cogs': '', // ICON_COGS
  'nf-fa-columns': '', // ICON_COLUMNS
  'nf-fa-comment': '', // ICON_CHAT
  'nf-fa-commenting': '', // ICON_COMMENTING
  'nf-fa-commenting_o': '', // ICON_COMMENTING_O
  'nf-fa-comments': '', // ICON_MESSAGE
  'nf-fa-compass': '', // ICON_COMPASS
  'nf-fa-compress': '', // ICON_COMPRESS
  'nf-fa-connectdevelop': '', // ICON_CONNECTDEVELOP
  'nf-fa-copy': '', // ICON_COPY
  'nf-fa-copyright': '', // ICON_COPYRIGHT
  'nf-fa-credit_card': '', // ICON_CREDIT_CARD
  'nf-fa-cross': '', // ICON_CROSS
  'nf-fa-crosshairs': '', // ICON_CROSSHAIRS
  'nf-fa-css3': '', // ICON_CSS3
  'nf-fa-cube': '', // ICON_PACKAGE
  'nf-fa-cubes': '', // ICON_PACKAGES
  'nf-fa-cut': '', // ICON_CUT
  'nf-fa-cutlery': '', // ICON_CUTLERY
  'nf-fa-dashboard': '', // ICON_DASHBOARD
  'nf-fa-database': '', // ICON_DATABASE
  'nf-fa-desktop': '', // ICON_DESKTOP_FA
  'nf-fa-diamond': '', // ICON_DIAMOND_FA
  'nf-fa-dna': '', // ICON_DNA
  'nf-fa-dot_circle_o': '', // ICON_DOT_CIRCLE
  'nf-fa-download': '', // ICON_DOWNLOAD
  'nf-fa-droplet': '', // ICON_DROPLET
  'nf-fa-edit': '', // ICON_EDIT
  'nf-fa-ellipsis_h': '', // ICON_ELLIPSIS_H
  'nf-fa-ellipsis_v': '', // ICON_ELLIPSIS_V
  'nf-fa-envelope': '', // ICON_MAIL
  'nf-fa-envelope_open': '', // ICON_MAIL_OPEN
  'nf-fa-eraser': '', // ICON_CLEAR
  'nf-fa-exchange': '', // ICON_SYNC
  'nf-fa-exclamation': '', // ICON_EXCLAMATION
  'nf-fa-exclamation_circle': '', // ICON_ALERT, ICON_EXCLAMATION_CIRCLE_ALT
  'nf-fa-exclamation_triangle': '', // ICON_WARNING, ICON_EXCLAMATION_TRIANGLE_ALT
  'nf-fa-expand': '', // ICON_EXPAND
  'nf-fa-external_link': '', // ICON_EXTERNAL, ICON_EXTERNAL_LINK_ALT
  'nf-fa-eye': '', // ICON_READ
  'nf-fa-eye_slash': '', // ICON_EYE_SLASH
  'nf-fa-eyedropper': '', // ICON_EYEDROPPER
  'nf-fa-fast_forward': '', // ICON_FAST_FORWARD
  'nf-fa-feed': '', // ICON_FEED
  'nf-fa-fighter_jet': '', // ICON_FIGHTER_JET
  'nf-fa-file': '', // ICON_FILE_FA
  'nf-fa-file_archive_o': '', // ICON_FILE_ARCHIVE
  'nf-fa-file_code': '', // ICON_FILE_CODE_FILLED
  'nf-fa-file_code_o': '', // ICON_FILE_CODE
  'nf-fa-file_o': '', // ICON_FILE, ICON_FILE_SIMPLE
  'nf-fa-file_pdf_o': '', // ICON_FILE_PDF
  'nf-fa-file_text': '', // ICON_FILE_TEXT
  'nf-fa-file_text_o': '', // ICON_FILE_TEXT_O
  'nf-fa-files_o': '', // ICON_FILES
  'nf-fa-film': '', // ICON_FILM
  'nf-fa-filter': '', // ICON_FILTER
  'nf-fa-fingerprint': '', // ICON_FINGERPRINT_FA
  'nf-fa-fire': '', // ICON_FIRE_FA
  'nf-fa-fire_extinguisher': '', // ICON_FIRE_EXTINGUISHER
  'nf-fa-firefox': '', // ICON_FIREFOX
  'nf-fa-flag': '', // ICON_FLAG
  'nf-fa-flag_checkered': '', // ICON_FLAG_CHECKERED
  'nf-fa-flash': '', // ICON_FLASH
  'nf-fa-flask': '', // ICON_FLASK
  'nf-fa-folder': '', // ICON_FOLDER
  'nf-fa-folder_open': '', // ICON_FOLDER_OPEN, ICON_FOLDER_OPEN_ALT
  'nf-fa-font': '', // ICON_FONT
  'nf-fa-fort_awesome': '', // ICON_FORT_AWESOME
  'nf-fa-forward': '', // ICON_FORWARD
  'nf-fa-gamepad': '', // ICON_GAMEPAD_FA
  'nf-fa-gavel': '', // ICON_GAVEL
  'nf-fa-gear': '', // ICON_GEAR
  'nf-fa-gears': '', // ICON_GEARS
  'nf-fa-ghost': '', // ICON_GHOST
  'nf-fa-gift': '', // ICON_GIFT
  'nf-fa-git': '', // ICON_GIT
  'nf-fa-github': '', // ICON_GITHUB
  'nf-fa-gitlab': '', // ICON_GITLAB
  'nf-fa-glass': '', // ICON_GLASS
  'nf-fa-globe': '', // ICON_BRAVE
  'nf-fa-google': '', // ICON_GOOGLE
  'nf-fa-graduation_cap': '', // ICON_GRADUATION_CAP
  'nf-fa-group': '', // ICON_GROUP
  'nf-fa-hammer': '', // ICON_HAMMER
  'nf-fa-hand': '', // ICON_HAND
  'nf-fa-hand_grab_o': '', // ICON_HAND_GRAB_O
  'nf-fa-hand_o_right': '', // ICON_HAND_POINTER
  'nf-fa-hand_paper_o': '', // ICON_HAND_PAPER_O
  'nf-fa-hand_peace_o': '', // ICON_HAND_PEACE_O
  'nf-fa-hand_pointer_o': '', // ICON_HAND_POINTER_O
  'nf-fa-hand_rock_o': '', // ICON_HAND_ROCK_O
  'nf-fa-hand_scissors_o': '', // ICON_HAND_SCISSORS_O
  'nf-fa-hand_stop_o': '', // ICON_HAND_STOP_O
  'nf-fa-handshake': '', // ICON_HANDSHAKE
  'nf-fa-handshake_o': '', // ICON_HANDSHAKE_O
  'nf-fa-hdd_o': '', // ICON_DISK, ICON_HDD_ALT
  'nf-fa-header': '', // ICON_HEADER
  'nf-fa-headphones': '', // ICON_HEADPHONES
  'nf-fa-heart': '', // ICON_HEART
  'nf-fa-heart_o': '', // ICON_HEART_O
  'nf-fa-heartbeat': '', // ICON_HEARTBEAT
  'nf-fa-history': '', // ICON_HISTORY
  'nf-fa-home': '', // ICON_HOME
  'nf-fa-hourglass': '', // ICON_HOURGLASS
  'nf-fa-hourglass_end': '', // ICON_HOURGLASS_END
  'nf-fa-hourglass_half': '', // ICON_HOURGLASS_HALF
  'nf-fa-hourglass_start': '', // ICON_HOURGLASS_START
  'nf-fa-id_badge': '', // ICON_ID_BADGE
  'nf-fa-id_card': '', // ICON_ID_CARD
  'nf-fa-id_card_o': '', // ICON_ID_CARD_O
  'nf-fa-image': '', // ICON_IMAGE
  'nf-fa-inbox': '', // ICON_INBOX
  'nf-fa-industry': '', // ICON_INDUSTRY
  'nf-fa-info': '', // ICON_INFO_FA
  'nf-fa-info_circle': '', // ICON_INFO, ICON_INFO_CIRCLE_ALT
  'nf-fa-institution': '', // ICON_INSTITUTION
  'nf-fa-key': '', // ICON_KEY
  'nf-fa-keyboard_o': '', // ICON_KEYBOARD
  'nf-fa-language': '', // ICON_LANGUAGE
  'nf-fa-laptop': '', // ICON_LAPTOP
  'nf-fa-layer_group': '', // ICON_LAYER_GROUP
  'nf-fa-leaf': '', // ICON_LEAF
  'nf-fa-legal': '', // ICON_LEGAL
  'nf-fa-level_down': '', // ICON_LEVEL_DOWN
  'nf-fa-level_up': '', // ICON_LEVEL_UP
  'nf-fa-life_ring': '', // ICON_LIFE_RING
  'nf-fa-lightbulb': '', // ICON_LIGHTBULB_FA
  'nf-fa-lightbulb_o': '', // ICON_LIGHTBULB, ICON_LIGHTBULB_OUTLINE
  'nf-fa-line': '', // ICON_LINE
  'nf-fa-line_chart': '', // ICON_GRAPH
  'nf-fa-link': '', // ICON_LINK
  'nf-fa-linux': '', // ICON_LINUX
  'nf-fa-list': '', // ICON_LIST
  'nf-fa-list_alt': '', // ICON_LIST_ALT
  'nf-fa-list_ol': '', // ICON_LIST_OL
  'nf-fa-list_ul': '', // ICON_LIST_UL
  'nf-fa-location_arrow': '', // ICON_LOCATION_ARROW
  'nf-fa-lock': '', // ICON_LOCK
  'nf-fa-long_arrow_right': '', // ICON_LONG_ARROW_RIGHT
  'nf-fa-low_vision': '', // ICON_LOW_VISION
  'nf-fa-magic': '', // ICON_MAGIC
  'nf-fa-magnet': '', // ICON_MAGNET
  'nf-fa-male': '', // ICON_MALE
  'nf-fa-map': '', // ICON_MAP
  'nf-fa-map_marker': '', // ICON_MAP_MARKER
  'nf-fa-map_o': '', // ICON_MAP_O
  'nf-fa-map_signs': '', // ICON_MAP_SIGNS
  'nf-fa-medkit': '', // ICON_MEDKIT
  'nf-fa-memory': '', // ICON_MEMORY
  'nf-fa-microchip': '', // ICON_MICROCHIP
  'nf-fa-microphone': '', // ICON_MICROPHONE
  'nf-fa-microsoft': '', // ICON_MICROSOFT
  'nf-fa-minus': '', // ICON_MINUS
  'nf-fa-minus_circle': '', // ICON_MINUS_CIRCLE
  'nf-fa-mobile': '', // ICON_MOBILE
  'nf-fa-money': '', // ICON_MONEY
  'nf-fa-moon': '', // ICON_MOON_FA
  'nf-fa-moon_o': '', // ICON_HIBERNATE, ICON_MOON_OUTLINE
  'nf-fa-mountain': '', // ICON_MOUNTAIN
  'nf-fa-mouse_pointer': '', // ICON_MOUSE_POINTER
  'nf-fa-music': '', // ICON_MUSIC
  'nf-fa-network_wired': '', // ICON_NETWORK_WIRED
  'nf-fa-newspaper': '', // ICON_NEWSPAPER_FA
  'nf-fa-newspaper_o': '', // ICON_NEWSPAPER
  'nf-fa-object_group': '', // ICON_OBJECT_GROUP
  'nf-fa-opera': '', // ICON_OPERA
  'nf-fa-pagelines': '', // ICON_PAGELINES
  'nf-fa-paint_brush': '', // ICON_PAINT_BRUSH
  'nf-fa-palette': '', // ICON_PALETTE
  'nf-fa-paper_plane': '', // ICON_PAPER_PLANE
  'nf-fa-paragraph': '', // ICON_PARAGRAPH
  'nf-fa-paste': '', // ICON_PASTE
  'nf-fa-pause': '', // ICON_PAUSE
  'nf-fa-pause_circle': '', // ICON_SUSPEND, ICON_PAUSE_CIRCLE_ALT
  'nf-fa-paw': '', // ICON_PAW
  'nf-fa-pencil': '', // ICON_WRITE
  'nf-fa-pencil_square': '', // ICON_PENCIL_SQUARE_FA
  'nf-fa-pencil_square_o': '', // ICON_PENCIL_SQUARE
  'nf-fa-percent': '', // ICON_PERCENT
  'nf-fa-phone': '', // ICON_PHONE
  'nf-fa-picture_o': '', // ICON_PICTURE
  'nf-fa-pie_chart': '', // ICON_PIE_CHART
  'nf-fa-plane': '', // ICON_PLANE
  'nf-fa-play': '', // ICON_PLAY
  'nf-fa-play_circle': '', // ICON_RUN, ICON_PLAY_CIRCLE_ALT
  'nf-fa-plug': '', // ICON_PLUG
  'nf-fa-plus': '', // ICON_PLUS
  'nf-fa-plus_circle': '', // ICON_PLUS_CIRCLE
  'nf-fa-plus_square': '', // ICON_PLUS_SQUARE
  'nf-fa-power_off': '', // ICON_SHUTDOWN, ICON_POWER_OFF_ALT
  'nf-fa-print': '', // ICON_PRINT
  'nf-fa-puzzle_piece': '', // ICON_PUZZLE_PIECE
  'nf-fa-question': '', // ICON_QUESTION_FA
  'nf-fa-question_circle': '', // ICON_QUESTION, ICON_QUESTION_CIRCLE_ALT
  'nf-fa-quote_left': '', // ICON_QUOTE_LEFT
  'nf-fa-quote_right': '', // ICON_QUOTE_RIGHT
  'nf-fa-random': '', // ICON_RANDOM
  'nf-fa-recycle': '', // ICON_RECYCLE
  'nf-fa-refresh': '', // ICON_REFRESH
  'nf-fa-remove': '', // ICON_TIMES
  'nf-fa-repeat': '', // ICON_REDO
  'nf-fa-reply': '', // ICON_REPLY
  'nf-fa-retweet': '', // ICON_RETWEET
  'nf-fa-ring': '', // ICON_RING
  'nf-fa-road': '', // ICON_ROAD
  'nf-fa-robot': '', // ICON_ROBOT
  'nf-fa-rocket': '', // ICON_ROCKET
  'nf-fa-rotate_left': '', // ICON_RESTART, ICON_ROTATE_LEFT_ALT
  'nf-fa-rotate_right': '', // ICON_REBOOT, ICON_ROTATE_RIGHT_ALT
  'nf-fa-route': '', // ICON_ROUTE
  'nf-fa-rss': '', // ICON_RSS
  'nf-fa-save': '', // ICON_SAVE
  'nf-fa-scissors': '', // ICON_SCISSORS
  'nf-fa-search': '', // ICON_SEARCH
  'nf-fa-search_plus': '', // ICON_SEARCH_PLUS
  'nf-fa-send': '', // ICON_SEND
  'nf-fa-server': '', // ICON_SERVER
  'nf-fa-share': '', // ICON_SHARE
  'nf-fa-share_alt': '', // ICON_SHARE_ALT
  'nf-fa-shield': '', // ICON_SHIELD
  'nf-fa-ship': '', // ICON_SHIP
  'nf-fa-shopping_bag': '', // ICON_SHOPPING_BAG
  'nf-fa-shopping_cart': '', // ICON_SHOPPING_CART
  'nf-fa-shower': '', // ICON_SHOWER
  'nf-fa-sign_in': '', // ICON_SIGN_IN
  'nf-fa-sign_out': '', // ICON_SIGN_OUT
  'nf-fa-signal': '', // ICON_SIGNAL
  'nf-fa-sitemap': '', // ICON_NETWORK
  'nf-fa-skull': '', // ICON_SKULL_FA
  'nf-fa-sliders': '', // ICON_SLIDERS
  'nf-fa-smile_o': '', // ICON_SMILE_O
  'nf-fa-snowflake': '', // ICON_SNOWFLAKE
  'nf-fa-snowflake_o': '', // ICON_SNOWFLAKE_O
  'nf-fa-sort': '', // ICON_SORT
  'nf-fa-sort_amount_asc': '', // ICON_SORT_AMOUNT_ASC
  'nf-fa-space_shuttle': '', // ICON_SPACE_SHUTTLE
  'nf-fa-spinner': '', // ICON_SPINNER
  'nf-fa-square': '', // ICON_SQUARE
  'nf-fa-square_o': '', // ICON_SQUARE_O
  'nf-fa-star': '', // ICON_STAR
  'nf-fa-star_half_o': '', // ICON_STAR_HALF_O
  'nf-fa-star_o': '', // ICON_STAR_O
  'nf-fa-stethoscope': '', // ICON_STETHOSCOPE
  'nf-fa-sticky_note': '', // ICON_STICKY_NOTE
  'nf-fa-stop': '', // ICON_STOP
  'nf-fa-stop_circle': '', // ICON_STOP_CIRCLE
  'nf-fa-street_view': '', // ICON_STREET_VIEW
  'nf-fa-suitcase': '', // ICON_SUITCASE
  'nf-fa-sun': '', // ICON_SUN_FA
  'nf-fa-sun_o': '', // ICON_SUN_O
  'nf-fa-table': '', // ICON_TABLE
  'nf-fa-tachometer': '', // ICON_TACHOMETER
  'nf-fa-tag': '', // ICON_TAG
  'nf-fa-tags': '', // ICON_TAGS
  'nf-fa-tasks': '', // ICON_TASKS
  'nf-fa-television': '', // ICON_TELEVISION
  'nf-fa-terminal': '', // ICON_TERMINAL_FA
  'nf-fa-text_width': '', // ICON_TEXT_WIDTH
  'nf-fa-th': '', // ICON_TH
  'nf-fa-th_large': '', // ICON_TH_LARGE
  'nf-fa-th_list': '', // ICON_TH_LIST
  'nf-fa-thermometer': '', // ICON_THERMOMETER_FA
  'nf-fa-thermometer_1': '', // ICON_THERMOMETER_1
  'nf-fa-thermometer_2': '', // ICON_THERMOMETER_2
  'nf-fa-thermometer_3': '', // ICON_THERMOMETER_3
  'nf-fa-thermometer_4': '', // ICON_THERMOMETER_4
  'nf-fa-thermometer_half': '', // ICON_THERMOMETER_HALF
  'nf-fa-thumb_tack': '', // ICON_PIN
  'nf-fa-thumbs_down': '', // ICON_THUMBS_DOWN
  'nf-fa-thumbs_up': '', // ICON_THUMBS_UP
  'nf-fa-ticket': '', // ICON_TICKET
  'nf-fa-times': '', // ICON_CLOSE
  'nf-fa-times_circle': '', // ICON_ERROR, ICON_TIMES_CIRCLE_ALT
  'nf-fa-tint': '', // ICON_TINT
  'nf-fa-toggle_on': '', // ICON_TOGGLE_ON
  'nf-fa-transgender': '', // ICON_TRANSGENDER
  'nf-fa-trash': '', // ICON_DELETE
  'nf-fa-trash_o': '', // ICON_TRASH
  'nf-fa-tree': '', // ICON_TREE
  'nf-fa-trophy': '', // ICON_TROPHY
  'nf-fa-truck': '', // ICON_TRUCK
  'nf-fa-tv': '', // ICON_TV
  'nf-fa-twitter': '', // ICON_TWITTER
  'nf-fa-umbrella': '', // ICON_UMBRELLA
  'nf-fa-undo': '', // ICON_UNDO
  'nf-fa-university': '', // ICON_UNIVERSITY
  'nf-fa-unlink': '', // ICON_UNLINK
  'nf-fa-unlock': '', // ICON_UNLOCK
  'nf-fa-unlock_alt': '', // ICON_UNLOCK_ALT
  'nf-fa-upload': '', // ICON_UPLOAD
  'nf-fa-user': '', // ICON_USER
  'nf-fa-user_circle': '', // ICON_USER_CIRCLE
  'nf-fa-user_o': '', // ICON_USER_O
  'nf-fa-user_plus': '', // ICON_USER_PLUS
  'nf-fa-user_secret': '', // ICON_USER_SECRET
  'nf-fa-user_times': '', // ICON_USER_TIMES
  'nf-fa-users': '', // ICON_USERS
  'nf-fa-venus_mars': '', // ICON_VENUS_MARS
  'nf-fa-video_camera': '', // ICON_VIDEO_CAMERA
  'nf-fa-volume_up': '', // ICON_VOLUME_UP
  'nf-fa-warning': '', // ICON_WARNING_FA
  'nf-fa-wheelchair': '', // ICON_WHEELCHAIR
  'nf-fa-wifi': '', // ICON_WIFI
  'nf-fa-wikipedia_w': '', // ICON_WIKIPEDIA
  'nf-fa-window_close': '', // ICON_WINDOW_CLOSE, ICON_WINDOW_CLOSE_ALT
  'nf-fa-window_maximize': '', // ICON_WINDOW_MAXIMIZE
  'nf-fa-window_minimize': '', // ICON_WINDOW_MINIMIZE
  'nf-fa-window_restore': '', // ICON_WINDOW_RESTORE
  'nf-fa-wrench': '', // ICON_WRENCH
  'nf-fa-yarn': '', // ICON_YARN
  'nf-md-alert': '󰀦', // ICON_MD_ALERT
  'nf-md-alert_circle': '󰀨', // ICON_MD_ALERT_CIRCLE
  'nf-md-alert_circle_outline': '󰗖', // ICON_MD_ALERT_CIRCLE_OUTLINE
  'nf-md-alert_outline': '󰀪', // ICON_MD_ALERT_OUTLINE
  'nf-md-antenna': '󱄙', // ICON_MD_ANTENNA
  'nf-md-anvil': '󰢛', // ICON_MD_ANVIL
  'nf-md-arrow_all': '󰁁', // ICON_MD_ARROW_ALL
  'nf-md-arrow_bottom_left': '󰁂', // ICON_MD_ARROW_BOTTOM_LEFT
  'nf-md-arrow_collapse_all': '󰁄', // ICON_MD_ARROW_COLLAPSE_ALL
  'nf-md-arrow_collapse_left': '󰞓', // ICON_COLLAPSE_LEFT
  'nf-md-arrow_collapse_right': '󰞔', // ICON_COLLAPSE_RIGHT
  'nf-md-arrow_down': '󰁅', // ICON_MD_ARROW_DOWN
  'nf-md-arrow_expand_all': '󰁌', // ICON_MD_ARROW_EXPAND_ALL
  'nf-md-arrow_expand_left': '󰞗', // ICON_EXPAND_LEFT
  'nf-md-arrow_expand_right': '󰞘', // ICON_EXPAND_RIGHT
  'nf-md-arrow_left': '󰁍', // ICON_MD_ARROW_LEFT
  'nf-md-arrow_right': '󰁔', // ICON_MD_ARROW_RIGHT
  'nf-md-arrow_top_right': '󰁜', // ICON_MD_ARROW_TOP_RIGHT
  'nf-md-arrow_up': '󰁝', // ICON_MD_ARROW_UP
  'nf-md-atom': '󰝨', // ICON_MD_ATOM
  'nf-md-atom_variant': '󰹻', // ICON_MD_ATOM_VARIANT
  'nf-md-axe': '󰣈', // ICON_MD_AXE
  'nf-md-axe_battle': '󱡂', // ICON_MD_AXE_BATTLE
  'nf-md-axis': '󰵈', // ICON_MD_AXIS
  'nf-md-axis_arrow': '󰵉', // ICON_MD_AXIS_ARROW
  'nf-md-axis_arrow_info': '󱐎', // ICON_MD_AXIS_ARROW_INFO
  'nf-md-bacteria': '󰻕', // ICON_MD_BACTERIA
  'nf-md-bacteria_outline': '󰻖', // ICON_MD_BACTERIA_OUTLINE
  'nf-md-barn': '󰭞', // ICON_MD_BARN
  'nf-md-barrel': '󰁴', // ICON_MD_BARREL
  'nf-md-barrel_outline': '󱨨', // ICON_MD_BARREL_OUTLINE
  'nf-md-battery': '󰁹', // ICON_MD_BATTERY
  'nf-md-battery_outline': '󰂎', // ICON_MD_BATTERY_OUTLINE
  'nf-md-beaker': '󰳪', // ICON_MD_BEAKER
  'nf-md-beaker_outline': '󰚐', // ICON_MD_BEAKER_OUTLINE
  'nf-md-bee': '󰾡', // ICON_MD_BEE
  'nf-md-binoculars': '󰂥', // ICON_MD_BINOCULARS
  'nf-md-bird': '󱗆', // ICON_MD_BIRD
  'nf-md-bluetooth': '󰂯', // ICON_MD_BLUETOOTH
  'nf-md-blur': '󰂵', // ICON_MD_BLUR
  'nf-md-bow_arrow': '󱡁', // ICON_MD_BOW_ARROW
  'nf-md-bridge': '󰘘', // ICON_MD_BRIDGE
  'nf-md-brightness_5': '󰃞', // ICON_MD_BRIGHTNESS_5
  'nf-md-brightness_6': '󰃟', // ICON_BRIGHTNESS, ICON_MD_BRIGHTNESS_6
  'nf-md-brightness_7': '󰃠', // ICON_MD_BRIGHTNESS_7
  'nf-md-bucket': '󱐕', // ICON_MD_BUCKET
  'nf-md-bucket_outline': '󱐖', // ICON_MD_BUCKET_OUTLINE
  'nf-md-bug': '󰃤', // ICON_MD_BUG
  'nf-md-bug_outline': '󰨰', // ICON_MD_BUG_OUTLINE
  'nf-md-butterfly': '󱖉', // ICON_MD_BUTTERFLY
  'nf-md-cactus': '󰶵', // ICON_MD_CACTUS
  'nf-md-calendar': '󰃭', // ICON_MD_CALENDAR
  'nf-md-calendar_clock': '󰃰', // ICON_MD_CALENDAR_CLOCK
  'nf-md-calendar_month': '󰸗', // ICON_MD_CALENDAR_MONTH
  'nf-md-calendar_today': '󰃶', // ICON_MD_CALENDAR_TODAY
  'nf-md-calendar_week': '󰨳', // ICON_MD_CALENDAR_WEEK
  'nf-md-camera': '󰄀', // ICON_MD_CAMERA
  'nf-md-camera_outline': '󰵝', // ICON_MD_CAMERA_OUTLINE
  'nf-md-campfire': '󰻝', // ICON_MD_CAMPFIRE
  'nf-md-candle': '󰗢', // ICON_MD_CANDLE
  'nf-md-castle': '󰄚', // ICON_MD_CASTLE
  'nf-md-cat': '󰄛', // ICON_MD_CAT
  'nf-md-chart_arc': '󰄦', // ICON_MD_CHART_ARC
  'nf-md-chart_areaspline': '󰄧', // ICON_MD_CHART_AREASPLINE
  'nf-md-chart_bar': '󰄨', // ICON_CHART_BAR
  'nf-md-chart_bell_curve': '󰱐', // ICON_MD_CHART_BELL_CURVE
  'nf-md-chart_bubble': '󰗣', // ICON_MD_CHART_BUBBLE
  'nf-md-chart_donut': '󰞯', // ICON_MD_CHART_DONUT
  'nf-md-chart_gantt': '󰙬', // ICON_MD_CHART_GANTT
  'nf-md-chart_histogram': '󰄩', // ICON_MD_CHART_HISTOGRAM
  'nf-md-chart_line': '󰄪', // ICON_MD_CHART_LINE
  'nf-md-chart_pie': '󰄫', // ICON_MD_CHART_PIE
  'nf-md-chart_scatter_plot': '󰺒', // ICON_MD_CHART_SCATTER_PLOT
  'nf-md-chart_timeline': '󰙮', // ICON_MD_CHART_TIMELINE
  'nf-md-chart_tree': '󰺔', // ICON_MD_CHART_TREE
  'nf-md-check': '󰄬', // ICON_MD_CHECK
  'nf-md-check_circle': '󰗠', // ICON_MD_CHECK_CIRCLE
  'nf-md-check_circle_outline': '󰗡', // ICON_MD_CHECK_CIRCLE_OUTLINE
  'nf-md-checkbox_blank_outline': '󰄱', // ICON_CHECKBOX_BLANK_OUTLINE
  'nf-md-chevron_left': '󰅁', // ICON_CHEVRON_LEFT_MD
  'nf-md-chevron_right': '󰅂', // ICON_CHEVRON_RIGHT_MD
  'nf-md-chip': '󰘚', // ICON_CHIP, ICON_MD_CHIP
  'nf-md-circle_double': '󰺕', // ICON_MD_CIRCLE_DOUBLE
  'nf-md-clock': '󰥔', // ICON_MD_CLOCK
  'nf-md-clock_fast': '󰅒', // ICON_MD_CLOCK_FAST
  'nf-md-clock_outline': '󰅐', // ICON_CLOCK_O, ICON_PHASE, ICON_MD_CLOCK_OUTLINE
  'nf-md-close': '󰅖', // ICON_CLOSE_MD, ICON_MD_CLOSE
  'nf-md-close_circle': '󰅙', // ICON_MD_CLOSE_CIRCLE
  'nf-md-close_circle_outline': '󰅚', // ICON_MD_CLOSE_CIRCLE_OUTLINE
  'nf-md-cog': '󰒓', // ICON_MANAGER, ICON_MD_COG
  'nf-md-cog_outline': '󰢻', // ICON_MD_COG_OUTLINE
  'nf-md-cogs': '󰣖', // ICON_MD_COGS
  'nf-md-compass': '󰆋', // ICON_MD_COMPASS
  'nf-md-compass_outline': '󰆌', // ICON_MD_COMPASS_OUTLINE
  'nf-md-cone': '󱥌', // ICON_MD_CONE
  'nf-md-connection': '󱘖', // ICON_CONNECTION, ICON_MD_CONNECTION
  'nf-md-console': '󰆍', // ICON_MD_CONSOLE
  'nf-md-console_line': '󰞷', // ICON_MD_CONSOLE_LINE
  'nf-md-contrast': '󰆕', // ICON_MD_CONTRAST
  'nf-md-contrast_circle': '󰆗', // ICON_MD_CONTRAST_CIRCLE
  'nf-md-controller_classic': '󰮂', // ICON_MD_CONTROLLER_CLASSIC
  'nf-md-cosine_wave': '󱑹', // ICON_MD_COSINE_WAVE
  'nf-md-cow': '󰆚', // ICON_MD_COW
  'nf-md-cpu_32_bit': '󰻟', // ICON_MD_CPU_32_BIT
  'nf-md-cpu_64_bit': '󰻠', // ICON_MD_CPU_64_BIT
  'nf-md-creation': '󰙴', // ICON_MD_CREATION
  'nf-md-crosshairs': '󰆣', // ICON_MD_CROSSHAIRS
  'nf-md-crosshairs_gps': '󰆤', // ICON_MD_CROSSHAIRS_GPS
  'nf-md-crown': '󰆥', // ICON_MD_CROWN
  'nf-md-crown_outline': '󱇐', // ICON_MD_CROWN_OUTLINE
  'nf-md-cube': '󰆦', // ICON_MD_CUBE
  'nf-md-cube_outline': '󰆧', // ICON_CUBE, ICON_MD_CUBE_OUTLINE
  'nf-md-cube_scan': '󰮄', // ICON_MD_CUBE_SCAN
  'nf-md-cylinder': '󱥎', // ICON_MD_CYLINDER
  'nf-md-database': '󰆼', // ICON_MD_DATABASE
  'nf-md-database_outline': '󱘲', // ICON_MD_DATABASE_OUTLINE
  'nf-md-desktop_classic': '󰟀', // ICON_DESKTOP
  'nf-md-diamond': '󰮊', // ICON_MD_DIAMOND
  'nf-md-diamond_outline': '󰮋', // ICON_MD_DIAMOND_OUTLINE
  'nf-md-dice_1': '󰇊', // ICON_MD_DICE_1
  'nf-md-dice_2': '󰇋', // ICON_MD_DICE_2
  'nf-md-dice_3': '󰇌', // ICON_MD_DICE_3
  'nf-md-dice_4': '󰇍', // ICON_MD_DICE_4
  'nf-md-dice_5': '󰇎', // ICON_MD_DICE_5
  'nf-md-dice_6': '󰇏', // ICON_MD_DICE_6
  'nf-md-dna': '󰚄', // ICON_MD_DNA
  'nf-md-dog': '󰩃', // ICON_MD_DOG
  'nf-md-door': '󰠚', // ICON_MD_DOOR
  'nf-md-door_open': '󰠜', // ICON_MD_DOOR_OPEN
  'nf-md-duck': '󰇥', // ICON_MD_DUCK
  'nf-md-earth': '󰇧', // ICON_MD_EARTH
  'nf-md-elephant': '󰟆', // ICON_MD_ELEPHANT
  'nf-md-ethernet': '󰈀', // ICON_ETHERNET, ICON_MD_ETHERNET
  'nf-md-eye': '󰈈', // ICON_MD_EYE
  'nf-md-eye_off': '󰈉', // ICON_MD_EYE_OFF
  'nf-md-eye_off_outline': '󰛑', // ICON_MD_EYE_OFF_OUTLINE
  'nf-md-eye_outline': '󰛐', // ICON_MD_EYE_OUTLINE
  'nf-md-factory': '󰈏', // ICON_MD_FACTORY
  'nf-md-family_tree': '󱘎', // ICON_MD_FAMILY_TREE
  'nf-md-fence': '󱞚', // ICON_MD_FENCE
  'nf-md-file_tree': '󰙅', // ICON_MD_FILE_TREE
  'nf-md-file_tree_outline': '󱏒', // ICON_MD_FILE_TREE_OUTLINE
  'nf-md-fingerprint': '󰈷', // ICON_FINGERPRINT
  'nf-md-fire': '󰈸', // ICON_MD_FIRE
  'nf-md-fire_circle': '󱠇', // ICON_MD_FIRE_CIRCLE
  'nf-md-fish': '󰈺', // ICON_MD_FISH
  'nf-md-fishbowl': '󰻳', // ICON_MD_FISHBOWL
  'nf-md-fishbowl_outline': '󰻴', // ICON_MD_FISHBOWL_OUTLINE
  'nf-md-flash': '󰉁', // ICON_MD_FLASH
  'nf-md-flash_outline': '󰛕', // ICON_MD_FLASH_OUTLINE
  'nf-md-flask': '󰂓', // ICON_MD_FLASK
  'nf-md-flask_empty_outline': '󰂕', // ICON_MD_FLASK_EMPTY_OUTLINE
  'nf-md-flask_outline': '󰂖', // ICON_FLASK_OUTLINE, ICON_MD_FLASK_OUTLINE
  'nf-md-flower': '󰉊', // ICON_MD_FLOWER
  'nf-md-flower_outline': '󰧰', // ICON_MD_FLOWER_OUTLINE
  'nf-md-food_apple': '󰉛', // ICON_MD_FOOD_APPLE
  'nf-md-food_drumstick': '󱐟', // ICON_MD_FOOD_DRUMSTICK
  'nf-md-forest': '󱢗', // ICON_MD_FOREST
  'nf-md-format_color_fill': '󰉦', // ICON_MD_FORMAT_COLOR_FILL
  'nf-md-function': '󰊕', // ICON_MD_FUNCTION
  'nf-md-function_variant': '󰡱', // ICON_MD_FUNCTION_VARIANT
  'nf-md-gamepad': '󰊖', // ICON_MD_GAMEPAD
  'nf-md-gamepad_variant': '󰊗', // ICON_MD_GAMEPAD_VARIANT
  'nf-md-gate': '󰊙', // ICON_MD_GATE
  'nf-md-gate_open': '󱅪', // ICON_MD_GATE_OPEN
  'nf-md-gauge': '󰊚', // ICON_MD_GAUGE
  'nf-md-gauge_empty': '󰡳', // ICON_MD_GAUGE_EMPTY
  'nf-md-gauge_full': '󰡴', // ICON_MD_GAUGE_FULL
  'nf-md-gauge_low': '󰡵', // ICON_MD_GAUGE_LOW
  'nf-md-globe_model': '󰣩', // ICON_MD_GLOBE_MODEL
  'nf-md-graph': '󱁉', // ICON_MD_GRAPH
  'nf-md-graph_outline': '󱁊', // ICON_MD_GRAPH_OUTLINE
  'nf-md-grass': '󱔐', // ICON_MD_GRASS
  'nf-md-greenhouse': '󰀭', // ICON_MD_GREENHOUSE
  'nf-md-grid': '󰋁', // ICON_GRID, ICON_MD_GRID
  'nf-md-grid_large': '󰝘', // ICON_GRID_LARGE, ICON_MD_GRID_LARGE
  'nf-md-grid_off': '󰋂', // ICON_MD_GRID_OFF
  'nf-md-group': '󰋃', // ICON_MD_GROUP
  'nf-md-hammer': '󰣪', // ICON_MD_HAMMER
  'nf-md-heart': '󰋑', // ICON_MD_HEART
  'nf-md-heart_outline': '󰋕', // ICON_MD_HEART_OUTLINE
  'nf-md-heart_pulse': '󰗶', // ICON_MD_HEART_PULSE
  'nf-md-help_circle': '󰋗', // ICON_MD_HELP_CIRCLE
  'nf-md-help_circle_outline': '󰘥', // ICON_MD_HELP_CIRCLE_OUTLINE
  'nf-md-hexagon': '󰋘', // ICON_MD_HEXAGON
  'nf-md-hexagon_multiple': '󰛡', // ICON_MD_HEXAGON_MULTIPLE
  'nf-md-hexagon_outline': '󰋙', // ICON_MD_HEXAGON_OUTLINE
  'nf-md-history': '󰋚', // ICON_MD_HISTORY
  'nf-md-home': '󰋜', // ICON_MD_HOME
  'nf-md-home_outline': '󰚡', // ICON_MD_HOME_OUTLINE
  'nf-md-horse': '󱖿', // ICON_MD_HORSE
  'nf-md-image': '󰋩', // ICON_MD_IMAGE
  'nf-md-image_filter_hdr': '󰋵', // ICON_TERRAIN, ICON_TERRAIN_MOUNTAIN, ICON_MD_IMAGE_FILTER_HDR
  'nf-md-image_outline': '󰥶', // ICON_MD_IMAGE_OUTLINE
  'nf-md-infinity': '󰛤', // ICON_MD_INFINITY
  'nf-md-information': '󰋼', // ICON_MD_INFORMATION
  'nf-md-information_outline': '󰋽', // ICON_MD_INFORMATION_OUTLINE
  'nf-md-island': '󱁏', // ICON_MD_ISLAND
  'nf-md-kubernetes': '󱃾', // ICON_KUBERNETES
  'nf-md-label': '󰌕', // ICON_MD_LABEL
  'nf-md-label_outline': '󰌖', // ICON_MD_LABEL_OUTLINE
  'nf-md-lan_connect': '󰌘', // ICON_LAN_CONNECT, ICON_MD_LAN_CONNECT
  'nf-md-lan_disconnect': '󰌙', // ICON_LAN_DISCONNECT, ICON_MD_LAN_DISCONNECT
  'nf-md-layers': '󰌨', // ICON_MD_LAYERS
  'nf-md-layers_outline': '󰧾', // ICON_MD_LAYERS_OUTLINE
  'nf-md-leaf': '󰌪', // ICON_MD_LEAF
  'nf-md-leaf_maple': '󰲓', // ICON_MD_LEAF_MAPLE
  'nf-md-lightbulb': '󰌵', // ICON_LIGHTBULB_MD
  'nf-md-lightbulb_outline': '󰌶', // ICON_TIP
  'nf-md-lighthouse': '󰧿', // ICON_MD_LIGHTHOUSE
  'nf-md-lightning_bolt': '󱐋', // ICON_MD_LIGHTNING_BOLT
  'nf-md-lightning_bolt_outline': '󱐌', // ICON_MD_LIGHTNING_BOLT_OUTLINE
  'nf-md-magnet': '󰍇', // ICON_MD_MAGNET
  'nf-md-magnet_on': '󰍈', // ICON_MD_MAGNET_ON
  'nf-md-map': '󰍍', // ICON_MD_MAP
  'nf-md-map_legend': '󰨁', // ICON_MD_MAP_LEGEND
  'nf-md-map_marker': '󰍎', // ICON_MD_MAP_MARKER
  'nf-md-map_marker_outline': '󰟙', // ICON_MD_MAP_MARKER_OUTLINE
  'nf-md-map_outline': '󰦂', // ICON_MD_MAP_OUTLINE
  'nf-md-math_compass': '󰍘', // ICON_MD_MATH_COMPASS
  'nf-md-math_integral': '󰿈', // ICON_MD_MATH_INTEGRAL
  'nf-md-math_log': '󱂅', // ICON_MD_MATH_LOG
  'nf-md-math_norm': '󰿊', // ICON_MD_MATH_NORM
  'nf-md-memory': '󰍛', // ICON_RAM, ICON_MD_MEMORY
  'nf-md-menu': '󰍜', // ICON_MENU_MD
  'nf-md-microscope': '󰙔', // ICON_MD_MICROSCOPE
  'nf-md-microsoft_edge': '󰇩', // ICON_EDGE
  'nf-md-molecule': '󰮬', // ICON_MD_MOLECULE
  'nf-md-molecule_co': '󱋾', // ICON_MD_MOLECULE_CO
  'nf-md-molecule_co2': '󰟤', // ICON_MD_MOLECULE_CO2
  'nf-md-moon_first_quarter': '󰽡', // ICON_MD_MOON_FIRST_QUARTER
  'nf-md-moon_full': '󰽢', // ICON_MD_MOON_FULL
  'nf-md-moon_last_quarter': '󰽣', // ICON_MD_MOON_LAST_QUARTER
  'nf-md-moon_new': '󰽤', // ICON_MD_MOON_NEW
  'nf-md-moon_waning_crescent': '󰽥', // ICON_MOON, ICON_MD_MOON_WANING_CRESCENT
  'nf-md-moon_waning_gibbous': '󰽦', // ICON_MD_MOON_WANING_GIBBOUS
  'nf-md-moon_waxing_crescent': '󰽧', // ICON_MD_MOON_WAXING_CRESCENT
  'nf-md-moon_waxing_gibbous': '󰽨', // ICON_MD_MOON_WAXING_GIBBOUS
  'nf-md-mushroom': '󰟟', // ICON_MD_MUSHROOM
  'nf-md-mushroom_outline': '󰟠', // ICON_MD_MUSHROOM_OUTLINE
  'nf-md-music_note': '󰎇', // ICON_MD_MUSIC_NOTE
  'nf-md-navigation': '󰎐', // ICON_MD_NAVIGATION
  'nf-md-numeric': '󰎠', // ICON_MD_NUMERIC
  'nf-md-numeric_0_box': '󰎡', // ICON_MD_NUMERIC_0_BOX
  'nf-md-numeric_1': '󰬺', // ICON_MD_NUMERIC_1
  'nf-md-numeric_1_box': '󰎤', // ICON_NUMERIC_1_BOX
  'nf-md-numeric_10_box': '󰽽', // ICON_NUMERIC_10_BOX
  'nf-md-numeric_2': '󰬻', // ICON_MD_NUMERIC_2
  'nf-md-numeric_2_box': '󰎧', // ICON_MD_NUMERIC_2_BOX
  'nf-md-numeric_3': '󰬼', // ICON_MD_NUMERIC_3
  'nf-md-numeric_3_box': '󰎪', // ICON_MD_NUMERIC_3_BOX
  'nf-md-numeric_4': '󰬽', // ICON_MD_NUMERIC_4
  'nf-md-numeric_4_box': '󰎭', // ICON_MD_NUMERIC_4_BOX
  'nf-md-numeric_5': '󰬾', // ICON_MD_NUMERIC_5
  'nf-md-numeric_5_box': '󰎱', // ICON_NUMERIC_5_BOX
  'nf-md-numeric_6': '󰬿', // ICON_MD_NUMERIC_6
  'nf-md-numeric_6_box': '󰎳', // ICON_MD_NUMERIC_6_BOX
  'nf-md-numeric_7': '󰭀', // ICON_MD_NUMERIC_7
  'nf-md-numeric_7_box': '󰎶', // ICON_MD_NUMERIC_7_BOX
  'nf-md-numeric_8': '󰭁', // ICON_MD_NUMERIC_8
  'nf-md-numeric_8_box': '󰎹', // ICON_MD_NUMERIC_8_BOX
  'nf-md-numeric_9': '󰭂', // ICON_MD_NUMERIC_9
  'nf-md-numeric_9_box': '󰎼', // ICON_MD_NUMERIC_9_BOX
  'nf-md-octagon': '󰏃', // ICON_MD_OCTAGON
  'nf-md-octagon_outline': '󰏄', // ICON_MD_OCTAGON_OUTLINE
  'nf-md-office_building': '󰦑', // ICON_MD_OFFICE_BUILDING
  'nf-md-opacity': '󰗌', // ICON_MD_OPACITY
  'nf-md-orbit': '󰀘', // ICON_MD_ORBIT
  'nf-md-orbit_variant': '󱗛', // ICON_MD_ORBIT_VARIANT
  'nf-md-owl': '󰏒', // ICON_MD_OWL
  'nf-md-package': '󰏓', // ICON_MD_PACKAGE
  'nf-md-package_variant': '󰏖', // ICON_MD_PACKAGE_VARIANT
  'nf-md-package_variant_closed': '󰏗', // ICON_MD_PACKAGE_VARIANT_CLOSED
  'nf-md-palette': '󰏘', // ICON_ATMOSPHERE, ICON_MD_PALETTE
  'nf-md-palette_outline': '󰸌', // ICON_MD_PALETTE_OUTLINE
  'nf-md-pause': '󰏤', // ICON_MD_PAUSE
  'nf-md-paw': '󰏩', // ICON_MD_PAW
  'nf-md-paw_outline': '󱙵', // ICON_MD_PAW_OUTLINE
  'nf-md-penguin': '󰻀', // ICON_MD_PENGUIN
  'nf-md-pentagon': '󰜁', // ICON_MD_PENTAGON
  'nf-md-pentagon_outline': '󰜀', // ICON_MD_PENTAGON_OUTLINE
  'nf-md-pi': '󰏿', // ICON_MD_PI
  'nf-md-pickaxe': '󰢷', // ICON_MD_PICKAXE
  'nf-md-pig': '󰐁', // ICON_MD_PIG
  'nf-md-pin': '󰐃', // ICON_PIN_MD
  'nf-md-pin_off': '󰐄', // ICON_PIN_OFF_MD
  'nf-md-pine_tree': '󰐅', // ICON_MD_PINE_TREE
  'nf-md-play': '󰐊', // ICON_MD_PLAY
  'nf-md-pliers': '󱦤', // ICON_MD_PLIERS
  'nf-md-power': '󰐥', // ICON_POWER, ICON_MD_POWER
  'nf-md-power_plug': '󰚥', // ICON_MD_POWER_PLUG
  'nf-md-power_plug_outline': '󱐥', // ICON_MD_POWER_PLUG_OUTLINE
  'nf-md-progress_alert': '󰲼', // ICON_MD_PROGRESS_ALERT
  'nf-md-progress_check': '󰦕', // ICON_MD_PROGRESS_CHECK
  'nf-md-progress_clock': '󰦖', // ICON_MD_PROGRESS_CLOCK
  'nf-md-puzzle': '󰐱', // ICON_MD_PUZZLE
  'nf-md-puzzle_outline': '󰩦', // ICON_MD_PUZZLE_OUTLINE
  'nf-md-pyramid': '󱥒', // ICON_MD_PYRAMID
  'nf-md-rabbit': '󰤇', // ICON_MD_RABBIT
  'nf-md-radioactive': '󰐼', // ICON_MD_RADIOACTIVE
  'nf-md-radioactive_circle': '󱡝', // ICON_MD_RADIOACTIVE_CIRCLE
  'nf-md-radioactive_circle_outline': '󱡞', // ICON_MD_RADIOACTIVE_CIRCLE_OUTLINE
  'nf-md-ray_end': '󰑀', // ICON_MD_RAY_END
  'nf-md-ray_start': '󰑂', // ICON_MD_RAY_START
  'nf-md-ray_vertex': '󰑅', // ICON_MD_RAY_VERTEX
  'nf-md-record': '󰑊', // ICON_MD_RECORD
  'nf-md-record_circle': '󰻂', // ICON_MD_RECORD_CIRCLE
  'nf-md-relation_many_to_many': '󱒖', // ICON_MD_RELATION_MANY_TO_MANY
  'nf-md-relation_one_to_many': '󱒢', // ICON_MD_RELATION_ONE_TO_MANY
  'nf-md-relation_one_to_one': '󱒣', // ICON_MD_RELATION_ONE_TO_ONE
  'nf-md-relation_one_to_zero_or_many': '󱒦', // ICON_MD_RELATION_ONE_TO_ZERO_OR_MANY
  'nf-md-road': '󰑡', // ICON_MD_ROAD
  'nf-md-road_variant': '󰑢', // ICON_MD_ROAD_VARIANT
  'nf-md-rotate_3d': '󰻇', // ICON_MD_ROTATE_3D
  'nf-md-rotate_3d_variant': '󰑤', // ICON_MD_ROTATE_3D_VARIANT
  'nf-md-rotate_left': '󰑥', // ICON_MD_ROTATE_LEFT
  'nf-md-rotate_right': '󰑧', // ICON_SIDEREAL, ICON_MD_ROTATE_RIGHT
  'nf-md-ruler': '󰑭', // ICON_MD_RULER
  'nf-md-ruler_square': '󰳂', // ICON_MD_RULER_SQUARE
  'nf-md-run': '󰜎', // ICON_MD_RUN
  'nf-md-run_fast': '󰑮', // ICON_MD_RUN_FAST
  'nf-md-sack': '󰴮', // ICON_MD_SACK
  'nf-md-satellite': '󰑰', // ICON_MD_SATELLITE
  'nf-md-satellite_variant': '󰑱', // ICON_MD_SATELLITE_VARIANT
  'nf-md-saw_blade': '󰹡', // ICON_MD_SAW_BLADE
  'nf-md-sawtooth_wave': '󱑺', // ICON_MD_SAWTOOTH_WAVE
  'nf-md-scale_balance': '󰗑', // ICON_MD_SCALE_BALANCE
  'nf-md-screwdriver': '󰑶', // ICON_MD_SCREWDRIVER
  'nf-md-server': '󰒋', // ICON_MD_SERVER
  'nf-md-server_network': '󰒍', // ICON_MD_SERVER_NETWORK
  'nf-md-sheep': '󰳆', // ICON_MD_SHEEP
  'nf-md-shield': '󰒘', // ICON_MD_SHIELD
  'nf-md-shield_account': '󰢏', // ICON_MD_SHIELD_ACCOUNT
  'nf-md-shield_check': '󰕥', // ICON_MD_SHIELD_CHECK
  'nf-md-shield_outline': '󰒙', // ICON_MD_SHIELD_OUTLINE
  'nf-md-shovel': '󰜐', // ICON_MD_SHOVEL
  'nf-md-sigma': '󰒠', // ICON_MD_SIGMA
  'nf-md-silo': '󰭉', // ICON_MD_SILO
  'nf-md-sine_wave': '󰥛', // ICON_MD_SINE_WAVE
  'nf-md-skull': '󰚌', // ICON_MD_SKULL
  'nf-md-skull_crossbones': '󰯆', // ICON_MD_SKULL_CROSSBONES
  'nf-md-skull_outline': '󰯈', // ICON_MD_SKULL_OUTLINE
  'nf-md-snake': '󱔎', // ICON_MD_SNAKE
  'nf-md-snowflake': '󰜗', // ICON_MD_SNOWFLAKE
  'nf-md-solar_panel': '󰶛', // ICON_MD_SOLAR_PANEL
  'nf-md-solar_power': '󰩲', // ICON_MD_SOLAR_POWER
  'nf-md-source_branch': '󰘬', // ICON_MD_SOURCE_BRANCH
  'nf-md-source_fork': '󰓁', // ICON_MD_SOURCE_FORK
  'nf-md-source_merge': '󰘭', // ICON_MD_SOURCE_MERGE
  'nf-md-speedometer': '󰓅', // ICON_MD_SPEEDOMETER
  'nf-md-speedometer_medium': '󰾅', // ICON_MD_SPEEDOMETER_MEDIUM
  'nf-md-speedometer_slow': '󰾆', // ICON_MD_SPEEDOMETER_SLOW
  'nf-md-sphere': '󱥔', // ICON_MD_SPHERE
  'nf-md-sphere_off': '󱥕', // ICON_MD_SPHERE_OFF
  'nf-md-spider': '󱇪', // ICON_MD_SPIDER
  'nf-md-sprout': '󰹦', // ICON_MD_SPROUT
  'nf-md-sprout_outline': '󰹧', // ICON_MD_SPROUT_OUTLINE
  'nf-md-square': '󰝤', // ICON_MD_SQUARE
  'nf-md-square_outline': '󰝣', // ICON_MD_SQUARE_OUTLINE
  'nf-md-square_rounded': '󱓻', // ICON_MD_SQUARE_ROUNDED
  'nf-md-square_wave': '󱑻', // ICON_MD_SQUARE_WAVE
  'nf-md-star': '󰓎', // ICON_STAR_MD, ICON_MD_STAR
  'nf-md-star_four_points': '󰫢', // ICON_STARS, ICON_CONSTELLATION, ICON_MD_STAR_FOUR_POINTS
  'nf-md-star_four_points_outline': '󰫣', // ICON_MD_STAR_FOUR_POINTS_OUTLINE
  'nf-md-star_outline': '󰓒', // ICON_MD_STAR_OUTLINE
  'nf-md-stop': '󰓛', // ICON_MD_STOP
  'nf-md-submarine': '󱕬', // ICON_SUBMARINE
  'nf-md-swap_horizontal': '󰓡', // ICON_MD_SWAP_HORIZONTAL
  'nf-md-swap_vertical': '󰓢', // ICON_MD_SWAP_VERTICAL
  'nf-md-sword': '󰓥', // ICON_MD_SWORD
  'nf-md-sword_cross': '󰞇', // ICON_MD_SWORD_CROSS
  'nf-md-sync': '󰓦', // ICON_MD_SYNC
  'nf-md-sync_alert': '󰓧', // ICON_MD_SYNC_ALERT
  'nf-md-sync_circle': '󱍸', // ICON_MD_SYNC_CIRCLE
  'nf-md-table': '󰓫', // ICON_MD_TABLE
  'nf-md-table_large': '󰓱', // ICON_MD_TABLE_LARGE
  'nf-md-tag': '󰓹', // ICON_MD_TAG
  'nf-md-tag_multiple': '󰓻', // ICON_MD_TAG_MULTIPLE
  'nf-md-tag_outline': '󰓼', // ICON_MD_TAG_OUTLINE
  'nf-md-target': '󰓾', // ICON_MD_TARGET
  'nf-md-telescope': '󰭎', // ICON_MD_TELESCOPE
  'nf-md-temperature_celsius': '󰔄', // ICON_MD_TEMPERATURE_CELSIUS
  'nf-md-temperature_fahrenheit': '󰔅', // ICON_MD_TEMPERATURE_FAHRENHEIT
  'nf-md-tent': '󰔈', // ICON_MD_TENT
  'nf-md-test_tube': '󰙨', // ICON_MD_TEST_TUBE
  'nf-md-test_tube_empty': '󰤑', // ICON_MD_TEST_TUBE_EMPTY
  'nf-md-test_tube_off': '󰤒', // ICON_MD_TEST_TUBE_OFF
  'nf-md-thermometer': '󰔏', // ICON_MD_THERMOMETER
  'nf-md-thermometer_high': '󱃂', // ICON_MD_THERMOMETER_HIGH
  'nf-md-thermometer_low': '󱃃', // ICON_MD_THERMOMETER_LOW
  'nf-md-timer': '󱎫', // ICON_TIMER, ICON_MD_TIMER
  'nf-md-timer_outline': '󰔛', // ICON_MD_TIMER_OUTLINE
  'nf-md-timer_sand': '󰔟', // ICON_MD_TIMER_SAND
  'nf-md-timer_sand_complete': '󱦟', // ICON_MD_TIMER_SAND_COMPLETE
  'nf-md-timer_sand_empty': '󰚭', // ICON_MD_TIMER_SAND_EMPTY
  'nf-md-torch': '󱘆', // ICON_MD_TORCH
  'nf-md-tortoise': '󰴻', // ICON_MD_TORTOISE
  'nf-md-tower_fire': '󰚂', // ICON_MD_TOWER_FIRE
  'nf-md-treasure_chest': '󰜦', // ICON_MD_TREASURE_CHEST
  'nf-md-tree': '󰔱', // ICON_MD_TREE
  'nf-md-tree_outline': '󰹩', // ICON_MD_TREE_OUTLINE
  'nf-md-triangle': '󰔶', // ICON_MD_TRIANGLE
  'nf-md-triangle_outline': '󰔷', // ICON_MD_TRIANGLE_OUTLINE
  'nf-md-trophy': '󰔸', // ICON_MD_TROPHY
  'nf-md-trophy_outline': '󰔺', // ICON_MD_TROPHY_OUTLINE
  'nf-md-tsunami': '󱪁', // ICON_MD_TSUNAMI
  'nf-md-ungroup': '󰕐', // ICON_MD_UNGROUP
  'nf-md-update': '󰚰', // ICON_MD_UPDATE
  'nf-md-vector_circle': '󰕖', // ICON_MD_VECTOR_CIRCLE
  'nf-md-vector_line': '󰕞', // ICON_MD_VECTOR_LINE
  'nf-md-vector_point': '󰕟', // ICON_MD_VECTOR_POINT
  'nf-md-vector_radius': '󰝊', // ICON_MD_VECTOR_RADIUS
  'nf-md-vector_square': '󰀁', // ICON_MD_VECTOR_SQUARE
  'nf-md-vector_triangle': '󰕣', // ICON_MD_VECTOR_TRIANGLE
  'nf-md-view_grid': '󰕰', // ICON_MD_VIEW_GRID
  'nf-md-view_grid_outline': '󱇙', // ICON_MD_VIEW_GRID_OUTLINE
  'nf-md-view_list': '󰕲', // ICON_MD_VIEW_LIST
  'nf-md-view_list_outline': '󱒋', // ICON_MD_VIEW_LIST_OUTLINE
  'nf-md-virus': '󱎶', // ICON_MD_VIRUS
  'nf-md-virus_outline': '󱎷', // ICON_MD_VIRUS_OUTLINE
  'nf-md-volcano': '󱪃', // ICON_MD_VOLCANO
  'nf-md-volume_high': '󰕾', // ICON_MD_VOLUME_HIGH
  'nf-md-volume_low': '󰕿', // ICON_MD_VOLUME_LOW
  'nf-md-volume_off': '󰖁', // ICON_MD_VOLUME_OFF
  'nf-md-vuejs': '󰡄', // ICON_VUE
  'nf-md-walk': '󰖃', // ICON_MD_WALK
  'nf-md-wall': '󰟾', // ICON_MD_WALL
  'nf-md-warehouse': '󰾁', // ICON_MD_WAREHOUSE
  'nf-md-water': '󰖌', // ICON_MD_WATER
  'nf-md-water_outline': '󰸊', // ICON_MD_WATER_OUTLINE
  'nf-md-wave': '󰼮', // ICON_MD_WAVE
  'nf-md-waves': '󰞍', // ICON_MD_WAVES
  'nf-md-weather_cloudy': '󰖐', // ICON_MD_WEATHER_CLOUDY
  'nf-md-weather_fog': '󰖑', // ICON_MD_WEATHER_FOG
  'nf-md-weather_hazy': '󰼰', // ICON_MD_WEATHER_HAZY
  'nf-md-weather_hurricane': '󰢘', // ICON_MD_WEATHER_HURRICANE
  'nf-md-weather_lightning': '󰖓', // ICON_MD_WEATHER_LIGHTNING
  'nf-md-weather_night': '󰖔', // ICON_MD_WEATHER_NIGHT
  'nf-md-weather_partly_cloudy': '󰖕', // ICON_SKY, ICON_MD_WEATHER_PARTLY_CLOUDY
  'nf-md-weather_partly_rainy': '󰼳', // ICON_MD_WEATHER_PARTLY_RAINY
  'nf-md-weather_partly_snowy': '󰼴', // ICON_MD_WEATHER_PARTLY_SNOWY
  'nf-md-weather_pouring': '󰖖', // ICON_MD_WEATHER_POURING
  'nf-md-weather_rainy': '󰖗', // ICON_MD_WEATHER_RAINY
  'nf-md-weather_snowy': '󰖘', // ICON_MD_WEATHER_SNOWY
  'nf-md-weather_snowy_heavy': '󰼶', // ICON_MD_WEATHER_SNOWY_HEAVY
  'nf-md-weather_sunny': '󰖙', // ICON_SUN_STATE, ICON_MD_WEATHER_SUNNY
  'nf-md-weather_sunset': '󰖚', // ICON_MD_WEATHER_SUNSET
  'nf-md-weather_sunset_down': '󰖛', // ICON_MD_WEATHER_SUNSET_DOWN
  'nf-md-weather_sunset_up': '󰖜', // ICON_MD_WEATHER_SUNSET_UP
  'nf-md-weather_tornado': '󰼸', // ICON_MD_WEATHER_TORNADO
  'nf-md-weather_windy': '󰖝', // ICON_MD_WEATHER_WINDY
  'nf-md-web': '󰖟', // ICON_BROWSER
  'nf-md-weight': '󰖡', // ICON_MD_WEIGHT
  'nf-md-white_balance_sunny': '󰖨', // ICON_SUN, ICON_CELESTIAL, ICON_MD_WHITE_BALANCE_SUNNY
  'nf-md-wifi': '󰖩', // ICON_MD_WIFI
  'nf-md-wifi_off': '󰖪', // ICON_WIFI_OFF, ICON_MD_WIFI_OFF
  'nf-md-wind_turbine': '󰶥', // ICON_MD_WIND_TURBINE
  'nf-md-wrench': '󰖷', // ICON_MD_WRENCH
  'nf-md-wrench_outline': '󰯠', // ICON_MD_WRENCH_OUTLINE
  'nf-oct-cpu': '', // ICON_CPU
  'nf-oct-pin': '', // ICON_OCT_PIN
  'nf-oct-terminal': '', // ICON_TERMINAL_ACTIVE
  'nf-weather-day_sunny': '', // ICON_WEATHER_DAY_SUNNY
}

/**
 * BLACKLIST-BASED OFFSET SYSTEM
 *
 * Convention: - = left/up, + = right/down
 *
 * All icons get a DEFAULT offset per component type.
 * Only icons that DIFFER from default are listed (blacklist approach).
 */

// ============================================================================
// DEFAULT OFFSETS (exported for component usage)
// ============================================================================

/** Default offset for Icon component (-2px left, -1px up) */
export const DEFAULT_ICON_OFFSET = { x: -2, y: -1 }

/** Default offset for SquareIconButton (-1px left, -1px up) */
export const DEFAULT_SQUARE_BUTTON_OFFSET = { x: -1, y: -1 }

// ============================================================================
// EXCEPTIONS (only icons that differ from their default)
// ============================================================================

/**
 * Icon component exceptions - icons that differ from DEFAULT_ICON_OFFSET { x: -1, y: -1 }
 */
const iconOffsetExceptions: Record<string, { x: number; y: number }> = {
  // Icons with non-default x offset
  'nf-fa-tachometer': { x: -2, y: -1 },
  'nf-fa-dashboard': { x: -2, y: -1 },
  'nf-fa-cog': { x: 0, y: -1 },
  'nf-fa-play_circle': { x: -4, y: -1 },
  'nf-fa-stop': { x: -4, y: -1 },
  'nf-fa-random': { x: -4, y: -1 },
  'nf-fa-flask': { x: 0, y: -1 },
  'nf-fa-play': { x: 0, y: -1 },
  'nf-fa-long_arrow_right': { x: 0, y: -1 },
  'nf-fa-file_text_o': { x: -3, y: -1 },
  'nf-fa-lock': { x: -3, y: -1 },
}

/**
 * SquareIconButton exceptions - icons that differ from DEFAULT_SQUARE_BUTTON_OFFSET
 * Currently empty - all icons match the default!
 */
const squareButtonOffsetExceptions: Record<string, { x: number; y: number }> = {
  // No exceptions - all SquareIconButton icons use the default { x: -1, y: -1 }
}

// ============================================================================
// GETTER FUNCTIONS
// ============================================================================

/**
 * Get offsets for Icon component (uses DEFAULT_ICON_OFFSET as base)
 */
export function getIconOffsets(name: string): { x: number; y: number } {
  return iconOffsetExceptions[name] ?? DEFAULT_ICON_OFFSET
}

/**
 * Get offsets for SquareIconButton (uses DEFAULT_SQUARE_BUTTON_OFFSET as base)
 */
export function getSquareButtonOffsets(name: string): { x: number; y: number } {
  return squareButtonOffsetExceptions[name] ?? DEFAULT_SQUARE_BUTTON_OFFSET
}

/**
 * Replace (nf-*-*) patterns with Unicode icons
 * @param content Markdown content
 * @returns Content with replaced icons
 */
export function replaceIconPatterns(content: string): string {
  if (!content || typeof content !== 'string') {
    return ''
  }

  return content.replace(/\(nf-[a-z]+-[a-z_]+\)/g, (match) => {
    const nfName = match.slice(1, -1) // Remove ( and )
    const unicode = nfNameToUnicode[nfName]
    return unicode || match // Return Unicode or original if not found
  })
}

export function getIconByName(name: string): string | undefined {
  return nfNameToUnicode[name]
}

export function getAllIconNames(): string[] {
  return Object.keys(nfNameToUnicode)
}
