info_dir=/usr/share/info

post_install() {
    install-info ${info_dir}/identica-mode.info.gz ${info_dir}/dir 2> /dev/null
cat << EOF
==> Put this in your ~/.emacs file to identify in identi.ca

;; Identi.ca mode
(require 'identica-mode)
(setq identica-username "yourusername")
(setq identica-password "yourpassword")
EOF
}

post_upgrade() {
    post_install $1
}

pre_remove () {
    install-info --delete ${info_dir}/identica-mode.info.gz ${info_dir}/dir 2> /dev/null
}