pkgname=inform7-ide

post_install() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
  update-desktop-database -q
  update-mime-database usr/share/mime
}

post_upgrade() {
  post_install "$1"
}

post_remove() {
  glib-compile-schemas usr/share/glib-2.0/schemas
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
  update-desktop-database -q
  update-mime-database usr/share/mime
}
