#!/usr/bin/env sh

post_install() {
    echo '------------------------'
    echo '| READ VERY CAREFULLY! |'
    echo '------------------------'
    echo '1. Create /etc/sub{u,g}id files (touch /etc/subuid /etc/subgid) or the'
    echo '   sysctl service will not start'
    echo ''
    echo '2. Make sure to start the sysbox service (systemctl start sysbox)'
    echo ''
    echo '3. To use sysbox with Docker, add the following to /etc/docker/daemon.json:'
    echo '{'
    echo '  "runtimes": {'
    echo '    "sysbox-runc": {'
    echo '      "path": "/usr/bin/sysbox-runc",'
    echo '      "runtimeArgs": ["--no-kernel-check"]'
    echo '    }'
    echo '  }'
    echo '}'
    echo 'Then restart the docker service (systemctl restart docker)'
    echo ''
    echo '4. You will need to either install the shiftfs kernel module,'
    echo '   or configure Docker in userns-remap mode (see link below)'
    echo ''
    echo '5. systemd must use cgroups v1, not v2 which is the default for'
    echo '   systemd >= 248. Make sure cgroups v1 is not disabled and try'
    echo '   adding systemd.unified_cgroup_hierarchy=0 to your boot options'
    echo ''
    echo '6. When starting a container, you will get an error about not being'
    echo '   able to mount /usr/src/linux-headers-xyz. Simply create an empty'
    echo '   directory at that path and it should work.'
    echo ''
    echo 'Note that Arch Linux is NOT officially supported.'
    echo 'For more information, please check:'
    echo 'https://github.com/nestybox/sysbox/blob/master/docs/user-guide/troubleshoot.md'
}
