post_install() {
	echo ""
	echo "--------------------"
	echo "Note:"
	echo "  Be sure that:"
	echo "    - lircd.service is disabled,"
	echo "    - You enable & start the make-ir-freaking-work.service,"
	echo "    - You are running kodi as service (kodi.service)."
	echo ""
	echo "  If this doesn't work for you, the IR codes in:"
	echo "    /etc/rc_keymaps/apple_remote_sab are probably not"
	echo "    working for you."
}

post_upgrade() {
	post_install
}

post_remove() {
}
