g sgx_prv - -

u! qgsd - "User for qgsd"  /var/opt/qgsd
m  qgsd sgx_prv
m  qgsd sgx

u! aesmd - "User for aesmd" /var/opt/aesmd
m  aesmd sgx_prv
m  aesmd sgx

u! pccs - - /opt/intel/sgx-dcap-pccs /bin/bash
