post_install() {
	cat <<EOF
==> To enable IntelliShell for your shell, add the following to your config:
==> Bash: eval "$(intelli-shell init bash)"
==> Zsh: eval "$(intelli-shell init zsh)"
==> Fish: intelli-shell init fish | source
==> Nu: mkdir ($nu.data-dir | path join "vendor/autoload") && intelli-shell init nushell | save -f ($nu.data-dir | path join "vendor/autoload/intelli-shell.nu")
EOF
}
