#!/usr/bin/env python3
# pylint: disable=C0103,C0111

import configparser
import shutil
import subprocess
import sys
from pathlib import Path
from textwrap import dedent
from typing import Dict, Set, Tuple

import inflection
from git import Repo
from xdg.BaseDirectory import xdg_cache_home, xdg_config_home, xdg_data_home

IOSEVKA_REPO = "https://github.com/be5invis/iosevka"


def get_repo(repo_dir: Path) -> Repo:
    if repo_dir.exists():
        print(f"Updating {IOSEVKA_REPO} ...", file=sys.stderr)
        repo = Repo(repo_dir)
        repo.remote().pull()
    else:
        repo = Repo.clone_from(IOSEVKA_REPO, repo_dir, depth=1)
    return repo


def install_iosevka(repo_dir: Path):
    get_repo(repo_dir)

    print("Installing iosevka...", file=sys.stderr)
    try:
        subprocess.run(["npm", "install"], cwd=repo_dir).check_returncode()
        subprocess.run(["npm", "install", "--package-lock-only"], cwd=repo_dir).check_returncode()
        subprocess.run(["npm", "audit", "fix"], cwd=repo_dir).check_returncode()
    except subprocess.CalledProcessError:
        print("Failed to install iosevka", file=sys.stderr)
        sys.exit(1)
    else:
        print("Iosevka installed.", file=sys.stderr)


def generate_font(iosevka_dir: Path, font_name: str, font_styles: Dict[str, Set[str]]):
    family_name = f"Iosevka {inflection.titleize(font_name)}"
    print(f"Building font with family name: {family_name}")

    with open(iosevka_dir / "private-build-plans.toml", "w") as fp:
        conf = f"""\
            [buildPlans.{font_name}]
            family = "{family_name}"
            design = [{', '.join(map(lambda style: f'"{style}"', font_styles['common']))}]
            upright = [{', '.join(map(lambda style: f'"{style}"', font_styles['upright']))}]
            italic = [{', '.join(map(lambda style: f'"{style}"', font_styles['italic']))}]
            oblique = [{', '.join(map(lambda style: f'"{style}"', font_styles['oblique']))}]
        """

        print(f"Building iosevka conf:\n{conf}", file=sys.stderr)
        fp.write(dedent(conf))

    subprocess.run(
        ["npm", "run", "build", "--", f"ttf::{font_name}"], cwd=iosevka_dir
    ).check_returncode()


def parse_config(config_file: Path) -> Tuple[str, Dict[str, Set[str]]]:
    print(f"Parsing iosevka-generate conf: {config_file} ...", file=sys.stderr)

    config = configparser.ConfigParser(
        allow_no_value=True, inline_comment_prefixes=(";")
    )
    config.read_dict({"options": {"name": "myosevka"}})

    sections = {"common", "upright", "italic", "oblique"}
    config.read_dict({s: {} for s in sections})
    config.read(config_file)

    font_styles = {
        section: {f"v-{char}-{style}" for char, style in config[section].items()}
        for section in sections
    }

    for option, value in config["options"].items():
        if option == "name":
            font_name = value
        elif not value:
            font_styles["common"].add(option)
        else:
            font_styles["common"].add(f"{option}-{value}")

    return (font_name, font_styles)


def store_fonts(dest: Path, source: Path):
    dest.mkdir(parents=True, exist_ok=True)
    for font in filter(lambda f: f.is_file(), source.glob("*")):
        shutil.move(source / font, dest / font.name)

    subprocess.run(["fc-cache", "--force"]).check_returncode()


if __name__ == "__main__":
    config_dir = Path(xdg_config_home) / "iosevka"
    install_dir = Path(xdg_cache_home) / "iosevka"

    install_iosevka(install_dir)
    for conf in Path(config_dir).glob("*.ini"):
        name, styles = parse_config(conf)
        generate_font(install_dir, name, styles)

        gen_dir = install_dir / "dist" / name / "ttf"
        font_dir = Path(xdg_data_home) / "fonts"

        store_fonts(font_dir, gen_dir)
