PACKAGE_NAME="ipu-bridge-legacy-cvs"
PACKAGE_VERSION="@PACKAGE_VERSION@"

MAKE[0]="make KERNELRELEASE=${kernelver} KERNEL_SRC=${kernel_source_dir}"

BUILT_MODULE_NAME[0]="ipu-bridge"
DEST_MODULE_LOCATION[0]="/updates/dkms"

BUILD_EXCLUSIVE_KERNEL_MIN="7.2"
BUILD_EXCLUSIVE_KERNEL_MAX="7.3"
AUTOINSTALL="yes"
