post_install() {
  echo "Registering iscan plugins and firmwares"
  for id in 0x013c 0x013d; do
    iscan-registry --add interpreter usb 0x04b8 $id \
      /usr/lib/iscan/libiscan-plugin-gt-s650 \
      /usr/share/iscan/esfw010c.bin
  done
}

pre_remove() {
  echo "Unregistering iscan plugins and firmwares"
  for id in 0x013c 0x013d; do
    iscan-registry --remove interpreter usb 0x04b8 $id \
      /usr/lib/iscan/libiscan-plugin-gt-s650
      /usr/share/iscan/esfw010c.bin
  done
}
