post_install() {
  echo "Registering iscan plugins and firmwares"
  iscan-registry --add interpreter usb 0x04b8 0x0131 \
    /usr/lib/iscan/libesci-interpreter-gt-f720 \
    /usr/share/esci/esfw8b.bin 
}

pre_remove() {
  echo "Unregistering iscan plugins and firmwares"
  iscan-registry --remove interpreter usb 0x04b8 0x0131 \
    /usr/lib/iscan/libesci-interpreter-gt-f720 \
    /usr/share/esci/esfw8b.bin 
}
