post_install() {
    export GCONF_CONFIG_SOURCE=$(gconftool-2 --get-default-source)
    gconftool-2 --makefile-install-rule usr/share/gconf/schemas/istanbul.schemas >/dev/null
}

pre_upgrade() {
    pre_remove
}

post_upgrade() {
    post_install
}

pre_remove() {
    schemas=$(pacman -Ql istanbul | grep 'gconf/schemas/.*schemas$' | awk '{ print $2 }')
    export GCONF_CONFIG_SOURCE=$(gconftool-2 --get-default-source)
    gconftool-2 --makefile-uninstall-rule ${schemas[@]} >/dev/null
}
