#!/bin/sh

progname="jalview"
mainclass="jalview.bin.Jalview"
basedir="/usr/share/java/$progname"

# build classpath: all jars in $basedir
cp=$(ls $basedir/*.jar | xargs echo | sed "s/ /:/g")

# run jar
"/usr/bin/java" -cp $cp $mainclass
