THIS_JDK='java-11-graalvm-ee'

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

note() {
	printf "${blue}::${yellow} archlinux-java:${bold} $1${all_off}\n"
}

fix_default() {
	if [ ! -x /usr/bin/java ]; then
		/usr/bin/archlinux-java unset
		echo ""
	else
		/usr/bin/archlinux-java get
	fi
}

post_install() {
	default=$(fix_default)
	case ${default} in
		"")
			/usr/bin/archlinux-java set ${THIS_JDK}
			note "'${THIS_JDK}' set as default Java environment."
			;;
		${THIS_JDK})
			note "'${THIS_JDK}' set as default Java environment."
			;;
		*)
			note "Default Java environment already set to '${default}'.
			       To use '${THIS_JDK}', run:
			         # archlinux-java set ${THIS_JDK}
			       For status, use:
			         $ archlinux-java status"
			;;
	esac

	if [ ! -f /etc/ssl/certs/java/cacerts ]; then
		/usr/bin/update-ca-trust
	fi
}

post_upgrade() {
	post_install
}

pre_remove() {
	default=$(fix_default)
	case ${default} in
		${THIS_JDK})
			/usr/bin/archlinux-java unset
			;;
		*)
			# Nothing
			;;
	esac
}

post_remove() {
	default=$(fix_default)
	if [[ ${default} ]]; then
		note "Default Java environment is '${default}'."
	else
		archlinux-java fix
		default=$(fix_default)
		if [[ ${default} ]]; then
			note "Default Java environment left as '${default}'."
		else
			note "Java environment unset."
		fi
	fi
}
