#!/usr/bin/env bash
if [ "$(id -u)" -eq "0" ]; then
  #restart as user jdownloader
  echo "changing to user \"jdownloader\""
  runuser jdownloader -c "/bin/bash $0 $@" -s /bin/bash
  exit $?
fi
groups | grep -q -E '(\s|^)jdownloader(\s|$)' >/dev/null
if [ "$?" -eq  0 ]; then
  echo "Starting global JDownloader"
  umask u=rwx,g=rwx,o=rx
  cd '/opt/JDownloader'
else
  echo "starting local JDownloader"
  mkdir -p "${HOME}/.jd"
	cd "${HOME}/.jd"
fi

if [ ! -f "JDownloader.jar" ]; then
	wget -O JDownloader.jar http://installer.jdownloader.org/JDownloader.jar
fi

exec java -Djava.awt.headless=true -jar JDownloader.jar -norestart "$@"
