post_upgrade() {
  # only show warning if upgrading to v2.3.3-1
  vercmp "$1" "2.3.3-1" > /dev/null 2>&1
  [[ $? -lt 0 ]] && exit 0

  cat << EOF

  CAUTION: This release will ask you to upgrade your sync target,
  whether it's Dropbox, OneDrive, Joplin Cloud, etc.
  Once it is done, only apps version 2.3+ will be able to
  sync with it, so make sure you are ready to upgrade all your
  apps before installing this version.

EOF
}
