#!/bin/sh
msg_blue() {
    printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
    printf "${blue}==>${yellow} Note:${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
  note "add '/usr/share/:/usr/local/share/' to you XDG_DATA_DIRS env, e.g"
  msg_blue 'echo 'XDG_DATA_DIRS=\"\$XDG_DATA_DIRS:/usr/share/:/usr/local/share/\"' >> /etc/environment'
}

post_upgrade() {
  post_install
}
