#!/bin/sh
export WINEPREFIX="$HOME/.keepass/wine"
export WINEARCH=win32
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG=-all

# First Run
if [ ! -d "$WINEPREFIX" ] ; then
    cp -r "/usr/share/keepass/wine" "$WINEPREFIX"
fi

# Start Keepass
wine "/usr/share/keepass/KeePass.exe" "`winepath -w "$@"`"
