## arg 1:  the new package version
post_install() {
  # Run install script
  # Don't install deps, done through pacman deps instead
  sudo INSTALL_DEPS=0 "/usr/share/keysharp/install.sh"

}

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
  # Run uninstall script
  # Don't install deps, done through pacman deps instead
  sudo INSTALL_DEPS=0 "/usr/share/keysharp/uninstall.sh"
}
## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  # Run install script
  # Don't install deps, done through pacman deps instead
  sudo INSTALL_DEPS=0 "/usr/share/keysharp/install.sh"
}

## arg 1:  the old package version
pre_remove() {
  # Run uninstall script
  # Don't install deps, done through pacman deps instead
  sudo INSTALL_DEPS=0 "/usr/share/keysharp/uninstall.sh"
}
