#!/usr/bin/ash

run_hook() {
    local cryptdev cryptname="root" cryptoptions
    local QUIET

    [ "${quiet}" = "y" ] && QUIET=" > /dev/null"

    if [ -n "${cryptdevice}" ]; then
        IFS=: read cryptdev cryptname cryptoptions <<EOF
$cryptdevice
EOF
    fi

    kpartx -v -a "/dev/mapper/${cryptname}" ${QUIET}
    if [ $? -ne 0 ]; then
        err "The command \"kpartx /dev/mapper/${cryptname}\" did not run successfully!"
        return 1
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
