msg() {
  printf "%b" "\e[1;31m==> WARNING: To use this effect disable the default Blur effect and any other forks of the blur effect as well (such as the one provided by LightlyShaders). Then enable the Better Blur effect. You can do this under Desktop Effects in System Settings\n\e[0m"
  printf "%b" "\e[1;33m==> NOTE: This is a patched build that fixes force blur covering opaque windows. See the patch file for details.\n\e[0m"
}

post_install() {
  msg
}
post_upgrade() {
  msg
}
