post_install() {
  echo " +---------------------------------------------------------------------+"
  echo " | To enable and start the layout-switcher daemon, run:                |"
  echo " |   systemctl --user enable --now layout-switcher.service             |"
  echo " | To bind layout-switcher to a hotkey, configure your compositor:     |"
  echo " |   pkill -USR1 layout-switcher                                       |"
  echo " +---------------------------------------------------------------------+"
}
