post_install() {
	echo "---------------------------------------------------------------"
	echo ":: Earth Star RA6E2 wiki / 地奇星 RA6E2 维基： "
	echo "   xdg-open https://wiki.lckfb.com/zh-hans/a6e2/"
	echo ":: Add yourself to the uucp group to access the serial ports:"
        echo "   sudo gpasswd -aG \$USER uucp"
        echo "   sudo udevadm control --reload-rules"
	echo "   newgrp uucp"
	echo "---------------------------------------------------------------"
}

post_upgrade() {
	post_install
}
