post_install() {
	echo "---------------------------------------------------------------"
	echo ":: Add yourself to the uucp group to access the serial ports:"
    echo "   sudo gpasswd -aG \$USER uucp"
    echo "   sudo udevadm control --reload-rules"
	echo ":: If adb fails to connect to the phone, add the current user to the adbusers group"
	echo "   sudo gpasswd -aG \$USER adbusers"
	echo "---------------------------------------------------------------"
}

post_upgrade() {
	post_install
}
