#!/bin/sh

if [[ "$1" != "-p" ]]; then
    WORKDIR=$HOME/LeavesMC
    mkdir -p $WORKDIR
    cd $WORKDIR
fi

if [[ "$1" == "gui" ]]; then
    exec java -jar /usr/share/java/leavesmc/leavesmc.jar "$@"
fi

exec java -jar /usr/share/java/leavesmc/leavesmc.jar nogui "$@"
