post_install() {
	systemctl enable --now lenovo-fancurve.service
	systemctl enable --now lenovo-fancurve.patch
	echo "Service was enable"
	echo "If fail reboot the system because LenovoLegionLinux module was not install"
}

post_upgrade() {
	post_install $1
}

pre_remove() {
	depmod -a $(uname -r)
	systemctl disable --now lenovo-fancurve.path
	systemctl disable --now lenovo-fancurve.service
	echo Uninstall finished.
	echo Reboot the system.
}
