#LEMONADE_HOST=
#LEMONADE_PORT=
#LEMONADE_LOG_LEVEL=
#LEMONADE_LLAMACPP=
#LEMONADE_CTX_SIZE=
#LEMONADE_LLAMACPP_ARGS=
#LEMONADE_EXTRA_MODELS_DIR=
#LEMONADE_DISABLE_MODEL_FILTERING=
#LEMONADE_ENABLE_DGPU_GTT=
#LEMONADE_LLAMACPP_ROCM_BIN
#LEMONADE_LLAMACPP_VULKAN_BIN=
#LEMONADE_LLAMACPP_CPU_BIN=
#LEMONADE_WHISPERCPP_BIN=
#LEMONADE_RYZENAI_SERVER_BIN=