# You can have several different profiles and use LESMA_PROFILE environment
# variable to switch between them. By default release is used.
# See https://rocket.rs/v0.5-rc/guide/configuration/#profiles for more info.
#
# All configuration parameters can also be set with environment variables.
# For each parameter, the corresponding environment variable is indicated.
# Note that all parameters are optional, if not defined the default values
# are used.
#
# If you want to use this configuration file, copy it as /etc/lesma.toml or
# as lesma.toml together with the executable file.
[release]
# Listen address, default 127.0.0.1
# LESMA_ADDRESS
address = "127.0.0.1"
# Listen port, default 8000
# LESMA_PORT
#port = 8000
# When a new URL for a paste or file is generated use http or https, by
# default is set to false and uses http
# LESMA_HTTPS
https=true
# Log level, the valid values are `critical`, `normal`, `debug`, `off`, if
# not defined the default value is off
# LESMA_LOG_LEVEL
#log_level = "normal"
# The size limit sets both the limit for uploaded files and for the
# information posted, default 10MiB. If you simply indicate a number the
# size is in bytes but you can use the suffixes kB, MB, GB.. for powers of
# ten or KiB, MiB, GiB.. for powers of two
# LESMA_SIZE_LIMIT
#size_limit = "5GiB"
# Default download limit for every paste or file created where a different
# value is not specified , default 0 (unlimited), maximum accepted value 255
# LESMA_DEFAULT_LIMIT
#default_limit = 1
# Default expiration time (in hours) for each paste or file created when
# a different value is not specified, default 720 hours (30 days)
# LESMA_DEFAULT_EXPIRE
#default_expire = 24
# Maximum expiration time that an user can set (in hours) for each paste or
# file, default 720 hours (30 days)
# LESMA_MAX_EXPIRE
#max_expire = 168
# Location of lesmas storage, if not defined, a temporary directory will be
# used, usually /tmp
# LESMA_STORAGE
storage = "/var/lib/lesma"

# Other sample
#[debug]
#address = "127.0.0.1"
#port = 9000
#log_level = "debug"
#storage = "/tmp/lesma"
