pre_install() {
	echo
	echo --------------------------
	echo Installing network-scan ...
	echo --------------------------
	echo Please remember to review the license agreement before
	echo using this software.
}

post_install() {
	chown root:bin '/usr/local/lexmark'
	chmod 755 '/usr/local/lexmark'
	chown root:bin '/usr/local/lexmark/network-scan.link'
	chmod 755 '/usr/local/lexmark/network-scan.link'
	chown root:bin '/usr/local/lexmark/network-scan.unlink'
	chmod 755 '/usr/local/lexmark/network-scan.unlink'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/bin'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/bin'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/bin/display.sh'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/bin/display.sh'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/bin/lexscan'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/bin/lexscan'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/bin/lshome'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/bin/lshome'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/bin/lsinet'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/bin/lsinet'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/bin/pxmstretch'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/bin/pxmstretch'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/bin/sbrowser'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/bin/sbrowser'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/LICENSE.TXT'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/LICENSE.TXT'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/Boost_license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/Boost_license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/jre_license'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/jre_license'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/libcurl_license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/libcurl_license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/openssl_license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/openssl_license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/sane_license'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/OpenSource_License/sane_license'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/ar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ar/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/ar/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/de'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/de'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/de/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/de/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/en'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/en'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/en/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/en/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/es'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/es'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/es/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/es/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/fr'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/fr'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/fr/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/fr/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/it'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/it'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/it/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/it/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ja'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/ja'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ja/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/ja/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ko'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/ko'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ko/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/ko/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/pl'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/pl'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/pl/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/pl/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/pt_br'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/pt_br'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/pt_br/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/pt_br/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ru'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/ru'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/ru/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/ru/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/zh_cn'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/zh_cn'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/zh_tw'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/license/zh_tw'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/license/zh_tw/license.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/license/zh_tw/license.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/readme.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/readme.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/supported-platforms.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/supported-platforms.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ar/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/de/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/en/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/es/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/fr/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/it/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ja/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ko/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pl/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/pt/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/lex-logo-new.png'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/lex-logo-new.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/style.css'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/style.css'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_brightness_icon_0.jpg'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_brightness_icon_0.jpg'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_contrast_icon_0.jpg'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_contrast_icon_0.jpg'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_negative_0.jpg'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_negative_0.jpg'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_scanmode_icon_0.jpg'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_scanmode_icon_0.jpg'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_scanresolution_icon_0.jpg'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_scanresolution_icon_0.jpg'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_single_or_multiple_page_option_icon_0.jpg'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/resource/xsane_single_or_multiple_page_option_icon_0.jpg'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/ru/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/adjusting-scan-settings-using-xsane-oowriter-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/canceling-scan-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/canceling-scan-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/checking-if-scan-driver-installed-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/checking-if-scan-driver-installed-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/cover.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/cover.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/edition-notice-date-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/edition-notice-date-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/index.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/index.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/installing-the-network-scan-driver-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/installing-the-network-scan-driver-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/printer-not-compatible-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/printer-not-compatible-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/printer-scans-page-status-applet-does-not-get-data-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/printer-stops-scanning-or-prints-failed-scanning-message-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/removing-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/removing-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/sane-does-not-recognize-network-scan-driver-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/sane-does-not-recognize-network-scan-driver-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scan-adf-one-page-scanned-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scan-adf-one-page-scanned-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-both-sides-page-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-both-sides-page-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-multiple-pages-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-multiple-pages-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-using-network-printer-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-using-network-printer-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-using-xsane-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/scanning-using-xsane-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/system-requirements-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/system-requirements-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/toc.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/toc.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/troubleshooting-chapter.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/troubleshooting-chapter.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/xsane-displays-garbage-characters-topic.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/ug/zh_TW/xsane-displays-garbage-characters-topic.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/version.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/version.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/weee'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/docs/weee'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/docs/weee/EU_Waste_Electronic_Information.pdf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/docs/weee/EU_Waste_Electronic_Information.pdf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/etc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/lexmark_nscan.conf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/lexmark_nscan.conf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/scan.conf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/scan.conf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/scan13.conf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/scan13.conf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/scan14.conf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/scan14.conf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/scan16.conf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/scan16.conf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/scan17.conf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/scan17.conf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/scan6.conf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/scan6.conf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/udev'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/etc/udev'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/udev/rules.d'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/etc/udev/rules.d'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/etc/udev/rules.d/99-lexmark.rules'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/etc/udev/rules.d/99-lexmark.rules'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/COPYRIGHT'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/COPYRIGHT'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/LICENSE'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/LICENSE'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/README'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/README'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/THIRDPARTYLICENSEREADME-JAVAFX.txt'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/THIRDPARTYLICENSEREADME-JAVAFX.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/THIRDPARTYLICENSEREADME.txt'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/THIRDPARTYLICENSEREADME.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/Welcome.html'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/Welcome.html'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/java'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/java'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/javaws'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/javaws'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/jcontrol'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/jcontrol'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/jjs'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/jjs'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/keytool'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/keytool'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/orbd'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/orbd'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/pack200'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/pack200'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/policytool'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/policytool'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/rmid'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/rmid'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/rmiregistry'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/rmiregistry'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/servertool'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/servertool'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/tnameserv'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/tnameserv'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/bin/unpack200'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/bin/unpack200'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/jli'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/jli'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/jli/libjli.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/jli/libjli.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/jvm.cfg'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/jvm.cfg'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libavplugin-53.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libavplugin-53.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libavplugin-54.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libavplugin-54.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libawt.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libawt.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libawt_headless.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libawt_headless.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libawt_xawt.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libawt_xawt.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libbci.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libbci.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdcpr.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdcpr.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdecora_sse.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdecora_sse.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdeploy.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdeploy.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdt_socket.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libdt_socket.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libfontmanager.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libfontmanager.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libfxplugins.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libfxplugins.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libglass.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libglass.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libgstreamer-lite.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libgstreamer-lite.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libhprof.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libhprof.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libinstrument.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libinstrument.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libj2gss.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libj2gss.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libj2pcsc.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libj2pcsc.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libj2pkcs11.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libj2pkcs11.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjaas_unix.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjaas_unix.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjava.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjava.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjava_crw_demo.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjava_crw_demo.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font_freetype.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font_freetype.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font_pango.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font_pango.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font_t2k.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_font_t2k.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_iio.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjavafx_iio.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjawt.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjawt.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjdwp.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjdwp.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjfr.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjfr.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjfxmedia.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjfxmedia.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjfxwebkit.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjfxwebkit.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjpeg.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjpeg.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsdt.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsdt.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsig.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsig.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsound.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsound.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsoundalsa.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libjsoundalsa.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libkcms.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libkcms.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/liblcms.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/liblcms.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libmanagement.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libmanagement.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libmlib_image.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libmlib_image.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnet.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnet.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnio.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnio.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnpjp2.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnpjp2.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnpt.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libnpt.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libprism_common.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libprism_common.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libprism_es2.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libprism_es2.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libprism_sw.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libprism_sw.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libresource.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libresource.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libsctp.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libsctp.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libsplashscreen.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libsplashscreen.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libsunec.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libsunec.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libt2k.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libt2k.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libunpack.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libunpack.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libverify.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libverify.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libzip.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/libzip.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/server'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/server'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/server/Xusage.txt'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/server/Xusage.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/server/libjvm.so'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/amd64/server/libjvm.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/applet'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/applet'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/calendars.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/calendars.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/charsets.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/charsets.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/classlist'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/classlist'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/CIEXYZ.pf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/CIEXYZ.pf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/GRAY.pf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/GRAY.pf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/LINEAR_RGB.pf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/LINEAR_RGB.pf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/PYCC.pf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/PYCC.pf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/sRGB.pf'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/lib/cmm/sRGB.pf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/content-types.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/content-types.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/currency.data'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/jre/lib/currency.data'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/MixedCodeMainDialog.ui'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/MixedCodeMainDialog.ui'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/MixedCodeMainDialogJs.ui'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/MixedCodeMainDialogJs.ui'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/cautionshield.icns'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/cautionshield.icns'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/ffjcext.zip'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/ffjcext.zip'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/java-icon.ico'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/java-icon.ico'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_de.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_de.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_es.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_es.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_fr.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_fr.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_it.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_it.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_ja.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_ja.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_ko.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_ko.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_pt_BR.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_pt_BR.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_sv.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_sv.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_zh_CN.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_zh_CN.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_zh_HK.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_zh_HK.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_zh_TW.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/messages_zh_TW.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/mixcode_s.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/mixcode_s.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/splash.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/splash.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/splash@2x.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/deploy/splash@2x.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications/sun-java.desktop'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications/sun-java.desktop'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications/sun-javaws.desktop'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications/sun-javaws.desktop'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications/sun_java.desktop'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/applications/sun_java.desktop'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/16x16/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrast/48x48/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/16x16/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/HighContrastInverse/48x48/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/16x16/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/LowContrast/48x48/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/16x16/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps/sun-javaws.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps/sun-javaws.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps/sun-jcontrol.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/apps/sun-jcontrol.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-application-x-java-archive.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-application-x-java-jnlp-file.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-text-x-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/icons/hicolor/48x48/mimetypes/gnome-mime-text-x-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime/packages'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime/packages'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime/packages/x-java-archive.xml'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime/packages/x-java-archive.xml'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime/packages/x-java-jnlp-file.xml'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/desktop/mime/packages/x-java-jnlp-file.xml'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/cldrdata.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/cldrdata.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/dnsns.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/dnsns.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/jfxrt.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/jfxrt.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/localedata.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/localedata.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/meta-index'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/meta-index'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/nashorn.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/nashorn.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/sunec.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/sunec.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/sunjce_provider.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/sunjce_provider.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/sunpkcs11.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/sunpkcs11.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/zipfs.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/ext/zipfs.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/flavormap.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/flavormap.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.5.bfc'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.5.bfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.5.properties.src'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.5.properties.src'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.6.bfc'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.6.bfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.6.properties.src'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.RedHat.6.properties.src'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.10.bfc'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.10.bfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.10.properties.src'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.10.properties.src'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.11.bfc'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.11.bfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.11.properties.src'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.SuSE.11.properties.src'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.Turbo.bfc'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.Turbo.bfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.Turbo.properties.src'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.Turbo.properties.src'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.bfc'
	chmod 555 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.bfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.properties.src'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fontconfig.properties.src'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightDemiBold.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightDemiBold.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightDemiItalic.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightDemiItalic.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightItalic.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightItalic.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightRegular.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaBrightRegular.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaSansDemiBold.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaSansDemiBold.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaSansRegular.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaSansRegular.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaTypewriterBold.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaTypewriterBold.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaTypewriterRegular.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/LucidaTypewriterRegular.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/fonts.dir'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/fonts/fonts.dir'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/hijrah-config-umalqura.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/hijrah-config-umalqura.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/cursors.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/cursors.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/invalid32x32.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/invalid32x32.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_CopyDrop32x32.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_CopyDrop32x32.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_CopyNoDrop32x32.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_CopyNoDrop32x32.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_LinkDrop32x32.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_LinkDrop32x32.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_LinkNoDrop32x32.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_LinkNoDrop32x32.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_MoveDrop32x32.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_MoveDrop32x32.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_MoveNoDrop32x32.gif'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/cursors/motif_MoveNoDrop32x32.gif'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java_HighContrast.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java_HighContrast.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java_HighContrastInverse.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java_HighContrastInverse.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java_LowContrast.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/images/icons/sun-java_LowContrast.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/javafx.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/javafx.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/javaws.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/javaws.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jce.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jce.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jexec'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jexec'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr/default.jfc'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr/default.jfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr/profile.jfc'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfr/profile.jfc'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfxswt.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jfxswt.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jsse.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jsse.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/jvm.hprof.txt'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/jvm.hprof.txt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/de'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/de'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/de/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/de/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/de/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/de/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/es'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/es'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/es/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/es/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/es/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/es/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/fr'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/fr'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/fr/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/fr/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/fr/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/fr/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/it'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/it'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/it/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/it/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/it/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/it/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ja'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ja'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ja/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ja/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ja/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ja/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko.UTF-8'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko.UTF-8'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko.UTF-8/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko.UTF-8/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko.UTF-8/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko.UTF-8/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/ko/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/pt_BR'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/pt_BR'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/pt_BR/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/pt_BR/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/pt_BR/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/pt_BR/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/sv'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/sv'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/sv/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/sv/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/sv/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/sv/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh.GBK'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh.GBK'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh.GBK/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh.GBK/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh.GBK/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh.GBK/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_HK.BIG5HK'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_HK.BIG5HK'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_HK.BIG5HK/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_HK.BIG5HK/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_HK.BIG5HK/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_HK.BIG5HK/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW.BIG5'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW.BIG5'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW.BIG5/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW.BIG5/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW.BIG5/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW.BIG5/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW/LC_MESSAGES/sunw_java_plugin.mo'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/locale/zh_TW/LC_MESSAGES/sunw_java_plugin.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/logging.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/logging.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/management'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/management'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/management-agent.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/management-agent.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/jmxremote.access'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/jmxremote.access'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/jmxremote.password.template'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/jmxremote.password.template'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/management.properties'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/management.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/snmp.acl.template'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/jre/lib/management/snmp.acl.template'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/meta-index'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/meta-index'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/net.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/net.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaSansDemiOblique.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaSansDemiOblique.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaSansOblique.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaSansOblique.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaTypewriterBoldOblique.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaTypewriterBoldOblique.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaTypewriterOblique.ttf'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/LucidaTypewriterOblique.ttf'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/fonts.dir'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/oblique-fonts/fonts.dir'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/plugin.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/plugin.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/psfont.properties.ja'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/psfont.properties.ja'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/psfontj2d.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/psfontj2d.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/resources.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/resources.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/rt.jar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/rt.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/US_export_policy.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/US_export_policy.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/blacklist'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/blacklist'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/blacklisted.certs'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/blacklisted.certs'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/cacerts'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/cacerts'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/java.policy'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/java.policy'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/java.security'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/java.security'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/javaws.policy'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/javaws.policy'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/local_policy.jar'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/local_policy.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/trusted.libraries'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/lib/security/trusted.libraries'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/sound.properties'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/sound.properties'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/lib/tzdb.dat'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/lib/tzdb.dat'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/man'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/java.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/java.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/javaws.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/javaws.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/jjs.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/jjs.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/keytool.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/keytool.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/orbd.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/orbd.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/pack200.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/pack200.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/policytool.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/policytool.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/rmid.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/rmid.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/rmiregistry.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/rmiregistry.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/servertool.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/servertool.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/tnameserv.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/tnameserv.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/unpack200.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/ja_JP.UTF-8/man1/unpack200.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/java.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/java.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/javaws.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/javaws.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/jjs.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/jjs.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/keytool.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/keytool.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/orbd.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/orbd.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/pack200.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/pack200.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/policytool.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/policytool.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/rmid.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/rmid.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/rmiregistry.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/rmiregistry.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/servertool.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/servertool.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/tnameserv.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/tnameserv.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/unpack200.1'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/man/man1/unpack200.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/plugin'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/plugin'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/plugin/desktop'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/jre/plugin/desktop'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/plugin/desktop/sun_java.desktop'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/plugin/desktop/sun_java.desktop'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/plugin/desktop/sun_java.png'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/plugin/desktop/sun_java.png'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/jre/release'
	chmod 644 '/usr/local/lexmark/unix_scan_drivers/jre/release'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/lib'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/lib'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/lib/sane'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/lib/sane'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/lib/sane/libsane-lexmark_nscan.so'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/lib/sane/libsane-lexmark_nscan.so'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/lib/sane/libsane-lexmark_nscan.so.1'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/lib/sane/libsane-lexmark_nscan.so.1'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/lib/sane/libsane-lexmark_nscan.so.1.0.16'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/lib/sane/libsane-lexmark_nscan.so.1.0.16'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/lib/scan.jar'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/lib/scan.jar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/scanner'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/scanner'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/icons'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/icons'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/icons/logo.xpm'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/icons/logo.xpm'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ar'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ar'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ar/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ar/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ar/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/ar/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/de'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/de'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/de/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/de/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/de/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/de/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/es'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/es'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/es/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/es/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/es/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/es/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/fr'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/fr'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/fr/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/fr/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/fr/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/fr/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/it'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/it'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/it/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/it/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/it/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/it/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ja'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ja'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ja/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ja/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ja/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/ja/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ko'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ko'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ko/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ko/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ko/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/ko/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/pl'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/pl'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/pl/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/pl/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/pl/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/pl/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/pt'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/pt'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/pt/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/pt/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/pt/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/pt/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ru'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ru'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ru/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/ru/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/ru/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/ru/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/zh'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/zh'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/zh/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/zh/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/zh/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/zh/LC_MESSAGES/sane-lexmark_nscan.mo'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/zh_TW'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/zh_TW'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/zh_TW/LC_MESSAGES'
	chmod 755 '/usr/local/lexmark/unix_scan_drivers/share/locale/zh_TW/LC_MESSAGES'
	chown root:bin '/usr/local/lexmark/unix_scan_drivers/share/locale/zh_TW/LC_MESSAGES/sane-lexmark_nscan.mo'
	chmod 444 '/usr/local/lexmark/unix_scan_drivers/share/locale/zh_TW/LC_MESSAGES/sane-lexmark_nscan.mo'


	if [ -z "$RPM_INSTALL_PREFIX" ];then
	   RPM_INSTALL_PREFIX=/usr/local/lexmark
	fi

	$RPM_INSTALL_PREFIX/network-scan.link $RPM_INSTALL_PREFIX
	linpus_version()
	{
		#-- Set font.properties file.
		VERSION="`cat /etc/linpus-release | awk '{print $4}'`"

		cd ${RPM_INSTALL_PREFIX}/unix_scan_drivers/jre/lib

		FONTFILE_SRC="font.properties.zh_TW.Redhat"
		FONTFILE_TRGT="font.properties.zh_TW"

		if [ "${VERSION}" = "9.6" ]; then
			FONTFILE_SRC="fontconfig.RedHat.4.properties.src"
			FONTFILE_TRGT="fontconfig.properties"
		fi

		if [ -f "${FONTFILE_SRC}" ];then
			/bin/cp -f ${FONTFILE_SRC} ${FONTFILE_TRGT}
		fi
	}

	redflag_version()
	{
		#-- Set font.properties file.
		cd ${RPM_INSTALL_PREFIX}/unix_scan_drivers/jre/lib

		FONTFILE_SRC="font.properties.zh.Turbo"
		FONTFILE_TRGT="font.properties.zh"

		cat /etc/redflag-release | grep "6.0" >/dev/null 2>&1
		if [ $? -eq 0 ]; then
			FONTFILE_SRC="fontconfig.RedHat.properties.src"
			FONTFILE_TRGT="fontconfig.properties"

			if [ -f "${FONTFILE_SRC}" ];then
				cat ${FONTFILE_SRC} | \
				sed -e 's/zysong/rfdw/g' \
					-e 's/\/chinese\//\/zh_CN\//g' > ${FONTFILE_TRGT}
			fi
		else
		   if [ -f "${FONTFILE_SRC}" ];then
			  /bin/cp -f ${FONTFILE_SRC} ${FONTFILE_TRGT}
		   fi
		fi
	}

	redhat_version()
	{
		cat /etc/redhat-release | grep "Enterprise" >/dev/null 2>&1
		if [ $? -eq 0 ];then
			cat /etc/redhat-release | grep "release 4 " >/dev/null 2>&1
			if [ $? -eq 0 ];then
				cd ${RPM_INSTALL_PREFIX}/unix_scan_drivers/jre/lib
				if [ -f "font.properties.ja.Redhat8.0" ];then
					rm -f font.properties.ja
					cat font.properties.ja.Redhat8.0 | sed -e 's/\.ttf/-subst.ttf/g' > font.properties.ja
				fi
			fi
			cat /etc/redhat-release | grep "release 5" >/dev/null 2>&1
			if [ $? -eq 0 ];then
				cd ${RPM_INSTALL_PREFIX}/unix_scan_drivers/jre/lib
				if [ -f "font.properties.ko.Redhat" ];then
					mv -f font.properties.ko.Redhat font.properties.ko
					cat font.properties.ko | sed -e 's/\/fonts\/ko\/TrueType/\/fonts\/korean\/TrueType/g' > font.properties.ko.Redhat
				fi
				if [ -f "font.properties.ko.Redhat" ];then
					mv -f font.properties.ko.Redhat font.properties.ko
					cat font.properties.ko | sed -e 's/\/fonts\/ko\/TrueType/\/fonts\/korean\/TrueType/g' > font.properties.ko.Redhat
				fi
				if [ -f "font.properties.zh_CN.Redhat" ];then
					mv -f font.properties.zh_CN.Redhat font.properties.zh_CN
					cat font.properties.zh_CN | sed -e 's/\/fonts\/zh_CN\/TrueType/\/fonts\/chinese\/TrueType/g' > font.properties.zh_CN.Redhat
					/bin/cp -f font.properties.zh_CN.Redhat font.properties.zh_SG.Redhat
				fi
				if [ -f "font.properties.zh_TW.Redhat" ];then
					mv -f font.properties.zh_TW.Redhat font.properties.zh_TW
					cat font.properties.zh_TW | sed -e 's/\/fonts\/zh_TW\/TrueType\/bsmi00lp.ttf/\/fonts\/chinese\/TrueType\/uming.ttf/g' | awk '$0 ~ /bold/{print "#" $0 ;next}{print}'> font.properties.zh_TW.Redhat
					/bin/cp -f font.properties.zh_TW.Redhat font.properties.zh_HK.Redhat
				fi
			fi

			cat /etc/redhat-release | grep "release 6" >/dev/null 2>&1
			if [ $? -eq 0 ];then
				cd ${RPM_INSTALL_PREFIX}/unix_scan_drivers/jre/lib

				FONTFILE_TRGT="fontconfig.RedHat.6.0.properties"
				dump_rhel6_properties > ${FONTFILE_TRGT};

				FONTFILE_TRGT="fontconfig.RedHat.6.properties"
				dump_rhel6_properties > ${FONTFILE_TRGT};

				FONTFILE_TRGT="fontconfig.RedHat.properties"
				dump_rhel6_properties > ${FONTFILE_TRGT};
			fi
		fi
	}


	set_default_paper_size()
	{
		#-- Set default paper size to A4 if required.
		PAPER="A4"
		if [ "${LANG}" = "C" ] || [ "${LANG}" = "POSIX" ];then
				PAPER="LETTER"
		else
			echo "${LANG}" | egrep  "AW|BS|BB|BZ|BM|KY|CL|CO|CR|DM|DO|EC|SV|GF|GD|GP|GU|GT|GY|HT|HN|JM|MQ|MX|MS|NI|PA|PY|PR|KN|LC|VC|SR|TT|TC|VE|VG|VI|US|CA" >/dev/null 2>&1
			if [ $? -eq 0 ];then
					PAPER="LETTER"
			fi
		fi

		if [ "${PAPER}" != "LETTER" ];then
			CFILE="${RPM_INSTALL_PREFIX}/unix_scan_drivers/etc/${LIB_NAME}.conf"
			cat ${CFILE} | sed -e 's/^option original-size 0/option original-size 4/g' -e 's/Valid values are 0 - 21. Default value is 0/Valid values are 0 - 21. Default value is 4/g' > ${CFILE}.up
			rm -f ${CFILE}
			mv ${CFILE}.up ${CFILE}
		fi
	}

	setup_demon()
	{
		script='TEMP'

		#this is for fedora & suse
		if [ -d /etc/X11/xinit/xinitrc.d ]; then
			script='/etc/X11/xinit/xinitrc.d/99demon_nscan.sh'
		fi

		#this is for ubuntu
		if [ -d /etc/X11/Xsession.d ]; then
			script='/etc/X11/Xsession.d/99demon_nscan'
		fi

		#terminate previous running instance/s of device monitor
		killall -9 demond_nscan > /dev/null 2>&1

		if [ "$script" != "TEMP" ]; then
			# do nothing
			temp="TEMP";
		else
			return;
		fi

		#remove previous xsession script, if any
		rm -rf "$script"* > /dev/null 2>&1

		#copy demon script to xsession directory
		cp ${RPM_INSTALL_PREFIX}/unix_scan_drivers/bin/demon "$script"
		chmod 555 "$script"
		#chmod +s "$script"

		#exit from this routine; auto-start will not be done anymore
		#due to unresolved complications
		return;

		#get the username used to logged in to the
		#system by checking the USER environment variables
		user1=$USER
		user2=$SUDO_USER
		user3=$USERNAME
		username="root"
		if [ "$user1" != "root" ]; then
			username=$user1;
		elif [ "$user2" != "root" ]; then
			username=$user2;
		elif [ "$user3" != "root" ]; then
			username=$user3;
		fi

		#run device monitor
		#TODO: investigate other ways to run daemon
		#/bin/sh ${script}
		#echo "username: $username"
		if [ "$username" != "root" ]; then
			export demon_app="$script"
			#sudo echo "sudo -u $username /bin/sh $demon_app"
			sudo -u $username at -f $demon_app now + 1 min 2> /dev/null
			if [ $? -ne 0 ]; then
				at -f $script now + 1 min 2> /dev/null;
			fi
		else
			at -f $script now + 1 min 2> /dev/null;
		fi;
	}

	setup_weee()
	{
		if [ -d ${RPM_INSTALL_PREFIX}/docs ]; then
			temp="TEMP";
		else
			mkdir -p ${RPM_INSTALL_PREFIX}/docs
		fi;
		cp ${RPM_INSTALL_PREFIX}/unix_scan_drivers/docs/weee/EU_Waste_Electronic_Information.pdf ${RPM_INSTALL_PREFIX}/docs
	}

	show_weee()
	{

	cat <<- WEEE_TEXT

	EU waste electronics information
	********************************

	The WEEE logo signifies specific recycling programs and procedures for
	electronic products in countries of the European Union. We encourage
	the recycling of our products. If you have further questions about
	recycling options in European Union countries, please refer to the
	document listed below.

	  ${RPM_INSTALL_PREFIX}/docs/EU_Waste_Electronic_Information.pdf

	*******************************

	WEEE_TEXT

	}

	dump_rhel6_properties()
	{
	cat <<- RHEL6_PROPERTIES_TEXT

	version=1


	allfonts.chinese-cn-iso10646=-misc-zysong18030-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	allfonts.chinese-tw-iso10646=-arphic technology co.-ar pl mingti2l big5-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	allfonts.lucida=-b&h-lucidasans-medium-r-normal-sans-*-%d-*-*-p-*-iso8859-1

	serif.plain.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.plain.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.plain.latin-1=-b&h-lucidabright-medium-r-normal--*-%d-*-*-p-*-iso8859-1

	serif.bold.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.bold.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.bold.latin-1=-b&h-lucidabright-demibold-r-normal--*-%d-*-*-p-*-iso8859-1

	serif.italic.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.italic.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.italic.latin-1=-b&h-lucidabright-medium-i-normal--*-%d-*-*-p-*-iso8859-1

	serif.bolditalic.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.bolditalic.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	serif.bolditalic.latin-1=-b&h-lucidabright-demibold-i-normal--*-%d-*-*-p-*-iso8859-1

	sansserif.plain.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.plain.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.plain.latin-1=-b&h-lucidasans-medium-r-normal-sans-*-%d-*-*-p-*-iso8859-1

	sansserif.bold.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.bold.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.bold.latin-1=-b&h-lucidasans-bold-r-normal-sans-*-%d-*-*-p-*-iso8859-1

	sansserif.italic.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.italic.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.italic.latin-1=-b&h-lucidasans-medium-i-normal-sans-*-%d-*-*-p-*-iso8859-1

	sansserif.bolditalic.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.bolditalic.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	sansserif.bolditalic.latin-1=-b&h-lucidasans-bold-i-normal-sans-*-%d-*-*-p-*-iso8859-1

	monospaced.plain.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.plain.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.plain.latin-1=-b&h-lucidatypewriter-medium-r-normal-sans-*-%d-*-*-m-*-iso8859-1

	monospaced.bold.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.bold.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.bold.latin-1=-b&h-lucidatypewriter-bold-r-normal-sans-*-%d-*-*-m-*-iso8859-1

	monospaced.italic.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.italic.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.italic.latin-1=-b&h-lucidatypewriter-medium-i-normal-sans-*-%d-*-*-m-*-iso8859-1

	monospaced.bolditalic.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.bolditalic.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	monospaced.bolditalic.latin-1=-b&h-lucidatypewriter-bold-i-normal-sans-*-%d-*-*-m-*-iso8859-1

	dialog.plain.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.plain.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.plain.latin-1=-b&h-lucidasans-medium-r-normal-sans-*-%d-*-*-p-*-iso8859-1

	dialog.bold.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.bold.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.bold.latin-1=-b&h-lucidasans-bold-r-normal-sans-*-%d-*-*-p-*-iso8859-1

	dialog.italic.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.italic.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.italic.latin-1=-b&h-lucidasans-medium-i-normal-sans-*-%d-*-*-p-*-iso8859-1

	dialog.bolditalic.japanese-iso10646=-misc-kochi gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.bolditalic.korean-iso10646=-misc-baekmuk gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialog.bolditalic.latin-1=-b&h-lucidasans-bold-i-normal-sans-*-%d-*-*-p-*-iso8859-1

	dialoginput.plain.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.plain.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.plain.latin-1=-b&h-lucidatypewriter-medium-r-normal-sans-*-%d-*-*-m-*-iso8859-1

	dialoginput.bold.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.bold.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.bold.latin-1=-b&h-lucidatypewriter-bold-r-normal-sans-*-%d-*-*-m-*-iso8859-1

	dialoginput.italic.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.italic.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.italic.latin-1=-b&h-lucidatypewriter-medium-i-normal-sans-*-%d-*-*-m-*-iso8859-1

	dialoginput.bolditalic.japanese-iso10646=-misc-kochi mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.bolditalic.korean-iso10646=-misc-baekmuk batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1
	dialoginput.bolditalic.latin-1=-b&h-lucidatypewriter-bold-i-normal-sans-*-%d-*-*-m-*-iso8859-1


	sequence.allfonts=latin-1
	sequence.allfonts.UTF-8.ko.KR=latin-1,korean-iso10646
	sequence.allfonts.UTF-8.ja.JP=latin-1,japanese-iso10646
	sequence.allfonts.UTF-8.zh.CN=latin-1,chinese-cn-iso10646
	sequence.allfonts.UTF-8.zh.TW=latin-1,chinese-tw-iso10646
	sequence.allfonts.UTF-8.zh.HK=latin-1,chinese-tw-iso10646
	sequence.fallback=lucida,chinese-tw-iso10646,chinese-cn-iso10646,japanese-iso10646,korean-iso10646


	exclusion.japanese-iso10646=2200-22ef,2701-27be,20a0-20aa,2153-215f,2166-2168,216a-216f,2173-2182


	filename.-arphic_technology_co.-ar_pl_mingti2l_big5-medium-r-normal--*-%d-*-*-c-*-iso10646-1=/usr/share/fonts/cjkuni-uming/uming.ttc
	filename.-misc-baekmuk_batang-medium-r-normal--*-%d-*-*-c-*-iso10646-1=/usr/share/fonts/un-core/UnDotum.ttf
	filename.-misc-baekmuk_gulim-medium-r-normal--*-%d-*-*-c-*-iso10646-1=/usr/share/fonts/un-core/UnDotum.ttf
	filename.-misc-kochi_gothic-medium-r-normal--*-%d-*-*-c-*-iso10646-1=/usr/share/fonts/vlgothic/VL-Gothic-Regular.ttf
	filename.-misc-kochi_mincho-medium-r-normal--*-%d-*-*-c-*-iso10646-1=/usr/share/fonts/ipa-mincho/ipam.ttf
	filename.-misc-zysong18030-medium-r-normal--*-%d-*-*-c-*-iso10646-1=/usr/share/fonts/cjkuni-uming/uming.ttc
	filename.-b&h-lucidasans-medium-r-normal-sans-*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaSansRegular.ttf
	filename.-b&h-lucidabright-medium-r-normal--*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaBrightRegular.ttf
	filename.-b&h-lucidabright-demibold-r-normal--*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaBrightDemiBold.ttf
	filename.-b&h-lucidabright-medium-i-normal--*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaBrightItalic.ttf
	filename.-b&h-lucidabright-demibold-i-normal--*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaBrightDemiItalic.ttf
	filename.-b&h-lucidasans-bold-r-normal-sans-*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaSansDemiBold.ttf
	filename.-b&h-lucidasans-medium-i-normal-sans-*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaSansRegular.ttf
	filename.-b&h-lucidasans-bold-i-normal-sans-*-%d-*-*-p-*-iso8859-1=\$JRE_LIB_FONTS/LucidaSansDemiBold.ttf
	filename.-b&h-lucidatypewriter-medium-r-normal-sans-*-%d-*-*-m-*-iso8859-1=\$JRE_LIB_FONTS/LucidaTypewriterRegular.ttf
	filename.-b&h-lucidatypewriter-bold-r-normal-sans-*-%d-*-*-m-*-iso8859-1=\$JRE_LIB_FONTS/LucidaTypewriterBold.ttf
	filename.-b&h-lucidatypewriter-medium-i-normal-sans-*-%d-*-*-m-*-iso8859-1=\$JRE_LIB_FONTS/LucidaTypewriterRegular.ttf
	filename.-b&h-lucidatypewriter-bold-i-normal-sans-*-%d-*-*-m-*-iso8859-1=\$JRE_LIB_FONTS/LucidaTypewriterBold.ttf

	awtfontpath.chinese-tw-iso10646=/usr/share/fonts/cjkuni-uming
	awtfontpath.chinese-cn-iso10646=/usr/share/fonts/cjkuni-uming
	awtfontpath.japanese-iso10646=/usr/share/fonts/vlgothic
	awtfontpath.korean-iso10646=/usr/share/fonts/un-core

	RHEL6_PROPERTIES_TEXT
	}

	echo
	LIB_NAME=lexmark_nscan
	LIB_DEV=lexmark-scanner
	RPM_PREFIX=lexmark

	if [ "${RPM_PREFIX}" = "lexmark" ];then
		PLINK="/usr/lexscan"
	elif [ "${RPM_PREFIX}" = "dell" ];then
		PLINK="/usr/dellscan"
	else
		PLINK="/usr/mfpscan"
	fi




	if [ -f "/etc/sane.d/dll.conf" ];then
		egrep "^${LIB_NAME}" /etc/sane.d/dll.conf >/dev/null 2>&1
		if [ $? -ne 0 ];then
			#-- echo "    Add: [ ${LIB_NAME} ] to /etc/sane.d/dll.conf"
			echo "${LIB_NAME}" >> /etc/sane.d/dll.conf
		fi
	fi

	IMAGE="${RPM_INSTALL_PREFIX}/unix_scan_drivers/share/icons/logo.xpm"
	if [ -d "/usr/share/sane/xsane" -a -f "${IMAGE}" ];then
		#-- echo "Install: /usr/share/sane/xsane/Lexmark-logo.xpm"
		#-- cp ${IMAGE} /usr/share/sane/xsane/Lexmark-logo.xpm
		if [ "${RPM_PREFIX}" = "lexmark" ];then
			cp ${IMAGE} /usr/share/sane/xsane/Lexmark-logo.xpm
		elif [ "${RPM_PREFIX}" = "dell" ];then
			cp ${IMAGE} /usr/share/sane/xsane/Dell-logo.xpm
		fi
	fi

	if [ -f "/etc/linpus-release" ];then
		linpus_version
	fi
	if [ -f "/etc/redflag-release" ];then
		redflag_version
	fi
	if [ -f "/etc/redhat-release" ];then
		redhat_version
	fi

	set_default_paper_size


	if [ "${RPM_PREFIX}" = "lexmark" ];then

		setup_weee
		show_weee
	fi

	if [ "`uname -m`" = "x86_64" ];then
		mkdir -p /usr/lib/sane
		ln -s ${RPM_INSTALL_PREFIX}/unix_scan_drivers/lib/sane/libsane* /usr/lib/sane/ 1> /dev/null 2>&1
		if [ -d /usr/lib/x86_64-linux-gnu ]; then
			mkdir -p /usr/lib/x86_64-linux-gnu/sane
			ln -s ${RPM_INSTALL_PREFIX}/unix_scan_drivers/lib/sane/libsane* /usr/lib/x86_64-linux-gnu/sane/ 1> /dev/null 2>&1
		fi
	else
		if [ -d /usr/lib/i386-linux-gnu ]; then
			mkdir -p /usr/lib/i386-linux-gnu/sane
			ln -s ${RPM_INSTALL_PREFIX}/unix_scan_drivers/lib/sane/libsane* /usr/lib/i386-linux-gnu/sane/ 1> /dev/null 2>&1
		fi
	fi

	echo "    Notes:"
	echo "      a.  A complete user guide is available in HTML format."
	echo
	echo "          ${PLINK}/docs/ug/en/index.html"
	echo
	echo "      b.  If your system has an enabled firewall, the driver may"
	echo "          not function correctly.  You can either disable your firewall"
	echo "          or open the required scanning ports; tcp:9751-9760.  See the"
	echo "          user guide for more details."
	echo
	echo "      c.  If your system is already USB-connected to the scanner before"
	echo "          installation was completed, this application may not function"
	echo "          correctly.  Please detach and re-attach the USB cable."
	echo
	echo "      d.  Log off, and then log on to your computer before scanning from"
	echo "          the device."
	echo
	echo "Installation Complete."
	echo
}

post_upgrade() {
	post_install
}

pre_remove() {
	if [ -z "$RPM_INSTALL_PREFIX" ];then
		RPM_INSTALL_PREFIX=/usr/local/lexmark
	fi

	if [ "$1" = "remove" -o "$1" = "0" ];then
		$RPM_INSTALL_PREFIX/network-scan.unlink 3.7.0.0
	fi

	# If above command fails, remove files manually
#	rm /etc/sane.d/lexmark_nscan.conf
#	rm /etc/sane.d/scan*.conf
#	rm /etc/udev/rules.d/99-lexmark.rules
#	rm /usr/lexscan
#	rm -rf /usr/lib64/sane/libsane-lexmark_nscan*
#	rm -rf /usr/local/lexmark
#	rm /usr/share/locale/*/LC_MESSAGES/sane-lexmark_nscan.mo

	#terminate running instance/s of device monitor
	killall -9 demond_nscan > /dev/null 2>&1

	if [ -d /etc/X11/Xsession.d ]; then
		if [ ! -f /etc/X11/Xsession.d/99demon_nscan ]; then
			rm /etc/X11/Xsession.d/99demon_nscan > /dev/null 2>&1
		fi
	fi
}

