post_install() {
echo -e '\n \033[1m\033[32m\e[4mFor on-exit directory changing, put the following lines into your bash/zshrc\e[0m :\e[36m

  lfcd(){ \
    tmp="$(mktemp)" ; /usr/share/lfp/lfp  -last-dir-path="$tmp" "$@"
    [ -f "$tmp" ] && dir="$(cat "$tmp")" && 
      rm -f "$tmp" >/dev/null 2>&1
    [ -d "$dir" ] && [ "$dir" != "$(pwd)" ] && 
      cd "$dir" ; }
  \e[0m

 \e[33mAnd use "lfcd" instead of "lfp"\e[0m\n\n\n'
 }
