post_install() {
    echo "    Set the PHONE_MAC_ADDRESS environment variable to your AirPods'"
    echo "    Bluetooth MAC address using 'export' (bash) or 'set -gx' (fish)."
    echo ""
    echo "    Make sure that your device is already paired before running"
    echo "    Librepods, as it causes issues with pairing during runtime."

    mkdir -p "$HOME/.config/wireplumber/wireplumber.conf.d"

    cd "$HOME/.config/wireplumber/wireplumber.conf.d" || return

    if [ ! -f "51-bluez-avrcp.conf" ]; then
        cat >"51-bluez-avrcp.conf" <<EOF
monitor.bluez.properties = {
  # Enable dummy AVRCP player for proper media control support
  # This is required for AirPods and other devices to send play/pause/skip commands
}
EOF
        systemctl --user restart wireplumber
    fi
}
