post_install() {
	cat << 'EOM'
==> You can set the address and port of your Linbox Converter Server in /etc/lbx-converter.conf"
==> In order to use the lbx-view program, you will need to install the xpdf...
==> In order to use the lbx-view-web program, you will need to install the
firefox package...

... or hack the scripts (;

EOM
}

post_upgrade() {
/bin/true
}

pre_remove() {
/bin/true
}

op=$1
shift

$op "$@"
