SEARCH_DIR("/lib64/")
SEARCH_DIR("/lib/")
SEARCH_DIR("/usr/lib64/")
SEARCH_DIR("/usr/lib/")
SEARCH_DIR("/usr/lib/gcc/x86_64-pc-linux-gnu/13.1.1/")
SEARCH_DIR("/usr/lib/lazarus/components/tdbf/lib/x86_64-linux/qt5/")
SEARCH_DIR("/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/")
SEARCH_DIR("/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/")
SEARCH_DIR("/usr/lib/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/")
SEARCH_DIR("/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/")
SEARCH_DIR("/usr/lib/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/")
SEARCH_DIR("/usr/lib/lazarus/lcl/units/x86_64-linux/")
SEARCH_DIR("/usr/lib/lazarus/components/freetype/lib/x86_64-linux/")
SEARCH_DIR("/usr/lib/lazarus/components/buildintf/units/x86_64-linux/")
SEARCH_DIR("/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/")
SEARCH_DIR("/usr/lib/lazarus/packager/units/x86_64-linux/")
SEARCH_DIR("./")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/httpd22/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-extra/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/gdbm/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fpgtk/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-console/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-json/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/openssl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/odata/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/gmp/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/proj4/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/openal/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/dbus/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rsvg/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/utils-pas2js/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libgc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/mad/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/pastojs/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libmicrohttpd/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-registry/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-passrc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/x11/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/newt/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/regexpr/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/googleapi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/cdrom/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/oggvorbis/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/modplug/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libgd/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/users/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/ptc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/chm/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/dts/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/bfd/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/ncurses/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fpmkunit/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/utmp/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/gtk2/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libxml2/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libvlc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fv/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libffi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libsee/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/gdbint/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fppkg/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/oracle/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/ggi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/numlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/vcl-compat/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/mysql/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/a52/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fastcgi/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/httpd24/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/ldap/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-net/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/opencl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-sdo/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/zlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libcurl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-web/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/gtk1/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/iconvenc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fpindexer/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-generics/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/gnutls/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/postgres/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libmagic/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/sqlite/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-pdf/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/symbolic/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/xforms/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-extra/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/hash/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-stl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/hermes/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/syslog/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/pthreads/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/pxlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/tplylib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libenet/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/imagemagick/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/unzip/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/opengl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libfontconfig/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/svgalib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-fpcunit/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/pcap/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/tcl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/graph/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/dblib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libtar/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-js/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/imlib/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fftw/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/odbc/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/gnome1/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-unicode/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/uuid/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-sound/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libusb/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-process/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/ibase/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-report/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libpng/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-res/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/jni/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-objpas/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/cairo/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/bzip2/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/lua/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/webidl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/libcups/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/sdl/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-async/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/aspell/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/zorba/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/opengles/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/units/x86_64-linux/")
SEARCH_DIR("/usr/lib/fpc/3.2.2/")
INPUT(
/lib64/crti.o
/usr/lib/gcc/x86_64-pc-linux-gnu/13.1.1/crtbeginS.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/si_c.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/abitag.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/htmlbuilder.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/htmlbuilder.or
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/system.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/cmem.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/lnfodwrf.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/exeinfo.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/strings.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/fpintres.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/objpas.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/cthreads.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/interfaces.o
/usr/lib/lazarus/lcl/units/x86_64-linux/forms.o
/usr/lib/lazarus/components/tdbf/lib/x86_64-linux/qt5/dbflaz.o
/usr/lib/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/datetimectrls.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/main.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/db_helpers.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/db_insertdemo.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/db_create_tables.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/replacers.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/editor_in_window.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/editor_css.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/editor_js.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/css_props_dlg.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/const_for_app.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/types_for_app.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/selectortagspages.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/selectors_for_menu.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/renderhtml.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/linux.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/baseunix.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/unix.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/unixtype.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/initc.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/dl.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/unixutil.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/ctypes.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/cwstring.o
/usr/lib/lazarus/lcl/units/x86_64-linux/interfacebase.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/dynlibs.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/unixcp.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/types.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/classes.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/sysutils.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/math.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpimage.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclproc.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lcltype.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lmessages.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclplatformdef.o
/usr/lib/lazarus/lcl/units/x86_64-linux/intfgraphics.o
/usr/lib/lazarus/lcl/units/x86_64-linux/themes.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazutf8.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/integerlist.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazutilities.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazloggerbase.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/graphtype.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/graphmath.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/errors.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/sysconst.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/typinfo.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/rtlconsts.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/laz_avl_tree.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazfileutils.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazmethodlist.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/laztracer.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclstrconsts.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazutilsstrconsts.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/fpcadds.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-objpas/strutils.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/gettext.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazclasses.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpreadbmp.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpwritebmp.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/bmpcomn.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpreadpng.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpwritepng.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpreadtiff.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpwritetiff.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fptiffcmn.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclversion.o
/usr/lib/lazarus/lcl/units/x86_64-linux/icnstypes.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpimgcmn.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/pngcomn.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/zstream.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/zbase.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/gzio.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/hash/crc.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/zdeflate.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/zinflate.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/trees.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/adler.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/infblock.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/infutil.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/infcodes.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/inftrees.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/paszlib/inffast.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazversion.o
/usr/lib/lazarus/lcl/units/x86_64-linux/graphics.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclintf.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/contnrs.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpcanvas.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpreadpnm.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpwritepnm.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpreadjpeg.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpwritejpeg.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpreadgif.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lresources.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclrescache.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsreferences.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/clipping.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jpeglib.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdapimin.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdatasrc.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdapistd.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jmorecfg.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdeferr.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jinclude.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jerror.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jmemmgr.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdmarker.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdinput.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcomapi.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jutils.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jmemnobs.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdmaster.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdcolor.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdsample.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdpostct.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jddctmgr.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdphuff.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdhuff.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdcoefct.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdmainct.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jquant1.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jquant2.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdmerge.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdct.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jidctfst.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jidctint.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jidctflt.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jidctred.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcapistd.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcapimin.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jdatadst.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcparam.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcinit.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcmarker.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcphuff.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jchuff.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcmaster.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jccolor.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcsample.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcprepct.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcdctmgr.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jccoefct.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jcmainct.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jfdctint.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jfdctfst.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/pasjpeg/jfdctflt.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-objpas/variants.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazconfigstorage.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/dynqueue.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-objpas/varutils.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/avglvltree.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazdbglog.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/syncobjs.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/fileutil.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/utf8process.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazsysutils.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/maps.o
/usr/lib/lazarus/lcl/units/x86_64-linux/tmschema.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/fgl.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/masks.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-process/process.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-process/pipes.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/termio.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtint.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qt5.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclmessageglue.o
/usr/lib/lazarus/lcl/units/x86_64-linux/controls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/extctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/dialogs.o
/usr/lib/lazarus/lcl/units/x86_64-linux/stdctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/graphutil.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazstringutils.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtx11dummywidget.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtproc.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclclasses.o
/usr/lib/lazarus/lcl/units/x86_64-linux/messages.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/custapp.o
/usr/lib/lazarus/lcl/units/x86_64-linux/menus.o
/usr/lib/lazarus/lcl/units/x86_64-linux/customtimer.o
/usr/lib/lazarus/lcl/units/x86_64-linux/actnlist.o
/usr/lib/lazarus/lcl/units/x86_64-linux/clipbrd.o
/usr/lib/lazarus/lcl/units/x86_64-linux/helpintfs.o
/usr/lib/lazarus/lcl/units/x86_64-linux/imglist.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/uitypes.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/singleinstance.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wslclclasses.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fpimgcanv.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/fppixlcanv.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/pixtools.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-image/ellipses.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsimglist.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsproc.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsfactory.o
/usr/lib/lazarus/lcl/units/x86_64-linux/propertystorage.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/rttiutils.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsmenus.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazlogger.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/chm/fasthtmlparser.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-objpas/system.uitypes.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wscontrols.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsforms.o
/usr/lib/lazarus/lcl/units/x86_64-linux/popupnotifier.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/textstrings.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/extendedstrings.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsstdctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsextctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/buttons.o
/usr/lib/lazarus/lcl/units/x86_64-linux/buttonpanel.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lcltaskdialog.o
/usr/lib/lazarus/lcl/units/x86_64-linux/imagelistcache.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsbuttons.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsdialogs.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lazcanvas.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lazregions.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtobjects.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/x11/x.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/x11/xlib.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/x11/xkb.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/x11/xkblib.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtcaret.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtthemes.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsfactory.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwidgets.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtsystemtrayicon.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/x11/xi.o
/usr/lib/lazarus/lcl/units/x86_64-linux/comctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/toolwin.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wscomctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wstoolwin.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtprivate.o
/usr/lib/lazarus/lcl/units/x86_64-linux/calendar.o
/usr/lib/lazarus/lcl/units/x86_64-linux/spin.o
/usr/lib/lazarus/lcl/units/x86_64-linux/grids.o
/usr/lib/lazarus/lcl/units/x86_64-linux/checklst.o
/usr/lib/lazarus/lcl/units/x86_64-linux/rubberband.o
/usr/lib/lazarus/lcl/units/x86_64-linux/pairsplitter.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wscalendar.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsspin.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/htmldefs.o
/usr/lib/lazarus/lcl/units/x86_64-linux/maskedit.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/dynamicarray.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlcfg.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lcsvutils.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/lazfilecache.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/laz2_dom.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlread.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlwrite.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/laz2_xmlutils.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/uriparser.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsgrids.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wschecklst.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsdesigner.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wspairsplitter.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsbuttons.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwscalendar.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwschecklst.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwscomctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwscontrols.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsdialogs.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsextctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsforms.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsmenus.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwspairsplitter.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsspin.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsstdctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsgrids.o
/usr/lib/lazarus/lcl/units/x86_64-linux/qt5/qtwsdesigner.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-objpas/dateutils.o
/usr/lib/lazarus/lcl/units/x86_64-linux/extdlgs.o
/usr/lib/lazarus/lcl/units/x86_64-linux/calcform.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsextdlgs.o
/usr/lib/lazarus/components/tdbf/lib/x86_64-linux/qt5/registerdbf.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf.o
/usr/lib/lazarus/packager/units/x86_64-linux/lazaruspackageintf.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/propedits.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/macrointf.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/db.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_common.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_dbffile.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_parser.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_prsdef.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_cursor.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_fields.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_pgfile.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_idxfile.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-objpas/fmtbcd.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/maskutils.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbconst.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_wtil.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_memo.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_str.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_collate.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_prscore.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_prssupp.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_lang.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/dbf_idxcur.o
/usr/lib/lazarus/lcl/units/x86_64-linux/editbtn.o
/usr/lib/lazarus/lcl/units/x86_64-linux/valedit.o
/usr/lib/lazarus/lcl/units/x86_64-linux/filectrl.o
/usr/lib/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/checkboxthemed.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/stringhashlist.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/objinspstrconsts.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/propeditutils.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/frmselectprops.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/stringspropeditdlg.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/keyvalpropeditdlg.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/collectionpropeditform.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/filefilterpropeditor.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/pagespropeditdlg.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/idewindowintf.o
/usr/lib/lazarus/lcl/units/x86_64-linux/groupededit.o
/usr/lib/lazarus/lcl/units/x86_64-linux/calendarpopup.o
/usr/lib/lazarus/lcl/units/x86_64-linux/timepopup.o
/usr/lib/lazarus/lcl/units/x86_64-linux/shellctrls.o
/usr/lib/lazarus/lcl/units/x86_64-linux/wsshellctrls.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/ideimagesintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/ideoptionsintf.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/lazideintf.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lazhelphtml.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/baseideintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/compoptsintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/projectintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/ideexterntoolintf.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/ideopteditorintf.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/srceditorintf.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lazhelpintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/macrodefintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/newitemintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/projpackintf.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/buildstrconsts.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/editorsyntaxhighlighterdef.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/idecommands.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/texttools.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/formeditingintf.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/objectinspector.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/idedialogs.o
/usr/lib/lazarus/components/buildintf/units/x86_64-linux/lazmsgworker.o
/usr/lib/lazarus/components/lazutils/lib/x86_64-linux/compwriterpas.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/componenteditors.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/unitresources.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/lazstringgridedit.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/checklistboxeditordlg.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/checkgroupeditordlg.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/componentreg.o
/usr/lib/lazarus/lcl/units/x86_64-linux/arrow.o
/usr/lib/lazarus/lcl/units/x86_64-linux/industrialbase.o
/usr/lib/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/treefilteredit.o
/usr/lib/lazarus/components/lazcontrols/lib/x86_64-linux/qt5/listfilteredit.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/idehelpintf.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/componenttreeview.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/oifavoriteproperties.o
/usr/lib/lazarus/components/ideintf/units/x86_64-linux/qt5/changeparentdlg.o
/usr/lib/lazarus/lcl/units/x86_64-linux/lclmemmanager.o
/usr/lib/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/datetimepicker.o
/usr/lib/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/dbdatetimepicker.o
/usr/lib/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/calcontrolwrapper.o
/usr/lib/lazarus/components/datetimectrls/lib/x86_64-linux/qt5/lclcalwrapper.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-extra/clocale.o
/usr/lib/lazarus/lcl/units/x86_64-linux/dbctrls.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/bufdataset.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/sqlite3conn.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/sqldb.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synhighlighterhtml.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedit.o
/usr/lib/lazarus/lcl/units/x86_64-linux/dbgrids.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/blcksock.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl-extra/sockets.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/synautil.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/synaip.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/synsock.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/ftpsend.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/regexpr/regexpr.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/httpsend.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/bufdataset_parser.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/sqlite/sqlite3dyn.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/sqlscript.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-db/sqltypes.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedittypes.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedithighlighter.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedithighlighterxmlbase.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedithighlighterfoldbase.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditstrconst.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditkeycmds.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-registry/registry.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-base/inifiles.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedittextbase.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-registry/xmlreg.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/dom.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/xmlread.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/xmlwrite.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/xmlutils.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/dtdmodel.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/xmlreader.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-xml/xmltextreader.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmiscprocs.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/lazsynedittext.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/lazsynimmbase.o
/usr/lib/lazarus/lcl/units/x86_64-linux/stdactns.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditsearch.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmousecmds.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditpointclasses.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synbeautifier.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarks.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkup.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkuphighall.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkupbracket.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkupwordgroup.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkupctrlmouselink.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkupspecialline.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkupselection.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmarkupspecialchar.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedittextbuffer.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditlines.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedittexttrimmer.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedittexttabexpander.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedittextdoublewidthchars.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditfoldedview.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syngutterbase.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syngutter.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditmiscclasses.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/lazsyntextarea.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syntextdrawer.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synedittextbidichars.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synguttercodefolding.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syngutterchanges.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syngutterlinenumber.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synguttermarks.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syngutterlineoverview.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/lazsyneditmousecmdstypes.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/synafpc.o
/home/artem/HTMLBUILDER/lib/x86_64-linux/synacode.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/fcl-net/netdb.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syncompletion.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/character.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/syneditplugins.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/unicodedata.o
/usr/lib/fpc/3.2.2/units/x86_64-linux/rtl/unicodenumtable.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synhighlightercss.o
/usr/lib/lazarus/components/synedit/units/x86_64-linux/qt5/synhighlighterjscript.o
)
INPUT(
-l-L/usr/lib -lQt5
-lpthread
-ldl
-lQt5Pas
-lX11
)
GROUP(
-lc
)
INPUT(
/usr/lib/gcc/x86_64-pc-linux-gnu/13.1.1/crtendS.o
/lib64/crtn.o
)
SECTIONS
{
  .fpcdata           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
  .threadvar : { *(.threadvar .threadvar.* .gnu.linkonce.tv.*) }
}
INSERT AFTER .data;
