# Colors
_g='\e[1;33m' # Bold Yellow (Headers & Symbols)
_b='\e[1;34m' # Bold Blue (Commands)
_r='\e[0m'    # Reset

post_install() {
    echo ""
    echo -e "${_g}:: ARCTIS MANAGER: INITIAL SETUP${_r}"
    echo -e "${_g}::${_r} -----------------------------------------------------------------------"
    echo -e "${_g}::${_r} This package make all the initial setup, you shouldn't have to run anything by default."
    echo -e "${_g}::${_r} -----------------------------------------------------------------------"
    echo ""
}

post_upgrade() {
    echo ""
    echo -e "${_g}:: ARCTIS MANAGER: UPDATE COMPLETED${_r}"
    echo -e "${_g}::${_r} -----------------------------------------------------------------------"
    echo -e "${_g}::${_r} This package make all the initial setup, you shouldn't have to run anything by default."
    echo -e "${_g}::${_r} "
    echo -e "${_g}::${_r} Some user files may remain from previous versions of the package."
	if [ -e ~/.config/systemd/user/arctis-manager.service ]; then
		echo -e "${_g}::${_r} ${_b}rm ~/.config/systemd/user/arctis-manager.service${_r}"
	fi
    echo -e "${_g}::${_r} -----------------------------------------------------------------------"
    echo ""
}

post_remove() {
    echo ""
    echo -e "${_g}:: ARCTIS MANAGER: FINAL CLEANUP${_r}"
    echo -e "${_g}::${_r} -----------------------------------------------------------------------"
    echo -e "${_g}::${_r} The package has been removed, but some user files may remain."
    echo -e "${_g}::${_r} To fully clean up, run these as your normal user:"
    echo -e "${_g}::${_r}"
    echo -e "${_g}::${_r} 1. Stop and disable the service:"
    echo -e "${_g}::${_r}    ${_b}systemctl --user disable --now arctis-manager${_r}"
    echo -e "${_g}::${_r}    ${_b}rm ~/.config/systemd/user/arctis-manager.service${_r}"
    echo -e "${_g}::${_r}"
    echo -e "${_g}::${_r} 2. Remove config files:"
    echo -e "${_g}::${_r}    ${_b}rm -rf ~/.config/arctis_manager${_r}"
    echo -e "${_g}::${_r}"
    echo -e "${_g}::${_r} 3. Remove udev rules:"
    echo -e "${_g}::${_r}    ${_b}sudo rm -f /etc/udev/rules.d/91-steelseries-arctis.rules${_r}"
    echo -e "${_g}::${_r}    ${_b}sudo rm -f /usr/lib/udev/rules.d/91-steelseries-arctis.rules${_r}"
    echo -e "${_g}::${_r} -----------------------------------------------------------------------"
    echo ""
}
