#!/usr/bin/env bash

# Update changes
function _5_2_2_2_changes() {
    echo ":: Update 5.2.2-2: A new command line option was added: add page_alloc.shuffle=1"
}

function _5_2_9_6_changes() {
    echo ":: Update 5.2.9-6: Microcode is no longer builtin. See https://wiki.archlinux.org/index.php/Microcode"
}


# Standard methods
function post_upgrade() {
    local version upgrades=(
        "5.2.2-2"
        "5.2.9-6"
    )
    
    for version in "${upgrades[@]}"; do
        if [[ "$(vercmp "${version}" "$2")" -eq "1" ]]; then
            echo ":: Displaying update notices for '${version}'"
            "_${version//[.-]/_}_changes"
        fi
    done
}

function post_install() {
    echo ":: Clear Linux bundles a custom command line which must be applied manually on other distributions."
    echo "   This is their default command line:"
    echo "   quiet console=tty0 console=ttyS0,115200n8 cryptomgr.notests initcall_debug"
    echo "   intel_iommu=igfx_off kvm-intel.nested=1 no_timer_check noreplace-smp"
    echo "   page_alloc.shuffle=1 rcupdate.rcu_expedited=1"
    echo "   rootfstype=ext4,btrfs,xfs,f2fs tsc=reliable rw"
}
