# Colored makepkg-like functions

note() {
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note "要传递给 electron 的自定义参数应该写在: ~/.config/qq-electron-flags.conf"
    note "通过此包安装的 QQ 在下载文件时，应使用「另存为」，另存为到「下载」文件夹，而不要直接点击「下载」。"
}

post_upgrade() {
    post_install
}
