.TH lip 1 "2025-01-01" "lip 0.24.0" "lip User Manual"
.SH NAME
lip \- A general package installer
.SH SYNOPSIS
.B lip
[\fIglobal options\fR] \fBcommands\fR [\fIcommand options\fR] [\fIarguments\fR]...
.SH DESCRIPTION
lip is a general package installer. You can use lip to install packages from any Git repository.
.SH COMMANDS
.TP
\fBcache\fP
Inspect and manage lip's cache.
.TP
\fBconfig\fP
Manage configuration.
.TP   
\fBinstall\fP
Install a tooth.
.TP   
\fBuninstall\fP
Uninstall a tooth.
.TP
\fBlist\fP
Lists installed teeth.
.TP
\fBshow\fP
Shows information about installed teeth.
.TP
\fBfreeze\fP
Generates specifiers.txt.
.TP
\fBtooth\fP
Maintains a tooth.
.TP
\fBhelp, h\fP
Shows a list of commands or help for one command.
.SH GLOBAL OPTIONS
.TP
\fB--verbose, -v\fP
Shows verbose output.
.TP
\fB--quiet, -q\fP
Shows only errors.
.TP
\fB--no-color\fP
Disable color output.
.TP
\fB--help, -h\fP
Shows the help.
.TP
\fB--verison, -V\fP
Prints the lip version.
.SH BUGS
.TP
Submit bug reports and request features online at:\fP
<\fIhttps://github.com/futrime/lip/issues\fR>
.SH SEE ALSO
.TP
Source at:\fP
<\fIhttps://github.com/futrime/lip\fR>
.TP
Online documentation at:\fP
<\fIhttps://futrime.github.io/lip/\fR>
.SH COPYRIGHT
Copyright 2023 futrime <\fIhttps://github.com/futrime\fR>.
.SH AUTHOR
Written by Huang FTS427 <\fIhttps://github.com/FTS427\fR>.