# llama.cpp-sycl.install

post_install() {
    echo "========================================================================"
    echo " Installation successful!"
    echo " Please read the GitHub README at:"
    echo " https://github.com/cantosun99/llama.cpp-sycl"
    echo " The use of llama.cpp with the SYCL backend has some unique quirks."
    echo "========================================================================"
}

# Trigger the same success message on package upgrades
post_upgrade() {
    post_install
}
