#!/bin/bash

note() {
    printf "${blue}==>${yellow} NOTE:${bold} %s${all_off}\n" "${1}"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note "Custom flags should be put directly in: ~/.config/lm-studio-flags.conf"

    chmod 4755 '/opt/LM-Studio/chrome-sandbox' || true

    if hash update-mime-database 2>/dev/null; then
        update-mime-database /usr/share/mime || true
    fi

    if hash update-desktop-database 2>/dev/null; then
        update-desktop-database /usr/share/applications || true
    fi
}
