# Maintainer: Dimitris Kiziridis <ragouel at outlook dot com>

post_install() {
  echo "Creating dedicated system user 'lms'"
  useradd -M -U lms
  echo "Creating directory /var/lms"
  install -d /var/lms
  echo "Changing directory ownership to 'lms'"
  chown lms:lms /var/lms
}

post_remove() {
  echo "Removing dedicated system user 'lms'"
  systemctl stop lms.service >> /dev/null
  userdel lms
  echo "Removing directory /var/lms"
  rm -rf /var/lms
}