#!/bin/sh

# determine the real invoking user/home
_user="${SUDO_USER:-$(logname 2>/dev/null)}"
_home="$(getent passwd "$_user" | cut -d: -f6)"
_data_home="${XDG_DATA_HOME:-$_home/.local/share}"

# paths and expected version
steam_dll="$_data_home/Steam/steamapps/common/Lossless Scaling/Lossless.dll"
required_version="3.2.0.0" # latest version

user_manifest="$_data_home/vulkan/implicit_layer.d/VkLayer_LS_frame_generation.json"
user_library="$_home/.local/lib/liblsfg-vk.so"

get_version() {
    case "$1" in
        1.6.0.0) echo "1.6" ;;
        3.0.0.2) echo "2.13" ;;
        3.0.0.1) echo "3.0" ;;
        3.1.0.2) echo "3.1" ;;
        *)        echo "$1" ;;  # fallback to productversion if unmapped
    esac
}

# extracts the ProductVersion string from the dll
get_product_version() {
    local file="$1"
    strings -e l "$file" 2>/dev/null | awk '/^ProductVersion$/ { getline; print; exit }'
}

check_steam_install() {
    if [ ! -f "$steam_dll" ]; then
        echo "==============================================================================================="
        echo "==  WARNING: Lossless Scaling DLL not found in the home Steam directory!                     =="
        echo "==  Please install the latest version via Steam.                                             =="
        echo "==                                                                                           =="
        echo "==  It should be installed under the following path:                                         =="
        echo "==    $_data_home/Steam/steamapps/common/Lossless Scaling/Lossless.dll"
        echo "==                                                                                           =="
        echo "==  If you've installed it under a different path, please set the env var:                   =="
        echo "==    LSFG_DLL_PATH=\"/your/path/Lossless.dll\"                                                =="
        echo "==============================================================================================="
    else
        version="$(get_product_version "$steam_dll")"
        if [ "$version" != "$required_version" ]; then
            short_installed=$(get_version "$version")
            echo "========================================================================================"
            echo "==  Lossless Scaling version mismatch!                                                =="
            echo "==    Installed version: $short_installed"
            echo "==                                                                                    =="
            echo "==  Please install the latest build via Steam:                                        =="
            echo "==    Library → Lossless Scaling → Properties → Betas → none                          =="
            echo "========================================================================================"
        fi
    fi
}

check_local_install() {
    residuals=()
    [ -f "$user_manifest" ] && residuals+=("$user_manifest")
    [ -f "$user_library" ]  && residuals+=("$user_library")

    if [ "${#residuals[@]}" -gt 0 ]; then
        echo "================================================================================================================================"
        echo "==  Found residual files from previous local install:                                                                         =="
        for file in "${residuals[@]}"; do
            echo "==    $file  "
        done
        echo "==                                                                                                                            =="
        echo "==  You can remove them with:                                                                                                 =="
        printf "==    rm"
        for file in "${residuals[@]}"; do
            printf " \"%s\"" "$file"
        done
        echo ""
        echo "================================================================================================================================"
    fi
}

post_install() {
    check_steam_install
    check_local_install

    echo "================================================================================================================================="
    echo "==  To enable lsfg-vk, set the env vars ENABLE_LSFG=1 and LSFG_MULTIPLIER to a value between 0 and 4 before running a program  =="
    echo "==  For more usage instructions, refer to the lsfg-vk wiki:                                                                    =="
    echo "==    https://github.com/PancakeTAS/lsfg-vk/wiki/Configuring-lsfg%E2%80%90vk                                                   =="
    echo "================================================================================================================================="
}

post_upgrade() {
    post_install
}
