post_install() {
    :
#!/bin/bash

# Link to the binary
ln -sf '/opt/lx-music-desktop/lx-music-desktop' '/usr/bin/lx-music-desktop'

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/lx-music-desktop/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true

}
post_remove() {
    :
#!/bin/bash

# Delete the link to the binary
rm -f '/usr/bin/lx-music-desktop'

}
