post_install()
{
	systemd-sysusers

	chmod 600 /etc/lxdui/auth.conf
	chown lxdui:lxdui /etc/lxdui/auth.conf

	cat <<EOF

To change the default admin password run

	lxdui user update -u admin [-p password]

To start LXDUI, run

	systemctl start lxdui

To enable LXDUI at boot, run

	systemctl enable lxdui

EOF
}

post_upgrade()
{
	chmod 600 /etc/lxdui/auth.conf
	chown lxdui:lxdui /etc/lxdui/auth.conf

	systemctl daemon-reload
}

pre_remove()
{
	systemctl stop lxdui
	systemctl disable lxdui
}

