post_install() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null

	# Link to the launcher
	ln -sf '/opt/LycheeSlicer/lycheeslicer' '/usr/bin/lycheeslicer'

	update-mime-database /usr/share/mime || true
	update-desktop-database /usr/share/applications || true
	update-desktop-database -q
}

post_upgrade() {
	post_install
}

post_remove() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null

	# Delete the link to the launcher
	rm -f '/usr/bin/lycheeslicer'
	update-desktop-database -q
}
