post_install() {
  if [ -n "$SUDO_USER" ]; then
    current_user="$SUDO_USER"
    uhome=$(getent passwd "$current_user" | cut -d: -f6)
else
    current_user=$(whoami)
    home_dir="$HOME"
fi
  mkdir  $uhome/Documents/note
  chmod +x  $uhome
  chmod 777  $uhome/Documents
  chmod 777  $uhome/Downloads 
  chmod 777  $uhome/Pictures
  chmod 777 $uhome/Documents/note
  chmod 777 -R /opt/lze-web
  ln -s $uhome/Documents /opt/lze-web/Documents
  ln -s $uhome/Downloads /opt/lze-web/Downloads
  ln -s $uhome/Pictures /opt/lze-web/Pictures
  ln -s /opt/lze-web/code/Terminal/webssh-start /usr/bin/webssh-start
  ln -s /opt/lze-web/code/Terminal/webssh-stop /usr/bin/webssh-stop
  ln -s /opt/lze-web/code/Terminal/webssh /usr/lib/python3.12/site-packages/webssh
  mv /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.conf.back
  mv /etc/httpd/conf/httpd.conf.lze /etc/httpd/conf/httpd.conf
  mv /etc/php/php.ini /etc/php/php.ini.bck
  mv /etc/php/php.lze /etc/php/php.ini
  systemctl enable --now httpd.service
sudo systemctl enable --now wessh.service
}

post_upgrade() {
	post_install
}

pre_remove() {
	#

	action="$1"
	if [ "$2" = "in-favour" ]; then
	  # Treat conflict remove as an upgrade.
	  action="upgrade"
	fi

}

post_remove() {
systemctl disable --now wessh.service
rm -rf /usr/lib/python3.12/site-packages/webssh
rm /etc/systemd/system/wessh.service
rm -rf /opt/lze-web
mv /etc/httpd/conf/httpd.conf.bck  /etc/httpd/conf/httpd.conf 
mv /etc/php/php.ini.bck  /etc/php/php.ini
}
