post_install() {
    echo "Enabling disable-wakeup.service..."

    # Enable the systemd service if not already enabled
    if ! systemctl is-enabled disable-wakeup.service &>/dev/null; then
        systemctl enable disable-wakeup.service
        echo "Service disable-wakeup.service has been enabled."
    else
        echo "Service disable-wakeup.service was already enabled."
    fi

    echo "Installation complete!"
    echo "To finalize:"
    echo "1. Stop and disable wpa_supplicant systemd service."
    echo "2. Enable and start iwd systemd service."
    echo "3. Enable and start disable-wakeup systemd service."
    echo "NOTE: If you had a macfand config before, this package will replace that."
    echo "NOTE: The disable-wakeup.service will disable auto wake up when lid opens"
}

