--- libkcapi-1.1.1/Makefile.am	2018-07-11 01:22:56.943190820 +0200
+++ libkcapi-1.1.1/Makefile.am.patch	2018-07-11 01:25:57.253183003 +0200
@@ -153,19 +153,8 @@
 
 install-exec-hook:
 	(cd $(DESTDIR)$(bindir) && \
-	($(foreach link, $(hasher_links), $(LN) -f kcapi-hasher $(link);)))
+	($(foreach link, $(hasher_links), $(LN) -f kcapi-hasher $(link)-kcapi;)))
 	-rm -f $(DESTDIR)$(bindir)/kcapi-hasher
-if HAVE_OPENSSL
-	$(MKDIR_P) $(DESTDIR)$(CHECK_DIR_BIN_FC)
-	$(MKDIR_P) $(DESTDIR)$(CHECK_DIR_BIN_HC)
-	(cd $(DESTDIR)$(bindir) && \
-	($(foreach link, $(hasher_links_fc), \
-		$(CHECKSUM_CMD_FC) $(link) > $(DESTDIR)$(CHECK_DIR_BIN_FC)/$(CHECK_PREFIX)$(link).$(CHECK_SUFFIX);) \
-	$(foreach link, $(hasher_links_hc), \
-		$(CHECKSUM_CMD_HC) $(link) > $(DESTDIR)$(CHECK_DIR_BIN_HC)/$(CHECK_PREFIX)$(link).$(CHECK_SUFFIX);):))
-	($(foreach lib, $(wildcard $(DESTDIR)$(libdir)/libkcapi.so*), \
-		$(CHECKSUM_CMD_FC) $(lib)  > $(DESTDIR)$(CHECK_DIR_LIB)/$(CHECK_PREFIX)$(notdir $(lib)).$(CHECK_SUFFIX);):)
-endif
 endif
 
 if ENABLE_KCAPI_RNGAPP
