diff --git a/Makefile b/Makefile
index d66bd80e..0952b41e 100644
--- a/Makefile
+++ b/Makefile
@@ -708,22 +708,6 @@ uninstall:	uninstall-i18n
 	-if [ "x$(BUNDLE)" != "x" ]; then \
 	  rm -rf $(BUNDLE); \
 	fi
-	@if [ "x$(shell which xdg-icon-resource install)" != "x" ]; then \
-	  xdg-icon-resource uninstall --size 192 tux4kids-tuxpaint ; \
-	  xdg-icon-resource uninstall --size 128 tux4kids-tuxpaint ; \
-	  xdg-icon-resource uninstall --size 96 tux4kids-tuxpaint ; \
-	  xdg-icon-resource uninstall --size 64 tux4kids-tuxpaint ; \
-	  xdg-icon-resource uninstall --size 48 tux4kids-tuxpaint ; \
-	  xdg-icon-resource uninstall --size 32 tux4kids-tuxpaint ; \
-	  xdg-icon-resource uninstall --size 22 tux4kids-tuxpaint ; \
-	  xdg-icon-resource uninstall --size 16 tux4kids-tuxpaint ; \
-	fi
-	@if [ "x$(shell which xdg-desktop-menu)" != "x" ]; then \
-	  xdg-desktop-menu uninstall tux4kids-tuxpaint.desktop ; \
-	fi
-	-if [ "x$(shell which update-desktop-database)" != "x" ]; then \
-	  update-desktop-database; \
-	fi
 
 # Install default config file:
 .PHONY: install-default-config
diff --git a/Makefile b/Makefile
index d66bd80e..3e45e063 100644
--- a/Makefile
+++ b/Makefile
@@ -906,24 +906,14 @@ install-nokia770:
 install-xdg:
 	@echo
 	@echo "...Installing launcher icon into desktop environment..."
-	@if [ "x$(shell which xdg-icon-resource install)" != "x" ]; then \
-	  xdg-icon-resource install --size 192 data/images/icon192x192.png tux4kids-tuxpaint ; \
-	  xdg-icon-resource install --size 128 data/images/icon128x128.png tux4kids-tuxpaint ; \
-	  xdg-icon-resource install --size 96 data/images/icon96x96.png tux4kids-tuxpaint ; \
-	  xdg-icon-resource install --size 64 data/images/icon64x64.png tux4kids-tuxpaint ; \
-	  xdg-icon-resource install --size 48 data/images/icon48x48.png tux4kids-tuxpaint ; \
-	  xdg-icon-resource install --size 32 data/images/icon32x32.png tux4kids-tuxpaint ; \
-	  xdg-icon-resource install --size 22 data/images/icon22x22.png tux4kids-tuxpaint ; \
-	  xdg-icon-resource install --size 16 data/images/icon16x16.png tux4kids-tuxpaint ; \
-	fi
-	@if [ "x$(shell which xdg-desktop-menu)" != "x" ]; then \
-	  cp src/tuxpaint.desktop ./tux4kids-tuxpaint.desktop ; \
-	  xdg-desktop-menu install tux4kids-tuxpaint.desktop ; \
-	  rm ./tux4kids-tuxpaint.desktop ; \
-	fi
-	@if [ "x$(shell which update-desktop-database)" != "x" ]; then \
-	  update-desktop-database ; \
-	fi
+	install data/images/icon192x192.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
+	install data/images/icon128x128.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
+	install data/images/icon96x96.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
+	install data/images/icon64x64.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
+	install data/images/icon48x48.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
+	install data/images/icon32x32.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
+	install data/images/icon22x22.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
+	install data/images/icon16x16.png $(DESTDIR)$(PREFIX)/share/icons/hicolor/ ; \
 
 # Install the PNG icon (for KDE desktop, etc.)
 # and the 24-color 32x32 XPM (for other Window managers):
