#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS =  `pkg-config gtk+-2.0 --cflags` -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS =  `pkg-config gtk+-2.0 --libs`

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/ev

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/ev

OBJ_DEBUG = $(OBJDIR_DEBUG)/src/biogeo.o $(OBJDIR_DEBUG)/src/csv.o $(OBJDIR_DEBUG)/src/events.o $(OBJDIR_DEBUG)/src/main.o $(OBJDIR_DEBUG)/src/map.o $(OBJDIR_DEBUG)/src/tree.o $(OBJDIR_DEBUG)/src/tview.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/src/biogeo.o $(OBJDIR_RELEASE)/src/csv.o $(OBJDIR_RELEASE)/src/events.o $(OBJDIR_RELEASE)/src/main.o $(OBJDIR_RELEASE)/src/map.o $(OBJDIR_RELEASE)/src/tree.o $(OBJDIR_RELEASE)/src/tview.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG)/src || mkdir -p $(OBJDIR_DEBUG)/src

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/src/biogeo.o: src/biogeo.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/biogeo.c -o $(OBJDIR_DEBUG)/src/biogeo.o

$(OBJDIR_DEBUG)/src/csv.o: src/csv.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/csv.c -o $(OBJDIR_DEBUG)/src/csv.o

$(OBJDIR_DEBUG)/src/events.o: src/events.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/events.c -o $(OBJDIR_DEBUG)/src/events.o

$(OBJDIR_DEBUG)/src/main.o: src/main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/main.c -o $(OBJDIR_DEBUG)/src/main.o

$(OBJDIR_DEBUG)/src/map.o: src/map.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/map.c -o $(OBJDIR_DEBUG)/src/map.o

$(OBJDIR_DEBUG)/src/tree.o: src/tree.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tree.c -o $(OBJDIR_DEBUG)/src/tree.o

$(OBJDIR_DEBUG)/src/tview.o: src/tview.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c src/tview.c -o $(OBJDIR_DEBUG)/src/tview.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)/src

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE)/src || mkdir -p $(OBJDIR_RELEASE)/src

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/src/biogeo.o: src/biogeo.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/biogeo.c -o $(OBJDIR_RELEASE)/src/biogeo.o

$(OBJDIR_RELEASE)/src/csv.o: src/csv.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/csv.c -o $(OBJDIR_RELEASE)/src/csv.o

$(OBJDIR_RELEASE)/src/events.o: src/events.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/events.c -o $(OBJDIR_RELEASE)/src/events.o

$(OBJDIR_RELEASE)/src/main.o: src/main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/main.c -o $(OBJDIR_RELEASE)/src/main.o

$(OBJDIR_RELEASE)/src/map.o: src/map.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/map.c -o $(OBJDIR_RELEASE)/src/map.o

$(OBJDIR_RELEASE)/src/tree.o: src/tree.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/tree.c -o $(OBJDIR_RELEASE)/src/tree.o

$(OBJDIR_RELEASE)/src/tview.o: src/tview.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c src/tview.c -o $(OBJDIR_RELEASE)/src/tview.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)/src

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

