SOURCES := $(wildcard */*.cpp) $(wildcard *.cpp)
OBJS := $(patsubst %.cpp,%.o,$(SOURCES))

CPPFLAGS += -I. -Ikio -DFINAL
CXXFLAGS += -Wno-multichar -pthread -fno-rtti

zasm: $(OBJS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) $(OBJS) -o $@

-include $(OBJS:.o=.d)

%.o: %.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c -o $@ $<
	$(CXX) -MM $(CPPFLAGS) $< > $*.d

.PHONY: clean

clean:
	rm -f kio/*.o *.o zasm
