INTEGRATION=1

BUILTINCOMPS=../dist/usr/bin
INTERNAL=../dist/usr/share/inform7

INBLORBNAME=inblorb
INFORM6NAME=i6
INFORM7NAME=i7
INTESTNAME=intest

BUILTINHTML=$(INTERNAL)/Documentation/
BUILTINHTMLINNER=$(BUILTINHTML)
INDOCOPTS=-to $(BUILTINHTML) website
