--- Makefile.orig	2005-08-21 15:47:45.000000000 +0200
+++ Makefile	2008-05-16 20:33:45.000000000 +0200
@@ -1,8 +1,9 @@
 # installation dirs : Edit at your convenance
-PREFIX=/usr/local
-INSTALLDIR=$(PREFIX)/bin
-MANDIR=$(PREFIX)/man/man1
 
+PREFIX=$(startdir)/pkg/usr
+INSTALLDIR=$(PREFIX)/bin
+MANDIR=$(PREFIX)/share/man/man1
+ETCDIR=$(startdir)/pkg/etc
 TARGETS = shn2make 
 
 default:
@@ -15,10 +16,12 @@
 all : $(TARGETS)
 
 install : all
-	install -d -m 755 $(INSTALLDIR)
+	mkdir -p $(INSTALLDIR)
+	mkdir -p $(MANDIR)
+	mkdir -p $(ETCDIR)
 	install -m 755 shn2make $(INSTALLDIR)
 	install -m 644 shn2make.1 $(MANDIR)
-
+	install shn2makerc_proto $(ETCDIR)
 uninstall : 
 	rm -f $(INSTALLDIR)/shn2make	
 	rm -f $(MANDIR)/shn2make.1
