INTEGRATION=1

BUILTINCOMPS=../dist/usr/bin
INTERNAL=../dist/usr/lib/inform7

INBLORBNAME=inblorb
INFORM6NAME=i6
INFORM7NAME=ni
INTESTNAME=intest

BUILTINHTML=../dist/usr/share/doc/inform7
BUILTINHTMLINNER=$(BUILTINHTML)
INDOCOPTS=-to $(BUILTINHTML) website
