INTEGRATION=1

BUILTINCOMPS=../dist/usr/bin
INTERNAL=../dist/usr/share/inform7

INBLORBNAME=inblorb
INFORM6NAME=inform6
INFORM7NAME=inform7
INTESTNAME=intest

BUILTINHTML=$(INTERNAL)/Documentation/
BUILTINHTMLINNER=$(BUILTINHTML)
INDOCOPTS=-to $(BUILTINHTML) website
