--- Makefile.orig	2014-02-08 18:26:53.620756895 +0100
+++ Makefile	2014-02-08 18:29:30.085498653 +0100
@@ -354,8 +354,7 @@
 	echo "Copying the program"
 	mkdir -p $(DESTDIR)$(BIN_DIRECTORY)
 	cp src/FreeDoko $(DESTDIR)$(BIN_DIRECTORY)
-	chgrp games $(DESTDIR)$(BIN_DIRECTORY)/FreeDoko
-	chmod 750 $(DESTDIR)$(BIN_DIRECTORY)/FreeDoko
+	chmod 755 $(DESTDIR)$(BIN_DIRECTORY)/FreeDoko
 	cd $(DESTDIR)$(BIN_DIRECTORY) && ln -sf FreeDoko freedoko
 #	Copying the program files
 	echo "Copying the program files"
@@ -363,8 +362,8 @@
 	for d in logo.png icon.png translations rules ai cardsets icongroups backgrounds sounds; do \
 	  cp -a data/$$d $(DESTDIR)$(DATA_DIRECTORY)/; \
 	done
-	chgrp -R games $(DESTDIR)$(DATA_DIRECTORY)
-	chmod -R o-rwx,g+rX,g-w $(DESTDIR)$(DATA_DIRECTORY)
+	chmod -R 755 $(DESTDIR)$(DATA_DIRECTORY)
+	find $(DESTDIR)$(DATA_DIRECTORY) -type f -exec chmod 644 {} \;
 #	Copying the documentation
 #	SuSE does want the documentation in the directory
 #	'/usr/share/doc/packages/freedoko' so adjust it here
@@ -377,25 +376,24 @@
 	  cd $(DESTDIR)$(HELP_DIRECTORY)/.. && ln -sf FreeDoko freedoko; \
 	fi
 	cp -a doc/* AUTHORS COPYING ChangeLog $(DESTDIR)$(HELP_DIRECTORY)/
-	chgrp -R games $(DESTDIR)$(HELP_DIRECTORY)
-	chmod -R o-rwx,g+rX,g-w $(DESTDIR)$(HELP_DIRECTORY)
+	chmod -R 755 $(DESTDIR)$(HELP_DIRECTORY)
+	find $(DESTDIR)$(HELP_DIRECTORY) -type f -exec chmod 644 {} \;
 	cd $(DESTDIR)$(DATA_DIRECTORY) && ln -sf $(DESTDIR)$(HELP_DIRECTORY)/ doc
 #	update the manual page
-	echo "update the manual page"
-	cd doc; \
-	  docbook-to-man freedoko.sgml > freedoko.6 \
-	  || docbook2man freedoko.sgml > freedoko.6
-	mkdir -p $(DESTDIR)$(MAN_DIRECTORY)
-	cp doc/freedoko.6 $(DESTDIR)$(MAN_DIRECTORY)/
-	chgrp games $(DESTDIR)$(MAN_DIRECTORY)/freedoko.6
-	chmod 640 $(DESTDIR)$(MAN_DIRECTORY)/freedoko.6
-	cd $(DESTDIR)$(MAN_DIRECTORY)/ && ln -sf freedoko.6 FreeDoko.6
+#	echo "update the manual page"
+#	cd doc; \
+#	  docbook-to-man freedoko.sgml > freedoko.6 \
+#	  || docbook2man freedoko.sgml > freedoko.6
+#	mkdir -p $(DESTDIR)$(MAN_DIRECTORY)
+#	cp doc/freedoko.6 $(DESTDIR)$(MAN_DIRECTORY)/
+#	chgrp games $(DESTDIR)$(MAN_DIRECTORY)/freedoko.6
+#	chmod 640 $(DESTDIR)$(MAN_DIRECTORY)/freedoko.6
+#	cd $(DESTDIR)$(MAN_DIRECTORY)/ && ln -sf freedoko.6 FreeDoko.6
 #	copy the icon
 	echo "copy the icon"
 	mkdir -p $(DESTDIR)$(ICON_DIRECTORY)
 	cp src/FreeDoko.png $(DESTDIR)$(ICON_DIRECTORY)/
-	chgrp games $(DESTDIR)$(ICON_DIRECTORY)/FreeDoko.png
-	chmod 640 $(DESTDIR)$(ICON_DIRECTORY)/FreeDoko.png
+	chmod 644 $(DESTDIR)$(ICON_DIRECTORY)/FreeDoko.png
 
 .PHONY: uninstall
 uninstall :
