post_install() {
	if ! getent group manticore >/dev/null; then
		addgroup --system manticore
	fi

	if ! getent passwd manticore >/dev/null; then
		adduser --system --ingroup manticore  --no-create-home --shell /bin/false manticore
	fi

	chown manticore:manticore /var/lib/manticore -R
	chown manticore:manticore /var/log/manticore -R
	chown manticore:manticore /etc/manticoresearch -R

	echo "Manticore Search (https://manticoresearch.com)"
	echo ""
	echo "Get started with Manticore Search:"
	echo "  https://manual.manticoresearch.com/Quick_start_guide"
	echo ""
	echo "Learn Manticore with interactive courses:"
	echo "  https://play.manticoresearch.com/"
	echo ""
	echo "Configuration file:"
	echo "   /etc/manticoresearch/manticore.conf"
	echo ""
	echo "To start Manticore Search, run the following command:"
	echo "  > systemctl start manticore"
}
