pre_install() {
  if [ -f "/usr/share/applications/mapleclassic18.desktop" ]; then
    rm /usr/share/applications/mapleclassic18.desktop
  fi
  if [ -f "/usr/share/applications/maplearchive18.desktop" ]; then
    rm /usr/share/applications/maplearchive18.desktop
  fi
  if [ -f "/usr/share/applications/maple18.desktop" ]; then
    rm /usr/share/applications/maple18.desktop
  fi
}

post_install() {
  echo -e "\033[1;33mRunning Maple 18 activation wizard!\033[0m"
  exec /usr/share/maple18/bin/activation
}

pre_upgrade() {
  if [ -f "/usr/share/applications/mapleclassic18.desktop" ]; then
    rm /usr/share/applications/mapleclassic18.desktop
  fi
  if [ -f "/usr/share/applications/maplearchive18.desktop" ]; then
    rm /usr/share/applications/maplearchive18.desktop
  fi
}

post_upgrade() {
  post_install
}

post_remove() {
  rm -rf /usr/share/maple18
}
