post_install() {
  ln -sf /usr/lib/libgdal.so /usr/share/maptiler-desktop/libgdal.so.20
  ln -sf /usr/lib/libwebp.so /usr/share/maptiler-desktop/libwebp.so.6
}

post_upgrade() {
  ln -sf /usr/lib/libgdal.so /usr/share/maptiler-desktop/libgdal.so.20
  ln -sf /usr/lib/libwebp.so /usr/share/maptiler-desktop/libwebp.so.6
}

post_remove() {
  rm /usr/share/maptiler-desktop/libgdal.so.20
  rm /usr/share/maptiler-desktop/libwebp.so.6
  rmdir /usr/share/maptiler-desktop
}
