post_install() {
	update-desktop-database --quiet usr/share/applications 2>/dev/null || :
	update-mime-database usr/share/mime 2>/dev/null || :
	gtk-update-icon-cache --quiet --force usr/share/icons/hicolor 2>/dev/null || :
}

post_upgrade() {
	post_install
}

post_remove() {
	update-desktop-database --quiet usr/share/applications 2>/dev/null || :
	update-mime-database usr/share/mime 2>/dev/null || :
	gtk-update-icon-cache --quiet --force usr/share/icons/hicolor 2>/dev/null || :
}
