#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

cd /var/lib/mautrix-facebook

if [[ ! -e /var/lib/mautrix-facebook/alembic ]]; then
  ln -s /usr/share/mautrix-facebook/alembic ./
fi
if [[ ! -e /var/lib/mautrix-facebook/alembic.ini ]]; then
  ln -s /usr/share/mautrix-facebook/alembic.ini ./
fi
sudo -u mautrix-facebook alembic -x config=/etc/synapse/mautrix-facebook/config.yaml upgrade head
