#!/bin/sh

#hard-check against openjdk-21
JV=21

export PATH="/usr/lib/jvm/java-${JV}-openjdk/bin/:$PATH"

# javafx is installed to 'java-xx-openjfx', not 'java-xx-openjdk'
exec java --module-path /usr/lib/jvm/java-${JV}-openjfx/lib/javafx.base.jar:/usr/lib/jvm/java-${JV}-openjfx/lib/javafx.controls.jar:/usr/lib/jvm/java-${JV}-openjfx/lib/javafx.graphics.jar:/usr/lib/jvm/java-${JV}-openjfx/lib/javafx.swing.jar --add-modules javafx.base,javafx.controls,javafx.graphics,javafx.swing -jar /usr/share/java/mcaselector.jar "$@"
