#!/bin/sh

JV="$(javac -version | sed -e "s,.* ,,")"

export PATH="/usr/lib/jvm/java-${JV}-openjdk/bin/:$PATH"

java --module-path /usr/lib/jvm/java-${JV}-openjdk/lib/javafx.base.jar:/usr/lib/jvm/java-${JV}-openjdk/lib/javafx.controls.jar:/usr/lib/jvm/java-${JV}-openjdk/lib/javafx.graphics.jar:/usr/lib/jvm/java-${JV}-openjdk/lib/javafx.swing.jar --add-modules javafx.base,javafx.controls,javafx.graphics,javafx.swing -jar /usr/share/java/mcaselector.jar "$@"
