# Folder to write and store mealie data; must exist before starting mealie
# DATA_DIR=/var/lib/mealie

# For additional options, see: https://docs.mealie.io/documentation/getting-started/installation/backend-config/
