# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

# arg 1:  the new package version
post_install() {
usr/bin/echo "******************************************************************"
usr/bin/echo "   SET YOUR CREDENTIALS IN /etc/conf.d/megasync-headless.conf"
usr/bin/echo "******************************************************************"
}
