update_ruby_deps() {
  cd /opt/metasploit-git
  bundle install --path vendor/bundle
  find /opt/metasploit-git/vendor/bundle/ruby -name robots.rb -exec chmod o+r '{}' \;
}


post_install() {
  echo 'Installing necessary ruby dependencies with ruby-bundle'
  update_ruby_deps
}


post_upgrade() {
  echo 'Updating ruby dependencies with ruby-bundle'
  update_ruby_deps
}

post_remove() {
  echo 'Deleting metasploit folder to remove locally installed gems'
  # remove old location
  rm -rf /usr/share/metasploit-git
  rm -rf /opt/metasploit-git
}

# vim: ts=2 sw=2 et:
