post_install() {
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload || true
        systemctl restart microsoft-identity-device-broker.service || true
    fi
}

post_upgrade() {
    post_install
}

pre_remove() {
    if [ -d /run/systemd/system ]; then
        systemctl stop microsoft-identity-device-broker.service || true
    fi

    # NOTE (chrisn): Run this command as root to remove all state files from the
    # device enrollment procedures.
    # dsreg --cleanup
}

post_remove() {
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload || true
    fi
}
