post_install() {
/bin/sh -c 'cd / && patch -RNp1 -r- -i /usr/share/libalpm/scripts/minetest-usrdir_patch.patch'
/bin/sh -c 'cd / && patch -Np1 -r- -i /usr/share/libalpm/scripts/minetest-usrdir_patch.patch'
}

post_upgrade() {
/bin/sh -c 'cd / && patch -RNp1 -r- -i /usr/share/libalpm/scripts/minetest-usrdir_patch.patch'
/bin/sh -c 'cd / && patch -Np1 -r- -i /usr/share/libalpm/scripts/minetest-usrdir_patch.patch'
}
