ICONDIR="/usr/share/icons/Mist"

update_icon_cache() {
  echo "Updating GTK icon cache..." || return 1
  gtk-update-icon-cache -f -t "${ICONDIR}" || return 1
}


# arg 1:  the new package version
post_install() {
  update_icon_cache
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  update_icon_cache
}

# arg 1:  the old package version
post_remove() {
  update_icon_cache
  rmdir "${ICONDIR}"
}
