#!/bin/bash
set -e

VER=7.0.0.r6.gc685ae6-6

pacget() {
  printf "mkconfig: %s...\n" "$3"
  paccat "$1" "$2" > "$3"
}

for file in {pacman,makepkg,fortran,rust}.conf; do
  pacget http://mirror.archlinuxarm.org/aarch64/core/pacman-${VER}-aarch64.pkg.tar.xz ${file}{,.aarch64}
  pacget http://mirror.archlinuxarm.org/armv7h/core/pacman-${VER}-armv7h.pkg.tar.xz ${file}{,.armv7h}
  pacget http://pool.mirror.archlinux32.org/i686/core/pacman-${VER}.1-i686.pkg.tar.zst ${file}{,.i686}
  pacget http://pool.mirror.archlinux32.org/pentium4/core/pacman-${VER}.1-pentium4.pkg.tar.zst ${file}{,.pentium4}
  pacget https://europe.mirror.pkgbuild.com/core/os/x86_64/pacman-${VER}-x86_64.pkg.tar.zst ${file}{,.x86_64}
  pacget https://archriscv.felixc.at/repo/core/pacman-7.0.0.r7.g1f38429-0-riscv64.pkg.tar.zst ${file}{,.riscv64}
done
