#!/usr/bin/bash

build() {
    add_module rbd
    add_module cbc

    add_runscript
}

help() {
    cat <<HELPEOF
This hook allows to map rbd, and use it as a root device.
It requires the 'ip' kernel argument of the net hook for ip settings and it uses an extra 'rbd' kernel argument for ceph settings.
Don't forget to set the net hook before the rbd hook in your mkinitcpio configuration file.

Arguments:
    ip: examples at https://wiki.archlinux.org/index.php/Mkinitcpio#Using_net
    rbd: rbd=<monitor address>:name=<username>,secret=<secret key>:<pool name>:<disk name>
HELPEOF
}


# vim: set ft=sh ts=4 sw=4 et:
