post_install() {
    echo "Running post-install/upgrade script..."

    # Define product location as the parent to resources folder
    PRODUCT_HOME="/opt/ModusToolboxProgtools-1.5"

    # Find and install udev rules scripts 
    find "${PRODUCT_HOME}" -type f -name "install_rules.sh" -executable -exec sed -i '/\bsudo service udev restart\b/s/^/# /' {} \; -exec {} \;
}

post_upgrade() {
    post_install
}
