#!/usr/bin/env bash

[ -z "$XDG_DATA_DIRS" ] && export XDG_DATA_DIRS=$HOME/.local/share:/usr/share
# Avoid useless question about adding a start icon
# if [ ! -f "$HOME/.local/share/applications/appimagekit-Molotov.desktop" ]; then
#     cp /usr/share/applications/appimagekit-Molotov.desktop "$HOME/.local/share/applications/appimagekit-Molotov.desktop"
#     echo "NoDisplay=true" >> "$HOME/.local/share/applications/appimagekit-Molotov.desktop"
#     echo "Hidden=true" >> "$HOME/.local/share/applications/appimagekit-Molotov.desktop"
#     chmod 755 "$HOME/.local/share/applications/appimagekit-Molotov.desktop"
# fi
export SKIP=yes
exec /opt/appimages/Molotov-MOLOTOV_VERSION.AppImage
