#!/bin/bash

## Get path to a JDK >= 8. If default JDK does not match, choose the first ##
## match from "archlinux-java status" list ##
java_default_version=`archlinux-java get | sed 's/[^0-9]//g'`
if [ "$java_default_version" -ge 8 ]
then
    JDK_PATH="java"
    ## echo "Using default JDK / JRE: "`archlinux-java get`
else
    java_versions=`archlinux-java status | grep -oe java-[8-9]*-[a-z]*`
    JDK_PATH="/usr/lib/jvm/"`echo $java_versions | cut -f 1 -d " " | sed 's_/jre__g'`"/jre/bin/java"
    echo "Default java version is smaller than 8."
    echo "Consider changing the default java version to 8 with archlinux-java." 
    echo "Using JDK / JRE 8 at "$JDK_PATH" for mongochef execution."
fi  


# Decide whether to use GTK2 or GTK3 based
# on KDE being used or not
# PURPOSE: Avoid crash due to bug in oxygen-gtk theme engine
if [ "$1" = "useGtk2" ]; then
	desktop="don't care"
	useGtk2="yes"
else
	desktop=""
	ps -e | grep -E '^.* kded4$' > /dev/null
	if [ $? -eq 0 ]; then
		desktop="KDE"
	elif [ -n "$XDG_DATA_DIRS" ]; then
		desktop=$XDG_DATA_DIRS
	elif [ -n "$XDG_CURRENT_DESKTOP" ]; then
		desktop=$XDG_CURRENT_DESKTOP
	elif [ -n "$DESKTOP_SESSION" ]; then
		desktop=$DESKTOP_SESSION
	fi

	echo $desktop |  grep -i KDE  > /dev/null
	if [ $? -eq 0 ]; then
		desktop="KDE"
		useGtk2="no"
	else
		useGtk2="yes"
		desktop="not KDE"
	fi
fi

if [ "$useGtk2" = "yes" ]; then
	# as workaround for https://bugs.eclipse.org/bugs/show_bug.cgi?id=435773
	export SWT_GTK3=0
fi

# Launch the java program
$JDK_PATH -jar /opt/mongochef/data-man-mongodb-core-*.jar

