post_install() {
  update-desktop-database -q /usr/share/applications
  echo ''
  echo '======================================================================'
  echo 'To create config directory, run mkdir -p "$HOME/.PGE_Project/configs",'
  echo 'then you can place config packs there'
  echo '======================================================================'
  echo ''
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}

