post_install() {
    echo "Updating icon cache and desktop database..."
    glib-compile-schemas /usr/share/glib-2.0/schemas
    gtk4-update-icon-cache -q -t -f /usr/share/icons/hicolor
    update-desktop-database -q /usr/share/applications
}

post_upgrade() {
    post_install
}

post_remove() {
    glib-compile-schemas /usr/share/glib-2.0/schemas
    gtk4-update-icon-cache -q -t -f /usr/share/icons/hicolor
    update-desktop-database -q /usr/share/applications
}