#!/bin/env sh

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    /opt/Morgen/morgen \
        --enable-features=UseOzonePlatform,WaylandWindowDecorations \
        --ozone-platform=wayland \
        $@
else
    /opt/Morgen/morgen $@
fi
