post_install() {
  getent group mosquitto > /dev/null || groupadd -g 567 mosquitto
  getent passwd mosquitto > /dev/null || useradd -c 'Mosquitto MQTT Broker daemon' -d /etc/mosquitto -s /bin/false -g mosquitto -u 567 -g 567 mosquitto
}

post_upgrade() {
  post_install $1
  usermod -u 567 mosquitto
  groupmod -g 567 mosquitto
}

post_remove() {
  post_install $1
  echo "You may want to remove mosquitto user and group"
}

# vim:set ts=2 sw=2 et:
