# arg 1:  the new package version
post_install() {
  echo " *** Documentation installed at /opt/mpich-fint64/share/doc/mpich/install.pdf"
  echo " *** /opt/mpich-fint64/bin is appended to PATH, see /etc/profile.d/mpich-fint64.sh"
  echo " *** Some binary names match those of OpenMPI located in /usr (if installed)
     and those of the MPICH version with ilp-32 (default) located in /usr/mpich"
  /bin/true
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  post_install $1
}
