all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

note() {
  printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

post_install() {
  note "Don't forget install youtube-dl or yt-dlp for mpv ytdl-hook support"
  note "The upstream mpv uses yt-dlp by default, But not yet released"
  note "If you want to use yt-dlp, you need to set \"script-opts=ytdl_hook-ytdl_path=yt-dlp\" in mpv.conf"
}

post_upgrade() {
  post_install
}
