post_install() {
    systemctl enable --now mullvad-daemon

    echo -------------------------------------------------------------
    echo 'mullvad-daemon has been enabled & started.'
    echo -------------------------------------------------------------
}

post_upgrade() {
    systemctl daemon-reload
    systemctl restart mullvad-daemon

    echo -------------------------------------------------------------
    echo 'mullvad-daemon has been restarted.'
    echo -------------------------------------------------------------
}

pre_remove() {
    systemctl disable --now mullvad-daemon
}

post_remove() {
    # Remove logs & cache
    rm -rf /var/log/mullvad-vpn/
    rm -rf /var/cache/mullvad-vpn/

    # Remove config. See backup()
    #rm -rf /etc/mullvad-vpn
}