post_upgrade() {
    echo -------------------------------------------------------------
    echo 'You need to restart the mullvad daemon'
    echo '# systemctl restart mullvad-daemon'
    echo -------------------------------------------------------------
}

post_install() {
    echo -------------------------------------------------------------
    echo 'Make sure to enable and run the mullvad daemon'
    echo '# systemctl enable --now mullvad-daemon'
    echo -------------------------------------------------------------
}
