post_install() {
    echo "==> Installing.."
    muslimtify daemon install

    echo "==> Done!, Print the status with:"
    echo "      muslimtify daemon status"
}

post_upgrade() {
    echo "==> Daemon updated. Restart it with:"
    echo "      muslimtify daemon uninstall && muslimtify daemon install"
}

post_remove() {
    echo "==> Remove the daemon with:"
    echo "      muslimtify daemon uninstall"
}
