post_install() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
	set -u

	DISPLAY=''

	echo "Running post install script..."

	# This script may run not from the app's dist directory (this true in case of DEB package)
	# The placeholder is overriden during the package configuration
	SCRIPT_DIR="/opt/myoffice-standard-home-edition"
	CO_PRODUCT_ARTIFACT_SUFFIX="-home-edition"

	source "${SCRIPT_DIR}/Common.26.1.0.sh"
	source "${SCRIPT_DIR}/LkSdkUtils.sh"

	# Initialize licensing - for linux create cache of HW ids, due to reading of them requires root access
	createHardwareIdCache()
	{
	    local boardSerial=$(cat /sys/devices/virtual/dmi/id/board_serial | tr -d '\n')
	    local productUuid=$(cat /sys/devices/virtual/dmi/id/product_uuid | tr -d '\n' | tr '[:lower:]' '[:upper:]')
	    local idFile="${RESOURCES_DIR}/revision.dat"
	    mkdir -p "${RESOURCES_DIR}"

	    echo "${boardSerial} | ${productUuid}" > "${idFile}"
	    chmod go=r "${idFile}"
	}

	if [[ "revision.dat" != "" ]]; then
	    createHardwareIdCache
	fi





	createAdminSettingsFile()
	{
	    mkdir -p "${ADMIN_SETTINGS_PATH}"
	    if [ ! -f "${ADMIN_SETTINGS_FILE}" ]; then
	        echo "[General]" > "${ADMIN_SETTINGS_FILE}"
	    fi
	}

	# Add vendor id to admin settings file
	createAdminSettingsFile
	if [[ "${MO_VENDOR_ID:-}" != "" ]]; then
	    echo -e "\nVendorId=\"${MO_VENDOR_ID}\"\n" >> "${ADMIN_SETTINGS_FILE}"
	else
	    echo -e "\nVendorId=\"\"\n" >> "${ADMIN_SETTINGS_FILE}"
	fi

	#Unsigned extensions administration default settings
	CO_ENABLE_QT_DESKTOP_USING_UNSAFE_EXTENSIONS="FALSE"
	if [ "${CO_ENABLE_QT_DESKTOP_USING_UNSAFE_EXTENSIONS,,}" = "false" ] || [ "${CO_ENABLE_QT_DESKTOP_USING_UNSAFE_EXTENSIONS}" = "0" ]; then
	    createAdminSettingsFile
	    if [ -z $(grep "UnsafeExtensionsEnabled" "${ADMIN_SETTINGS_FILE}") ]; then
	      echo -e "\nUnsafeExtensionsEnabled=false\n" >> "${ADMIN_SETTINGS_FILE}"
	    fi
	fi

	echo "Done."
	update-desktop-database -q
}

post_upgrade() {
	post_install
}

pre_remove() {
	set -u

	DISPLAY=''

	# This script may run not from the app's dist directory (this true in case of DEB package)
	# The placeholder is overriden during the package configuration
	SCRIPT_DIR="/opt/myoffice-standard-home-edition"
	CONFIG_DIR="New Cloud Technologies Ltd."
	LKSDK_DIR_NAME="LkSdkWorkingDir"

	source "${SCRIPT_DIR}/Common.26.1.0.sh"

	if [[ "${TAG}" == "upgrade" || "${TAG}" == "1" ]]; then
	    echo "Skipping uninstall step..."
	    exit 0
	fi



	source "${SCRIPT_DIR}/LkSdkUtils.sh"



	# Remove vendor id in admin settings file
	if [ -f "${ADMIN_SETTINGS_FILE}" ]; then
	    sed -i "/VendorId=/c\VendorId=\"\"" "${ADMIN_SETTINGS_FILE}"
	fi



	echo "Done"
}

post_remove() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
	update-desktop-database -q
}