post_install(){
  echo ":: You need to initialize the MySQL data directory prior to starting"
  echo "   the service. This can be done with mysql_install_db command, e.g.:"
  echo "   mysql_install_db --user=mysql --basedir=/usr --datadir=/var/lib/mysql"
  echo ":: Additionally you should secure your MySQL installation using"
  echo "   mysql_secure_installation command after starting the mysqld service"
}

