# .nani files with one string question and one string answer per line
learning_path="$HOME/.config/nani/learning"
# Name of file(s) in learning directory or use "NANI?!" for all files
# Per default files for hiragana and katakana exist
learning_mode=""
