pre_remove() {
	sudo /opt/Natron2/NatronSetup
}

post_install() {
	echo "Make sure you do install Natron in /opt/Natron2/NatronSetup , Otherwise the removal will not work. You can remove it then by doing : sudo pacman -R natron-bin && sudo <path_to_natron_dir>/NatronSetup"
	curl -O http://downloads.natron.fr/Linux/releases/64bit/files/Natron-2.0.0-RC5-Linux-x86_64bit.tgz
	tar xf Natron-2.0.0-RC5-Linux-x86_64bit.tgz
	sudo ./Natron-2.0.0-RC5-Linux-x86_64bit
}
