post_install() {
    echo "==========================================================="
    echo " To enable the shred-extension-rs in Nautilus, you need to "
    echo " restart the file manager. Run the following command:      "
    echo "                                                           "
    echo "                     nautilus -q                           "
    echo "==========================================================="
}

post_upgrade() {
    post_install
}
