post_install() {
  echo "==> Additional setup is required"
  echo "  -> See http://wiki.navit-project.org/index.php/Configuration"
  echo
  echo "==> No maps are bundled with the install"
  echo "  -> See http://wiki.navit-project.org/index.php/Maps"
  echo

  xdg-icon-resource forceupdate
}

post_upgrade() {
  post_install "$1"
}

post_remove() {
  xdg-icon-resource forceupdate
}

# vim:set ts=2 sw=2 et:
