#!/usr/bin/env bash

readonly success=$'\e[1;32m'
readonly info=$'\e[0;36m'
readonly warn=$'\e[0;33m'
readonly reset=$'\e[0m'

post_install() {
    echo "${success}Thanks for installing Nextshot!"
    echo
    echo "${info}Dependencies vary based on your current environment"
    echo "${reset}Run 'nextshot --deps' after configuration to ensure"
    echo "that you have all the required packages installed."
    echo
}

post_upgrade() {
    post_install "$1"
}
