# Colored makepkg-like functions
note() {
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}
all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note "Follow the instructions on this page to enable and configure the app:"
    note "https://github.com/icewind1991/files_external_dropbox"
}

post_upgrade() {
    post_install $1
}
