server {
	listen 80;
	listen [::]:80;

	access_log off;

	server_name https://pipedproxy-cdg.kavin.rocks;

	proxy_buffering on;
	proxy_buffers 1024 16k;
	proxy_set_header X-Forwarded-For "";
	proxy_set_header CF-Connecting-IP "";
	proxy_hide_header "alt-svc";
	sendfile on;
	sendfile_max_chunk 512k;
	tcp_nopush on;
	aio threads=default;
	aio_write on;
	directio 16m;
	proxy_hide_header Cache-Control;
	proxy_hide_header etag;
	proxy_http_version 1.1;
	proxy_set_header Connection keep-alive;
	proxy_max_temp_file_size 32m;

	location ~ (/videoplayback|/api/v4/|/api/manifest/) {
		proxy_pass http://unix:/var/run/piped/proxy.sock;
		add_header Cache-Control private always;
	}

	location / {
		proxy_pass http://unix:/var/run/piped/proxy.sock;
		add_header Cache-Control "public, max-age=604800";
	}
}
