proxy_cache_path /tmp/pipedapi levels=1:2 keys_zone=pipedapi:4m max_size=2g inactive=60m use_temp_path=off;

server {
    listen 80;

    server_name pipedapi.kavin.rocks;

    location / {
        proxy_cache pipedapi;
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Connection "keep-alive";
    }
}
