worker_processes  1;

pid /var/lib/concrnt/webui/nginx.pid;

events {
    worker_connections  1024;
}


http {
  client_body_temp_path /var/lib/concrnt/webui/nginx-client-body;
  fastcgi_temp_path /var/lib/concrnt/webui/nginx-fastcgi;
  uwsgi_temp_path /var/lib/concrnt/webui/nginx-uwsgi;
  scgi_temp_path /var/lib/concrnt/webui/nginx-scgi;
  proxy_temp_path /var/lib/concrnt/webui/nginx-proxy;

  server {
    listen 28282;

    types {
      image/svg+xml	   svg;
      text/css         css;
      text/html        html htm;
      text/javascript  js mjs;
    }
  
    access_log /var/log/concrnt/webui/nginx-access.log;
    error_log /var/log/concrnt/webui/nginx-error.log;

    rewrite ^/web$ /web/ permanent;

    location /web/ {
      alias /usr/share/webapps/concrnt/;
      index index.html;
      try_files $uri $uri/ /index.html =404;
    }
  }
}
