if ($badagent) {
	rewrite ^ /iocaine_reserved_twjsbnpi6hi32b3d$request_uri;
}

location /iocaine_reserved_twjsbnpi6hi32b3d {
	proxy_set_header Host $host;
	proxy_pass http://127.0.0.1:42069;
#	proxy_pass http://unix:/run/iocaine/iocaine.sock;
}
