# bash completion for notes
# Generated by notes completions bash. Do not edit by hand.

_notes() {
  local cur prev cword command opts choices
  COMPREPLY=()
  cur=${COMP_WORDS[COMP_CWORD]}
  prev=${COMP_WORDS[COMP_CWORD-1]}
  cword=$COMP_CWORD
  command=${COMP_WORDS[1]-}

  if (( cword == 1 )); then
    COMPREPLY=( $(compgen -W 'root context list read write delete handoffs mcp completions help -h --help' -- "$cur") )
    return
  fi

  case $command in
    root)
      opts='--projects --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    context)
      opts='--command --json --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    list)
      case $prev in
        --format)
          COMPREPLY=( $(compgen -W 'labels json' -- "$cur") )
          return
          ;;
      esac
      opts='--all --tag --format --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    read)
      opts='--path --json --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    write)
      opts='--path --stdin --expected-hash --json --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    delete)
      opts='--path --json --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    handoffs)
      case $prev in
        --format)
          COMPREPLY=( $(compgen -W 'labels json' -- "$cur") )
          return
          ;;
      esac
      opts='--all --list --format --help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    mcp)
      opts='--help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    completions)
      opts='--help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
    help)
      opts='--help -h'
      if [[ $cur == -* ]]; then
        COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
      fi
      return
      ;;
  esac
}

complete -F _notes notes
