post_install() {
    echo "## To complete installation, add the following line to your bashrc"
    echo '## [[ -f /usr/share/nwd/nwd-preexec.sh ]] && source /usr/share/nwd/nwd-preexec.sh'
}

post_upgrade() {
    echo '## Upgrade will be effective only after a source of your bashrc.'
    echo '## source /etc/bash.bashrc'
}

post_removal() {
    echo "## To complete removal, remove the source of nwd/preexec.sh from your bashrc"
}
