post_install() {
  echo
  echo '!!! NOTE !!!'
  echo 'It is *strongly* encouraged to add users to the "users" group (usermod -aG users <username>) if they will be playing ezQuake/nQuake.
  Trust me. If you hit a bug and you are using a user not in the users group, you are testing bad and you should feel bad.'
  echo
}

post_upgrade () {

  # Fix some group ownerships...
  find /opt/quake -group games -exec chgrp users '{}' \;

}
