post_install() {

  cat << EOF

   ╭────────────────────────────────────────────────────────╮
   │                                                        │
   │     For help installing additional kernels, visit:     │
   │  https://wiki.archlinux.org/index.php/Jupyter#Kernels  │
   │                                                        │
   ╰────────────────────────────────────────────────────────╯

EOF
}

post_upgrade() {
  post_install
}

