post_install() {
    mv -f /usr/include/linux/ntsync.h /usr/share/ntsync/ntsync.h_orig
    cp -a /usr/share/ntsync/ntsync.h /usr/include/linux

    echo -e ":: The ntsync module needs to be loaded manually the first time!"
    echo -e "   It should load automatically after a reboot."
}

post_upgrade() {
    cp -a /usr/share/ntsync/ntsync.h /usr/include/linux
}

pre_remove() {
    mv -f /usr/share/ntsync/ntsync.h_orig /usr/include/linux/ntsync.h
}
