post_upgrade() {
  # driver version 595.45.04-1 and beyond no longer requires the services to be enabled
  if (( $(vercmp $2 595.45.04-1) < 0)); then
    for service in nvidia-resume nvidia-hibernate nvidia-suspend nvidia-suspend-then-hibernate; do
        if systemctl is-enabled --quiet "$service" 2>/dev/null; then
            printf '%s\n' "Disabling ${service}..."
            systemctl disable "$service"
        fi
    done
  fi
}

pre_remove() {
  for service in nvidia-resume nvidia-hibernate nvidia-suspend nvidia-suspend-then-hibernate; do
    if systemctl is-enabled --quiet "$service" 2>/dev/null; then
      systemctl disable "$service"
    fi
  done
}
