# https://download.nvidia.com/XFree86/Linux-x86_64/595.45.04/README/powermanagement.html#PreservingVideo31185
# Save and restore all video memory allocations
options nvidia NVreg_UseKernelSuspendNotifiers=1
#
# The destination should not be using tmpfs, so we prefer /var/tmp instead of /tmp
options nvidia NVreg_TemporaryFilePath=/var/tmp
