# Blacklist nouveau and nova
blacklist nouveau
blacklist nova_core
blacklist nova_drm

# Make sure that all modules are loaded after the main one.
softdep nvidia post: nvidia-uvm nvidia-drm

# The destination should not be using tmpfs, so we prefer
# /var/tmp instead of /tmp
options nvidia NVreg_TemporaryFilePath=/var/tmp
