# https://download.nvidia.com/XFree86/Linux-x86_64/595.45.04/README/powermanagement.html
# Enable Suspend Notifiers for faster and more modern suspend
options nvidia NVreg_UseKernelSuspendNotifiers=1
#
# The destination should not be using tmpfs, so we prefer
# /var/tmp instead of /tmp
options nvidia NVreg_TemporaryFilePath=/var/tmp
