### Option:Plugins.NVIDIA.System.Path
#	Path to loadable plugin executable.
#
# Mandatory: yes
# Default:
Plugins.NVIDIA.System.Path=/usr/bin/zabbix-agent2-plugin-nvidia-gpu

### Option: Plugins.NVIDIA.Timeout
#	Amount of time to wait for a server to respond when first connecting and on
#   follow up operations in the session.
#   Global item-type timeout (or individual item timeout) will override this value if it is greater.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.NVIDIA.Timeout=<Global timeout>
