/*
 * Copyright 2024 Mesa Contributors
 * SPDX-License-Identifier: MIT
 *
 * VK_NV_low_latency2 (NVIDIA Reflex) for NVK  — v2
 * =================================================
 * Pure userspace / CPU-side implementation.  No special nouveau kernel uAPI
 * is required.  The five Vulkan entry points are wired up so that
 * VKD3D-Proton >=2.12 and DXVK-NVAPI >=0.7 can expose the Reflex
 * low-latency mode toggle to games running through NVK/Nouveau.
 *
 * Design
 * ------
 * Per-swapchain state (mode config + last-sleep timestamp + timing history)
 * is stored in a fixed-size open-addressed hash table keyed on the opaque
 * VkSwapchainKHR handle.  A single pthread_rwlock protects the table.
 * Erased slots are marked with a tombstone so probe chains for colliding
 * swapchains remain intact across create/destroy cycles.
 *
 * vkSetLatencySleepModeNV  – stores mode config in the table
 * vkLatencySleepNV         – spawns a detached thread that enforces
 *                            minimumIntervalUs via clock_nanosleep and then
 *                            signals the app's timeline semaphore.  The
 *                            calling thread returns immediately, satisfying
 *                            the Vulkan spec ("the command returns
 *                            immediately").
 * vkSetLatencyMarkerNV     – records per-frame timestamps in a ring buffer
 * vkGetLatencyTimingsNV    – returns recorded timing history to the caller
 * vkQueueNotifyOutOfBandNV – intentional no-op; Nouveau has no OOB scheduler
 *
 * Activation
 * ----------
 * The extension is advertised unconditionally for all NVK devices (Turing+).
 * Games should enable it via:
 *   DXVK_ENABLE_NVAPI=1 PROTON_ENABLE_NVAPI=1 %command%
 * if using DXVK-NVAPI / VKD3D-Proton to translate D3D12 or D3D11 Reflex.
 */

/* nvk_entrypoints.h is auto-generated by vk_entrypoints_gen.py during the
 * Mesa build.  It provides VKAPI_ATTR prototypes for every nvk_FunctionName()
 * entry point registered in the NVK entrypoints Python file.  The file lives
 * in the build directory; the meson-generated include paths already point
 * there so the include just works. */
#include "nvk_entrypoints.h"

/* nvk_device.h gives us nvk_device_from_handle() and the nvk_device struct
 * so we can reach the Vulkan dispatch table for SignalSemaphore. */
#include "nvk_device.h"

#include "util/macros.h"
#include "vk_log.h"
#include "vk_util.h"

#include <errno.h>
#include <pthread.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* =========================================================================
 * Constants
 * ========================================================================= */

/** Depth of the per-swapchain frame-timing ring buffer. */
#define NVK_LL2_HIST   64u

/** Number of slots in the global swapchain-keyed hash table.
 *  Must be a power of two.  128 slots handles many swapchain
 *  create/destroy cycles before tombstones begin to accumulate. */
#define NVK_LL2_TABLE 128u

/** Tombstone sentinel — slot was occupied but the swapchain was destroyed.
 *  (uintptr_t)1 is never a valid dispatchable Vulkan handle. */
#define NVK_LL2_TOMBSTONE ((VkSwapchainKHR)(uintptr_t)1)

/* =========================================================================
 * Per-swapchain latency state
 * ========================================================================= */

struct nvk_ll2_state {
   /* --- Mode config set by vkSetLatencySleepModeNV ----------------------- */
   bool     enabled;           /**< lowLatencyMode                          */
   bool     boost;             /**< lowLatencyBoost (stored, not acted on)  */
   uint32_t min_interval_us;   /**< minimumIntervalUs                       */

   /* --- Pacing ----------------------------------------------------------- */
   /** CLOCK_MONOTONIC nanoseconds recorded at the end of the last sleep. */
   uint64_t last_sleep_ns;

   /* --- Timing history ring buffer --------------------------------------- */
   VkLatencyTimingsFrameReportNV hist[NVK_LL2_HIST];
   uint32_t hist_head;    /**< Index of the next slot to be written         */
   uint32_t hist_count;   /**< Number of valid entries currently stored     */
};

struct nvk_ll2_entry {
   VkSwapchainKHR       key; /**< VK_NULL_HANDLE = empty, TOMBSTONE = dead  */
   struct nvk_ll2_state val;
};

/* Global table + lock.  Zero-initialised by static storage duration. */
static pthread_rwlock_t     g_ll2_lock = PTHREAD_RWLOCK_INITIALIZER;
static struct nvk_ll2_entry g_ll2_tbl[NVK_LL2_TABLE];

/* =========================================================================
 * Hash-table helpers  (all callers must hold g_ll2_lock appropriately)
 * ========================================================================= */

static uint32_t
ll2_hash(VkSwapchainKHR sc)
{
   uint64_t v = (uint64_t)(uintptr_t)sc;
   v ^= v >> 33;
   v *= (uint64_t)0xff51afd7ed558ccdULL;
   v ^= v >> 33;
   return (uint32_t)(v & (NVK_LL2_TABLE - 1));
}

/**
 * Find an existing entry or allocate a new slot (reusing tombstones).
 * Returns NULL only if the table is completely full of live entries.
 * Caller must hold g_ll2_lock for *writing*.
 */
static struct nvk_ll2_state *
ll2_get_or_create(VkSwapchainKHR sc)
{
   const uint32_t h = ll2_hash(sc);
   struct nvk_ll2_entry *tomb = NULL;

   for (uint32_t i = 0; i < NVK_LL2_TABLE; i++) {
      struct nvk_ll2_entry *e = &g_ll2_tbl[(h + i) & (NVK_LL2_TABLE - 1)];

      if (e->key == sc)
         return &e->val;

      /* Track the first tombstone in case we need to reuse it. */
      if (e->key == NVK_LL2_TOMBSTONE && !tomb)
         tomb = e;

      if (e->key == VK_NULL_HANDLE) {
         /* Prefer reusing a tombstone slot to keep probe chains short. */
         struct nvk_ll2_entry *slot = tomb ? tomb : e;
         slot->key = sc;
         memset(&slot->val, 0, sizeof(slot->val));
         return &slot->val;
      }
   }
   /* Table is full of live entries + tombstones — try to reuse tombstone. */
   if (tomb) {
      tomb->key = sc;
      memset(&tomb->val, 0, sizeof(tomb->val));
      return &tomb->val;
   }
   return NULL;
}

/**
 * Find an existing entry.  Tombstones are skipped (probe chain continues);
 * only VK_NULL_HANDLE terminates the search.
 * Caller must hold g_ll2_lock for *reading* (or writing).
 */
static struct nvk_ll2_state *
ll2_find(VkSwapchainKHR sc)
{
   const uint32_t h = ll2_hash(sc);
   for (uint32_t i = 0; i < NVK_LL2_TABLE; i++) {
      struct nvk_ll2_entry *e = &g_ll2_tbl[(h + i) & (NVK_LL2_TABLE - 1)];
      if (e->key == sc)
         return &e->val;
      if (e->key == VK_NULL_HANDLE)
         return NULL;
      /* NVK_LL2_TOMBSTONE: keep probing — a live entry may sit beyond it. */
   }
   return NULL;
}

/**
 * Mark the slot for sc as a tombstone so later probe chains remain valid.
 * Caller must hold g_ll2_lock for *writing*.
 */
static void
ll2_erase(VkSwapchainKHR sc)
{
   const uint32_t h = ll2_hash(sc);
   for (uint32_t i = 0; i < NVK_LL2_TABLE; i++) {
      struct nvk_ll2_entry *e = &g_ll2_tbl[(h + i) & (NVK_LL2_TABLE - 1)];
      if (e->key == sc) {
         memset(&e->val, 0, sizeof(e->val));
         e->key = NVK_LL2_TOMBSTONE;
         return;
      }
      if (e->key == VK_NULL_HANDLE)
         return;
   }
}

/* =========================================================================
 * Frame-report ring-buffer helpers
 * ========================================================================= */

static VkLatencyTimingsFrameReportNV *
ll2_frame_get_or_create(struct nvk_ll2_state *s, uint64_t present_id)
{
   for (uint32_t i = 0; i < s->hist_count; i++) {
      const uint32_t idx =
         (s->hist_head - 1u - i + NVK_LL2_HIST) & (NVK_LL2_HIST - 1u);
      if (s->hist[idx].presentID == present_id)
         return &s->hist[idx];
   }

   const uint32_t slot = s->hist_head;
   s->hist_head = (slot + 1u) & (NVK_LL2_HIST - 1u);
   if (s->hist_count < NVK_LL2_HIST)
      s->hist_count++;

   VkLatencyTimingsFrameReportNV *fr = &s->hist[slot];
   memset(fr, 0, sizeof(*fr));
   fr->sType     = VK_STRUCTURE_TYPE_LATENCY_TIMINGS_FRAME_REPORT_NV;
   fr->presentID = present_id;
   return fr;
}

/* =========================================================================
 * Clock helpers
 * ========================================================================= */

static inline uint64_t
monotonic_ns(void)
{
   struct timespec ts;
   clock_gettime(CLOCK_MONOTONIC, &ts);
   return (uint64_t)ts.tv_sec * UINT64_C(1000000000)
        + (uint64_t)ts.tv_nsec;
}

static inline uint64_t
monotonic_us(void)
{
   return monotonic_ns() / UINT64_C(1000);
}

/* =========================================================================
 * Async sleep + semaphore signal
 *
 * vkLatencySleepNV must return immediately (Vulkan spec §46.3).  We spawn a
 * detached thread per call that does the actual clock_nanosleep and then
 * signals the application's timeline semaphore.
 *
 * Thread-creation overhead (~5 µs on Linux) is negligible relative to the
 * minimum-interval sleep durations games use (typically 500–16 000 µs).
 * If malloc or pthread_create fail we fall back to a synchronous in-line
 * signal so the game is never permanently stuck on its semaphore wait.
 * ========================================================================= */

struct ll2_sleep_args {
   VkDevice       device;          /**< opaque handle passed to SignalSemaphore */
   VkSwapchainKHR swapchain;       /**< used to update last_sleep_ns            */
   VkSemaphore    semaphore;       /**< timeline semaphore to signal             */
   uint64_t       value;           /**< timeline value to signal                 */
   uint64_t       wake_target_ns;  /**< absolute CLOCK_MONOTONIC time; 0=ASAP   */
};

static void *
ll2_sleep_thread(void *arg)
{
   struct ll2_sleep_args *a = (struct ll2_sleep_args *)arg;

   /* Sleep until the wake target if one was given. */
   if (a->wake_target_ns > 0u) {
      struct timespec wts = {
         .tv_sec  = (time_t)(a->wake_target_ns / UINT64_C(1000000000)),
         .tv_nsec = (long)  (a->wake_target_ns % UINT64_C(1000000000)),
      };
      int r;
      do {
         r = clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &wts, NULL);
      } while (r == EINTR);
   }

   /* Record actual wake time for the next interval calculation. */
   const uint64_t wake_actual = monotonic_ns();
   pthread_rwlock_wrlock(&g_ll2_lock);
   struct nvk_ll2_state *s = ll2_find(a->swapchain);
   if (s)
      s->last_sleep_ns = wake_actual;
   pthread_rwlock_unlock(&g_ll2_lock);

   /* Signal the application's timeline semaphore. */
   const VkSemaphoreSignalInfo si = {
      .sType     = VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO,
      .pNext     = NULL,
      .semaphore = a->semaphore,
      .value     = a->value,
   };
   struct nvk_device *dev = nvk_device_from_handle(a->device);
   dev->vk.dispatch_table.SignalSemaphore(a->device, &si);

   free(a);
   return NULL;
}

/**
 * Signal the semaphore inline (synchronous fallback for malloc/pthread
 * failures — ensures the game is never stuck on an unsignalled semaphore).
 */
static VkResult
ll2_signal_sync(VkDevice device,
                VkSemaphore semaphore,
                uint64_t    value)
{
   const VkSemaphoreSignalInfo si = {
      .sType     = VK_STRUCTURE_TYPE_SEMAPHORE_SIGNAL_INFO,
      .pNext     = NULL,
      .semaphore = semaphore,
      .value     = value,
   };
   struct nvk_device *dev = nvk_device_from_handle(device);
   return dev->vk.dispatch_table.SignalSemaphore(device, &si);
}

/* =========================================================================
 * VK_NV_low_latency2 entry points
 * ========================================================================= */

/**
 * vkSetLatencySleepModeNV
 *
 * Stores or updates the Reflex configuration for a swapchain.
 * pSleepModeInfo == NULL clears the state (disables Reflex for this chain).
 */
VKAPI_ATTR VkResult VKAPI_CALL
nvk_SetLatencySleepModeNV(VkDevice device,
                           VkSwapchainKHR swapchain,
                           const VkLatencySleepModeInfoNV *pSleepModeInfo)
{
   pthread_rwlock_wrlock(&g_ll2_lock);

   if (!pSleepModeInfo) {
      ll2_erase(swapchain);
      pthread_rwlock_unlock(&g_ll2_lock);
      return VK_SUCCESS;
   }

   struct nvk_ll2_state *s = ll2_get_or_create(swapchain);
   if (!s) {
      pthread_rwlock_unlock(&g_ll2_lock);
      return VK_ERROR_OUT_OF_HOST_MEMORY;
   }

   s->enabled         = (pSleepModeInfo->lowLatencyMode  == VK_TRUE);
   s->boost           = (pSleepModeInfo->lowLatencyBoost == VK_TRUE);
   s->min_interval_us = pSleepModeInfo->minimumIntervalUs;

   pthread_rwlock_unlock(&g_ll2_lock);
   return VK_SUCCESS;
}

/**
 * vkLatencySleepNV
 *
 * Returns immediately (Vulkan spec requirement).  A detached background
 * thread enforces minimumIntervalUs via clock_nanosleep and then signals
 * the application's timeline semaphore.
 */
VKAPI_ATTR VkResult VKAPI_CALL
nvk_LatencySleepNV(VkDevice device,
                    VkSwapchainKHR swapchain,
                    const VkLatencySleepInfoNV *pSleepInfo)
{
   /* Snapshot pacing parameters under the read lock. */
   pthread_rwlock_rdlock(&g_ll2_lock);
   const struct nvk_ll2_state *s = ll2_find(swapchain);
   const bool     do_pace = s && s->enabled && s->min_interval_us > 0;
   const uint64_t min_ns  = do_pace
                            ? (uint64_t)s->min_interval_us * UINT64_C(1000)
                            : 0u;
   const uint64_t last_ns = do_pace ? s->last_sleep_ns : 0u;
   pthread_rwlock_unlock(&g_ll2_lock);

   /* Compute the absolute wake target (0 = signal immediately). */
   uint64_t wake_target = 0u;
   if (do_pace && last_ns > 0u) {
      const uint64_t candidate = last_ns + min_ns;
      if (candidate > monotonic_ns())
         wake_target = candidate;
   }

   /* Allocate args on the heap (freed by the worker thread). */
   struct ll2_sleep_args *args =
      (struct ll2_sleep_args *)malloc(sizeof(*args));
   if (!args)
      return ll2_signal_sync(device, pSleepInfo->signalSemaphore,
                             pSleepInfo->value);

   args->device         = device;
   args->swapchain      = swapchain;
   args->semaphore      = pSleepInfo->signalSemaphore;
   args->value          = pSleepInfo->value;
   args->wake_target_ns = wake_target;

   pthread_t tid;
   if (pthread_create(&tid, NULL, ll2_sleep_thread, args) != 0) {
      free(args);
      return ll2_signal_sync(device, pSleepInfo->signalSemaphore,
                             pSleepInfo->value);
   }

   pthread_detach(tid);
   return VK_SUCCESS;  /* returns immediately — semaphore signalled async */
}

/**
 * vkSetLatencyMarkerNV
 *
 * Records per-frame timing markers into the ring buffer.
 */
VKAPI_ATTR void VKAPI_CALL
nvk_SetLatencyMarkerNV(VkDevice device,
                        VkSwapchainKHR swapchain,
                        const VkSetLatencyMarkerInfoNV *pLatencyMarkerInfo)
{
   const uint64_t ts_us = monotonic_us();

   pthread_rwlock_wrlock(&g_ll2_lock);

   struct nvk_ll2_state *s = ll2_find(swapchain);
   if (!s) {
      /* Markers can arrive before SetLatencySleepModeNV in some engines. */
      s = ll2_get_or_create(swapchain);
      if (!s) {
         pthread_rwlock_unlock(&g_ll2_lock);
         return;
      }
   }

   VkLatencyTimingsFrameReportNV *fr =
      ll2_frame_get_or_create(s, pLatencyMarkerInfo->presentID);

   switch (pLatencyMarkerInfo->marker) {
   case VK_LATENCY_MARKER_SIMULATION_START_NV:
      fr->simStartTimeUs          = ts_us; break;
   case VK_LATENCY_MARKER_SIMULATION_END_NV:
      fr->simEndTimeUs            = ts_us; break;
   case VK_LATENCY_MARKER_RENDERSUBMIT_START_NV:
      fr->renderSubmitStartTimeUs = ts_us; break;
   case VK_LATENCY_MARKER_RENDERSUBMIT_END_NV:
      fr->renderSubmitEndTimeUs   = ts_us; break;
   case VK_LATENCY_MARKER_PRESENT_START_NV:
      fr->presentStartTimeUs      = ts_us;
      /* Update pacing reference so LatencySleepNV has a real anchor. */
      s->last_sleep_ns = monotonic_ns();
      break;
   case VK_LATENCY_MARKER_PRESENT_END_NV:
      fr->presentEndTimeUs        = ts_us; break;
   case VK_LATENCY_MARKER_INPUT_SAMPLE_NV:
      fr->inputSampleTimeUs       = ts_us; break;
   case VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_START_NV:
      fr->renderSubmitStartTimeUs = ts_us; break;
   case VK_LATENCY_MARKER_OUT_OF_BAND_RENDERSUBMIT_END_NV:
      fr->renderSubmitEndTimeUs   = ts_us; break;
   case VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_START_NV:
      fr->presentStartTimeUs      = ts_us; break;
   case VK_LATENCY_MARKER_OUT_OF_BAND_PRESENT_END_NV:
      fr->presentEndTimeUs        = ts_us; break;
   case VK_LATENCY_MARKER_TRIGGER_FLASH_NV:
      break;
   default:
      break;
   }

   pthread_rwlock_unlock(&g_ll2_lock);
}

/**
 * vkGetLatencyTimingsNV
 *
 * Returns per-frame timing history.  Standard two-call array-query pattern:
 * first call with pTimings == NULL sets timingCount to the available count.
 */
VKAPI_ATTR void VKAPI_CALL
nvk_GetLatencyTimingsNV(VkDevice device,
                         VkSwapchainKHR swapchain,
                         VkGetLatencyMarkerInfoNV *pLatencyMarkerInfo)
{
   pthread_rwlock_rdlock(&g_ll2_lock);

   const struct nvk_ll2_state *s = ll2_find(swapchain);

   if (!s || s->hist_count == 0u) {
      pLatencyMarkerInfo->timingCount = 0u;
      pthread_rwlock_unlock(&g_ll2_lock);
      return;
   }

   if (!pLatencyMarkerInfo->pTimings) {
      pLatencyMarkerInfo->timingCount = s->hist_count;
      pthread_rwlock_unlock(&g_ll2_lock);
      return;
   }

   const uint32_t out_n =
      MIN2(pLatencyMarkerInfo->timingCount, s->hist_count);
   pLatencyMarkerInfo->timingCount = out_n;

   for (uint32_t i = 0u; i < out_n; i++) {
      const uint32_t src =
         (s->hist_head - s->hist_count + i + NVK_LL2_HIST) & (NVK_LL2_HIST - 1u);
      pLatencyMarkerInfo->pTimings[i] = s->hist[src];
   }

   pthread_rwlock_unlock(&g_ll2_lock);
}

/**
 * vkQueueNotifyOutOfBandNV
 *
 * Intentional no-op.  Nouveau/NVK has no out-of-band GPU scheduler.
 */
VKAPI_ATTR void VKAPI_CALL
nvk_QueueNotifyOutOfBandNV(VkQueue queue,
                            const VkOutOfBandQueueTypeInfoNV *pQueueTypeInfo)
{
   (void)queue;
   (void)pQueueTypeInfo;
}
