post_install() {
    echo "==> To complete installation, add the following lines to your bashrc"
    echo '    [[ -S /run/user/$USER/i3/ipc-socket.$(pidof i3) && -f /usr/share/nwd/preexec.sh ]] \'
    echo '        && . /usr/share/nwd/preexec.sh'
    echo '==> and restart bash'
}

post_upgrade() {
    echo '==> Upgrade will be effective only after you restart bash'
}

post_remove() {
    echo "==> To complete removal, remove the `source` of preexec.sh from your bashrc"
}
