[options]
; database
list_db = False
db_host = /run/postgresql/
db_port = False
db_user = odoo
db_password = odoo
db_name = odoo

; addons
addons_path = /usr/share/odoo/venv/lib/python3.13/site-packages/odoo/addons,/var/lib/odoo/.local/share/Odoo/addons/18.0
default_productivity_apps = True

; performance
proxy_mode = True
workers = 25
limit_time_cpu = 600
limit_time_real = 1200

; logs
syslog = False
log_file = /var/log/odoo/odoo-server.log
