post_install(){
  # show message after each install
  echo "If first install, you need to initialize the database:
        1) Please set your database connection details in /etc/odoo/odoo.conf.
	2) sudo -u odoo source /var/lib/odoo/.venv/bin/activate
        3) sudo -u odoo /var/lib/odoo/.venv/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log -i base"
}

post_upgrade(){
  # show message only if major version differs
  if [ "${1%.*}" -gt "${2%.*}" ]; then
    echo "A new major version of Odoo has been released, you should upgrade
          the odoo database by running the following as the odoo user:
          1. sudo -u odoo source /var/lib/odoo/.venv/bin/activate
          2. sudo -u odoo /var/lib/odoo/.venv/bin/odoo --config /etc/odoo/odoo.conf --logfile /var/log/odoo/odoo-server.log -u all"
  fi
}
