# shellcheck shell=bash
# -*- sh -*-

post_install() {
  cat <<__EOT__
» The opnk command has been renamed to openk in 3.0. This is still
» available as a symlink, but it will be removed in a later
» release.
»
» If you have opted to install the Full-Text RSS Site Config,
» add the following line to your ~/.config/offpunk/offpunkrc:
»
»   set ftr_site_config /usr/share/ftr-site-config
__EOT__
}

pre_upgrade () {
    new_version=$(echo "$1" | cut -d "." -f 1-2 )
    old_version=$(echo "$2" | cut -d "." -f 1-2 )

    if [[ "$old_version" < "3.0" ]] ; then
        post_install "$@"
    fi

    if [[ "$old_version" < "3.2" ]] ; then
        echo '========================================================================='
        echo '||                           /!\ WARNING /!\                           ||'
        echo '========================================================================='
        echo "Offpunk : Dependency 'python-requests' has been remplaced by 'curl' and is now recommended instead of suggested"
        echo "Offpunk : Dependency 'python-chardet' has been remplaced by 'python-charset-normalizer' and is now suggested"
    fi
}

# eof
