# shellcheck shell=bash
# -*- sh -*-

post_install() {
  cat <<__EOT__
» The opnk command has been renamed to openk. This is still
» available as a symlink, but it will be removed in a later
» release.
»
» If you have opted to install the Full-Text RSS Site Config,
» add the following line to your ~/.config/offpunk/offpunkrc:
»
»   set ftr_site_config /usr/share/ftr-site-config
__EOT__
}

post_upgrade() {
  post_install "$@"
}

# eof
