# arg 1: the new package version
post_install() {
  echo "Updating font cache... " 
  fc-cache -fs >/dev/null 2>&1
  mkfontscale /usr/share/fonts/local
  mkfontdir /usr/share/fonts/local
}

# arg 1: the new package version
# arg 2: the old package version
post_upgrade() {
  post_install $1
}

# arg 1: the old package version
post_remove() {
  fc-cache -fs >/dev/null 2>&1
  mkfontscale /usr/share/fonts/local
  mkfontdir /usr/share/fonts/local
}
