infodir=usr/share/info

post_install() {
    for file in oleo.info{,-1,-2,-3,-4}; do
        install-info $infodir/$file $infodir/dir 2> /dev/null
    done
    install-info --entry="* Oleo: (oleo). A lightweight spreadsheet program" \
        $infodir/oleo.info $infodir/dir
}

post_upgrade() {
    post_install
}

pre_remove() {
    for file in oleo.info{,-1,-2,-3,-4}; do
        install-info --delete $infodir/$file $infodir/dir 2> /dev/null
    done
}
