# Vulkan is currently an Experimental feature. To enable, you must set OLLAMA_VULKAN=1 for the Ollama server as described in the FAQ
# https://docs.ollama.com/faq#how-do-i-configure-ollama-server
OLLAMA_VULKAN=1

# Vulkan Environment Variables for Ollama Optimization
GGML_VK_VISIBLE_DEVICES=0,1,2,3
