# onenet-edpproto-debugger-wine.install
info() {
    echo -e "Wine OneNET EdpProto 调试工具，设备模拟器，运行环境Win7+"
}
post_install() {
    info
}
post_upgrade() {
    echo "deleting the onenet-edpproto-debugger bottle..."
    find /home -maxdepth 3 -name "onenet-edpproto-debugger" -exec rm -rf {} \;
    info
}
pre_remove() {
    echo "deleting the onenet-edpproto-debugger bottle..."
    find /home -maxdepth 3 -name "onenet-edpproto-debugger" -exec rm -rf {} \;
}
