
post_install() {
  echo "OpenJazz needs original Jazz Jackrabbit™ data files to play."
  echo "You can put them in '/usr/share/openjazz' for global installation or"
  echo "in ${XDG_DATA_HOME:-/.local/share}/openjazz' for yourself."
  echo "Legal game data download:"
  echo "        https://www.dosgamesarchive.com/related-games/jazz-jackrabbit"
}

post_remove() {
  if [ -d usr/share/openjazz ]; then
    echo "Remember to remove/backup installed data files in '/usr/share/openjazz'."
  fi
}
