post_upgrade() {
    update-desktop-database -q
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_install() {
    echo "You will need the original game assets to play this game, see https://github.com/OpenRA/ra2/wiki for details."
    echo "Beware you will need the expansion game assets, which are only in C&C: Ultimate Edition."
    post_upgrade
}

post_remove() {
    post_upgrade
}
