post_upgrade() {
  post_install
}

post_install() {
  echo -e "\nOpenMW needs the original Morrowind game files to run, and you need to tell OpenMW where they are."
  echo "You can specify the Data Files location by editing or creating:"
  echo -e "\n\t/home/<username>/.config/openmw/openmw.cfg\n"
  echo "Specify the full path to the Data Files directory after data=, no quotes, no escape characters."
  echo "For example:"
  echo -e "\n\tdata=/home/<username>/openmw/Data Files\n"
}
