#!/bin/sh
cd "/usr/lib/openra-mw"

# Run the game
mono --debug OpenRA.Game.exe Game.Mod=mw Engine.LaunchPath="/usr/bin/openra-mw" "Engine.ModSearchPaths=/usr/lib/openra-mw/mods" "$@"

# Show a crash dialog if something went wrong
if [ $? != 0 ] && [ $? != 1 ]; then
  ERROR_MESSAGE="OpenRA Medieval Warfare has encountered a fatal error.\nPlease refer to the crash logs and FAQ for more information.\n\nLog files are located in ~/.openra/Logs\nThe FAQ is available at http://wiki.openra.net/FAQ"
  if command -v zenity > /dev/null; then
    zenity --no-wrap --error --title "OpenRA Medieval Warfare" --text "${ERROR_MESSAGE}" 2> /dev/null
  elif command -v kdialog > /dev/null; then
    kdialog --title "OpenRA Medieval Warfare" --error "${ERROR_MESSAGE}"
  else
    printf "${ERROR_MESSAGE}\n"
  fi
  exit 1
fi

