post_install() {
    if ! getent group opendaylight >/dev/null; then
        groupadd opendaylight --system
    fi
    if ! getent passwd opendaylight >/dev/null; then
        useradd -c 'OpenDaylight user' -g opendaylight -d '/opt/opendaylight' \
            -s /bin/bash opendaylight --system
        passwd -l opendaylight >/dev/null
    fi

    chown -R opendaylight:opendaylight '/opt/opendaylight'
}

# vim: set ts=4 sw=4 et:
