
post_install() {
  echo "OpenJazz needs original Jazz Jackrabbit™ data files to play. You can put them in"
  echo "'/usr/share/openjazz' for global installation or in '~/.openjazz' for yourself."
  echo "Legal game data download:"
  echo "        http://www.dosgamesarchive.com/gamegroup/jazz-jackrabbit/"
}

post_upgrade() {
  post_install
}

post_remove() {
  if [ -d usr/share/openjazz ]; then
    echo "Remember to remove/backup installed data files in '/usr/share/openjazz'."
  fi
}
