#!/bin/sh

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/OpenSpace/lib/:/opt/OpenSpace/modules/webbrowser/ext/Release/"

export OPENSPACE_SYNC=$HOME/.config/openspace

exec /opt/OpenSpace/bin/OpenSpace "$@"

