#!/bin/bash

# Allow users to override command-line options
# Based on Gentoo's chromium package (and by extension, Debian's)
if [[ -f /etc/%pkgname%/default ]]; then
	. /etc/%pkgname%/default
fi

# Prefer user defined OPERA_USER_FLAGS (from env) over system
# default OPERA_FLAGS (from /etc/%pkgname%/default)
OPERA_FLAGS=${OPERA_USER_FLAGS:-$OPERA_FLAGS}

exec /usr/lib/%operabin% $OPERA_FLAGS "$@"
