all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

noteb() {
  printf "${blue}  ->${yellow} ${bold}$1${all_off}\n"
}

note() {
  printf "${blue}  ->${yellow} $1${all_off}\n"
}

post_install() {
  echo
  noteb "Action required before the first launch or after upgrade of the package:"
  echo  "sudo chown -R \$USER:\$USER /opt/orbitiny/{shared,usr/bin/.config}"
}

post_upgrade() {
    post_install
}
