#!/bin/sh

mkdir ~/.osudownloader # Make main folder with the needed tools
clear
echo "Downloading latest version of Osu.Masive.Beatmap.Downloader"
# Download the downloader using wget
if wget -q https://github.com/GarciaMiguelangel/Osu-Masive-Beatmap-Downloader/releases/download/v1.3-Beta/Osu.Masive.Beatmap.Downloader.jar ; then
	clear && echo "Success!" && mv Osu.Masive.Beatmap.Downloader.jar ~/.osudownloader/osudownload.jar
else
	clear && echo "The files couldn't be downloaded! Check your internet connection"
fi


