post_install() {
# EL7 magic
  /usr/bin/udevadm trigger --subsystem-match="virtio-ports" \
    --attr-match="name=com.redhat.rhevm.vdsm"
  /usr/bin/udevadm trigger --subsystem-match="virtio-ports" \
    --attr-match="name=ovirt-guest-agent.0"
  /usr/bin/udevadm trigger --subsystem-match="memory"
}

pre_remove() {
  /usr/bin/systemctl stop ovirt-guest-agent.service > /dev/null 2>&1

# non blocking uninstalled notification
  echo -e '{"__name__": "uninstalled"}\n' | dd \
    of=/dev/virtio-ports/com.redhat.rhevm.vdsm \
    oflag=nonblock status=noxfer conv=nocreat 1>& /dev/null || :

  echo -e '{"__name__": "uninstalled"}\n' | dd \
    of=/dev/virtio-ports/org.ovirt.vdsm \
    oflag=nonblock status=noxfer conv=nocreat 1>& /dev/null || :
}

post_remove() {
# Let udev clear access rights
  /usr/bin/udevadm trigger --subsystem-match="virtio-ports" \
    --attr-match="name=com.redhat.rhevm.vdsm"
  /usr/bin/udevadm trigger --subsystem-match="virtio-ports" \
    --attr-match="name=ovirt-guest-agent.0"
}
