#!/bin/sh

# Modified and improved version of Cisco's Script

# As for now, PacketTracer works with built-in arch libraries
# If you exprerience any troubles, try to uncomment
# the following line

export LD_LIBRARY_PATH="/opt/packettracer/bin"

exec /opt/packettracer/bin/PacketTracer7 "$@"

