PT7HOME=/opt/packettracer/
export PT7HOME

if QT_VERSION > QT_VERSION_CHECK(5, 5, 0)
QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_AUTO_SCREEN_SCALE_FACTOR
else
QT_DEVICE_PIXEL_RATIO=auto
export QT_DEVICE_PIXEL_RATIO
fi

