infodir="usr/share/info"
filelist=('parted.info')

post_install() {
  if [[ -x "/usr/bin/install-info" ]]; then
    for file in ${filelist[@]}; do
      install-info "${infodir}/${file}.gz" "${infodir}/dir" 2> /dev/null
    done
  fi
}

post_upgrade() {
  post_install
}

pre_remove() {
  if [[ -x "/usr/bin/install-info" ]]; then
    for file in ${filelist[@]}; do
      install-info --delete "${infodir}/${file}" "${infodir}/dir" 2> /dev/null
    done
  fi
}

# vim:set ts=2 sw=2 et:
