#!/usr/bin/env python3
# patch_entrypoints.py — Step 8
# Register VK_NV_low_latency2 entry points in NVK's dispatch table.
# Run from the mesa source root.
import re, pathlib, sys, textwrap

FUNCS = [
    'SetLatencySleepModeNV',
    'LatencySleepNV',
    'SetLatencyMarkerNV',
    'GetLatencyTimingsNV',
    'QueueNotifyOutOfBandNV',
]

base  = pathlib.Path('src/nouveau/vulkan')
mb_p  = base / 'meson.build'

# ── Diagnostic dump ──────────────────────────────────────────────────────────
print("==> Step 8 diagnostic: .py files under src/nouveau/vulkan/")
py_files = sorted(base.glob('*.py'))
for f in py_files:
    print(f"==>   {f}")
if not py_files:
    print("==>   (none)")

if mb_p.exists():
    mb = mb_p.read_text()
    # Print the lines that mention entrypoints so the log is informative.
    print("==> Step 8 diagnostic: meson.build lines mentioning entrypoints/gen:")
    for lineno, line in enumerate(mb.splitlines(), 1):
        if re.search(r'entrypoint|vk_entrypoints_gen|custom_target.*nvk_', line, re.I):
            print(f"==>   {lineno:4d}: {line}")
else:
    mb = ""
    print("==> Step 8 WARNING: meson.build not found!")

# ── Step 8a: find the existing entrypoints Python file ───────────────────────
# Strategy 1 – well-known names
candidates = [
    base / 'nvk_entrypoints.py',
    base / 'nvk_device_entrypoints.py',
    base / 'nvk_cmd_entrypoints.py',
]
# Strategy 2 – glob for anything with "entrypoint" in the name
for f in sorted(base.glob('*entrypoint*.py')):
    if f not in candidates:
        candidates.append(f)
# Strategy 3 – extract filename from meson.build (multiple patterns)
for pat in [
    # files('nvk_something.py') inside a vk_entrypoints_gen block
    r"vk_entrypoints_gen[^)]{0,400}files\(\s*['\"]([^'\"]+\.py)['\"]",
    # any files('*.py') near 'entrypoint' keyword within 5 lines
    r"entrypoint[^)]{0,200}files\(\s*['\"]([^'\"]+\.py)['\"]",
    # plain files('nvk_*.py')
    r"files\(\s*['\"](\bnvk_[^'\"]+\.py)['\"]",
]:
    for m in re.finditer(pat, mb, re.DOTALL | re.IGNORECASE):
        cand = base / m.group(1)
        if cand not in candidates:
            candidates.append(cand)
            print(f"==>   meson.build regex found candidate: {cand}")

ep_file = None
for c in candidates:
    if c.exists():
        ep_file = c
        print(f"==> Step 8: using entrypoints file: {ep_file}")
        break

if ep_file:
    # ── Patch the existing entrypoints file ──────────────────────────────────
    s = ep_file.read_text()

    missing = [f for f in FUNCS if f not in s]
    if not missing:
        print(f"==> {ep_file.name}: all NV_low_latency2 entry points already present — skipping.")
        sys.exit(0)

    print(f"==> {ep_file.name}: adding: {missing}")

    # Detect indent from existing entries
    indent = '    '
    m = re.search(r"^([ \t]+)['\"][A-Z][A-Za-z0-9]+['\"]", s, re.MULTILINE)
    if m:
        indent = m.group(1)

    new_lines = ''.join(f"{indent}'{f}',\n" for f in missing)

    # a) After the last NV/EXT/KHR entry
    last_nv = None
    for m in re.finditer(r"[ \t]*['\"][A-Z][A-Za-z0-9]+(NV|EXT|KHR)['\"][,]?[ \t]*\n", s):
        last_nv = m
    if last_nv:
        pos = last_nv.end()
        s = s[:pos] + new_lines + s[pos:]
        ep_file.write_text(s)
        print(f"==> {ep_file.name}: inserted after last NV/EXT/KHR entry.")
        sys.exit(0)

    # b) Before the last closing ]
    last_bracket = None
    for m in re.finditer(r'^\s*\]\s*$', s, re.MULTILINE):
        last_bracket = m
    if last_bracket:
        pos = last_bracket.start()
        s = s[:pos] + new_lines + s[pos:]
        ep_file.write_text(s)
        print(f"==> {ep_file.name}: inserted before closing ']'.")
        sys.exit(0)

    # c) Append
    s = s.rstrip('\n') + '\n# VK_NV_low_latency2 — added by PKGBUILD\n' + new_lines
    ep_file.write_text(s)
    print(f"==> {ep_file.name}: appended to end of file.")
    sys.exit(0)

# ── Step 8b: no existing entrypoints .py file found ─────────────────────────
# This happens when NVK does not yet have a dedicated entrypoints Python file
# (the extension list is embedded differently in meson.build).
# We create a minimal nvk_ll2_entrypoints.py and patch it into the
# vk_entrypoints_gen custom_target in meson.build.
print("==> Step 8: no existing entrypoints file — creating nvk_ll2_entrypoints.py")

NEW_EP_FILE = base / 'nvk_ll2_entrypoints.py'

# Build the entrypoints file in the format vk_entrypoints_gen.py expects.
# The generator reads a list called `override_functions` (or similar).
# We emit both the common formats seen in Mesa drivers so at least one works.
EP_CONTENT = textwrap.dedent("""\
    # VK_NV_low_latency2 entry points for NVK — generated by PKGBUILD
    # vk_entrypoints_gen.py reads the list below to emit dispatch-table
    # entries pointing to nvk_FunctionName() implementations.
    DEVICE_COMMANDS = [
        'SetLatencySleepModeNV',
        'LatencySleepNV',
        'SetLatencyMarkerNV',
        'GetLatencyTimingsNV',
    ]
    QUEUE_COMMANDS = [
        'QueueNotifyOutOfBandNV',
    ]
""")
NEW_EP_FILE.write_text(EP_CONTENT)
print(f"==> Created {NEW_EP_FILE}")

# Now wire it into meson.build.
if not mb_p.exists():
    print("==> Step 8 FATAL: meson.build missing — cannot wire new entrypoints file!", file=sys.stderr)
    sys.exit(1)

if 'nvk_ll2_entrypoints.py' in mb:
    print("==> meson.build: nvk_ll2_entrypoints.py already referenced — skipping.")
    sys.exit(0)

# Find the custom_target that produces nvk_entrypoints.h / nvk_entrypoints.c
# and inject our file into its `input :` list.
# Pattern covers both single-line and multi-line input arrays.
patched = False

# Pattern A: input that already uses files([...]) or files(...)
# e.g.  input : [vk_entrypoints_gen, files('nvk_entrypoints.py'), ...]
#   or  input : [vk_entrypoints_gen, 'nvk_entrypoints.py', ...]
for pat in [
    # files('existing.py') inside the same input list near nvk_entrypoints
    r"(custom_target\s*\(\s*['\"]nvk_entrypoints['\"][^)]{0,800}input\s*:\s*\[[^\]]*?)(\])",
    # any custom_target whose output mentions nvk_entrypoints.h
    r"(custom_target[^)]{0,200}output\s*:[^)]{0,200}nvk_entrypoints\.h['\"][^)]{0,200}input\s*:\s*\[[^\]]*?)(\])",
]:
    m = re.search(pat, mb, re.DOTALL)
    if m:
        insert = ",\n    files('nvk_ll2_entrypoints.py')"
        mb = mb[:m.end(1)] + insert + mb[m.end(1):]
        mb_p.write_text(mb)
        print(f"==> meson.build: injected nvk_ll2_entrypoints.py into nvk_entrypoints custom_target input.")
        patched = True
        break

if not patched:
    # Pattern B: append a brand-new vk_entrypoints_gen call for just our functions.
    # Find where the existing nvk_entrypoints custom_target ends and add ours after.
    # First try to locate the closing paren of the main custom_target.
    m = re.search(r"(custom_target\s*\(\s*['\"]nvk_entrypoints['\"].*?\)[ \t]*\n)",
                  mb, re.DOTALL)
    if m:
        insert_pos = m.end()
        new_target = textwrap.dedent(f"""\

            # VK_NV_low_latency2 extra entry points — injected by PKGBUILD
            nvk_ll2_entrypoints = custom_target(
              'nvk_ll2_entrypoints',
              input  : [vk_entrypoints_gen, files('nvk_ll2_entrypoints.py')],
              output : ['nvk_ll2_entrypoints.h', 'nvk_ll2_entrypoints.c'],
              command: [
                prog_python, '@INPUT0@',
                '--xml', vk_api_xml,
                '--proto', '--weak', '--beta',
                '--out-h', '@OUTPUT0@',
                '--out-c', '@OUTPUT1@',
                '@INPUT1@',
              ],
            )
            nvk_files += [nvk_ll2_entrypoints[0], nvk_ll2_entrypoints[1]]
        """)
        mb = mb[:insert_pos] + new_target + mb[insert_pos:]
        mb_p.write_text(mb)
        print("==> meson.build: added nvk_ll2_entrypoints custom_target (Pattern B).")
        patched = True

if not patched:
    # Last resort: print what we need the user to do manually and hard-fail.
    print("==> Step 8 FATAL: could not auto-patch meson.build.", file=sys.stderr)
    print("==>   Please inspect src/nouveau/vulkan/meson.build and add", file=sys.stderr)
    print("==>   'nvk_ll2_entrypoints.py' to the vk_entrypoints_gen custom_target", file=sys.stderr)
    print("==>   input list, then re-run makepkg.", file=sys.stderr)
    sys.exit(1)
