.TH PCLINK 1 "2.6.0" "PCLink" "User Commands"
.SH NAME
pclink \- Remote PC Control and File Management
.SH SYNOPSIS
.B pclink
[\fIOPTIONS\fR]
.SH DESCRIPTION
PCLink enables secure remote control and management of PCs from mobile devices.
.SH OPTIONS
.TP
\fB\-\-startup\fR
Start in headless mode (system tray only)
.TP
\fB\-\-help\fR
Show help message and exit
.SH FILES
.TP
\fI~/.config/pclink/\fR
User configuration directory
.SH AUTHOR
Azhar Zouhir <support@bytedz.xyz>
