post_install() {
    update-desktop-database -q
    systemctl daemon-reload
    # ln to old name to keep compatibility
    ln -s /usr/bin/peercoind /usr/bin/ppcoind

    echo ""
    echo "If you are having troubles with blockchain download, just backup wallet.dat, remove .ppcoin directory and start over."
}

post_upgrade() {
    post_install $1
}

post_remove() {
    post_install $1
    rm /usr/bin/ppcoind
}
