post_upgrade() {
    echo -e "\e[1;31m==================================> WARNING <=================================="
    echo -e "\e[1;31m==>\e[0m If you encounter any problem after upgrading Persepolis"
	echo -e "\e[1;32m==>\e[0m Remove persepolis settings from your home directory by following commands:"
	echo -e "\e[1;33m==>\e[0m rm -rf \"\$HOME/.config/persepolis_download_manager/setting\""
	echo -e "\e[1;33m==>\e[0m rm -rf \"\$HOME/.config/persepolis_download_manager/windows_size\""
    echo -e "\e[1;31m==================================> WARNING <=================================="	
}
