post_install() {
	echo ""
  echo "#########################################################################"
  echo "To create the database environment load the script /usr/share/pgagent.sql"
  echo "#########################################################################"
	echo ""
}

post_upgrade() {
	echo ""
  echo "#############################################################"
  echo "To update the database environment for the new version"
  echo "load the script /usr/share/pgagent_upgrade.sql (if provided)"
  echo "#############################################################"
	echo ""
}
