#!/bin/sh

if [ ! -z $XDG_CONFIG_HOME ]; then
    confdir=$XDG_CONFIG_HOME/PhoenixEmuProject
else 
    confdir=$HOME/.config/PhoenixEmuProject
fi
mkdir -p $confdir
cd  $confdir
if [ ! -d $confdir/scalers ]; then 
    cp -fr /opt/phoenix-emu-project/scales/ $confdir/scales/
fi 
if [ ! -d $confdir/shaders ]; then 
    cp -fr /opt/phoenix-emu-project/shaders/ $confdir/shaders/
fi 
if [ ! -d $confdir/skin ]; then 
    cp -fr /opt/phoenix-emu-project/skin/ $confdir/skin/
fi 
if [[ $LANG != "ru_RU"* ]]; then
    cp -f /opt/phoenix-emu-project/translation.xml.eng $confdir/translation.xml
fi
/opt/phoenix-emu-project/PhoenixEmuProject

