## (Ji_M)
## update Desktop Environment
__update_DE() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-desktop-database -q
}

## arrg 1:  the new package version
post_install() {
  __update_DE
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
  __update_DE
}

## arg 1:  the old package version
post_remove() {
  __update_DE
}

# vim:set ts=2 sw=2 et:
