cgi.fix_pathinfo=0
max_execution_time = 1000
max_input_time = 1000
memory_limit=512G

extension=bcmath
extension=exif
;extension=gd
;extension=gmp
;extension=pdo_dblib
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
;extension=xml
