post_install() {
  cat <<- EOF
    ==> please read configuration instructions at /usr/share/doc/pihole/configuration
    ==> first install/update run...
EOF
  cat /proc/net/if_inet6 2>&1 > /dev/null && touch /etc/pihole/.useIPv6
  /usr/bin/gravity.sh > /dev/null
  systemctl daemon-reload > /dev/null
  systemctl start pi-hole-gravity.timer > /dev/null
}

post_upgrade() {
  post_install $1
}

post_remove() {
  rm -R /etc/pihole/
}
