context.objects = [
    {   factory = adapter
        args = {
            factory.name         = api.alsa.pcm.sink
            node.name            = "Inferno sink"
            media.class          = Audio/Sink
            object.linger        = true
            session.suspend-timeout-seconds = 0
            node.pause-on-idle   = false
            node.suspend-on-idle = false
            node.always-process  = true
            api.alsa.path        = "inferno:RX_CHANNELS=24,TX_CHANNELS=24,NAME=highq"
            api.alsa.headroom    = 128
            api.alsa.pcm.card    = 999
        }
    }
    {   factory = adapter
        args = {
            factory.name         = api.alsa.pcm.source
            node.name            = "Inferno source"
            media.class          = Audio/Source
            object.linger        = true
            session.suspend-timeout-seconds = 0
            node.pause-on-idle   = false
            node.suspend-on-idle = false
            node.always-process  = true
            api.alsa.path        = "inferno:RX_CHANNELS=24,TX_CHANNELS=24,NAME=highq"
            api.alsa.headroom    = 128
            api.alsa.pcm.card    = 999
        }
    }
]
