# Define the lines to be added or removed
PIPER_CONFIG=/etc/speech-dispatcher/speechd.conf
PIPER_MODULE=/etc/speech-dispatcher/modules/piper-tts-generic.conf
VOICE_LINE=(
	'GenericLanguage "nl" "nl_BE" "utf-8"'
	'AddVoice "nl" "FEMALE1" "nl/nl_BE/nathalie/medium/nl_BE-nathalie-medium"'
	'AddVoice "nl" "FEMALE2" "nl/nl_BE/nathalie/x_low/nl_BE-nathalie-x_low"'
	'AddVoice "nl" "MALE1" "nl/nl_BE/rdh/medium/nl_BE-rdh-medium"'
	'AddVoice "nl" "MALE2" "nl/nl_BE/rdh/x_low/nl_BE-rdh-x_low"'
)
DEFAULT_VOICE='DefaultVoice "nl/nl_BE/nathalie/medium/nl_BE-nathalie-medium"'

post_install() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_CONFIG ]; then
    pkill -f speech-dispatcher || true
    if ! grep -q '^DefaultVoice' $PIPER_MODULE; then
        echo "$DEFAULT_VOICE" >> $PIPER_MODULE
    fi
    for LINE in "${VOICE_LINE[@]}"; do
      # Add the lines only if they do not already exist
      if ! grep -q "$LINE" $PIPER_MODULE; then
        echo "$LINE" >> $PIPER_MODULE
      fi
    done
  fi
}

post_remove() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "nl"/d' $PIPER_MODULE
    sed -i '/^AddVoice "nl"/d' $PIPER_MODULE
    sed -i '/^DefaultVoice "\/nl\//d' $PIPER_MODULE
  fi
}

post_upgrade() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "nl"/d' $PIPER_MODULE
    sed -i '/^AddVoice "nl"/d' $PIPER_MODULE
  fi
  post_install
}

