# Define the lines to be added or removed
PIPER_CONFIG=/etc/speech-dispatcher/speechd.conf
PIPER_MODULE=/etc/speech-dispatcher/modules/piper-tts-generic.conf
VOICE_LINE=(
	'GenericLanguage "ne" "ne_NP" "utf-8"'
	'AddVoice "ne" "MALE1" "ne/ne_NP/chitwan/medium/ne_NP-chitwan-medium"'
	'AddVoice "ne" "FEMALE1" "ne/ne_NP/google/medium/ne_NP-google-medium"'
	'AddVoice "ne" "FEMALE2" "ne/ne_NP/google/x_low/ne_NP-google-x_low"'
)
DEFAULT_VOICE='DefaultVoice "ne/ne_NP/chitwan/medium/ne_NP-chitwan-medium"'

post_install() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_CONFIG ]; then
    pkill -f speech-dispatcher || true
    if ! grep -q '^DefaultVoice' $PIPER_MODULE; then
        echo "$DEFAULT_VOICE" >> $PIPER_MODULE
    fi
    for LINE in "${VOICE_LINE[@]}"; do
      # Add the lines only if they do not already exist
      if ! grep -q "$LINE" $PIPER_MODULE; then
        echo "$LINE" >> $PIPER_MODULE
      fi
    done
  fi
}

post_remove() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "ne"/d' $PIPER_MODULE
    sed -i '/^AddVoice "ne"/d' $PIPER_MODULE
    sed -i '/^DefaultVoice "\/ne\//d' $PIPER_MODULE
  fi
}

post_upgrade() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "ne"/d' $PIPER_MODULE
    sed -i '/^AddVoice "ne"/d' $PIPER_MODULE
  fi
  post_install
}

