context.objects = [
    {
        factory = adapter
        args    = {
            factory.name     = support.null-audio-sink
            node.name        = "clownfish_playback"
            media.class      = "Audio/Sink"
            audio.position   = [ FL FR ]
            node.virtual     = true
        }
    }
]

context.modules = [
    {
        name = libpipewire-module-loopback
        args = {
            capture.props    = {
                node.name      = "clownfish_loopback_capture"
                node.target    = "clownfish_playback"
                stream.capture.sink = true
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name        = "clownfish_mic"
                node.description = "Clownfish Virtual Mic"
                media.class      = "Audio/Source"
                audio.position   = [ FL FR ]
            }
        }
    }
]
