# Define the lines to be added or removed
PIPER_CONFIG=/etc/speech-dispatcher/speechd.conf
PIPER_MODULE=/etc/speech-dispatcher/modules/piper-tts-generic.conf
VOICE_LINE=(
	'GenericLanguage "ar" "ar_JO" "utf-8"'
	'AddVoice "ar" "MALE1" "ar/ar_JO/kareem/medium/ar_JO-kareem-medium"'
	'AddVoice "ar" "MALE2" "ar/ar_JO/kareem/low/ar_JO-kareem-low"'

)
DEFAULT_VOICE='DefaultVoice "ar/ar_JO/kareem/medium/ar_JO-kareem-medium"'

post_install() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_CONFIG ]; then
    pkill -f speech-dispatcher || true
    if ! grep -q '^DefaultVoice' $PIPER_MODULE; then
        echo "$DEFAULT_VOICE" >> $PIPER_MODULE
    fi
    for LINE in "${VOICE_LINE[@]}"; do
      # Add the lines only if they do not already exist
      if ! grep -q "$LINE" $PIPER_MODULE; then
        echo "$LINE" >> $PIPER_MODULE
      fi
    done
  fi
}

post_remove() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "ar"/d' $PIPER_MODULE
    sed -i '/^AddVoice "ar"/d' $PIPER_MODULE
    sed -i '/^DefaultVoice "\/ar\//d' $PIPER_MODULE
  fi
}

post_upgrade() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "ar"/d' $PIPER_MODULE
    sed -i '/^AddVoice "ar"/d' $PIPER_MODULE
  fi
  post_install
}

