# Define the lines to be added or removed
PIPER_CONFIG=/etc/speech-dispatcher/speechd.conf
PIPER_MODULE=/etc/speech-dispatcher/modules/piper-tts-generic.conf
VOICE_LINE=(
	'GenericLanguage "ca" "ca_ES" "utf-8"'
	'AddVoice "ca" "FEMALE1" "ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium"'
	'AddVoice "ca" "FEMALE2" "ca/ca_ES/upc_ona/x_low/ca_ES-upc_ona-x_low"'
	'AddVoice "ca" "MALE1" "ca/ca_ES/upc_pau/x_low/ca_ES-upc_pau-x_low"'
)
DEFAULT_VOICE='DefaultVoice "ca/ca_ES/upc_ona/medium/ca_ES-upc_ona-medium"'

post_install() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_CONFIG ]; then
    pkill -f speech-dispatcher || true
    if ! grep -q '^DefaultVoice' $PIPER_MODULE; then
        echo "$DEFAULT_VOICE" >> $PIPER_MODULE
    fi
    for LINE in "${VOICE_LINE[@]}"; do
      # Add the lines only if they do not already exist
      if ! grep -q "$LINE" $PIPER_MODULE; then
        echo "$LINE" >> $PIPER_MODULE
      fi
    done
  fi
}

post_remove() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "ca"/d' $PIPER_MODULE
    sed -i '/^AddVoice "ca"/d' $PIPER_MODULE
    sed -i '/^DefaultVoice "\/ca\//d' $PIPER_MODULE
  fi
}

post_upgrade() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "ca"/d' $PIPER_MODULE
    sed -i '/^AddVoice "ca"/d' $PIPER_MODULE
  fi
  post_install
}

