# Define the lines to be added or removed
PIPER_CONFIG=/etc/speech-dispatcher/speechd.conf
PIPER_MODULE=/etc/speech-dispatcher/modules/piper-tts-generic.conf
VOICE_LINE=(
	'GenericLanguage "te" "te_IN" "utf-8"'
	'AddVoice "te" "FEMALE1" "te/te_IN/maya/medium/te_IN-maya-medium"'
	'AddVoice "te" "FEMALE2" "te/te_IN/padmavathi/medium/te_IN-padmavathi-medium"'
	'AddVoice "te" "MALE1" "te/te_IN/venkatesh/medium/te_IN-venkatesh-medium"'
)
DEFAULT_VOICE='DefaultVoice "te/te_IN/maya/medium/te_IN-maya-medium"'

post_install() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_CONFIG ]; then
    pkill -f speech-dispatcher || true
    if ! grep -q '^DefaultVoice' $PIPER_MODULE; then
        echo "$DEFAULT_VOICE" >> $PIPER_MODULE
    fi
    for LINE in "${VOICE_LINE[@]}"; do
      # Add the lines only if they do not already exist
      if ! grep -q "$LINE" $PIPER_MODULE; then
        echo "$LINE" >> $PIPER_MODULE
      fi
    done
  fi
}

post_remove() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "te"/d' $PIPER_MODULE
    sed -i '/^AddVoice "te"/d' $PIPER_MODULE
    sed -i '/^DefaultVoice "\/te\//d' $PIPER_MODULE
  fi
}

post_upgrade() {
  # Check if the piper-generic.conf file exists
  if [ -f $PIPER_MODULE ]; then
    # Remove the lines if they exist
    sed -i '/^GenericLanguage "te"/d' $PIPER_MODULE
    sed -i '/^AddVoice "te"/d' $PIPER_MODULE
  fi
  post_install
}

