# Maintainer: Derek Wisong
#
# This PKGBUILD was generated by `cargo aur`: https://crates.io/crates/cargo-aur

pkgname=datui-bin
pkgver=0.2.42
pkgrel=1
pkgdesc="Data Exploration in the Terminal"
url="https://derekwisong.github.io/datui"
license=("MIT")
arch=("x86_64")
provides=("datui")
conflicts=("datui")
depends=("fontconfig")
source=("https://github.com/derekwisong/datui/releases/download/v$pkgver/datui-$pkgver-x86_64.tar.gz")
sha256sums=("9269ef32405ec0dd04e009d21e02052a888121b8881abbc169e133b50970cd21")

package() {
    install -Dm755 datui -t "$pkgdir/usr/bin"
    install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
    install -Dm644 "target/release/datui.1.gz" "$pkgdir/usr/share/man/man1/datui.1.gz"
}
