# Maintainer: Agent Labs <support at nebula dot gg>
# Generated by the nebula-desktop stable release workflow.
pkgname=nebula-desktop-bin
pkgver=0.2.16
pkgrel=1
pkgdesc="Desktop companion app for nebula.gg"
arch=('x86_64')
url="https://github.com/agent-labs-dev/nebula-desktop/tree/main/apps/desktop"
license=('MIT')
depends=('alsa-lib' 'at-spi2-core' 'cairo' 'libcups' 'dbus' 'expat' 'gcc-libs' 'glib2' 'glibc' 'gtk3' 'libdrm' 'libnotify' 'libx11' 'libxcb' 'libxcomposite' 'libxdamage' 'libxext' 'libxfixes' 'libxkbcommon' 'libxrandr' 'libxss' 'mesa' 'nspr' 'nss' 'pango' 'systemd-libs' 'libayatana-appindicator')
provides=("nebula-desktop=$pkgver")
conflicts=('nebula-desktop')
options=('!strip')
install='nebula-desktop-bin.install'
source=("Nebula-0.2.16-x64.pacman::https://app-assets.nebula.gg/desktop/stable/0.2.16/Nebula-x64.pacman")
noextract=('Nebula-0.2.16-x64.pacman')
sha256sums=('26eb38b6cdee02124d819d625618a8d813b1ff07beff87887ceaf87daa0de2de')

package() {
  bsdtar -xf "$srcdir/Nebula-0.2.16-x64.pacman" -C "$pkgdir" \
    --exclude='.MTREE' --exclude='.PKGINFO' --exclude='.INSTALL'
  install -d "$pkgdir/usr/bin"
  ln -sf /opt/Nebula/nebula-desktop "$pkgdir/usr/bin/nebula-desktop"
  printf 'aur\n' > "$pkgdir/opt/Nebula/resources/package-type"
}
