.TH pkgcacheclean 8 "2016-05-22" "pkgcacheclean 1.8.2" "pkgcacheclean manual"
.SH NAME
pkgcacheclean \- a simple utility to clean pacman cache
.SH SYNOPSIS
.B pkgcacheclean
[option...] [preserve_number]
.SH DESCRIPTION
For installed packages, \fIpreserve_number\fR of versions are reserved. This
includes the current version and the newest (\fIpreserve_number\fR - 1) of the
remaining. For uninstalled packages all versions are deleted. The default
number is 2.
.SH OPTIONS
.TP
\-n, \-\-dry-run
Perform a trial run with no changes made
.TP
\-d, \-\-cachedir=PATH
Set alternative (absolute) cache directory PATH. Default is /var/cache/pacman/pkg/
.TP
\-k, \-\-all\-as\-installed
Treat not-installed packages as installed
.TP
\-v, \-\-verbose
Verbose output
.TP
\-q, \-\-quiet
Suppress output, default
.TP
\-?, \-\-help
Give a help list
.TP
\-\-usage
Give a short usage message
.TP
\-V, \-\-version
Print program version
.SH EXAMPLES
.TP
Do a verbose dry-run for cleaning up all but the latest 3 versions:
.B pkgcacheclean -nv 3
