plugins/rsvg/xp/Makefile
plugins/rsvg/Makefile
plugins/s5/xp/Makefile
plugins/s5/Makefile
plugins/hrtext/xp/Makefile
plugins/hrtext/Makefile
plugins/pdf/xp/Makefile
plugins/pdf/Makefile
plugins/goffice/Makefile
plugins/goffice/unix/Makefile
plugins/openxml/exp/xp/Makefile
plugins/openxml/exp/Makefile
plugins/openxml/omml_xslt/Makefile
plugins/openxml/Makefile
plugins/openxml/imp/xp/Makefile
plugins/openxml/imp/Makefile
plugins/openxml/common/xp/Makefile
plugins/openxml/common/Makefile
plugins/babelfish/xp/Makefile
plugins/babelfish/Makefile
plugins/iscii/xp/Makefile
plugins/iscii/Makefile
plugins/passepartout/xp/Makefile
plugins/passepartout/Makefile
plugins/psion/xp/Makefile
plugins/psion/Makefile
plugins/hancom/xp/Makefile
plugins/hancom/Makefile
plugins/t602/xp/Makefile
plugins/t602/Makefile
plugins/mswrite/xp/Makefile
plugins/mswrite/Makefile
plugins/paint/win/Makefile
plugins/paint/xp/Makefile
plugins/paint/Makefile
plugins/paint/unix/Makefile
plugins/garble/xp/Makefile
plugins/garble/Makefile
plugins/collab/backends/telepathy/Makefile
plugins/collab/backends/telepathy/unix/Makefile
plugins/collab/backends/sugar/Makefile
plugins/collab/backends/sugar/unix/Makefile
plugins/collab/backends/sipsimple/xp/Makefile
plugins/collab/backends/sipsimple/Makefile
plugins/collab/backends/sipsimple/unix/Makefile
plugins/collab/backends/Makefile
plugins/collab/backends/xmpp/xp/Makefile
plugins/collab/backends/xmpp/Makefile
plugins/collab/backends/xmpp/unix/Makefile
plugins/collab/backends/fake/xp/Makefile
plugins/collab/backends/fake/Makefile
plugins/collab/backends/service/win/Makefile
plugins/collab/backends/service/xp/Makefile
plugins/collab/backends/service/Makefile
plugins/collab/backends/service/unix/Makefile
plugins/collab/backends/tcp/win/Makefile
plugins/collab/backends/tcp/xp/Makefile
plugins/collab/backends/tcp/Makefile
plugins/collab/backends/tcp/unix/Makefile
plugins/collab/Makefile
plugins/collab/core/packet/xp/Makefile
plugins/collab/core/packet/Makefile
plugins/collab/core/sync/xp/Makefile
plugins/collab/core/sync/Makefile
plugins/collab/core/Makefile
plugins/collab/core/account/xp/Makefile
plugins/collab/core/account/Makefile
plugins/collab/core/dialogs/win/Makefile
plugins/collab/core/dialogs/xp/Makefile
plugins/collab/core/dialogs/Makefile
plugins/collab/core/dialogs/unix/Makefile
plugins/collab/core/plugin/xp/Makefile
plugins/collab/core/plugin/Makefile
plugins/collab/core/session/xp/Makefile
plugins/collab/core/session/Makefile
plugins/mathview/xp/Makefile
plugins/mathview/Makefile
plugins/mathview/itex2mml/Makefile
plugins/mathview/data/Makefile
plugins/opendocument/exp/xp/Makefile
plugins/opendocument/exp/Makefile
plugins/opendocument/Makefile
plugins/opendocument/imp/xp/Makefile
plugins/opendocument/imp/Makefile
plugins/opendocument/common/xp/Makefile
plugins/opendocument/common/Makefile
plugins/pdb/xp/Makefile
plugins/pdb/Makefile
plugins/docbook/xp/Makefile
plugins/docbook/Makefile
plugins/clarisworks/xp/Makefile
plugins/clarisworks/Makefile
plugins/gda/Makefile
plugins/gda/unix/Makefile
plugins/ots/xp/Makefile
plugins/ots/Makefile
plugins/Makefile
plugins/wikipedia/xp/Makefile
plugins/wikipedia/Makefile
plugins/wml/xp/Makefile
plugins/wml/Makefile
plugins/command/xp/Makefile
plugins/command/Makefile
plugins/opml/xp/Makefile
plugins/opml/Makefile
plugins/wmf/xp/Makefile
plugins/wmf/Makefile
plugins/loadbindings/xp/Makefile
plugins/loadbindings/Makefile
plugins/epub/exp/xp/Makefile
plugins/epub/exp/Makefile
plugins/epub/Makefile
plugins/epub/dialogs/win/Makefile
plugins/epub/dialogs/xp/Makefile
plugins/epub/dialogs/Makefile
plugins/epub/dialogs/gtk/Makefile
plugins/epub/imp/xp/Makefile
plugins/epub/imp/Makefile
plugins/epub/common/xp/Makefile
plugins/epub/common/Makefile
plugins/latex/xsltml/Makefile
plugins/latex/xp/Makefile
plugins/latex/Makefile
plugins/eml/xp/Makefile
plugins/eml/Makefile
plugins/bmp/xp/Makefile
plugins/bmp/Makefile
plugins/wpg/xp/Makefile
plugins/wpg/Makefile
plugins/applix/xp/Makefile
plugins/applix/Makefile
plugins/aiksaurus/aiksaurusgtk3/Makefile
plugins/aiksaurus/win/Makefile
plugins/aiksaurus/xp/Makefile
plugins/aiksaurus/Makefile
plugins/wordperfect/xp/Makefile
plugins/wordperfect/Makefile
plugins/gdict/Makefile
plugins/gdict/unix/Makefile
plugins/mht/xp/Makefile
plugins/mht/Makefile
plugins/openwriter/xp/Makefile
plugins/openwriter/Makefile
plugins/mif/xp/Makefile
plugins/mif/Makefile
plugins/urldict/xp/Makefile
plugins/urldict/Makefile
plugins/presentation/xp/Makefile
plugins/presentation/Makefile
plugins/sdw/xp/Makefile
plugins/sdw/Makefile
plugins/freetranslation/xp/Makefile
plugins/freetranslation/Makefile
plugins/xslfo/xp/Makefile
plugins/xslfo/Makefile
plugins/kword/xp/Makefile
plugins/kword/Makefile
plugins/gimp/xp/Makefile
plugins/gimp/Makefile
plugins/google/xp/Makefile
plugins/google/Makefile
plugins/grammar/patronuswrap/Makefile
plugins/grammar/xp/Makefile
plugins/grammar/Makefile
