post_install() {
  cat << EOF

Tab completion for Bash is enabled by package already.

To enable tab completion for Fish, or Zsh:

# Fish
poetry completions fish > ~/.config/fish/completions/poetry.fish

# Zsh
poetry completions zsh > ~/.zfunc/_poetry

Note: you may need to restart your shell in order for the changes to take effect.

For zsh, you must then add the following line in your ~/.zshrc before compinit:

fpath+=~/.zfunc

EOF
}

post_upgrade() {
  post_install
}
