#! /bin/bash
## helper script to run PRO.
GAMEDIR="GAMEDIRNAMESETBYPKGBUILD"
GAMEBINARY="GAMEBINARYNAMESETBYPKGBUILD"

## enforce opengl to workaround a bug that makes the game start in direct3d mode on linux -> "-force-glcore"
## https://docs.unity3d.com/Manual/OpenGLCoreDetails.html
OPTIONS="-force-glcore"

echo -e "--> \"${GAMEDIR}/${GAMEBINARY}\" ${OPTIONS} ${@}"
echo -e "..."

## to workaround an error that the game can't find some importtant files on some systems, we cd to the game root first
cd "${GAMEDIR}"

## start the game!
"${GAMEDIR}/${GAMEBINARY}" ${OPTIONS} ${@}

exit
