post_install() {
  cat <<'HELP'
Welcome to Polybarman!

Quick Start:

    # Usage example in your ~/.config/polybar/launch.zsh:
    autoload -Uz polybarman
    alias pbm=polybarman

    pbm require --id 'group/plugin-name' --src 'https://...'

    pbm apply

CLI Usage:

    # Assume you are logged in Zsh
    autoload -Uz polybarman   # <- for better UX add this line to your ~/.zshrc
    polybarman --help

More Info: https://codeberg.org/mohterbaord/polybarman

HELP
}

post_upgrade() {
  post_install
}
