#!/bin/sh
cd /usr/lib/portablemc

[ -d "$HOME/.minecraft" ] && portablemc_dir="$HOME/.minecraft" || portablemc_dir="${XDG_DATA_HOME:-$HOME/.local/share}/portablemc/"

# Uncomment to default to using system java
#args=""
#for i in "$@"; do
#	if [ "$i" = "start" ]; then
#		args="$args $i --jvm $(which java)"
#	else
#		args="$args $i"
#	fi
#done
#
#python -m portablemc --main-dir "$portablemc_dir" --work-dir "$portablemc_dir" $args

python -m portablemc --main-dir "$portablemc_dir" --work-dir "$portablemc_dir" "$@"
