#!/usr/bin/bash

# This is your Application ID, avoid conflict
appID="io.riceneeder.electronicwechat"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName="Electronic_WeChat"

# This is the state directory of your application, which is located under "XDG_DATA_HOME"
stateDirectory="EWeChat_Data"

# This is the target executable to launch
launchTarget="electron /usr/lib/electronic-wechat-uos-bin/app.asar --enable-wayland-ime --ozone-platform-hint=auto --wayland-text-input-version=3 --enable-features=AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoDecodeLinuxGL"

# Takes boolean value. When enabled, do not process XAuth files and forces wayland input method. Generally this should be true when possible.
waylandOnly="adaptive"

# Takes boolean value.
bindInputDevices="false"

# Takes boolean value. Binds /dev/video* into the sandbox. Required if target application uses /dev/video* interfaces directly instead of v4l2.
bindCameras="false"

# Takes boolean value. Binds PipeWire socket into the sandbox. Required if target application doesn't use Portals.
bindPipewire="false"

# Expose all GPUs. Takes boolean value, usually used in games.
gameMode="false"
