#!/usr/bin/bash

# This is your Application ID, avoid conflict
appID="go.to.library"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName="Z-Library"

# This is the state directory of your application, which is located under "XDG_DATA_HOME"
stateDirectory="Z-Library_Data"

# This is the target executable to launch
launchTarget="electron /usr/lib/z-library-bwrap/app.asar --ozone-platform-hint=auto --enable-wayland-ime --wayland-text-input-version=3 --gtk-version=3"

# Takes boolean value. When enabled, do not process XAuth files and forces wayland input method. Generally this should be true when possible.
waylandOnly="false"

# Takes boolean value.
bindInputDevices="false"

# Takes boolean value. Binds /dev/video* into the sandbox. Required if target application uses /dev/video* interfaces directly instead of v4l2.
bindCameras="false"

# Takes boolean value. Binds PipeWire socket into the sandbox. Required if target application doesn't use Portals.
bindPipewire="false"

# Expose all GPUs. Takes boolean value, usually used in games.
gameMode="false"

# Below you can set envs that will be imported into the application sandbox
