
post_install() {
    echo "Configuring QWD $1"
    sed -i 's/machines_insert=no/machines_insert=yes/' /usr/bin/qwdctl

    grep -q "perl_module"      /etc/httpd/conf/httpd.conf || echo "LoadModule perl_module modules/mod_perl.so" >> /etc/httpd/conf/httpd.conf
    # MPM ITK requires prefork, that conflicts with mpm_event
    sed -i 's/LoadModule mpm_event/#LoadModule mpm_event/'                   /etc/httpd/conf/httpd.conf
    sed -i 's/#LoadModule mpm_prefork_module/LoadModule mpm_prefork_module/' /etc/httpd/conf/httpd.conf
    grep -q "mpm_itk"          /etc/httpd/conf/httpd.conf || echo "LoadModule mpm_itk_module modules/mpm_itk.so" >> /etc/httpd/conf/httpd.conf
    grep -q "qemu-web-desktop" /etc/httpd/conf/httpd.conf || echo "Include conf/extra/qemu-web-desktop.conf" >> /etc/httpd/conf/httpd.conf

    apachectl restart
    qwdctl download

    ln -sf /var/lib/qemu-web-desktop/machines.html     /usr/share/qemu-web-desktop/html/desktop
    ln -sf /usr/share/qemu-web-desktop/html/desktop    /srv/http/qemu-web-desktop
    ln -sf /usr/share/qemu-web-desktop/html/desktop    /srv/http/
    ln -sf /var/lib/qemu-web-desktop/machines          /srv/http/desktop/

    url=https://gitlab.com/soleil-data-treatment/soleil-software-projects/qemu-web-desktop

    echo "QWD: Now connect to http://localhost/qemu-web-desktop (or remotely)."
    echo "Refer to"
    echo "  $url"
    echo "for further service configuration."
    echo "If you wish to pass-through a GPU, use 'qwdctl gpu' command."
}
