.TH Powercord "1" "August 2020" "2.0.0" "Usage"
.SH NAME
    Powercord
.SH DESCRIPTION
    A lightweight discord client mod focused on simplicity and performance.
.SH Usage
    powercord <COMMAND>
.SH Commands
    inject   - Injects the script into discord
    uninject - Uninjects the script from discord, returning it to its original state
.SH "SEE ALSO"
    https://github.com/powercord-org/powercord
