post_install() {
	echo ""  	
	echo "==> To enable precached on your system, the following commands will need to be run:"  	
	echo ""  	
	echo "==> $ sudo systemctl enable --now precached.service"
	echo "==> $ systemctl --user enable --now precached-trigger.service"
	echo ""  	

	#systemctl preset-all
}

pre_remove() {
	systemctl stop precached.service
}

post_remove() {
	rm -fr "/var/lib/precached/"
}

