#!/bin/zsh

# Variable Replacement tool
PKGBUILD=$(pwd)/PKGBUILD
setVar() {
  echo 'import("fs").then(fs=>fs.writeFileSync("'"$PKGBUILD"'",fs.readFileSync("'"$PKGBUILD"'","utf-8").replace(/(?<='$1'=")[a-zA-Z0-9_]*(?=")/,"'$2'")))' | node;
}

# Get package info
source $PKGBUILD;

# Update the PKGBUILD version
setVar _pkgdate $(date +'%Y%M%d_%H%M_%S');

# Clone the repo
cd /tmp
tmpdir=/tmp/$_reponame-$_pkgname-$_pkgdate
git clone "$_repo" $tmpdir
cd $tmpdir/$_pkgsubdir;

# Update the PKGBUILD commit
setVar _pkgcommit $(git rev-parse --short HEAD);

# Cleanup
rm -rf $tmpdir;

# Get the package
source $PKGBUILD;
tmpdir=/tmp/pixelnuke-zip-$pkgver
mkdir -p $tmpdir;
cd $tmpdir;
curl -o pixelflut-repo.zip $source[1];
# unzip pixelflut-repo.zip;

# Update the PKGBUILD hash
setVar _pkghash $(sha512sum pixelflut-repo.zip);

# Cleanup
rm -rf $tmpdir;
