post_install() {
	ln -s /opt/processing/processing.desktop /usr/share/applications/processing.desktop
	# Symlink all sizes of icon.
	ln -s /opt/processing/lib/icons/pde-16.png /usr/share/icons/hicolor/16x16/apps/processing.png
	ln -s /opt/processing/lib/icons/pde-32.png /usr/share/icons/hicolor/32x32/apps/processing.png
	ln -s /opt/processing/lib/icons/pde-64.png /usr/share/icons/hicolor/64x64/apps/processing.png
	ln -s /opt/processing/lib/icons/pde-128.png /usr/share/icons/hicolor/128x128/apps/processing.png
	ln -s /opt/processing/lib/icons/pde-256.png /usr/share/icons/hicolor/256x256/apps/processing.png
	ln -s /opt/processing/lib/icons/pde-512.png /usr/share/icons/hicolor/512x512/apps/processing.png
	ln -s /opt/processing/lib/icons/pde-1024.png /usr/share/icons/hicolor/1024x1024/apps/processing.png
	# Finished symlinking icons.
	ln -s /opt/processing/processing /usr/bin/processing
}
pre_remove() {
	rm /usr/share/applications/processing.desktop
	# The -f flag disables warnings for nonexistant files,
	# since there isn't every possible icon size.
	rm -f /usr/share/icons/hicolor/*/apps/processing.png
	rm /usr/bin/processing
}
