post_install() {
    echo ">> Documentation: https://wiki.archlinux.org/index.php/Prosody"
}

post_upgrade() {
    post_install $1
}

post_remove() {
    paths=(/etc/prosody /var/lib/prosody /var/log/prosody
           /var/log/old/prosody)
    first=true
    for path in ${paths[@]}; do
        if [ -d $path ]; then
            if $first; then
                first=false
                echo "==> Leftover Paths:"
            fi
            echo "==> $path"
        fi
    done
}
