#!/bin/sh

# This file is used to invoke nanopb_generator.py as a plugin
# to protoc on Linux and other *nix-style systems.
# Use it like this:
# protoc --nanopb_out=dir foo.proto

exec /usr/share/nanopb/generator/nanopb_generator.py --protoc-plugin
