.\"     Title: PSBL
.\"    Author: Yaroslav Halchenko
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: February  4, 2004
.\"    Manual: 
.\"    Source: 
.\"
.TH "PSBL" "1" "February 4, 2004" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
psbl \- A program for automatic booklet formatting of postscript files
.SH "SYNOPSIS"
.HP 5
\fBpsbl\fR [\fB\-help\fR] [\fB\-lastbbox\fR] [\fB\-impose_option\ \fR\fB\fIio\fR\fR] [\fB\-lpi\ \fR] [\fB\-max_pages\ \fR\fB\fImp\fR\fR\fB\ \fR] [\fB\-evenodd\ \fR]\fI postscript\&.file \fR
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBpsbl\fR\&. Run it with \'\-help\' to see description of options
.PP
This manual page was written for the
Debian(TM)
distribution because the original program does not have a manual page\&.
.SH "SEE ALSO"
.PP
impose (1), fixtd (1), bboxx (1)\&.
.SH "AUTHOR"
.PP
This manual page was written by Yaroslav Halchenko
<debian@onerussian\&.com>
for the
Debian(TM)
system (but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the
GNU
General Public License, Version 2 any later version published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common\-licenses/GPL\&.
.SH "AUTHOR"
.PP
\fBYaroslav Halchenko\fR
.sp -1n
.IP "" 4
Author.
.SH "COPYRIGHT"
Copyright \(co 2003 Yaroslav Halchenko
.br
