post_install() {
  note() {
    all_off="$(tput sgr0)"
    bold="${all_off}$(tput bold)"
    blue="${bold}$(tput setaf 4)"
    yellow="${bold}$(tput setaf 3)"

    echo "${blue}==>${yellow} NOTE:${bold} ${1}${all_off}"
  }

  echo ''
  note '##############################################################'
  note '## https://pa-dlna.readthedocs.io/en/stable/configuration.html'
  note '## To enable the pulseaudio-dlna service, run:'
  note '## systemctl --user enable --now pulseaudio-dlna.service'
  note '##############################################################'
  echo ''
}
post_upgrade() {
  post_install
}
