post_install() {
	cat << EOF
---------------------------------------------------------------------------
To install documentation for PyMTP, install epydoc and issue the following 
command to have the documentation installed in <output directory>: 
epydoc -o <output directory> pymtp.py
---------------------------------------------------------------------------
EOF
}

post_upgrade() {
	post_install
}
