post_install() {
  echo "Do not forget to check the release notes!"
  echo "https://pynote.readthedocs.org/en/latest/changelog.html"
}

post_upgrade() {
  echo "Do not forget to check the release notes!"
  echo "https://pynote.readthedocs.org/en/latest/changelog.html"
  echo "You find upgrade instructions here:"
  echo "https://pynote.readthedocs.org/en/latest/faq.html#upgrading-from-0-2-to-1-0"
}
