.\" Copyright (C) 2011 Ben Dowling <http://www.coderholic.com/pyradio>
.\" This manual is freely distributable under the terms of the GPL.
.\"
.TH PYRADIO 1 "November 2018"

.SH NAME
.PP
pyradio \- a console based Internet radio player

.SH SYNOPSIS
.PP
\fBpyradio\fR
.RI \fI[OPTIONS]
[path/to/]stations.csv

.SH DESCRIPTION
.PP
.B pyradio
is a command line internet radio player. 
.PP
It will use one of the following players: \fImpv\fR, \fImplayer\fR or \fIvlc\fR, detected in that order. If none of them is detected, \fBpyradio\fR will \fBsilently\ terminate\fR (use \fB-d\fR option to get a log file).
.PP
If \fImpv\fR is detected, \fIsocat\fR is required too.
.PP
It is possible to use 
a custom stations list in \fB~/.pyradio/stations.csv.
.PP
If custom stations list is missing, \fBpyradio\fR would use a 
default one.

.SH OPTIONS

.IP \fB-h\fR,\fB\ \--help            
Show this help message and exit.
.IP \fB-s\fR,\fB\ \--stations\ \fI[STATIONS]
Use specified station CSV file.
.IP \fB-p\fR,\fB\ \--play\ \fI\<PLAY\>
Play station number \fI\<PLAY\>\fR. Select randome station if \fI\<PLAY\>\fR not specified.
.IP \fB-r\fR,\fB\ \--random          
Start and play a random station.
.IP \fB-a\fR,\fB\ \--add             
Add station to list.
.IP \fB-l\fR,\fB\ \--list            
List of added stations.
.IP \fB-u\fR,\fB\ \--use-player\ \fI[USE_PLAYER]
Specify which player to use (\fImpv\fR,\ \fImplayer\fR\ or\ \fIcvlc\fR).
.IP \fB-d\fR,\fB\ \--debug           
Debug mode (pyradio.log created). To be attached with any bug report.

.SH CONTROLS

.IP \fB\Up/Down/PgUp/PgDown     
Change station selection
.IP \fBj/k
Change station selection (vi-like)
.IP \fBEnter                   
Play selected station
.IP \fB-/+                     
Change volume
.IP \fBv
Save volume (mpv and mplayer only)
.IP \fBm                       
Mute
.IP \fBr                       
Select and play a random station
.IP \fBSpace                   
Stop/start playing selected station
.IP \fBEsc/q                   
Quit

.SH FILES
.PP
.I /usr/share/doc/pyradio/stations.csv

.I /usr/share/doc/pyradio/README.md

.I /usr/share/licenses/pyradio/LICENSE

.SH AUTHOR
.PP
 \fBBen Dowling <http://www.coderholic.com/pyradio>
.PP
 The man page was written by \fBaksr <aksr at t-com dot me>\fR for Arch Linux.
