[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyre-extensions"
version = "0.0.32"
description = "Type system extensions for use with the pyre type checker"
readme = "pyre_extensions/README.md"
license = { text = "MIT" }
authors = [
  { name = "Facebook", email = "pyre@fb.com" },
]
dependencies = [
  "typing-inspect",
  "typing-extensions",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Console",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Typing :: Typed",
]

[project.urls]
Homepage = "https://pyre-check.org"
Source = "https://github.com/facebook/pyre-check"

[tool.setuptools.packages.find]
include = ["pyre_extensions*"]
