post_install() {
	printf "\n\033[1;33m  ==> DEPRECATION WARNING:\033[0m\n"
	cat <<- EOF
	  This package (python-gdspy) is now legacy and was archived
	  upstream on Aug 9, 2024. It will no longer receive updates.

	  The official recommendation is to migrate to: python-gdstk
	  NOTE: This is NOT a drop-in replacement. 

	  This package remains available for backward-compatibility with 
	  legacy scripts only.

	EOF
}

post_upgrade() {
  post_install
}

# vim: set ts=4 sw=4 et:
