post_install() {
	cat <<- EOF 1>&2
		--> WARNING: Panflute is not 100% compatible with Pandoc 2.10+. Most
		--> notibly anything to do with tables is not supported, see upstream
		--> issue here: https://github.com/sergiocorreia/panflute/issues/142
		--> In order to use, please downgrade Pandoc to 2.9.x (one way is to
		--> use a pacman mirror that has an archive of old packages, then add
		--> Pandoc to your HoldPkg list).
	EOF
}

post_upgrade() {
	post_install
}
