#!/bin/sh
# Q3Rally Arch Linux Launcher
exec quake3 +set com_basegame baseq3r +set com_gamename Q3Rally \
  +set com_legacyprotocol 0 +set com_homepath .q3rally \
  +set sv_master1 master.q3rally.com "$@"