.TH QTCREATOR 1 "March  5, 2009"
.SH NAME
qtcreator \- Integrated Development Environment for Qt
.SH SYNOPSIS
.B qtcreator
.RI [ options ] " file(s)"
.br
.SH DESCRIPTION
.B Qt Creator
is a lightweight, cross-platform integrated development environment (IDE)
designed to make development with the Qt application framework faster and
easier.
.SH OPTIONS
.TP
.B \-help
Show summary of options.
.TP
.B \-version
Show version of program.
.TP
.B \-client
Attempt to connect to already running instance.
.TP
.B \-noload \fI<plugin>\fB
Do not load \fI<plugin>\fB
.TP
.B file(s)
Files to load.
.SH SEE ALSO
.br
The full documentation is available in /usr/share/qtcreator/doc
.SH AUTHOR
This manual page was written by Adam Majer <adamm@zombino.com> and
Jeremy Laine <jeremy.laine@m4x.org>, for the Debian project
(and may be used by others).
