message_the_user() {
  echo "If not already done, you might want to add your user to the following groups:"
  echo 'usermod -a -G efusb $USER'
  echo 'usermod -a -G uucp $USER'
  echo "This ensures proper device permissions for communication."
  echo 'This package automatically manages device permissions through the use of a new "efusb" group'
  echo "If you want to run nut along with this software, remove all nut-related files/lines in /etc/udev/rules.d"
  echo "Then run: 'udevadm control --reload; udevadm trigger'"
  echo "then, add the nut user to the efusb group: usermod -a G efusb nut"
  echo "You may need to reboot after these changes"
  echo "You may also need to unpulug and plug in the usb connection to the device"
}

post_install() {
  message_the_user "$1"
}

post_upgrade() {
  message_the_user "$1"
}

post_remove() {
 udevadm control --reload
}
