		# This is a Nginx location block for the radicle-explorer SPA,
		# to be included or pasted into a server{...} block.
		#
		# To customize the SPA (e.g., provide the default Radicle node
		# port/endpoint), copy /usr/share/radicle-explorer/config.json
		# into /etc/radicle-explorer/config.json and edit it.

		location / {
			root /usr/share/radicle-explorer;
			try_files $uri $uri/ /index.html;
		}

		location = /config.json {
			root /;
			try_files /etc/radicle-explorer/config.json /usr/share/radicle-explorer/config.json =404;
		}

		# For convenience, this is an example Nginx location block for
		# a local radicle-httpd instance, if one wishes to run it
		# alongside the radicle-explorer web app on the same domain.

		location ~ "^/(raw|api|[a-zA-Z0-9]{28-29}(\.git)?)(/|$)" {
			proxy_pass http://127.0.0.1:8777;

			proxy_http_version 1.1;
			proxy_set_header   Connection        "";

			proxy_set_header   Host              $host;
			proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
			proxy_set_header   X-Forwarded-Proto $scheme;
		}
