post_install() {
cat << EOF

raxml has installed all buildable executables, falling into categories

1.  your hardware (AVX, AVX2, SSE)
2.  parallel pthreads versions
3.  coarse grained MPI versions
4.  hybrid MPI/pthreads versions

if you either want (or need) an executable that is just called raxml,
create a symlink like this to your preferred variant:

    ln -s /usr/bin/raxmlHPC-PTHREADS-AVX2 /usr/bin/raxml

EOF
}

post_upgrade() {
  post_install
}
