// SPDX-License-Identifier: GPL-3.0-or-later
= Neon Knights Themes - Openbox

[quote]
Dark Openbox theme with vivid colors.

This package includes:
....
neon-knights-openbox-blue 1.1
neon-knights-openbox-green 1.1
neon-knights-openbox-orange 1.1
neon-knights-openbox-red 1.1
neon-knights-openbox-violet 1.1
neon-knights-openbox-yellow 1.1
....

Upstream URLs:

- https://www.pling.com/p/1307202/[Pling]
- https://www.opencode.net/ju1464/Neon_Knights_Themes/-/archive/master/Neon_Knights_Themes-master.tar.bz2[Source tar.bz2]
- https://www.opencode.net/ju1464/Neon_Knights_Themes.git[Repository]

== Copying

Please refer to link:CREDITS[CREDITS] (copied from upstream) for
detailed authorial information on package sources.

=== The PKGBUILD

`Copyright (c) 2019 Elias Elwyn, GPLv3.0+`

Please refer to link:COPYING[COPYING], or contact
<mailto:a@jthv.ai[a@jthv.ai]>.

This script is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 3 of the License, or (at your
option) any later version.

This script is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.
