#!/bin/bash
#
# Run `ldd` on each binary in /usr/bin and save the broken ones grouped by repo.

shopt -s nullglob

readonly REBUILD_DETECTOR_CACHE_DIR="/var/cache/rebuild-detector"
mkdir -p "$REBUILD_DETECTOR_CACHE_DIR"


get_installed_pkgs() {
    printf -v installed '[%s]' "$(gettext installed)"
    pacman -Sl | awk -v i="$installed" '$NF == i { print $1,$2 }'
}

get_binaries() {
    find -L /usr/bin -type f -print0 | xargs -0 readlink -f
}

get_broken_pkgs() {
     parallel --will-cite 'ldd "{}" 2>/dev/null | grep "not found" >/dev/null && pacman -Qo "{}" | cut -d" " -f5'
}

get_pkg_repo() {
    grep " $1" installed | cut -d' ' -f1
}


tmp=$(mktemp -dt "rebuild-detector.XXXXXXXX") || exit
trap 'rm -rf $tmp' EXIT
cd "$tmp" || exit

get_installed_pkgs >installed
get_binaries | get_broken_pkgs >broken

rm -f "$REBUILD_DETECTOR_CACHE_DIR/"*.list

while read -r pkg; do
    repo="$(get_pkg_repo "$pkg")"
    echo "$pkg" >>"$REBUILD_DETECTOR_CACHE_DIR/$repo.list"
done <broken

for list in "$REBUILD_DETECTOR_CACHE_DIR/"*.list; do
    sort -u "$list" -o "$list"
done

exit 0
