# https://github.com/dedicatedcode/reitti/blob/main/README.md#environment-variables

SERVER_ADDRESS="127.0.0.1"
SERVER_PORT=8080

POSTGIS_HOST="127.0.0.1"
POSTGIS_PORT=5432
POSTGIS_DB="reitti"
POSTGIS_USER="reitti"
POSTGIS_PASSWORD=""
LOGGING_LEVEL="INFO"

RABBITMQ_HOST="127.0.0.1"
RABBITMQ_PORT=5672
RABBITMQ_USER="reitti"
RABBITMQ_PASSWORD="reitti"
RABBITMQ_VHOST="/"

REDIS_HOST="127.0.0.1"
REDIS_PORT=6379
REDIS_USERNAME=""
REDIS_PASSWORD=""

DISABLE_LOCAL_LOGIN=false

OIDC_ENABLED=false
OIDC_SIGN_UP_ENABLED=true
OIDC_CLIENT_ID=""
OIDC_CLIENT_SECRET=""
OIDC_ISSUER_URI=""
OIDC_SCOPE="openid,profile"
OIDC_AUTHENTICATION_METHOD="client_secret_basic"

ADVERTISE_URI=""

DANGEROUS_LIFE=false

PROCESSING_WAIT_TIME=15

PHOTON_BASE_URL=""

REITTI_PROCESS_DATA_CRON="0 */10 * * * *"

CUSTOM_TILES_SERVICE=""
CUSTOM_TILES_ATTRIBUTION=""

PROCESSING_BATCH_SIZE=1000
PROCESSING_WORKERS_PER_QUEUE="4-16"

REITTI_STORAGE_PATH="/var/lib/reitti"
