# # Configure the rebuild reminder dialog. $pkgname, $pkgver and $pkgrel are available.
#
# # Default values
# app_name=$pkgname
# message="Kwin was updated. It is necessary to rebuild $pkgname."
# icon=update-medium
# urgency=normal
# action="Execute configured function"
#
# # Defining a do_rebuild function will offer an action with label $action.
# # This allows the user to both choose the method to rebuild the package as well as the interactive environment to do it in.
# # The function will be executed in the user's environment.
# # Example do_rebuild:
# do_rebuild() {
#   konsole --hold -e makepkg --dir /path/to/package --cleanbuild --syncdeps --force --install --rmdeps
# }
#
# # It is possible to explicitly define the users who should receive the message.
# # If not set, it will default to all logged in users.
# # This option does nothing if defined in a local config file.
# # Example users:
# users=(me you them)
