post_install() {
    printf "$(tput setaf 4)You will also need to set environment variables for Houdini to find RenderMan. For example, for Houdini 19.5.805 default version, edit the following file:$(tput sgr0)\n\n"
    printf "$(tput setaf 2)~/houdini19.5/houdini.env$(tput sgr0)\n\n"
    printf "$(tput setaf 4)And set the environment as follows:$(tput sgr0)\n\n"
    printf "$(tput setaf 2)RMANTREE=/opt/pixar/RenderManProServer-26.0$(tput sgr0)\n"
    printf "$(tput setaf 2)RFHTREE=/opt/pixar/RenderManForHoudini-26.0$(tput sgr0)\n"
    printf "$(tput setaf 2)RMAN_PROCEDURALPATH=\$RFHTREE/3.9/19.5.805/openvdb:&$(tput sgr0)\n"
    printf "$(tput setaf 2)HOUDINI_PATH=\$RFHTREE/3.9/19.5.805:&$(tput sgr0)\n"
}

post_upgrade() {
    post_install $1
}
