version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".gitignore",
    "aspia-router.install",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
