# https://rimgo.codeberg.page/docs/usage/configuration/
# Commented values are the defaults as of v1.4.2

#ADDRESS=0.0.0.0
#PORT=3000

# Should not be changed unless you have a registered Imgur app
IMGUR_CLIENT_ID=546c25a59c58ad7

# Use the X-Forwarded-Proto header for the base URL scheme
#PROTOCOL_DETECTION=0

# Whether the instance uses HTTPS
#SECURE=0

# Use WebP for images unless the no_webp query parameter is set
#FORCE_WEBP=0

# Privacy info is required to be in the public instance list, encouraged otherwise

# Optional, URL to privacy policy
#PRIVACY_POLICY=

# Optional, message to display on privacy page
#PRIVACY_MESSAGE=

# (clearnet only) The country the instance is located
#PRIVACY_COUNTRY=

# (clearnet only) The provider the instance is using (ISP for self-hosted, or hosting provider)
#PRIVACY_PROVIDER=

# Whether the instance uses Cloudflare proxy (orange cloud icon)
#PRIVACY_CLOUDFLARE=

# (required) Whether the instance collects data (ie Traefik proxy does not (set this to true), Nginx does by default (set this to false))
#PRIVACY_NOT_COLLECTED=

# Whether the instance collects IP addresses
#PRIVACY_IP=

# Whether the instance collects request URLs
#PRIVACY_URL=

# Whether the instance collects user agents
#PRIVACY_DEVICE=

# Whether the instance only collects this data for diagnostic purposes
#PRIVACY_DIAGNOSTICS=

# https://rimgo.codeberg.page/docs/usage/proxy/
#HTTP_PROXY=
#HTTPS_PROXY=
