post_install() {
    echo
    echo "  It is very convenient to create the following aliases:"
    echo
    echo "    alias rm='rmtrash'"
    echo "    alias rmdir='rmdirtrash'"
    echo "    alias sudo='sudo '"
    echo
}

post_remove() {
    echo
    echo "  Make sure to delete the following aliases if you created them:"
    echo
    echo "    alias rm='rmtrash'"
    echo "    alias rmdir='rmdirtrash'"
    echo "    alias sudo='sudo '"
    echo
}
