#Type  Path                    Mode   User   Group     Age    Argument
d      /etc/rnacos             0755   root   rnacos    -      -
d      /var/lib/rnacos         0750   rnacos rnacos    -      -
z      /etc/rnacos/env.conf    0664   root   rnacos    -      -
