#!/bin/bash

cp -vf /boot/dtbs/rk3288-miqi.dtb /boot/dtbs/rk3288-openhour.dtb
echo "Editing rk3288-openhour.dtb for differences between Openhour Chameleon and Miqi"
fdtput /boot/dtbs/rk3288-openhour.dtb -d   /mmc@ff0f0000 non-removable
fdtput /boot/dtbs/rk3288-openhour.dtb -t u /mmc@ff0f0000 bus-width 4
fdtput /boot/dtbs/rk3288-openhour.dtb -t s /mmc@ff0f0000 cap-sd-highspeed
fdtput /boot/dtbs/rk3288-openhour.dtb -t x /mmc@ff0f0000 card-detect-delay 0xc8

rootdev=$(lsblk -pilno pkname,type,mountpoint | grep -G 'part /$' |  head -n1 | cut -d " " -f1)
partlabeluboot=$(lsblk -plno partlabel $rootdev | grep -G '\-uboot$' )
[ ! -n "$partlabeluboot" ] && exit 0
rkdev=${partlabeluboot#*-}
target=${partlabeluboot%"-$rkdev"}
rkdev=${rkdev/"-uboot"/""}
if [[ "$rkdev" =~ "@" ]]; then
  atfdevice=${rkdev#*@}
  rkdev=${rkdev%"@$atfdevice"}
fi

cp -vf "/boot/dtbs/${target}-${rkdev}.dtb" "/boot/dtbs/${target}-tojoin.dtb"
for bp in $(shopt -s nullglob; echo /boot/dtbos/*.dts); do
  echo Creating overlay from $bp
  dtc -q -I dts -O dtb -o ${bp/".dts"/".dtbo"} $bp
  cat $bp | grep "//fdtput" | while read -r line ; do
    echo fdtput "/boot/dtbs/${target}-tojoin.dtb" ${line/"//fdtput"/""}
         fdtput "/boot/dtbs/${target}-tojoin.dtb" ${line/"//fdtput"/""}
  done
done

dtbos="$(shopt -s nullglob; echo /boot/dtbos/${target}-all-*.dtbo /boot/dtbos/${target}-${rkdev}-*.dtbo)"
if test -n "$dtbos"; then
  fdtoverlay -vi "/boot/dtbs/${target}-tojoin.dtb" \
              -o "/boot/dtbs/${target}-joined.dtb" \
              $dtbos
else
  echo "No overlay applied!"
  cp -vf "/boot/dtbs/${target}-tojoin.dtb" \
         "/boot/dtbs/${target}-joined.dtb"
fi
exit 0
