#!/bin/bash
if [ -f "/boot/dtbs/rk3288-miqi.dtb" ]; then
  cp -vf /boot/dtbs/rk3288-miqi.dtb /boot/dtbs/rk3288-openhour.dtb
  echo "Editing rk3288-openhour.dtb for differences between Openhour Chameleon and Miqi"
  fdtput /boot/dtbs/rk3288-openhour.dtb -d   /mmc@ff0f0000 non-removable
  fdtput /boot/dtbs/rk3288-openhour.dtb -t u /mmc@ff0f0000 bus-width 4
  fdtput /boot/dtbs/rk3288-openhour.dtb -t s /mmc@ff0f0000 cap-sd-highspeed
  fdtput /boot/dtbs/rk3288-openhour.dtb -t x /mmc@ff0f0000 card-detect-delay 0xc8
fi
for bp in $(shopt -s nullglob; echo /boot/dtbos/*.dts); do
  echo Creating overlay from $bp
  dtc -q -I dts -O dtb -o ${bp/".dts"/".dtbo"} $bp
  cat $bp | grep "//fdtput" | while read -r line ; do
    echo fdtput ${line/"//fdtput"/""}
         fdtput ${line/"//fdtput"/""}
  done
done
target="rk3288"
ubootdev=$(ls /dev/disk/by-partlabel/${target}-*-uboot | head -n1)
[ ! -L "$ubootdev" ] && exit 0
[ ! -n "$ubootdev" ] && exit 0
rkdev=$(basename $ubootdev)
rkdev=${rkdev/"${target}-"/""}
rkdev=${rkdev/"-uboot"/""}
fdtoverlay -vi "/boot/dtbs/${target}-${rkdev}.dtb" \
            -o "/boot/dtbs/${target}-joined.dtb" \
            $(shopt -s nullglob; echo /boot/dtbos/${target}-all-*.dtbo) \
            $(shopt -s nullglob; echo /boot/dtbos/${target}-${rkdev}-*.dtbo)
exit 0
