post_install () {
    chown -R $USER "/usr/local/Roon/"
    chmod +x "/usr/bin/roon"

    echo "  To discover your Roon Core connection details, execute:
    '/usr/local/Roon/bin/get_core_ip'
    then follow the instructions for authorization.
    Next, update 'RoonCoreIP' & 'RoonCorePort' inside '/usr/local/Roon/etc/roon_api.ini'."
    
}

post_upgrade() {
    chown -R $USER "/usr/local/Roon/"
}

post_remove() {
    rm "/usr/local/Roon/etc/roontoken.txt"
}
