post_install() {
  echo ""
  echo "Waybar config"
  echo "In modules add:"
  echo ""
  echo '  "custom/roon",'
  echo ""
  echo "Then add the extension block:"
  echo ""
  echo '  "custom/roon": {'
  echo '    "exec": "cat /tmp/waybar_roon_info.json",'
  echo '    "format": "{text}",'
  echo '    "tooltip": true,'
  echo '    "return-type": "json",'
  echo '    "signal": 3'
  echo '  },'
  echo ""
}

