#!/bin/bash

# Copyright Piero Olmeda - AudioLinux  <audiolinux AT fastmail DOT fm>
# https://www.audio-linux.com

# License: custom - All rights reserved

source /etc/rtirq.conf

echo "
REALTIME PRIORITY
"
echo "IRQS"
source /etc/rtapp/rtapp.conf
app="jackd jackdbus $APPLICATIONS"

rtirq status | grep "$RTIRQ_NAME_LIST"                

echo "
APPLICATIONS"
for WORD in $app
                do
                if [[ $(pidof $WORD) ]]
                    then
                    ps -eLo rtprio,cmd | grep $WORD | grep -v grep                   
                fi
                done
  
