post_install() {
  cat<<EOF

Unload and load kernel modules:

  rmmod rtw88_{8{723de,723d,821ce,821c,822be,822b,822ce,822c},core,pci}
  modprobe rtw_{8{723de,723d,821ce,821c,822be,822b,822ce,822c},core,pci}

EOF
}

pre_remove() {
  cat<<EOF

Unload and load kernel modules:

  rmmod rtw_{8{723de,723d,821ce,821c,822be,822b,822ce,822c},core,pci}
  modprobe rtw88_{8{723de,723d,821ce,821c,822be,822b,822ce,822c},core,pci}

EOF
}
