# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  if (( "$(vercmp "$2" "0.r132.598988e")" <= 0 )); then
    cat << EOF || return 1

After upgrading to systemd 254, run

  sudo sbupdate

to rebuild EFI images.

EOF
  fi

  post_install "$1"
}

post_install() {
  cat << EOF || return 1

This tool is no longer maintained. For alternatives, refer to:

https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot

EOF
}
