post_install() {
	if [ -x /sbin/ldconfig ]; then
	  /sbin/ldconfig /usr/lib32
	fi
}
post_upgrade() {
	if [ -x /sbin/ldconfig ]; then
	  /sbin/ldconfig /usr/lib32
	fi
}
post_remove() {
	if [ -x /sbin/ldconfig ]; then
	  /sbin/ldconfig /usr/lib32
	fi
	for LIBS in "libcncpmsimg357.so" "libcncpmslld357c.so" "libcncpmslld357.so"; do
	  if [ -h /usr/lib32/${LIBS} ]; then
	    rm -f /usr/lib32/${LIBS}
	  fi
	done
}
