_cache() {
  echo "Updating font cache..."
  fc-cache -vfs
  mkfontscale /usr/share/fonts/misc
  mkfontdir /usr/share/fonts/misc
}

post_install() {
  echo "Enabling fontconfig files..."
  ln -fs -t /etc/fonts/conf.d/ /etc/fonts/conf.avail/70-yes-bitmaps.conf
  ln -fs -t /etc/fonts/conf.d/ /etc/fonts/conf.avail/75-yes-scientifica.conf
  _cache
}

post_upgrade() {
  post_install ${1}
}

post_remove() {
  _cache
}
