post_install() {
	echo
	echo 'To set LD_LIBRARY_PATH, /etc/ld.so.conf.d/ cannot be used.'
	echo 'This leads to conflicts with existing Qt libraries.'
	echo 'Export LD_LIBRARY_PATH yourself. For examples see below.'
	echo
	echo '    SecureCRT'
	echo '    ---------'
	echo '        export LD_LIBRARY_PATH=/opt/scrt-sfx-opt-bin/scrt-sfx-9.2.1.2794.ubuntu20-64:${LD_LIBRARY_PATH}'
	echo '        /opt/scrt-sfx-opt-bin/scrt-sfx-9.2.2.2794.ubuntu20-64/SecureCRT'
	echo
	echo '        i3 example'
	echo '        ----------'
	echo '        bindsym <modifier key>+<key> exec env LD_LIBRARY_PATH=/opt/scrt-sfx-opt-bin/scrt-sfx-9.2.2.2794.ubuntu20-64:${LD_LIBRARY_PATH} /opt/scrt-sfx-opt-bin/scrt-sfx-9.2.2.2794.ubuntu20-64/SecureCRT'
	echo
	echo '    SecureFX'
	echo '    --------'
	echo '        export LD_LIBRARY_PATH=/opt/scrt-sfx-opt-bin/scrt-sfx-9.2.2.2794.ubuntu20-64:${LD_LIBRARY_PATH}'
	echo '        /opt/scrt-sfx-opt-bin/scrt-sfx-9.2.2.2794.ubuntu20-64/SecureFX'
	echo
	echo '        i3 example'
	echo '        ----------'
	echo '        bindsym <modifier key>+<key> exec env LD_LIBRARY_PATH=/opt/scrt-sfx-opt-bin/scrt-sfx-9.2.2.2794.ubuntu20-64:${LD_LIBRARY_PATH} /opt/scrt-sfx-opt-bin/scrt-sfx-9.2.2.2794.ubuntu20-64/SecureFX'
	echo
}
