#!/usr/bin/sh

[ -f /etc/sd-zram.conf ] && . /etc/sd-zram.conf

start() {
	if [ ! -d /sys/block/zram0 ]; then
		modprobe zram
		[ -n "$ZRAM_COMPRESSION" ] && echo "$ZRAM_COMPRESSION" > /sys/block/zram0/comp_algorithm
		[ ! "$ZRAM_SIZE" ] && ZRAM_SIZE=40
		MEM=$((`awk '{print $2; exit}' /proc/meminfo` * 1024 * $ZRAM_SIZE/100 ))
		echo $MEM > /sys/block/zram0/disksize
		mkswap -L zram0 /dev/zram0
		swapon -p 100 /dev/zram0
	fi
}

stop() {
	swapoff /dev/zram0
	rmmod zram
}

case $1 in
  start|stop) "$1" ;;
esac
