post_install() {
    getent group seeks  >/dev/null || groupadd -r seeks
    getent passwd seeks >/dev/null || useradd -r -c "Seeks daemon" -g seeks -M -d /var/lib/seeks -s /bin/false seeks
    passwd -l seeks &>/dev/null
    chown seeks:seeks var/log/seeks var/lib/seeks
}

pre_remove() {
    getent passwd seeks &>/dev/null && userdel seeks >/dev/null
    getent group seeks &>/dev/null && groupdel seeks >/dev/null
    return 0
}


