post_install() {
    # Configure /etc/selinux/config
    if [ -e /etc/selinux/config ]
    then
        echo ">>> In order to use this policy, set SELINUXTYPE=refpolicy-arch-git in /etc/selinux/config."
    else
        /usr/bin/ln -v -s config.refpolicy-arch-git /etc/selinux/config
    fi

    echo ">>> Building refpolicy-arch-git policy store. Please wait..."
    /usr/bin/semodule -s refpolicy-arch-git -i /usr/share/selinux/refpolicy-arch-git/*.pp
    echo ">>> Relabeling the filesystem may be needed."
    echo ">>> This can be done with: /usr/bin/restorecon -rF /"
}

post_upgrade() {
    post_install
}

post_remove() {
    echo ">>> Removing refpolicy-arch-git left-over files in /var/lib/selinux"
    /usr/bin/rm -rf /var/lib/selinux/refpolicy-arch-git

    if [ -L /etc/selinux/config ] && ! [ -e /etc/selinux/config ]
    then
        echo ">>> Removing now-broken symbolic link /etc/selinux/config"
        /usr/bin/rm /etc/selinux/config
    fi
}
