post_install() {
  if [ -z $(getent group sensu) ]; then
    /usr/bin/groupadd sensu
  fi
  if [ -z $(getent passwd sensu) ]; then
    /usr/bin/useradd -s /sbin/nologin -d /var/lib/sensu -m -g sensu sensu
  fi
}

post_upgrade() {
  if [ -z $(getent group sensu) ]; then
    /usr/bin/groupadd sensu
  fi
  if [ -z $(getent passwd sensu) ]; then
    /usr/bin/useradd -s /sbin/nologin -d /var/lib/sensu -m -g sensu sensu
  fi
}

post_remove() {
  /usr/bin/userdel sensu
  /usr/bin/groupdel sensu
}
