# See https://valheim.fandom.com/wiki/Dedicated_servers#Linux
# ENV vars reflect CLI parameters
# Allow PORT and PORT+1 over UDP in your firewall

NAME="Valheim"
WORLD="world0"
PASSWORD="secret"
PORT=2456

# Steam A2S
PUBLIC=0

# Generates permittedlist.txt, bannedlist.txt, and adminlist.txt in
# /var/opt/valheim/.config/unity3d/IronGate/Valheim/
# Split by whitespace, get steam IDs from https://steamdb.com/en/tools/steam-id-finder
PERMITTED_STEAM_IDS=""
BANNED_STEAM_IDS=""
ADMIN_STEAM_IDS=""
