post_install() {
    ln -sf /opt/Session/session-messenger-desktop /usr/bin/session-messenger-desktop
    update-desktop-database /usr/share/applications
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -f '/usr/bin/session-messenger-desktop'
    update-desktop-database /usr/share/applications
    gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
