set (BUILD_SERVER              OFF CACHE BOOL "" FORCE)
set (BUILD_RECEIVER            OFF CACHE BOOL "" FORCE)
set (BUILD_LIBCVMFS_CACHE      OFF CACHE BOOL "" FORCE)
set (BUILD_LIBCVMFS            OFF CACHE BOOL "" FORCE)
