#!/bin/sh

ps -e | grep '^.*gnome-session.*$' &>/dev/null
if [ $? -eq 0 ]; then
  pacman -Qi gnome-shell-extension-topicons-plus &>/dev/null
  if [ $? -ne 0 ]; then
    while [ "$1" = "--use-tray-icon" -o "$1" = "--start-in-tray" ]; do shift; done
    echo "Tray icons are no longer supported by default on Gnome."
    echo "If you want use the tray icon of Signal-Desktop:"
    echo "pacman -S gnome-shell-extension-topicons-plus"
    echo "Then re-login and enable this extension in 'Tweaks' (gnome-tweak-tool)."
  fi 
fi

exec /usr/lib/signal-desktop/signal-desktop "$@"
