post_install() {
  echo >&2 'Applying patch for signal-desktop issue #6368...'
  /usr/share/libalpm/scripts/signal-desktop-fix-sway-patch
}

post_upgrade() {
  echo >&2 'Applying patch for signal-desktop issue #6368...'
  /usr/share/libalpm/scripts/signal-desktop-fix-sway-patch
}

pre_remove() {
  echo >&2 'Undoing modifications to signal-desktop...'
  /usr/share/libalpm/scripts/signal-desktop-fix-sway-unpatch
}
