post_install() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-desktop-database -q
  echo "Reloading udev rules ..."
  udevadm control --reload-rules
  udevadm trigger --action=add
  echo ""
  echo "======================================================================"
  echo "Important: To access the serial console add yourself to the uucp group"
  echo "To add yourself to uucp use: sudo usermod -aG uucp \$(whoami)"
  echo "======================================================================"
  echo ""
}

post_upgrade() {
  post_install
}

post_remove() {
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  update-desktop-database -q
}
