#!/bin/bash

. /usr/lib/rc/functions

case "$1" in
    start)
        stat_busy "Triggering uevents"
        smdev -s || stat_die
        add_daemon smdev
        stat_done
        ;;
    *)
        echo "usage: $0 {start}"
        exit 1
        ;;
esac
