post_install() {
  echo "Set up IPMI fan thresholds by reading"
  echo "https://github.com/petersulyok/smfc/tree/main?tab=readme-ov-file#6-ipmi-fan-control-and-sensor-thresholds"
  echo
  echo "Prior to enabling the service,"
  echo "Check if the cpu temp monitor module for your system is loaded"
  echo "coretemp kernel module for Intel CPUs"
  echo "k10temp kernel module for AMD CPUs"
  echo "Load module as needed"
  echo
  echo "Enable Super Micro Fan Control as systemd service"
  echo "by running:"
  echo "$ systemctl enable smfc.service"
  echo
  echo "Modify /etc/smfc/smfc.conf and fill 'hd_names' with"
  echo "the hard drive and/or SSD you'd like to monitor the"
  echo "temperatures of."
  echo
  echo "Increase verbosity of the service by modifying"
  echo "command-line arguments in /etc/default/smfc."
}
