pre_install() {
    return
}

post_install() {
    return
}

pre_upgrade() {
    /usr/bin/bash -c "[[ -f /usr/share/libalpm/hooks.bin/snap-pac/.pre ]] && mv /usr/share/libalpm/hooks.bin/snap-pac/.pre /tmp/snap-pac-pre_root"
    return
}

post_upgrade() {
    return
}

pre_remove() {
    echo "NOTE: No post snapshot will be performed for this transaction, since you are removing the pacman hooks."
}

post_remove() {
    return
}
