post_install() {
  echo "To use this theme, add the following lines to /etc/sddm.conf:"
  echo
  echo "[Theme]"
  echo "Current=solarized-sddm-theme"
  echo
  echo "To change the font used in this theme, add the following"
  echo "lines to /usr/share/sddm/themes/solarized-sddm-theme/theme.conf:"
  echo
  echo "[General]"
  echo "displayFont='YourFont'"
  echo
  echo "Version 0.1.8 brings a new background image"
  echo "If you want the former backgrounds, add the following"
  echo "lines to /usr/share/sddm/themes/solarized-sddm-theme/theme.conf:"
  echo
  echo "[General]"
  echo "background='Assets/bars_background.png'"
  echo "background='Assets/circles_background.png'"
  echo "background='Assets/traces_background.png'"
  echo
}

post_upgrade() {
  post_install
}
