post_install() {
    groupadd -f games
    useradd -r -s /sbin/nologin -c "Spearmint Daemon user" -M -d /opt/spearmint -g games spearmint > /dev/null 2>&1
    chown -R spearmint:games /opt/spearmint

    echo '!!!'
    echo '!!! NOTE: TO PLAY SPEARMINT, YOU MUST BE PART OF THE "games" GROUP!'
    echo '!!! To play Spearmint with the Retail Version of Quake III: Arena,'
    echo '!!!  place pak[0-8].pk3 file from the retail game in /opt/spearmint/baseq3/'
    echo '!!!'
    echo '!!!'
    echo '!!! When you have the .pk3 file(s) installed, you can run the game via: spearmint'
    echo '!!! See https://github.com/clover-moe/spearmint/wiki for more documentation.'
    echo '!!!'
}

post_upgrade() {
    post_install ${1}
}

post_remove() {
    #userdel -rf spearmint > /dev/null 2>&1
    userdel spearmint > /dev/null 2>&1
    if egrep -q '^games:.*:$' /etc/group;
    then
      groupdel games
    fi
    if [[ -d '/opt/spearmint' ]];
    then
    	chown -R root:root /opt/spearmint > /dev/null 2>&1
    fi
}
