#!/bin/sh

MINIM_HOME="/opt/minimserver"
MINIM_DATA="/home/$USER/.minimserver/data"
cd "$MINIM_DATA"
if [ -z "$LANG" ]; then
    export LANG="en_US.utf8"
fi
MINIM_LANG="$LANG" java -jar "$MINIM_HOME/lib/mserver.jar" --noconsole --nohup </dev/null >minimserver.out 2>&1 &

exit
