#!/usr/bin/env bash

DESTDIR=~/.suckless
BUILDDIR=~/.suckless-build

usage() {
  echo "Usage: suckless-rebuild st|slstatus <config.h>"
  exit 1
}

if [[ ${#@} != 2 || $1 =~ ^-h$|^--help$ || $2 =~ ^-h$|^--help$ ]]; then
  usage
fi

software=$1
config=$2

if [[ ! $software =~ ^st$|^slstatus$ ]]; then
  echo "Unknown suckless software '$software'."
  exit 1
fi
if [[ ! -d /usr/src/$software ]]; then
  echo "'an9wer-$software' may not be installed."
  exit 1
fi
if [[ ! -f $config ]]; then
  echo "'$config' is not a regular file."
  exit 1
fi

if [[ -e $BUILDDIR/$software ]]; then
  temp=$(mktemp -u -d /tmp/$software.XXXXX)
  mv "$BUILDDIR/$software" "$temp"
fi

mkdir -p "$BUILDDIR"
cp -r /usr/src/$software "$BUILDDIR/$software"
cp -f "$config" "$BUILDDIR/$software"

cd "$BUILDDIR/$software"
if make &> build.log && make PREFIX="$DESTDIR" install &> build.log; then
  echo "Done! Recommend to add '~/.suckless/bin' to \$PATH to use new builded st."
else
  echo "Some error occurred, check '$BUILDDIR/$software/build.log' to find more."
fi
if [[ -v temp ]]; then
  sed -i "1i The last built directory was moved to $temp\n" build.log
fi

# vim: set filetype=sh:
