post_install() {
    if ! grep -qi "^svxlink:" /etc/group; then
        groupadd svxlink
    fi

    if ! grep -qi "^svxlink:" /etc/passwd; then
        useradd -m -d /var/spool/svxlink -g svxlink -G uucp,tty,audio svxlink
    fi

    chown -R svxlink:svxlink /var/spool/svxlink
}

pre_remove() {
    systemctl stop svxlink.service 2>/dev/null || true
}

post_remove() {
    if grep -qi "^svxlink:" /etc/passwd; then
        userdel svxlink
    fi

    if grep -qi "^svxlink:" /etc/group; then
        groupdel svxlink
    fi
}

post_upgrade() {
    gpasswd -a svxlink uucp
    gpasswd -a svxlink tty
    gpasswd -a svxlink audio
}
