#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

SWAPSPACE_ARGS="-q -d -p /var/run/swapspace.pid"
PIDFILE=/var/run/swapspace.pid
PID=$(cat $PIDFILE 2> /dev/null)
if ! readlink -q /proc/$PID/exe | grep -q \^/usr/sbin/swapspace; then
	PID=
	rm -f $PIDFILE
fi

[ -r /etc/conf.d/swapspace ] && . /etc/conf.d/swapspace

PID=$(get_pid swapspace)

case "$1" in
	start)
		stat_busy "Starting swapspace"
		[[ -z $PID ]] && /usr/sbin/swapspace $SWAPSPACE_ARGS
		if [[ $? -gt 0 ]]; then
			stat_fail
		else
			add_daemon swapspace
			stat_done
		fi
		;;
	stop)
		stat_busy "Stopping swapspace"
		[[ ! -z $PID ]] && kill $PID &> /dev/null
		if [[ $? -gt 0 ]]; then
			stat_fail
		else
			rm_daemon swapspace
			stat_done
		fi
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
		stat_busy "Checking swapspace status..."
		ck_status swapspace
		;;
	*)
		echo "usage: $0 {start|stop|restart|status}"
esac
