#!/bin/bash

post_install() {
    /usr/bin/sed -i 's|Exec=sway|Exec=env XDG_CURRENT_DESKTOP=sway;wlroots XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-sway}" XDG_SESSION_TYPE=wayland sway|' /usr/share/wayland-sessions/sway.desktop
}

post_upgrade() {
    post_install
}

post_remove() {
    /usr/bin/sed -i 's|Exec=env XDG_CURRENT_DESKTOP=sway;wlroots XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-sway}" XDG_SESSION_TYPE=wayland sway|Exec=sway|' /usr/share/wayland-sessions/sway.desktop
}
