post_install() {
  cat <<'EOF'

                       ▄▀▀▀▀ █   █ ▄▀▀▀▀ ▄▀▀▀▀    ▄▀    ▄▀
                        ▀▀▀▄ ▀▀▀▀█  ▀▀▀▄ █      ▄▀    ▄▀
                       ▀▀▀▀  ▀▀▀▀▀ ▀▀▀▀   ▀▀▀▀ ▀     ▀
                      //  SEE YOU SPACE COWBOY //

Stop your other notification daemon before enabling sysc-notify.service.
Docs: https://nomadcxx.github.io/sysc/docs/

EOF
}

post_upgrade() {
  post_install
}
