post_install() {
        if ! command -v git >/dev/null; then
                if [ "$USER" = "root" ]; then
                        echo "Downloading/Installing git for root."
                        pacman -S --needed git
                else
                        echo "Downloading/Installing git."
                        sudo pacman -S --needed git
                fi
        fi

        if ! command -v git >/dev/null; then
                if [ "$USER" = "root" ]; then
                        sudo pacman -S --needed make
                else
                        sudo pacman -S --needed make
                fi
        fi
        echo "sysinfo-bin: Downloading and Building neofetch."
        mkdir -p "$HOME/temp"
        cd "$HOME/temp"
        git clone https://github.com/dylanaraps/neofetch
        echo "Going into directory '$HOME/temp/neofetch'"
        cd neofetch
        sudo make install
        cd ..
        rm -rf neofetch
        cd ..
        echo "sysinfo-bin: Installed NeoFetch!"
}

post_upgrade() {
	if ! command -v neofetch >/dev/null; then
        	if ! command -v git >/dev/null; then
        	        if [ "$USER" = "root" ]; then
        	                echo "Downloading/Installing git for root."
        	                pacman -S --needed git
        	        else
         	                echo "Downloading/Installing git."
        	                sudo pacman -S --needed git
              	        fi
     	        fi

        	if ! command -v git >/dev/null; then
                	if [ "$USER" = "root" ]; then
                        	sudo pacman -S --needed make
                	else
                        	sudo pacman -S --needed make
                	fi
        	fi
        	echo "sysinfo-bin: Downloading and Building neofetch."
        	mkdir -p "$HOME/temp"
        	cd "$HOME/temp"
        	git clone https://github.com/dylanaraps/neofetch
        	echo "Going into directory '$HOME/temp/neofetch'"
        	cd neofetch
        	sudo make install
        	cd ..
        	rm -rf neofetch
        	cd ..
        	echo "sysinfo-bin: Welcome back, $USER"
		echo "We already installed neofetch for you. thank you for using this app!"
	else
		echo "sysinfo-bin: Welcome back, $USER"
		echo "Thank you for using this app!"
	fi
}

