title SystemRescue 12.01
linux /systemrescue/vmlinuz
initrd /systemrescue/intel_ucode.img
initrd /systemrescue/amd_ucode.img
initrd /systemrescue/sysresccd.img
sort-key systemrescue
options archisolabel=EFI archisobasedir=systemrescue iomem=relaxed copytoram net.ifnames=0
