d     /var/lib/tandoor   0710 tandoor http  - -
d     /var/lib/tandoor/mediafiles   0710 tandoor http  - -
d     /var/lib/tandoor/mediafiles/recipes   0730 tandoor http  - -
L     /usr/share/tandoor/mediafiles         -    -       -     - /var/lib/tandoor/mediafiles
