#!/bin/sh

post_install() {
  /usr/bin/sh /usr/share/tango/db/check_and_create_db.sh
}

post_upgrade() {
  /usr/bin/sh /usr/share/tango/db/check_and_create_db.sh
}

post_remove() {
  echo "***************************************************"
  echo ">>> tango-database was successfully removed but <<<"
  echo ">>> The tango mariadb database was NOT removed! <<<"
  echo "***************************************************"
}
