pre_install() {
  # add taskd group if it doesn't exist
  getent group taskd &> /dev/null || groupadd --system taskd

  # add taskd user if it doesn't exist
  getent passwd taskd &> /dev/null || \
      useradd --system -m -d /var/lib/taskd -g taskd taskd
}

post_install() {
  echo "Please follow the configuration instructions at
 /usr/lib/taskd/taskd.notes to finish setting up Taskserver."
}

pre_upgrade() {
  pre_install
}

post_upgrade() {
  post_install
}
