## arg 1:  the new package version
#pre_install() {
    case `ps --no-headers -o comm 1` in
        dinit)
            echo "::: Detected [dinit]"
            echo " :: Stopping [technitium-dns-server] service"
            dinitctl stop technitium-dns-server
            # dinitctl unload technitium-dns-server
            echo " :: Showing status of [technitium-dns-server] service"
            dinitctl status technitium-dns-server
        ;;
        init)
            echo "::: Detected [init]"
        ;;
        systemd)
            echo "::: Detected [systemd]"
            echo " :: Stopping [technitium-dns-server] service"
            systemctl stop technitium-dns-server
            echo " :: Showing status of [technitium-dns-server] service"
            systemctl status technitium-dns-server
        ;;
        *)
            echo "::: Unknown init system"
        ;;
    esac
#}

## arg 1:  the new package version
post_install() {
    case `ps --no-headers -o comm 1` in
        dinit)
            echo "::: Detected [dinit]"
            echo " :: Installing [technitium-dns-server] service description file"
            ln -sf /opt/technitium-dns-server/service/technitium-dns-server.dinit /etc/dinit.d/technitium-dns-server
            echo " :: Reloading [technitium-dns-server] service"
            dinitctl reload technitium-dns-server
            echo " :: Starting [technitium-dns-server] service"
            dinitctl start technitium-dns-server
            echo " :: Showing status of [technitium-dns-server] service"
            dinitctl status technitium-dns-server
        ;;
        init)
            echo "::: Detected [init]"
        ;;
        systemd)
            echo "::: Detected [systemd]"
            echo " :: Installing [technitium-dns-server] service files"
            ln -sf /opt/technitium-dns-server/service/technitium-dns-server.service /usr/lib/systemd/system/technitium-dns-server.service
            ln -sf /opt/technitium-dns-server/service/technitium-dns-server.sysuser /usr/lib/sysusers.d/technitium-dns-server.conf
            echo " :: Creating user and group"
            systemd-sysusers
            echo " :: Reloading [systemd] services definitions"
            systemctl daemon-reload
            echo " :: Starting [technitium-dns-server] service"
            systemctl start technitium-dns-server
            echo " :: Showing status of [technitium-dns-server] service"
            systemctl status technitium-dns-server
        ;;
        *)
            echo "::: Unknown init system"
        ;;
    esac
}

#pre_upgrade() {
    case `ps --no-headers -o comm 1` in
        dinit)
            echo "::: Detected [dinit]"
            echo " :: Stopping [technitium-dns-server] service"
            dinitctl stop technitium-dns-server
            # dinitctl unload technitium-dns-server
            echo " :: Showing status of [technitium-dns-server] service"
            dinitctl status technitium-dns-server
        ;;
        init)
            echo "::: Detected [init]"
        ;;
        systemd)
            echo "::: Detected [systemd]; stopping [systemd] service files"
            systemctl stop technitium-dns-server
        ;;
        *)
            echo "::: Unknown init system"
        ;;
    esac
#}

post_upgrade() {
    case `ps --no-headers -o comm 1` in
        dinit)
            echo "::: Detected [dinit]"
            echo " :: Installing [technitium-dns-server] service description file"
            ln -sf /opt/technitium-dns-server/service/technitium-dns-server.dinit /etc/dinit.d/technitium-dns-server
            echo " :: Reloading [technitium-dns-server] service description file"
            dinitctl reload technitium-dns-server
            echo " :: Starting [technitium-dns-server] service description file"
            dinitctl start technitium-dns-server
            echo " :: Showing status of [technitium-dns-server] service"
            dinitctl status technitium-dns-server
        ;;
        init)
            echo "::: Detected [init]"
        ;;
        systemd)
            echo "::: Detected [systemd]"
            echo " :: Installing [technitium-dns-server] service files"
            ln -sf /opt/technitium-dns-server/service/technitium-dns-server.service /usr/lib/systemd/system/technitium-dns-server.service
            ln -sf /opt/technitium-dns-server/service/technitium-dns-server.sysuser /usr/lib/sysusers.d/technitium-dns-server.conf
            echo " :: Creating user and group"
            systemd-sysusers
            echo " :: Reloading services definitions"
            systemctl daemon-reload
            echo " :: Starting [technitium-dns-server] service"
            systemctl stop technitium-dns-server
            systemctl start technitium-dns-server
            echo " :: Showing status of [technitium-dns-server] service"
            systemctl status technitium-dns-server
        ;;
        *)
            echo "::: Unknown init system"
        ;;
    esac
}
