post_install() {
 echo -e "\n\n\e[1;32m[+]\e[0;1;37m  Add one of the header scripts to your shells rc file to\
 apply it upon opening a terminal.\e[1;32m\n\n[+]\e[0;1;37m  Scripts located in\e[0;1;33m\
 '/opt/terminal-headers'\e[0m\n\n"

 ls /opt/terminal-headers | grep "Header$" | while read -r HEADER ; do
   echo -e "\e[1;32m[+] \e[37mLinking \e[36m"$HEADER" \e[37mto [33m/bin/$HEADER[0m";
   ln -s /opt/terminal-headers/$HEADER /usr/bin/$HEADER >/dev/null 2>&1
 done
}

post_upgrade() {
  post_install
}

pre_remove() {
  ls /opt/terminal-headers | grep "Header$" | while read -r HEADER ; do
    echo -e "\e[1;31m[-] \e[37mRemoving \e[36m"$HEADER"'s \e[37msymbolic link from /usr/bin"
    rm /usr/bin/$HEADER >/dev/null 2>&1
  done
}

