info_dir=usr/share/info

post_install() {
  install-info ${info_dir}/asy-faq.info.gz ${info_dir}/dir 2>/dev/null
  echo ">>> updating the filename database for texlive..."
  mktexlsr --quiet usr/share/texmf
}

post_upgrade() {
  post_install
}

pre_remove() {
  install-info --delete ${info_dir}/asy-faq.info.gz ${info_dir}/dir 2>/dev/null
}

post_remove() {
  echo ">>> updating the filename database for texlive..."
  mktexlsr --quiet usr/share/texmf
}
