note1() {
  printf "${BOLD}${BLUE}==>${YELLOW} NOTE:${ALL_OFF}${WHITE} $1${ALL_OFF}\n"
}

note2() {
  printf "${BOLD}${BLUE}==>      ${ALL_OFF}${WHITE} $1${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="${ALL_OFF}$(tput bold)"
BLACK="$(tput setaf 0)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
MAGENTA="$(tput setaf 5)"
CYAN="$(tput setaf 6)"
WHITE="$(tput setaf 7)"

post_install() {
  if grep -qsE '\bpni\b' /proc/cpuinfo ; then
    note1 "Custom flags should be put directly in: ~/.config/thorium-flags.conf"
    note2 "The launcher is called: 'thorium-browser'"
  else
    note1 "Your processor does not support SSE3 instructions."
    note2 "thorium-browser may not work on your computer."
  fi
}

post_upgrade() {
  post_install
}
