post_install() {
  if [[ "`pkg-config --modversion thunarx-2 2>/dev/null`" != '' ]] ; then
    printf "$(tput setaf 1)$(tput bold)  ==> NOTE: $(tput sgr0)"
    echo "You have installed thunarx-python 0.3.0 for the GTK2 version of"
    echo "  thunar. Do not upgrade to verson 0.4.0 until you install the GTK3 version of"
    echo "  thunar (version >=1.7.0) which has not yet been added to the extra repo" 
  fi
}

post_upgrade() {
	post_install
}

