all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

msg_blue() {
    printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
    printf "${blue}==>${yellow} Note:${bold} $1${all_off}\n"
}

post_note() {
  note 'For enables Global Menu:'
  msg_blue '1. Go to Settings > General > Config Editor(the last button at the bottom)'
  msg_blue "2. Search for ${all_off}widget.gtk.global-menu.enabled"
  msg_blue "3. Set it to true"
}

post_install() {
  post_note
}

post_upgrade() {
  post_note
}
