# Colored makepkg-like functions
# shellcheck disable=2155
readonly OFF="$(tput sgr0)"
readonly BOLD="${OFF}$(tput bold)"
readonly BLUE="${BOLD}$(tput setaf 4)"
readonly YELLOW="${BOLD}$(tput setaf 3)"

info() {
    printf "%s==>%s %s%s\n" "$BLUE" "$BOLD" "$1" "$OFF"
}

note() {
    printf "%s==>%s NOTE:%s %s%s\n" "$BLUE" "$YELLOW" "$BOLD" "$1" "$OFF"
}

post_install() {
    note "Custom flags should be put directly in: ~/.config/ticktick-flags.conf"
}

post_upgrade() {
    post_install
}
