.TH TICK "1" "January 2018" "Tick 1.2.0" "User Commands"

.SH NAME
Tick - Command line stock price tracker.

.SH SYNOPSIS
tick [OPTION]...

.SH DESCRIPTION
Create your portfolio by adding your current holdings. Then, you can use the built in functions to get information on the current price. Stock information taken from IEX and Alpha Vantage's free API.

.SS
Portfolio:

.TP
[add/rm/set] [symbol/USD$] [quantity of shares] [USD spent]
Either adds, removes, or sets the amount of the given stock with respect to the given values. The parameter add will add your
input to the current portfolio, rm will subtract from your current portfolio, and set will set your portfolio to the input,
discarding any existing data about that stock. Trading fees should be factored into "USD SPENT". "Symbol" may also be input
as "USD$" for US Dollars. This is good for keeping track of how much money is unallocated in your brokerage account. Typically,
your initial amount of USD can be added as "tick add USD$ [amount] [amount]", where [amount] is the same number. When you are
paid dividends or capital gains that are not reinvested into a specific security, you should update your portfolio with
"tick add USD$ [dividend/capital gain amount] 0".

.TP
[check] [currency name/all]
Prints information about your current portfolio holdings. Either a symbol or the keyword 'all' can be used. The keyword 'all' will print information about all your current holdings, as well as a grand total.

.SH FILES
.I ~/.tick_portfolio
.RS
Portfolio file.

.SH GITHUB
Please report any bugs using the GitHub issue tracker: https://github.com/aokellermann/tick/issues

.SH AUTHORS
Antony Kellermann -- https://github.com/aokellermann