#!/bin/bash
# Command line interface for tinyMediaManager
set -e

mkdir --parents "$HOME/.tiny-media-manager"
cd "$HOME/.tiny-media-manager"
ln --symbolic --force /usr/share/tinyMediaManager/plugins/ ./

java \
  -Djava.net.preferIPv4Stack=true \
  -Dappbase=http://www.tinymediamanager.org/ \
  -Djna.nosys=true \
  -Djava.awt.headless=true \
  -Xms64m \
  -Xmx512m \
  -Xss512k \
  -cp /usr/share/tinyMediaManager/tmm.jar:/usr/share/tinyMediaManager/lib/* \
  org.tinymediamanager.TinyMediaManager \
  "$@"
