post_install() {
    :
#!/bin/bash

# Link to the binary
ln -sf '/opt/Tivoli Cloud VR/tivoli-cloud-vr' '/usr/bin/tivoli-cloud-vr'

# SUID chrome-sandbox for Electron 5+
chmod 4755 '/opt/Tivoli Cloud VR/chrome-sandbox' || true

update-mime-database /usr/share/mime || true
update-desktop-database /usr/share/applications || true

}
post_remove() {
    :
#!/bin/bash

# Delete the link to the binary
rm -f '/usr/bin/tivoli-cloud-vr'

}
