# Type Path Mode User Group Age Argument
d /var/lib/commafeed-@DB 0750 commafeed-@DB commafeed-@DB - -
Z /var/lib/commafeed-@DB - commafeed-@DB commafeed-@DB - -
d /etc/commafeed-@DB 0750 root commafeed-@DB - -
z /etc/commafeed-@DB/application.properties 0640 root commafeed-@DB - -
