## Consistent response time for gaming
#    Path                  Mode UID  GID  Age Argument
w /proc/sys/vm/compaction_proactiveness - - - - 0
w /proc/sys/vm/watermark_boost_factor - - - - 1
w /proc/sys/vm/min_free_kbytes - - - - 1048576
w /proc/sys/vm/watermark_scale_factor - - - - 500
w /proc/sys/vm/swappiness - - - - 10
w /sys/kernel/mm/lru_gen/enabled - - - - 5
w /proc/sys/vm/zone_reclaim_mode - - - - 0
w /sys/kernel/mm/transparent_hugepage/enabled - - - - madvise
w /sys/kernel/mm/transparent_hugepage/shmem_enabled - - - - advise
w /sys/kernel/mm/transparent_hugepage/defrag - - - - never
w /proc/sys/vm/page_lock_unfairness - - - - 1
w /proc/sys/kernel/sched_child_runs_first - - - - 0
w /proc/sys/kernel/sched_autogroup_enabled - - - - 1
w /proc/sys/kernel/sched_cfs_bandwidth_slice_us - - - - 3000
w /sys/kernel/debug/sched/base_slice_ns  - - - - 3000000
w /sys/kernel/debug/sched/migration_cost_ns - - - - 500000
w /sys/kernel/debug/sched/nr_migrate - - - - 8

## Power management for intel
w /sys/devices/system/cpu/cpufreq/policy*/energy_performance_preference - - - - balance_power
w /sys/devices/system/cpu/intel_pstate/energy_efficiency - - - - 1
w /sys/block/sda/device/power/control - - - - auto
w /sys/bus/pci/devices/0000:00:17.0/ata1/power/control - - - - auto
w /sys/bus/pci/devices/0000:00:17.0/ata2/power/control - - - - auto
w /sys/bus/pci/devices/0000:00:17.0/ata3/power/control - - - - auto
w /sys/bus/pci/devices/0000:00:17.0/ata4/power/control - - - - auto
w /sys/bus/pci/devices/0000:00:17.0/ata5/power/control - - - - auto
w /sys/bus/pci/devices/0000:01:00.0/power/control - - - - auto
w /sys/bus/pci/devices/0000:01:00.1/power/control - - - - auto
w /sys/bus/pci/devices/0000:01:00.2/power/control - - - - auto
w /sys/bus/pci/devices/0000:01:00.3/power/control - - - - auto
