d /var/lib/moonraker 0755 moonraker moonraker - -
d /var/lib/moonraker/gcodes 0755 moonraker moonraker - -
d /var/lib/moonraker/database 0755 moonraker moonraker - -
d /var/lib/moonraker/logs 0755 moonraker moonraker - -
d /var/lib/moonraker/config 0755 moonraker moonraker - -
