post_install() {
	echo -e "To use the GDM theme,you should:\n1. Back up the original theme file:\n\tsudo cp -av /usr/share/gnome-shell-theme.gresource{,~}\n2. Install glib2:\n\tsudo pacman -S glib2\n3. Replace the theme file:\n\tcd /usr/share/themes/{your GTK Theme name}/gnome-shell\n\tsudo glib-compile-resources --target=/usr/share/gnome-shell/gnome-shell-theme.gresource gnome-shell-theme.gresource.xml"
}
