set (CMAKE_SYSTEM_NAME none)
set (CMAKE_SYSTEM_PROCESSOR riscv64)

set (CMAKE_C_COMPILER riscv64-elf-gcc)
set (CMAKE_CXX_COMPILER riscv64-elf-g++)

set (CMAKE_FIND_ROOT_PATH /usr/riscv64-elf)
set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
