post_install() {
  echo "
Welcome to tori!
-----------------------------------------------------------------------------
Default Config Path: /etc/tori/
Default Data Path: /var/lib/tori/
Default User & Group: tori:tori

$ sudo usermod -aG docker tori
$ sudo usermod -aG tori \$USER
$ newgrp tori  # activate group without logging out
$ sudo systemctl start tori.service
-----------------------------------------------------------------------------

More: https://github.com/thobiasn/tori-cli
"
}

post_remove() {
  echo "
To fully remove tori, clean up the following:
-----------------------------------------------------------------------------
$ sudo gpasswd -d \$USER tori
$ sudo userdel tori
$ sudo groupdel tori
$ sudo rm -rf /etc/tori /var/lib/tori
-----------------------------------------------------------------------------
"
}
# vim: set ts=2 sw=2 et:
