# Traefik format: v1 / v2 / v3 (у вас Traefik v2/v3 найімовірніше)
TCD_VERSION=v2

# Traefik ACME storage
TCD_SOURCE=/etc/traefik/acme.json

# Where to write PEM files (for Stalwart to read)
TCD_DEST=/etc/stalwart-mail/public-certs

# What to restart after cert update
TCD_POSTHOOK_SERVICE=stalwart-mail.service