post_install() { cat << EOF

Configuration
-------------

Configuration files are saved in:

    /etc/transabyss

You will most likely want to edit the genomes section transcriptome.cfg to point
to the location of your genomes.

Preparing Genomes
-----------------

The genomes are usually created by downloading a reference genome,
e.g. [hg19][1], and running gmap_build, see [gmap README][2]:

    gmap_build -g -d hg19 -D /path/to/genomes chr22.fa.gz

[1]: ftp://hgdownload.cse.ucsc.edu/goldenPath/hg19/chromosomes/
[2]: http://research-pub.gene.com/gmap/src/README

Getting Started
---------------

transabyss installs an /etc/profile.d/transabyss.sh script that you either need
to source right now or restart your shell session.

EOF
}

post_upgrade() {
  post_install
}
