#!/usr/bin/ash

run_hook () {
    echo -e "\033[104m               \033[0m"
    echo -e "\033[48;5;219m               \033[0m"
    echo -e "\033[48;5;15m               \033[0m"
    echo -e "\033[48;5;219m               \033[0m"
    echo -e "\033[104m               \033[0m"
}
