.TH TRAVERSO 1 "November  5, 2007"
.SH NAME
traverso \- a multitrack audio recorder and editor
.SH SYNOPSIS
.B traverso
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B traverso
command.
.PP
\fBtraverso\fP is a multitrack audio recording and editing 
suite, with an innovative and easy to master user interface.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v
Show version of program.
.TP
.B \-\-d1
Set debug level to 1 (BASIC).
.TP
.B \-\-d2
Set debug level to 2 (FLOOD).
.TP
.B \-\-d3
Set debug level to 3 (SUPER_FLOOD).
.TP
.B \-\-d4
Set debug level to 4 (ALL).
.TP
.B \-\-log
Create a ~/traverso.log file instead of dumping debug messages to stdout.
.SH AUTHOR
traverso was written by Remon Sijrier.
.PP
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@phys.ethz.ch>,
for the Debian project (but may be used by others).
