post_install() {
    chmod a+x /opt/trueconf/client/trueconf
    chmod a+x /opt/trueconf/client/trueconf-autostart

    ln -f -s /opt/trueconf/client/trueconf /usr/bin/trueconf

    if command -v "xdg-desktop-menu" >/dev/null 2>&1; then
        xdg-desktop-menu install --novendor --mode system /usr/share/applications/trueconf.desktop > /dev/null 2>&1 || true
    fi
    update-desktop-database > /dev/null 2>&1 || true

    for process_name in TrueConf trueconf; do
        while IFS= read -r process; do
            kill -s 50 "${process}"
        done < <(pgrep -x "${process_name}" || true)
    done
}

post_upgrade() {
    post_install
}

pre_remove() {
    for process_name in TrueConf trueconf; do
        while IFS= read -r process; do
            kill "${process}"
        done < <(pgrep -x "${process_name}" || true)
    done
}