post_install() {
    echo
    printf '\033[1;33m::\033[0m \033[1mNote:\033[0m To force this font, symlink /usr/share/fontconfig/conf.avail/75-apple-color-emoji.conf to /etc/fonts/conf.d/ and rebuild the system font cache with `fc-cache -f -v`.'
    echo
    echo "   If needed, use the \"Apple Color Emoji\" family in your font config. See \`man 5 fonts-conf\` for other options."
    echo
}

post_remove() {
    echo
    printf "\033[1;33m::\033[0m \033[1mNote:\033[0m Remove Apple Color Emoji from your font configuration files, e.g., \`rm /etc/fonts/conf.d/75-apple-color-emoji.conf\`."
    echo
}
