post_install() {
    echo -e '\nActivate using: \nsystemctl enable --now tuptime-sync.timer tuptime.service\n'
}

post_upgrade() {
    local DB='/var/lib/tuptime/tuptime.db'
    if [ -f ${DB} ]; then
        [ "$(stat -c '%U' ${DB})" == '_tuptime' ] || { systemd-sysusers && chown _tuptime:_tuptime ${DB}; }
    fi
    ! id tuptime &>/dev/null || echo -e '\nUser "tuptime" was replaced with "_tuptime", you may remove it.\n'
}

# vim: ts=4 sw=4 et:
