binary_message() {
    echo "To prevent problems with software of other coins the binaries for this package are as follows:"
    echo "  miner => trtl-miner"
    echo "  zedwallet => trtl-zedwallet"
    echo "  zedwallet-beta => trtl-zedwallet-beta"
    echo "  wallet-api => trtl-wallet-api"
    echo "  TurtleCoind => unchanged"
    echo "  turtle-service => unchanged"
    echo
}

post_install() {
    binary_message
}

post_upgrade() {
    binary_message
}
