post_install() {
  echo '# WARNING!!!'
  echo '# Make sure there are 4 Mebibytes of unallocated space before the first partition!'
  echo '# Otherwise the partition data will be destroyed!'
  echo '#'
  echo '# Install U-Boot to SD / MMC card with:'
  echo '# sudo sh /usr/lib/u-boot/platform_install.sh /dev/mmcblkX'
  mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr > /dev/null 2>&1
}

post_upgrade() {
  post_install
}

pre_remove() {
  rm -f /boot/boot.scr
}
