post_install() {
	cd /usr/share/webapps/unarelith

	bash setup_prod.sh

	# Set permissions
	chown http:http . db.sqlite3
	chown http:http -R static myenv

	echo "Please change your secret key with this one (/usr/share/webapps/unarelith/unarelith/settings.py):"
	python -c 'import random; result = "".join([random.choice("abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)") for i in range(50)]); print(result)'
}
