#!/bin/bash
export WINEPREFIX="$HOME/.local/share/wineprefixes/uniextract2"
export WINEDEBUG=-all

declare -a args

for arg; do
  if [[ "${arg:0:1}" = "-" ]]; then
    args+=("${arg/#-//}")
  else
    args+=("$(winepath -w "$arg")")
  fi
done

wine /opt/UniExtract2/UniExtract.exe "${args[@]}"
