post_install() {
    echo
    echo 'ADDITIONAL COMMENTS:'
    echo ' - Script to run the Universal G-Code Sender is located at' \
         '/usr/bin/ugs'
    echo ' - A desktop entry file has not been provided'
    echo
}

post_upgrade() {
    echo
    echo 'ADDITIONAL COMMENTS:'
    echo ' - Script to run the Universal G-Code Sender is located at' \
         '/usr/bin/ugs'
    echo ' - A desktop entry file has not been provided'
    echo
}
