#!/usr/bin/env ruby

# new_sha = `makepkg -g`
pkgbuild = File.readlines("PKGBUILD").map do |line|
  if line =~ /\Apkgver=/
    "pkgver=HEAD\n"
  else
    line
  end
end.join

File.write("PKGBUILD", pkgbuild)
system("makepkg --printsrcinfo > .SRCINFO")
# puts new_sha
puts "done!"

