import dataclasses
import os

from fontTools.ttLib import TTFont
from fontTools.ttLib.tables._n_a_m_e import table__n_a_m_e


@dataclasses.dataclass
class FontUpdateInfo:
    otf: str
    mac_family: str
    mac_style: str
    mac_full: str
    win_family: str
    win_style: str
    win_full: str
    win_typo_f: str
    win_typo_sub_f: str

    def add_compat_names(self):
        font = TTFont(f'{self.otf}.otf')
        font_tab: table__n_a_m_e = font["name"]
        font_tab.setName(string=self.mac_family, nameID=1, platformID=1, platEncID=0, langID=0)
        font_tab.setName(string=self.mac_style, nameID=2, platformID=1, platEncID=0, langID=0)
        font_tab.setName(string=self.mac_full, nameID=4, platformID=1, platEncID=0, langID=0)
        font_tab.setName(string=self.win_family, nameID=1, platformID=3, platEncID=1, langID=0x0409)
        font_tab.setName(string=self.win_style, nameID=2, platformID=3, platEncID=1, langID=0x0409)
        font_tab.setName(string=self.win_full, nameID=4, platformID=3, platEncID=1, langID=0x0409)
        font_tab.setName(string=self.win_typo_f, nameID=16, platformID=3, platEncID=1, langID=0x0409)
        font_tab.setName(string=self.win_typo_sub_f, nameID=17, platformID=3, platEncID=1, langID=0x0409)
        font.save(f'{self.otf}-compat.otf')
        os.remove(f'{self.otf}.otf')


fonts_update_info = [
    FontUpdateInfo(otf='lmmono10-italic',
                   mac_family='Latin Modern Mono',
                   mac_style='10 Italic',
                   mac_full='Latin Modern Mono 10 Italic',
                   win_family='LM Mono 10',
                   win_style='Italic',
                   win_full='LMMono10-Italic',
                   win_typo_f='Latin Modern Mono',
                   win_typo_sub_f='10 Italic'),

    FontUpdateInfo(otf='lmmono10-regular',
                   mac_family='Latin Modern Mono',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Mono 10 Regular',
                   win_family='LM Mono 10',
                   win_style='Regular',
                   win_full='LMMono10-Regular',
                   win_typo_f='Latin Modern Mono',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmmono12-regular',
                   mac_family='Latin Modern Mono',
                   mac_style='12 Regular',
                   mac_full='Latin Modern Mono 12 Regular',
                   win_family='LM Mono 12',
                   win_style='Regular',
                   win_full='LMMono12-Regular',
                   win_typo_f='Latin Modern Mono',
                   win_typo_sub_f='12 Regular'),

    FontUpdateInfo(otf='lmmono8-regular',
                   mac_family='Latin Modern Mono',
                   mac_style='8 Regular',
                   mac_full='Latin Modern Mono 8 Regular',
                   win_family='LM Mono 8',
                   win_style='Regular',
                   win_full='LMMono8-Regular',
                   win_typo_f='Latin Modern Mono',
                   win_typo_sub_f='8 Regular'),

    FontUpdateInfo(otf='lmmono9-regular',
                   mac_family='Latin Modern Mono',
                   mac_style='9 Regular',
                   mac_full='Latin Modern Mono 9 Regular',
                   win_family='LM Mono 9',
                   win_style='Regular',
                   win_full='LMMono9-Regular',
                   win_typo_f='Latin Modern Mono',
                   win_typo_sub_f='9 Regular'),

    FontUpdateInfo(otf='lmmonocaps10-oblique',
                   mac_family='Latin Modern Mono Caps',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Mono Caps 10 Oblique',
                   win_family='LM Mono Caps 10',
                   win_style='Italic',
                   win_full='LMMonoCaps10-Oblique',
                   win_typo_f='Latin Modern Mono Caps',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmmonocaps10-regular',
                   mac_family='Latin Modern Mono Caps',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Mono Caps 10 Regular',
                   win_family='LM Mono Caps 10',
                   win_style='Regular',
                   win_full='LMMonoCaps10-Regular',
                   win_typo_f='Latin Modern Mono Caps',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmmonolt10-bold',
                   mac_family='Latin Modern Mono Light',
                   mac_style='10 Bold',
                   mac_full='Latin Modern Mono Light 10 Bold',
                   win_family='LM Mono Light 10',
                   win_style='Bold',
                   win_full='LMMonoLt10-Bold',
                   win_typo_f='Latin Modern Mono Light',
                   win_typo_sub_f='10 Bold'),

    FontUpdateInfo(otf='lmmonolt10-boldoblique',
                   mac_family='Latin Modern Mono Light',
                   mac_style='10 Bold Oblique',
                   mac_full='Latin Modern Mono Light 10 Bold Oblique',
                   win_family='LM Mono Light 10',
                   win_style='Bold Italic',
                   win_full='LMMonoLt10-BoldOblique',
                   win_typo_f='Latin Modern Mono Light',
                   win_typo_sub_f='10 Bold Oblique'),

    FontUpdateInfo(otf='lmmonolt10-oblique',
                   mac_family='Latin Modern Mono Light',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Mono Light 10 Oblique',
                   win_family='LM Mono Light 10',
                   win_style='Italic',
                   win_full='LMMonoLt10-Oblique',
                   win_typo_f='Latin Modern Mono Light',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmmonolt10-regular',
                   mac_family='Latin Modern Mono Light',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Mono Light 10 Regular',
                   win_family='LM Mono Light 10',
                   win_style='Regular',
                   win_full='LMMonoLt10-Regular',
                   win_typo_f='Latin Modern Mono Light',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmmonoltcond10-oblique',
                   mac_family='Latin Modern Mono Light Cond',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Mono Light Cond 10 Oblique',
                   win_family='LM Mono Light Cond 10',
                   win_style='Italic',
                   win_full='LMMonoLtCond10-Oblique',
                   win_typo_f='Latin Modern Mono Light Cond',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmmonoltcond10-regular',
                   mac_family='Latin Modern Mono Light Cond',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Mono Light Cond 10 Regular',
                   win_family='LM Mono Light Cond 10',
                   win_style='Regular',
                   win_full='LMMonoLtCond10-Regular',
                   win_typo_f='Latin Modern Mono Light Cond',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmmonoprop10-oblique',
                   mac_family='Latin Modern Mono Prop',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Mono Prop 10 Oblique',
                   win_family='LM Mono Prop 10',
                   win_style='Italic',
                   win_full='LMMonoProp10-Oblique',
                   win_typo_f='Latin Modern Mono Prop',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmmonoprop10-regular',
                   mac_family='Latin Modern Mono Prop',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Mono Prop 10 Regular',
                   win_family='LM Mono Prop 10',
                   win_style='Regular',
                   win_full='LMMonoProp10-Regular',
                   win_typo_f='Latin Modern Mono Prop',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmmonoproplt10-bold',
                   mac_family='Latin Modern Mono Prop Light',
                   mac_style='10 Bold',
                   mac_full='Latin Modern Mono Prop Light 10 Bold',
                   win_family='LM Mono Prop Light 10',
                   win_style='Bold',
                   win_full='LMMonoPropLt10-Bold',
                   win_typo_f='Latin Modern Mono Prop Light',
                   win_typo_sub_f='10 Bold'),

    FontUpdateInfo(otf='lmmonoproplt10-boldoblique',
                   mac_family='Latin Modern Mono Prop Light',
                   mac_style='10 BoldOblique',
                   mac_full='Latin Modern Mono Prop Light 10 BoldOblique',
                   win_family='LM Mono Prop Light 10',
                   win_style='Bold Italic',
                   win_full='LMMonoPropLt10-BoldOblique',
                   win_typo_f='Latin Modern Mono Prop Light',
                   win_typo_sub_f='10 BoldOblique'),

    FontUpdateInfo(otf='lmmonoproplt10-oblique',
                   mac_family='Latin Modern Mono Prop Light',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Mono Prop Light 10 Oblique',
                   win_family='LM Mono Prop Light 10',
                   win_style='Italic',
                   win_full='LMMonoPropLt10-Oblique',
                   win_typo_f='Latin Modern Mono Prop Light',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmmonoproplt10-regular',
                   mac_family='Latin Modern Mono Prop Light',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Mono Prop Light 10 Regular',
                   win_family='LM Mono Prop Light 10',
                   win_style='Regular',
                   win_full='LMMonoPropLt10-Regular',
                   win_typo_f='Latin Modern Mono Prop Light',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmmonoslant10-regular',
                   mac_family='Latin Modern Mono Slanted',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Mono Slanted 10 Regular',
                   win_family='LM Mono Slanted 10',
                   win_style='Regular',
                   win_full='LMMonoSlant10-Regular',
                   win_typo_f='Latin Modern Mono Slanted',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmroman10-bold',
                   mac_family='Latin Modern Roman',
                   mac_style='10 Bold',
                   mac_full='Latin Modern Roman 10 Bold',
                   win_family='LM Roman 10',
                   win_style='Bold',
                   win_full='LMRoman10-Bold',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='10 Bold'),

    FontUpdateInfo(otf='lmroman10-bolditalic',
                   mac_family='Latin Modern Roman',
                   mac_style='10 Bold Italic',
                   mac_full='Latin Modern Roman 10 Bold Italic',
                   win_family='LM Roman 10',
                   win_style='Bold Italic',
                   win_full='LMRoman10-BoldItalic',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='10 Bold Italic'),

    FontUpdateInfo(otf='lmroman10-italic',
                   mac_family='Latin Modern Roman',
                   mac_style='10 Italic',
                   mac_full='Latin Modern Roman 10 Italic',
                   win_family='LM Roman 10',
                   win_style='Italic',
                   win_full='LMRoman10-Italic',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='10 Italic'),

    FontUpdateInfo(otf='lmroman10-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Roman 10 Regular',
                   win_family='LM Roman 10',
                   win_style='Regular',
                   win_full='LMRoman10-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmroman12-bold',
                   mac_family='Latin Modern Roman',
                   mac_style='12 Bold',
                   mac_full='Latin Modern Roman 12 Bold',
                   win_family='LM Roman 12',
                   win_style='Bold',
                   win_full='LMRoman12-Bold',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='12 Bold'),

    FontUpdateInfo(otf='lmroman12-italic',
                   mac_family='Latin Modern Roman',
                   mac_style='12 Italic',
                   mac_full='Latin Modern Roman 12 Italic',
                   win_family='LM Roman 12',
                   win_style='Italic',
                   win_full='LMRoman12-Italic',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='12 Italic'),

    FontUpdateInfo(otf='lmroman12-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='12 Regular',
                   mac_full='Latin Modern Roman 12 Regular',
                   win_family='LM Roman 12',
                   win_style='Regular',
                   win_full='LMRoman12-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='12 Regular'),

    FontUpdateInfo(otf='lmroman17-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='17 Regular',
                   mac_full='Latin Modern Roman 17 Regular',
                   win_family='LM Roman 17',
                   win_style='Regular',
                   win_full='LMRoman17-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='17 Regular'),

    FontUpdateInfo(otf='lmroman5-bold',
                   mac_family='Latin Modern Roman',
                   mac_style='5 Bold',
                   mac_full='Latin Modern Roman 5 Bold',
                   win_family='LM Roman 5',
                   win_style='Bold',
                   win_full='LMRoman5-Bold',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='5 Bold'),

    FontUpdateInfo(otf='lmroman5-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='5 Regular',
                   mac_full='Latin Modern Roman 5 Regular',
                   win_family='LM Roman 5',
                   win_style='Regular',
                   win_full='LMRoman5-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='5 Regular'),

    FontUpdateInfo(otf='lmroman6-bold',
                   mac_family='Latin Modern Roman',
                   mac_style='6 Bold',
                   mac_full='Latin Modern Roman 6 Bold',
                   win_family='LM Roman 6',
                   win_style='Bold',
                   win_full='LMRoman6-Bold',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='6 Bold'),

    FontUpdateInfo(otf='lmroman6-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='6 Regular',
                   mac_full='Latin Modern Roman 6 Regular',
                   win_family='LM Roman 6',
                   win_style='Regular',
                   win_full='LMRoman6-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='6 Regular'),

    FontUpdateInfo(otf='lmroman7-bold',
                   mac_family='Latin Modern Roman',
                   mac_style='7 Bold',
                   mac_full='Latin Modern Roman 7 Bold',
                   win_family='LM Roman 7',
                   win_style='Bold',
                   win_full='LMRoman7-Bold',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='7 Bold'),

    FontUpdateInfo(otf='lmroman7-italic',
                   mac_family='Latin Modern Roman',
                   mac_style='7 Italic',
                   mac_full='Latin Modern Roman 7 Italic',
                   win_family='LM Roman 7',
                   win_style='Italic',
                   win_full='LMRoman7-Italic',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='7 Italic'),

    FontUpdateInfo(otf='lmroman7-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='7 Regular',
                   mac_full='Latin Modern Roman 7 Regular',
                   win_family='LM Roman 7',
                   win_style='Regular',
                   win_full='LMRoman7-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='7 Regular'),

    FontUpdateInfo(otf='lmroman8-bold',
                   mac_family='Latin Modern Roman',
                   mac_style='8 Bold',
                   mac_full='Latin Modern Roman 8 Bold',
                   win_family='LM Roman 8',
                   win_style='Bold',
                   win_full='LMRoman8-Bold',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='8 Bold'),

    FontUpdateInfo(otf='lmroman8-italic',
                   mac_family='Latin Modern Roman',
                   mac_style='8 Italic',
                   mac_full='Latin Modern Roman 8 Italic',
                   win_family='LM Roman 8',
                   win_style='Italic',
                   win_full='LMRoman8-Italic',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='8 Italic'),

    FontUpdateInfo(otf='lmroman8-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='8 Regular',
                   mac_full='Latin Modern Roman 8 Regular',
                   win_family='LM Roman 8',
                   win_style='Regular',
                   win_full='LMRoman8-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='8 Regular'),

    FontUpdateInfo(otf='lmroman9-bold',
                   mac_family='Latin Modern Roman',
                   mac_style='9 Bold',
                   mac_full='Latin Modern Roman 9 Bold',
                   win_family='LM Roman 9',
                   win_style='Bold',
                   win_full='LMRoman9-Bold',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='9 Bold'),

    FontUpdateInfo(otf='lmroman9-italic',
                   mac_family='Latin Modern Roman',
                   mac_style='9 Italic',
                   mac_full='Latin Modern Roman 9 Italic',
                   win_family='LM Roman 9',
                   win_style='Italic',
                   win_full='LMRoman9-Italic',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='9 Italic'),

    FontUpdateInfo(otf='lmroman9-regular',
                   mac_family='Latin Modern Roman',
                   mac_style='9 Regular',
                   mac_full='Latin Modern Roman 9 Regular',
                   win_family='LM Roman 9',
                   win_style='Regular',
                   win_full='LMRoman9-Regular',
                   win_typo_f='Latin Modern Roman',
                   win_typo_sub_f='9 Regular'),

    FontUpdateInfo(otf='lmromancaps10-oblique',
                   mac_family='Latin Modern Roman Caps',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Roman Caps 10 Oblique',
                   win_family='LM Roman Caps 10',
                   win_style='Italic',
                   win_full='LMRomanCaps10-Oblique',
                   win_typo_f='Latin Modern Roman Caps',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmromancaps10-regular',
                   mac_family='Latin Modern Roman Caps',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Roman Caps 10 Regular',
                   win_family='LM Roman Caps 10',
                   win_style='Regular',
                   win_full='LMRomanCaps10-Regular',
                   win_typo_f='Latin Modern Roman Caps',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmromandemi10-oblique',
                   mac_family='Latin Modern Roman Demi',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Roman Demi 10 Oblique',
                   win_family='LM Roman Demi 10',
                   win_style='Italic',
                   win_full='LMRomanDemi10-Oblique',
                   win_typo_f='Latin Modern Roman Demi',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmromandemi10-regular',
                   mac_family='Latin Modern Roman Demi',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Roman Demi 10 Regular',
                   win_family='LM Roman Demi 10',
                   win_style='Regular',
                   win_full='LMRomanDemi10-Regular',
                   win_typo_f='Latin Modern Roman Demi',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmromandunh10-oblique',
                   mac_family='Latin Modern Roman Dunhill',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Roman Dunhill 10 Oblique',
                   win_family='LM Roman Dunhill 10',
                   win_style='Italic',
                   win_full='LMRomanDunh10-Oblique',
                   win_typo_f='Latin Modern Roman Dunhill',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmromandunh10-regular',
                   mac_family='Latin Modern Roman Dunhill',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Roman Dunhill 10 Regular',
                   win_family='LM Roman Dunhill 10',
                   win_style='Regular',
                   win_full='LMRomanDunh10-Regular',
                   win_typo_f='Latin Modern Roman Dunhill',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmromanslant10-bold',
                   mac_family='Latin Modern Roman Slanted',
                   mac_style='10 Bold',
                   mac_full='Latin Modern Roman Slanted 10 Bold',
                   win_family='LM Roman Slanted 10',
                   win_style='Bold',
                   win_full='LMRomanSlant10-Bold',
                   win_typo_f='Latin Modern Roman Slanted',
                   win_typo_sub_f='10 Bold'),

    FontUpdateInfo(otf='lmromanslant10-regular',
                   mac_family='Latin Modern Roman Slanted',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Roman Slanted 10 Regular',
                   win_family='LM Roman Slanted 10',
                   win_style='Regular',
                   win_full='LMRomanSlant10-Regular',
                   win_typo_f='Latin Modern Roman Slanted',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmromanslant12-regular',
                   mac_family='Latin Modern Roman Slanted',
                   mac_style='12 Regular',
                   mac_full='Latin Modern Roman Slanted 12 Regular',
                   win_family='LM Roman Slanted 12',
                   win_style='Regular',
                   win_full='LMRomanSlant12-Regular',
                   win_typo_f='Latin Modern Roman Slanted',
                   win_typo_sub_f='12 Regular'),

    FontUpdateInfo(otf='lmromanslant8-regular',
                   mac_family='Latin Modern Roman Slanted',
                   mac_style='8 Regular',
                   mac_full='Latin Modern Roman Slanted 8 Regular',
                   win_family='LM Roman Slanted 8',
                   win_style='Regular',
                   win_full='LMRomanSlant8-Regular',
                   win_typo_f='Latin Modern Roman Slanted',
                   win_typo_sub_f='8 Regular'),

    FontUpdateInfo(otf='lmromanslant9-regular',
                   mac_family='Latin Modern Roman Slanted',
                   mac_style='9 Regular',
                   mac_full='Latin Modern Roman Slanted 9 Regular',
                   win_family='LM Roman Slanted 9',
                   win_style='Regular',
                   win_full='LMRomanSlant9-Regular',
                   win_typo_f='Latin Modern Roman Slanted',
                   win_typo_sub_f='9 Regular'),

    FontUpdateInfo(otf='lmromanunsl10-regular',
                   mac_family='Latin Modern Roman Unslanted',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Roman Unslanted 10 Regular',
                   win_family='LM Roman Unslanted 10',
                   win_style='Regular',
                   win_full='LMRomanUnsl10-Regular',
                   win_typo_f='Latin Modern Roman Unslanted',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmsans10-bold',
                   mac_family='Latin Modern Sans',
                   mac_style='10 Bold',
                   mac_full='Latin Modern Sans 10 Bold',
                   win_family='LM Sans 10',
                   win_style='Bold',
                   win_full='LMSans10-Bold',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='10 Bold'),

    FontUpdateInfo(otf='lmsans10-boldoblique',
                   mac_family='Latin Modern Sans',
                   mac_style='10 Bold Oblique',
                   mac_full='Latin Modern Sans 10 Bold Oblique',
                   win_family='LM Sans 10',
                   win_style='Bold Italic',
                   win_full='LMSans10-BoldOblique',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='10 Bold Oblique'),

    FontUpdateInfo(otf='lmsans10-oblique',
                   mac_family='Latin Modern Sans',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Sans 10 Oblique',
                   win_family='LM Sans 10',
                   win_style='Italic',
                   win_full='LMSans10-Oblique',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmsans10-regular',
                   mac_family='Latin Modern Sans',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Sans 10 Regular',
                   win_family='LM Sans 10',
                   win_style='Regular',
                   win_full='LMSans10-Regular',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmsans12-oblique',
                   mac_family='Latin Modern Sans',
                   mac_style='12 Oblique',
                   mac_full='Latin Modern Sans 12 Oblique',
                   win_family='LM Sans 12',
                   win_style='Italic',
                   win_full='LMSans12-Oblique',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='12 Oblique'),

    FontUpdateInfo(otf='lmsans12-regular',
                   mac_family='Latin Modern Sans',
                   mac_style='12 Regular',
                   mac_full='Latin Modern Sans 12 Regular',
                   win_family='LM Sans 12',
                   win_style='Regular',
                   win_full='LMSans12-Regular',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='12 Regular'),

    FontUpdateInfo(otf='lmsans17-oblique',
                   mac_family='Latin Modern Sans',
                   mac_style='17 Oblique',
                   mac_full='Latin Modern Sans 17 Oblique',
                   win_family='LM Sans 17',
                   win_style='Italic',
                   win_full='LMSans17-Oblique',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='17 Oblique'),

    FontUpdateInfo(otf='lmsans17-regular',
                   mac_family='Latin Modern Sans',
                   mac_style='17 Regular',
                   mac_full='Latin Modern Sans 17 Regular',
                   win_family='LM Sans 17',
                   win_style='Regular',
                   win_full='LMSans17-Regular',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='17 Regular'),

    FontUpdateInfo(otf='lmsans8-oblique',
                   mac_family='Latin Modern Sans',
                   mac_style='8 Oblique',
                   mac_full='Latin Modern Sans 8 Oblique',
                   win_family='LM Sans 8',
                   win_style='Italic',
                   win_full='LMSans8-Oblique',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='8 Oblique'),

    FontUpdateInfo(otf='lmsans8-regular',
                   mac_family='Latin Modern Sans',
                   mac_style='8 Regular',
                   mac_full='Latin Modern Sans 8 Regular',
                   win_family='LM Sans 8',
                   win_style='Regular',
                   win_full='LMSans8-Regular',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='8 Regular'),

    FontUpdateInfo(otf='lmsans9-oblique',
                   mac_family='Latin Modern Sans',
                   mac_style='9 Oblique',
                   mac_full='Latin Modern Sans 9 Oblique',
                   win_family='LM Sans 9',
                   win_style='Italic',
                   win_full='LMSans9-Oblique',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='9 Oblique'),

    FontUpdateInfo(otf='lmsans9-regular',
                   mac_family='Latin Modern Sans',
                   mac_style='9 Regular',
                   mac_full='Latin Modern Sans 9 Regular',
                   win_family='LM Sans 9',
                   win_style='Regular',
                   win_full='LMSans9-Regular',
                   win_typo_f='Latin Modern Sans',
                   win_typo_sub_f='9 Regular'),

    FontUpdateInfo(otf='lmsansdemicond10-oblique',
                   mac_family='Latin Modern Sans Demi Cond',
                   mac_style='10 Oblique',
                   mac_full='Latin Modern Sans Demi Cond 10 Oblique',
                   win_family='LM Sans Demi Cond 10',
                   win_style='Italic',
                   win_full='LMSansDemiCond10-Oblique',
                   win_typo_f='Latin Modern Sans Demi Cond',
                   win_typo_sub_f='10 Oblique'),

    FontUpdateInfo(otf='lmsansdemicond10-regular',
                   mac_family='Latin Modern Sans Demi Cond',
                   mac_style='10 Regular',
                   mac_full='Latin Modern Sans Demi Cond 10 Regular',
                   win_family='LM Sans Demi Cond 10',
                   win_style='Regular',
                   win_full='LMSansDemiCond10-Regular',
                   win_typo_f='Latin Modern Sans Demi Cond',
                   win_typo_sub_f='10 Regular'),

    FontUpdateInfo(otf='lmsansquot8-bold',
                   mac_family='Latin Modern Sans Quotation',
                   mac_style='8 Bold',
                   mac_full='Latin Modern Sans Quotation 8 Bold',
                   win_family='LM Sans Quot 8',
                   win_style='Bold',
                   win_full='LMSansQuot8-Bold',
                   win_typo_f='Latin Modern Sans Quotation',
                   win_typo_sub_f='8 Bold'),

    FontUpdateInfo(otf='lmsansquot8-boldoblique',
                   mac_family='Latin Modern Sans Quotation',
                   mac_style='8 Bold Oblique',
                   mac_full='Latin Modern Sans Quotation 8 Bold Oblique',
                   win_family='LM Sans Quot 8',
                   win_style='Italic',
                   win_full='LMSansQuot8-BoldOblique',
                   win_typo_f='Latin Modern Sans Quotation',
                   win_typo_sub_f='8 Bold Oblique'),

    FontUpdateInfo(otf='lmsansquot8-oblique',
                   mac_family='Latin Modern Sans Quotation',
                   mac_style='8 Oblique',
                   mac_full='Latin Modern Sans Quotation 8 Oblique',
                   win_family='LM Sans Quot 8',
                   win_style='Bold Italic',
                   win_full='LMSansQuot8-Oblique',
                   win_typo_f='Latin Modern Sans Quotation',
                   win_typo_sub_f='8 Oblique'),

    FontUpdateInfo(otf='lmsansquot8-regular',
                   mac_family='Latin Modern Sans Quotation',
                   mac_style='8 Regular',
                   mac_full='Latin Modern Sans Quotation 8 Regular',
                   win_family='LM Sans Quot 8',
                   win_style='Regular',
                   win_full='LMSansQuot8-Regular',
                   win_typo_f='Latin Modern Sans Quotation',
                   win_typo_sub_f='8 Regular'),
]

for font_up_info in fonts_update_info:
    font_up_info.add_compat_names()
