#!/bin/bash
pip2arch CodeIntel #-v2.0.0b10
sed -e '/Automatically generated by pip2arch/d' -i PKGBUILD

pkgver=$(grep -oPm1 '(?<=pkgver=).*' PKGBUILD)
url=$(grep -oPm1 "(?<=source=\(').*(?=')" PKGBUILD)
digest=$(grep -oPm1 "(?<=sums=\(').*(?=')" PKGBUILD)

cp pip2arch-fix-tmpl.patch pip2arch-fix.patch
sed -e "s@<pkgver>@${pkgver}@g" -e "s@<source>@${url}@g" \
    -e "s@<hash>@${digest}@g" -i pip2arch-fix.patch

patch -p1 < pip2arch-fix.patch
if [ $? -eq 0 ]; then
    rm pip2arch-fix.patch
    makepkg --printsrcinfo > .SRCINFO
fi
