post_install() {
  echo ""
  echo "Installed files. Please edit your config in /etc/owncloud/news/updater.ini and run:"
  echo "    systemctl enable owncloud-news-updater.service"
  echo "    systemctl start owncloud-news-updater.service"
  echo "to run the updater on startup and:"
  echo "    systemctl restart owncloud-news-updater.service"
  echo "to reload the changes if you change the config in /etc/owncloud/news/updater.ini"

}
