#!/usr/bin/env bash

# Return Submodule's Git Command
function echoGitCMDForSubModule {
    local -A subParent
    local gitCMDName='git '
    for path in "${!subCommit[@]}"; do
        configUrl="-c submodule.${subName[$path]}.url=\"\${srcdir}/${path//\//|}\" \\"
        moduleParent=$path
        while true; do
            moduleParent=${moduleParent%\/*}
            if [[ -f $moduleParent/.gitmodules ]]; then
                subParent[$moduleParent]+="$configUrl"$'\n'$(printf %"${#gitCMDName}"s); break
            elif [[ $moduleParent == "${moduleParent%\/*}" ]]; then
                subParent[.]+="$configUrl"$'\n'$(printf %"${#gitCMDName}"s); break
            fi
        done
    done
    for parent in "${!subParent[@]}"; do
        echo -e "${gitCMDName}${subParent[$parent]}-c protocol.file.allow=always -C '$parent' submodule update"
    done
}

declare subModuleSourceTextStart="# Auto generated by '${0##*/}', do not edit."
declare subModuleSourceTextEnd='# End'

# Return Submodule's Source Text
function echoSourceTextForSubModule {
    sourceArrayName='source+=('
    subModuleSourceText+="${subModuleSourceTextStart}"$'\n'"${sourceArrayName}"
    count=1 && for path in "${!subCommit[@]}"; do
        if [[ $path =~ ^(src|pkg|PKGBUILD|.SRCINFO)$ ]]; then
            echo 'TODO: fix submodule that name as src,pkg,PKGBUILD or .SRCINFO.' && exit 1
        fi
        subModule="${path//\//|}::git+${subUrl[$path]}#commit=${subCommit[$path]}"
        if [ "${#subCommit[@]}" == "$count" ]; then
            subModuleSourceText+="'$subModule'"
        else
            subModuleSourceText+="'$subModule'"$'\n'$(printf %"${#sourceArrayName}"s)
        fi
        ((count++))
    done
    subModuleSourceText+=") ${subModuleSourceTextEnd}"
    echo "$subModuleSourceText"
}

# Update source array in PKGBUILD
#
# $1=[Path to PKGBUILD]
function updateBuildScriptForSubModule {
    if buildScriptFile=$(readlink -se "$1"); then
        buildScript=$(cat "$buildScriptFile" 2> /dev/null)
        SourceText="$(echoSourceTextForSubModule)"
        if [[ $buildScript != *$SourceText* ]]; then
            sourceTextForSed=$(echo "$SourceText"|sed -ze 's&\n&\\n&g' -e 's&|&\\|&g')
            sededbuildScript=$(echo "$buildScript" | sed -z "s|\n$subModuleSourceTextStart\nsource+=([^)]*) $subModuleSourceTextEnd\n|\n$sourceTextForSed|")

            if [ "$buildScript" == "$sededbuildScript" ]; then
                echo "$SourceText" >> "$buildScriptFile"
            else
                echo "$sededbuildScript" > "$buildScriptFile"
            fi

            # shellcheck disable=SC2181,SC2320
            if [[ $? != 0 ]]; then
                echo "Failed to update '$buildScriptFile'. The file has not been modified."
            else
                echo "The source of submodules in '$buildScriptFile' have been updated! Please update checksums, then do makepkg again."
            fi && exit 2
        else
            echo "No update for Submodules, continue..." && exit 0
        fi
    else
        echo "Failed to update '$buildScriptFile'. The file is not exist." && exit 1
    fi
}

function printUsage {
	cat <<-EOF
	Update source array of Git submodules in PKGBUILD

	Contain functions:
	"echoSourceTextForSubModule": Echo source array of given Git repository
	"echoGitCMDForSubModule": Echo Git command for PKGBUILD to change submodule's url
	"updateBuildScriptForSubModule [Path to PKGBUILD]": Update source array and replace it in PKGBUILD

	example:
	    $ export _repo="[Path to Git repository]"
	    $ ${0##*/} echoSourceTextForSubModule
	    $ ${0##*/} echoGitCMDForSubModule
	    $ ${0##*/} updateBuildScriptForSubModule "[Path to PKGBUILD]"

	EOF
}

# $1=[ Path to Git Repository ]
declare -A subUrl
declare -A subName
declare -A subPath
declare -A subCommit
function readGitModules {
    gitModulesFile=$(readlink -se "$1/.gitmodules") || return 1
    gitModules=$(git config -f "$gitModulesFile" -l) || return 2

    # Submodule's Commit Array
    gitModulesStatus=$(git submodule status --recursive --cached -- "$1") || return 3
    IFS=$'\n' && for line in $gitModulesStatus; do
        line=${line:1}; line=${line% (*)}
        path=${line#* }
        subCommit+=(["$path"]="${line% *}")
        if [[ -f $path/.gitmodules ]]; then
            gitModules+=$'\n'$(git config -f "$path/.gitmodules" -l | sed "s#.path=#.path=$path/#g") || return 4
        fi
    done && unset IFS

    # Submodule's Path Array
    IFS=$'\n' && for line in $gitModules; do
        name=${line#submodule.}; name=${name%.*=*}
        if [[ $line =~ .*.path=.* ]]; then
            subName+=(["${line#*.path=}"]="$name") # So we can get name by path
            subPath+=(["$name"]="${line#*.path=}")
        fi
    done && unset IFS

    # Submodule's Url Array
    IFS=$'\n' && for line in $gitModules; do
        name=${line#submodule.}; name=${name%.*=*}
        if [[ $line =~ .*.url=.* ]]; then
            subUrl+=(["${subPath[$name]}"]="${line#*.url=}")
        fi
    done && unset IFS

    # Only support 'path' and 'url'
}

if ! type git > /dev/null 2>&1; then
    echo "This script needs \`git\` in order to work, aborting..." && exit 1
fi

gitRepo=${_repo:-$PWD}
if ! readGitModules "$gitRepo"; then
    code=$?; printUsage
    echo "No submodule in '$gitRepo', aborting..."
    exit "$code"
fi

#for path in "${!subName[@]}"; do
#    echo -e "$path:\n  ${subCommit[$path]}\n  ${subName[$path]}\n  ${subUrl[$path]}\n"
#done

case "$1" in
    echoGitCMDForSubModule)
        echoGitCMDForSubModule
        ;;
    echoSourceTextForSubModule)
        echoSourceTextForSubModule
        ;;
    updateBuildScriptForSubModule)
        updateBuildScriptForSubModule "${2:-$PWD/../../PKGBUILD}" # The path to PKGBUILD in most case
        ;;
    *)
        printUsage && exit 1
        ;;
esac
