#!/bin/bash

IS_UNITY_FAMILY=`echo $XDG_CURRENT_DESKTOP | awk -F: "{print $1}"`

if [ "$IS_UNITY_FAMILY" == "Unity" ]; then
  export XDG_CURRENT_DESKTOP=Unity
fi

cd "/opt/upwork"
exec "./upwork" "$@"
