post_install () {
	echo "==> To enable tabbedex place the following in ~/.Xdefaults"
	echo "==> URxvt.perl-ext-common:  default,tabbedex"
	echo "==> For documentation see urxvtperl man file (section on the tabbed"
	echo "==> extension), also see the comments at the top of the tabbedex source"
	echo "==> code: /usr/lib/urxvt/perl/tabbedex"
}

post_upgrade () {
	post_install $1
}

# vim: set ts=4 sw=4 noet:
