#!/bin/bash
cd /opt/usc-game-v0.5.0/bin/songs/nautica/
url=$(dialog --title "下載圖譜" --inputbox "下載鏈接\nhttps://ksm.dev/\n(Download右鍵複製鏈接)" 0 0 2>&1 >> /dev/tty)
if [ "$url" = "" ]
then
    dialog --infobox "沒有輸入鏈接！" 0 0
    sleep 1
    exit
fi
curl -L -o download.zip $url
unzip download.zip
rm -rf download.zip
