#!/bin/bash

WINEDEBUG=-all wine /usr/share/usenti/usenti.exe "$(winepath -w "$1")"

if [ $? -eq 53 ]
then
    winetricks -q mfc42
    WINEDEBUG=-all wine /usr/share/usenti/usenti.exe "$(winepath -w "$1")"
fi
