post_install() {
	cat << EOF
====================================================
All binaries are prefixed with valveresourceformat-*
valveresourceformat-wine included for wine wrapping
====================================================
EOF
}

post_upgrade() {
	cat << EOF
====================================================
All binaries are prefixed with valveresourceformat-*
valveresourceformat-wine included for wine wrapping
====================================================
EOF
}
