post_install() {
  update-desktop-database -q /usr/share/applications
  printf "--------------------------------------------------\n"
  printf " Rebuild the package when out-of-date.\n\n"
  printf " Use \"vatsim-crc clean\" to clean up WINEPREFIX.\n\n"
  printf " Personally, I recommend Proton over Wine:\n"
  printf " This package automatically detects umu-run and   \n"
  printf " proton-ge-custom-bin. You may specify custom     \n"
  printf " PROTONPATH on first run of each upgrade and it   \n"
  printf " will be saved for future use." 
  printf "--------------------------------------------------\n"
}

post_upgrade() {
  post_install $1
}

post_remove() {
  post_install $1
}
