post_install() {
  mkdir -p /var/lib/vdr/plugins/live
  cd /var/lib/vdr/plugins/live
  if [ ! -e live.pem ] || [ ! -e live-key.pem ]; then
    openssl req -new -x509 -keyout live-key.pem -out live.pem -days 9999 -nodes -batch
  fi
}

post_upgrade() {
  post_install
}

post_remove() {
  rm /var/lib/vdr/plugins/live/live.pem
  rm /var/lib/vdr/plugins/live/live-key.pem
  rmdir /var/lib/vdr/plugins/live 2> /dev/null
}
