post_install() {
    if command -v 'nvim' &>/dev/null ; then
        vimprog='/usr/bin/nvim'
    else
        vimprog='/usr/bin/vim'
    fi

    # adapted from https://pastebin.com/5PNhhrMv
    echo -n "Updating help tags..."
    $vimprog --noplugins -u NONE \
        --cmd ":helptags /usr/share/vim/vimfiles/doc/" --cmd ":q" > /dev/null 2>&1
    echo "done."
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
