post_install(){
  echo ''
  echo 'To generate the Csound helptags accessed via Shift-K run'
  echo '  mkdir -p ~/.vim/doc/ && \ '
  echo '  ln -s /usr/share/vim/vimfiles/doc/csound.txt ~/.vim/doc/csound.txt && \ '
  echo '  cd ~/.vim/ && \ '
  echo '  vim -c "helptags doc/"'
  echo ''
}

post_upgrade(){
  echo ''
  echo 'Remember to update your helptags by running'
  echo '  cd ~/.vim/ && \ '
  echo '  vim -c "helptags doc/"'
  echo ''
}

# vim: et sw=2 ts=2
