upstream viseron {
    server 127.0.0.1:9999;
}

upstream go2rtc {
    server 127.0.0.1:1984;
}

server {
    listen 8888;
    server_name _;

    # Required for proxying WebSockets
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # go2rtc WebRTC stream
    location /live {
        proxy_pass http://go2rtc/api/ws;
    }

    # API
    location /api {
        proxy_pass http://viseron/api;
    }

    # WebSockets
    location /websocket {
        proxy_pass http://viseron/websocket;
    }

    # Camera Streams
    location ~ ^/[A-Za-z0-9_]+/mjpeg-stream$ {
        proxy_pass http://viseron;
        proxy_buffering off;
        gzip off;
    }
    location ~ ^/[A-Za-z0-9_]+/mjpeg-streams/[A-Za-z0-9_\-]+$ {
        proxy_pass http://viseron;
        proxy_buffering off;
        gzip off;
    }
    location ~ ^/[A-Za-z0-9_]+/static-mjpeg-streams/[A-Za-z0-9_\-]+$ {
        proxy_pass http://viseron;
        proxy_buffering off;
        gzip off;
    }

    # Files
    location /files {
        proxy_pass http://viseron/files;
    }

    # Frontend
    location / {
        add_header Cache-Control "no-store";
        expires off;

        location /assets/ {
            root /usr/lib/viseron/viseron/frontend;
        }

        root /usr/lib/viseron/viseron/frontend;
        try_files $uri $uri.html $uri/ /index.html;
    }
}
