post_install() {
    pkgver=$1
    cat <<EOF
POST INSTALL INFO

1. If you selected Vitis, then installation of Versal Qemu emulator may have
failed. To reinstall run the following script:

   ⚠️ The installer uses sudo.
   $_installprefix/$pkgver/Vitis/data/emulation/qemu/comp/qemu_scripts/qemu/x86_64-qemu-xilinx-nativesdk-standalone -d $_installprefix/Vitis/$pkgver/data/emulation/qemu/comp/qemu -y

EOF
}
