## arg 1:  the new package version
post_install() {
    cat << EOF


** Mangosd expects game data files to be located in /var/lib/vmangos.
** These can be extracted from the client, or obtained from elsewhere and
** placed in the directory.
** Note that the extraction process will take up to a couple hours.

Procedure for extracting:
1. Cd to your MMORPG installation directory
2. $ sudo -u vmangos /usr/share/vmangos/vmangos-extract-data.sh
    - Run as 'vmangos' user to have permissions over the target directory.

** Sql scripts to set up the databases can be found in /usr/share/vmangos/sql.
** Use MariaDB to set up databases.

** More info:
** https://github.com/vmangos/wiki/wiki/Getting-it-working

** To start the server, use
**     # systemctl start vmangos-realmd vmangos-mangosd
** Stdin of the console can be written to at /run/vmangos-mangosd.stdin


EOF
}

post_upgrade() {
    cat << EOF
** Databases need to be updated.
** Sql scripts can be found at /usr/share/vmangos/sql/migrations.
EOF
}
