post_install() {
  /usr/share/vscodium-translucent-features/patch.py vscodium-translucent-features patch
}

pre_upgrade() {
  /usr/share/vscodium-translucent-features/patch.py vscodium-translucent-features restore
}

post_upgrade() {
  /usr/share/vscodium-translucent-features/patch.py vscodium-translucent-features patch
}

pre_remove() {
  /usr/share/vscodium-translucent-features/patch.py vscodium-translucent-features restore
  /usr/bin/rm -f /usr/share/vscodium-translucent-features/cache.json
}
