post_install() {
  /usr/share/vscodium-electron-features/patch.py vscodium-electron-features patch
}

pre_upgrade() {
  /usr/share/vscodium-electron-features/patch.py vscodium-electron-features restore
}

post_upgrade() {
  /usr/share/vscodium-electron-features/patch.py vscodium-electron-features patch
}

pre_remove() {
  /usr/share/vscodium-electron-features/patch.py vscodium-electron-features restore
  /usr/bin/rm -f /usr/share/vscodium-electron-features/cache.json
}
