post_install() {
  for file in \
    /usr/lib/code*/package.json \
    /opt/visual-studio-code*/resources/app/package.json \
    /opt/vscodium*/resources/app/package.json \
    /usr/share/applications/code*.desktop \
    /usr/share/applications/vscode*.desktop \
    /usr/share/applications/vscodium*.desktop; do
    if [[ -f "${file}" ]]; then
      echo "${file}" | /usr/lib/vscode-xdg-patch-hook/apply-xdg-patch.sh
    fi
  done
}

post_upgrade() {
  post_install
}
