post_install() {
    echo "=============================================="
    echo ">>> vtlock: To enable VT locking, set the setuid bit:"
    echo "    sudo chmod u+s /usr/bin/vtlock"
    echo ">>> Then create a wrapper script."
    echo "    Examples in /usr/share/doc/vtlock/README.md"
    echo ">>> To verify future signed releases, import the GPG key:"
    echo "    gpg --recv-keys E0844009CF213E78ECD348795A6792BF5ECC3AC6"
    echo "=============================================="
}

post_upgrade() {
    echo "=============================================="
    echo ">>> vtlock upgrade detected <<<"
    echo ">>> Re-set the setuid bit after upgrade:"
    echo "    sudo chmod u+s /usr/bin/vtlock"
    echo "=============================================="
}
