post_install() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

	if [ -L '/usr/bin/vutron' -a -e '/usr/bin/vutron' -a "`readlink '/usr/bin/vutron'`" != '/etc/alternatives/vutron' ]; then
	    rm -f '/usr/bin/vutron'
	else
	    ln -sf '/opt/VutronMusic/vutron' '/usr/bin/vutron'
	fi

	# SUID chrome-sandbox for Electron 5+
	chmod 4755 '/opt/VutronMusic/chrome-sandbox' || true

	if hash update-mime-database 2>/dev/null; then
	    update-mime-database /usr/share/mime || true
	fi

	if hash update-desktop-database 2>/dev/null; then
	    update-desktop-database /usr/share/applications || true
	fi
	update-desktop-database -q
}

post_upgrade() {
	post_install
}

post_remove() {
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

	# Delete the link to the binary
	rm -f '/usr/bin/vutron'
	update-desktop-database -q
}
