pre_upgrade()
{
  echo ""
  systemctl stop wazuh-dashboard
  cp /etc/wazuh-dashboard/opensearch_dashboards.yml /etc/wazuh-dashboard/opensearch_dashboards.yml.old
}

post_upgrade()
{
  cp /etc/wazuh-dashboard/opensearch_dashboards.yml /etc/wazuh-dashboard/opensearch_dashboards.yml.pacnew
  cp /etc/wazuh-dashboard/opensearch_dashboards.yml.old /etc/wazuh-dashboard/opensearch_dashboards.yml
  systemctl daemon-reload
  systemctl start wazuh-dashboard
}

post_install()
{
  echo "creating wazuh-indexer user and group"
  groupadd -f wazuh-dashboard
  usuario="wazuh-dashboard" && id "$usuario" &>/dev/null || useradd --system -d /usr/share/wazuh-dashboard -g wazuh-dashboard -s /usr/bin/nologin  wazuh-dashboard
  chown -R wazuh-dashboard:wazuh-dashboard /usr/share/wazuh-dashboard
  chown -R wazuh-dashboard:wazuh-dashboard /etc/wazuh-dashboard
  echo "Done!"
  echo "Visit https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html and follow the configure instructions"
}
