pre_upgrade()
{
  echo "Note that the upgrade process doesn't update plugins installed manually. Outdated plugins might cause the upgrade to fail."
  echo "visit https://documentation.wazuh.com/current/upgrade-guide/upgrading-central-components.html for more details"
  echo "backup the existing Wazuh indexer security configuration files"
  /usr/share/wazuh-indexer/bin/indexer-security-init.sh --options "-backup /etc/wazuh-indexer/opensearch-security -icl -nhnv"
  systemctl stop wazuh-indexer
  cp /etc/wazuh-indexer/jvm.options /etc/wazuh-indexer/jvm.options.old
  echo "pre_upgrade finished"
}

post_upgrade()
{
  echo "Manually reapply any custom settings to the /etc/wazuh-indexer/jvm.options file, check /etc/wazuh-indexer/jvm.options.old"
  /usr/share/wazuh-indexer/bin/indexer-security-init.sh
  chown -R wazuh-indexer:wazuh-indexer /usr/share/wazuh-indexer/*
  chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/*
  systemctl daemon-reload
  systemctl start wazuh-indexer
  echo "finished"
}

post_install()
{
  echo "creating wazuh-indexer user and group"
  groupadd -f wazuh-indexer
  usuario="wazuh-indexer" && id "$usuario" &>/dev/null || useradd --system -d /usr/share/wazuh-indexer -g wazuh-indexer -s /usr/bin/nologin wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /usr/share/wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /var/log/wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /var/lib/wazuh-indexer
  echo "patching files"
  rm /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh
  rm /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-certs-tool.sh
  wget https://arashi.solutions/wazuh-passwords-tool.sh -O /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh
  wget https://arashi.solutions/wazuh-certs-tool.sh -O /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-certs-tool.sh
  echo "Done!"
  echo "Visit https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html and follow the configure instructions and Cluster initialization instructions"
}
