post_install()
{
  echo "creating wazuh-indexer user and group"
  groupadd -f wazuh-indexer
  usuario="wazuh-indexer" && id "$usuario" &>/dev/null || useradd -d /usr/share/wazuh-indexer -g wazuh-indexer -s /usr/bin/nologin wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /usr/share/wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /var/log/wazuh-indexer
  chown -R wazuh-indexer:wazuh-indexer /var/lib/wazuh-indexer
  echo "patching files"
  mv -f wazuh-passwords-tool.sh /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh
  mv -f wazuh-certs-tool.sh /usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-certs-tool.sh
  echo "Done!"
  echo "Visit https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html and follow the configure instructions and Cluster initialization instructions"
}
