post_install() {
    ln -sf /opt/WhatsAppForDesktop/UnofficialWhatsApp /usr/bin/whatsappfordesktop
    desktop-file-install /opt/WhatsAppForDesktop/whatsappfordesktop.desktop
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

post_remove() {
    rm -f /usr/bin/whatsappfordesktop
    rm -f /usr/share/applications/whatsappfordesktop.desktop
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}
