post_install() {
glib-compile-schemas /usr/share/glib-2.0/schemas

if command -v update-desktop-database >/dev/null 2>&1; then
update-desktop-database -q /usr/share/applications
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
fi
}

post_upgrade() {
post_install
}

post_remove() {
glib-compile-schemas /usr/share/glib-2.0/schemas

if command -v update-desktop-database >/dev/null 2>&1; then
update-desktop-database -q /usr/share/applications
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
fi
}

