monitor.v4l2.rules = [
  {
    matches = [
      {
        device.name = "v4l2_device.pci-0000_00_05.0"
      }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
