#!/usr/bin/bash

if [ ! -z $2 ]; then
	export launchTarget="env QT_IM_MODULE=xim $1 -style=gtk+ $2"
else
	export launchTarget="env QT_IM_MODULE=xim $1 -style=gtk+"
fi

exec env bwBindPar="$2" portable
