_update() {
  [[ -x usr/bin/xdg-icon-resource ]] && xdg-icon-resource forceupdate --theme hicolor > /dev/null 2>&1 || true
  [[ -x usr/bin/gtk-update-icon-cache ]] && gtk-update-icon-cache -q -f -t usr/share/icons/hicolor || true
  [[ -x usr/bin/update-desktop-database ]] && update-desktop-database -q || true
}

post_install() {
  _update
  echo "Run xdiffextsetup for the first time to configure your diff tool."
}

post_upgrade() {
  post_install $1
}

post_remove() {
  _update
}
