post_install() {
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-FriDay'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-FriDay-Night'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-MonDay'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-MonDay-Night'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-SaturDay'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-SaturDay-Night'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-SunDay'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-SunDay-Night'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-ThursDay'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-ThursDay-Night'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-TuesDay'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-TuesDay-Night'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-WednesDay'
  gtk-update-icon-cache -f '/usr/share/icons/Xenlism-Wildfire-WednesDay-Night'
}


post_upgrade() {
    post_install
}

post_remove() {
    post_install
}
