post_install() {
    echo '    Try to delete ~/.xmind/ directory if XMind crashes on start.'
    echo '    Edit PKGBUILD and rebuild the package to change GTK or Java version.'
    echo '    You can also set GTK version in the "/usr/share/xmind/XMind/XMind.ini"'
    echo '    file on the line after "--launcher.GTK_version".'
    echo '    You must add "--add-modules=java.se.ee" line at the end of the file'
    echo '    if you are using Java version 10.'
}

post_upgrade() {
    post_install
}
