#!/bin/bash
get_valid_users() {
	_l="/etc/login.defs"
	_p="/etc/passwd"
	l=$(grep "^UID_MIN" "$_l")
	l1=$(grep "^UID_MAX" "$_l")
	awk -F':' -v "min=${l##UID_MIN}" -v "max=${l1##UID_MAX}" '{
        if ($3 >= min && $3 <= max && $7 != "/sbin/nologin") print $0
    }' "$_p" | cut -d: -f1
}

disable_user_service() {
	users=$(get_valid_users)
	for i in $users; do
		echo "Disabling xppentablet.service for user '$i'"
		sudo systemctl --machine "$i"@ disable --now --user xppentablet.service
	done
}

pre_install()  {
AppName=PenTablet
pid=`ps -e|grep $AppName`
appScript=$AppName".sh"
if [ -n "$pid" ]; then
	echo $pid
	arr=()
	while read -r line; do
	   arr+=("$line")
	done <<< "$pid"
	for val in "${arr[@]}";
	do
		appid=`echo $val | awk '{print $1}'`
	   	name=`echo $val | awk '{print $4}'`
	   	echo "ID:"$appid
		echo "Name:"$name
		if [ "$name" = "$appScript" ]; then
			echo "close $appScript"
			kill -15 $appid
		elif [ "$name" = "$AppName" ]; then
			echo "close $AppName"
			kill -15 $appid
		fi
	done
fi
}

post_install() {
RuleDir="/usr/lib/udev/rules.d"
ruleName="10-xp-pen.rules"
AutoStartDir=/etc/xdg/autostart
appDesktopName=xppentablet.desktop

# Checking and applying the udev rule
if [ -f "$RuleDir/$ruleName" ]; then
	udevadm control --reload-rules && udevadm trigger
fi

systemd-tmpfiles --create /usr/lib/tmpfiles.d/xppenlinux-v3.conf

#Removing autostart scripts as the systemd service is now used.
if [ -f "$AutoStartDir/pentablet.desktop" ] || [ -f "$AutoStartDir/$appDesktopName" ]; then
	rm -f "$AutoStartDir/ugee-pentablet.desktop"
	rm -f "$AutoStartDir/pentablet.desktop"
	rm -f "$AutoStartDir/xppentablet.desktop"
fi

#Reload daemon
systemctl daemon-reload

cat <<EOF

********************
installation successful!

to restart the xp-pen driver, please run:
systemctl --user restart xppentablet.service

if you want the driver to autostart, please run:
systemctl --user enable xppentablet.service

********************

EOF

}
pre_upgrade() {
pre_install
}
post_upgrade() {
post_install
}
pre_remove () {
	pre_install
	disable_user_service
}
post_remove() {
	echo "Uninstall succeeded."
}
