#!/bin/sh
set -e

usage="
Usage: yada [ path ]
"

analyze() {
	echo "directory:"
	du -hd1 | sort -rh | sed -e 's/.\///' -e '/\.$/d' | awk '{print "\t"$0}'
	echo "file:"
	find . -maxdepth 1 -type f -exec du -ah {} + | sort -rh | sed -e 's/.\///' | awk '{print "\t"$0}'
	echo "total:"
	du -hd0 | awk '{print "\t"$1"\ttotal"}'
}

case $# in
	0)
		analyze
		;;
	1)
		pushd "$1" >/dev/null
		analyze
		popd >/dev/null
		;;
	*)
		echo "$usage"
		;;
esac
