post_install(){
  DIR=/usr/share/zlodej/DATADISK
  cp -n $DIR/{ORIGIN,GAMES}.LST
  [ $USER = root ] && USER=$SUDO_USER
  chown $USER:$USER $DIR/GAMES.LST
}
pre_remove(){
  DIR=/usr/share/zlodej/DATADISK
  [ "`diff $DIR/{ORIGIN,GAMES}.LST`" = "" ] && rm $DIR/GAMES.LST || true
}
post_remove(){
  DIR=/usr/share/zlodej
  [ -d $DIR ] && echo -e "\e[31mThe following files have not been removed:\n\n`find $DIR -type f|sort`\e[m" || true
}
