#/bin/sh

# arg 1:  the new package version
post_install() {
  echo '==> Use `sudo -u znc znc --datadir=/var/lib/znc --makeconf` to generate your first config'
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
  if [[ -d /var/lib/znc/.znc ]]; then
    echo '==> Migrating /var/lib/znc/.znc to /var/lib/znc'
    mv /var/lib/znc/.znc/* /var/lib/znc/
    rmdir /var/lib/znc/.znc
  fi
}
