post_install() {
    echo
    echo "To configure your desktop environment to open Zoom links in Firejail, run:"
    echo
    for scheme in zoommtg zoomus tel callto zoomphonecall zoomphonesms zoomcontactcentercall; do
        echo "xdg-mime default ZoomFirejail.desktop x-scheme-handler/$scheme"
    done
    echo
}

post_upgrade() {
    # xdg-mime instructions added in 0.1.4
    # zoomphonesms and zoomcontactcentercall new mime types added in 0.9.74-2
    # but I forgot to edit post_upgrade() in 0.9.74-2, so I edited
    # post_upgrade() in 0.9.74-3 to make sure people upgraded to 0.9.74-2 but
    # did not receive new mime types notice will receive one
    if [ $(vercmp $2 0.9.74-2) -le 0 ]; then
        post_install
    fi
}
