# ZRAM Compression Algorithm reference: https://wiki.archlinux.org/title/Zram#Compression_algorithm
# Possible values: zstd, lzo, lzo-rle, lz4, lz4hc.
#ZRAM_COMP_ALGORITHM=zstd

# Swap Priority (higher values are used first)
#ZRAM_PRIORITY=100

# ZRAM Size (100 means 100% of RAM)
#ZRAM_SIZE=100
