note()
{
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}
all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"
post_install()
{
    note "============================="
    note "Please enter zw3d to start"
    note "Or click on the icon to start"
    note "============================="
}
post_remove()
{
    note "zw3d-bin has been deleted"
}
